// Code generated by ent, DO NOT EDIT.

package monitorevent

import (
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the monitorevent type in the database.
	Label = "monitor_event"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldKind holds the string denoting the kind field in the database.
	FieldKind = "kind"
	// FieldSeverity holds the string denoting the severity field in the database.
	FieldSeverity = "severity"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldSource holds the string denoting the source field in the database.
	FieldSource = "source"
	// FieldSubjectType holds the string denoting the subject_type field in the database.
	FieldSubjectType = "subject_type"
	// FieldSubjectID holds the string denoting the subject_id field in the database.
	FieldSubjectID = "subject_id"
	// FieldFingerprint holds the string denoting the fingerprint field in the database.
	FieldFingerprint = "fingerprint"
	// FieldTitle holds the string denoting the title field in the database.
	FieldTitle = "title"
	// FieldMessage holds the string denoting the message field in the database.
	FieldMessage = "message"
	// FieldAPIKeyID holds the string denoting the api_key_id field in the database.
	FieldAPIKeyID = "api_key_id"
	// FieldAPIKeyNameSnapshot holds the string denoting the api_key_name_snapshot field in the database.
	FieldAPIKeyNameSnapshot = "api_key_name_snapshot"
	// FieldAPIKeyPrefix holds the string denoting the api_key_prefix field in the database.
	FieldAPIKeyPrefix = "api_key_prefix"
	// FieldUserID holds the string denoting the user_id field in the database.
	FieldUserID = "user_id"
	// FieldUserEmailSnapshot holds the string denoting the user_email_snapshot field in the database.
	FieldUserEmailSnapshot = "user_email_snapshot"
	// FieldGroupID holds the string denoting the group_id field in the database.
	FieldGroupID = "group_id"
	// FieldAccountID holds the string denoting the account_id field in the database.
	FieldAccountID = "account_id"
	// FieldAccountNameSnapshot holds the string denoting the account_name_snapshot field in the database.
	FieldAccountNameSnapshot = "account_name_snapshot"
	// FieldPlatform holds the string denoting the platform field in the database.
	FieldPlatform = "platform"
	// FieldPluginID holds the string denoting the plugin_id field in the database.
	FieldPluginID = "plugin_id"
	// FieldTaskType holds the string denoting the task_type field in the database.
	FieldTaskType = "task_type"
	// FieldMethod holds the string denoting the method field in the database.
	FieldMethod = "method"
	// FieldEndpoint holds the string denoting the endpoint field in the database.
	FieldEndpoint = "endpoint"
	// FieldRequestPath holds the string denoting the request_path field in the database.
	FieldRequestPath = "request_path"
	// FieldModel holds the string denoting the model field in the database.
	FieldModel = "model"
	// FieldHTTPStatus holds the string denoting the http_status field in the database.
	FieldHTTPStatus = "http_status"
	// FieldUpstreamStatus holds the string denoting the upstream_status field in the database.
	FieldUpstreamStatus = "upstream_status"
	// FieldErrorCode holds the string denoting the error_code field in the database.
	FieldErrorCode = "error_code"
	// FieldErrorType holds the string denoting the error_type field in the database.
	FieldErrorType = "error_type"
	// FieldCount holds the string denoting the count field in the database.
	FieldCount = "count"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldResolvedAt holds the string denoting the resolved_at field in the database.
	FieldResolvedAt = "resolved_at"
	// FieldIgnoredAt holds the string denoting the ignored_at field in the database.
	FieldIgnoredAt = "ignored_at"
	// FieldAutoResolveAt holds the string denoting the auto_resolve_at field in the database.
	FieldAutoResolveAt = "auto_resolve_at"
	// FieldExpiresAt holds the string denoting the expires_at field in the database.
	FieldExpiresAt = "expires_at"
	// FieldDetail holds the string denoting the detail field in the database.
	FieldDetail = "detail"
	// Table holds the table name of the monitorevent in the database.
	Table = "monitor_events"
)

// Columns holds all SQL columns for monitorevent fields.
var Columns = []string{
	FieldID,
	FieldKind,
	FieldSeverity,
	FieldStatus,
	FieldSource,
	FieldSubjectType,
	FieldSubjectID,
	FieldFingerprint,
	FieldTitle,
	FieldMessage,
	FieldAPIKeyID,
	FieldAPIKeyNameSnapshot,
	FieldAPIKeyPrefix,
	FieldUserID,
	FieldUserEmailSnapshot,
	FieldGroupID,
	FieldAccountID,
	FieldAccountNameSnapshot,
	FieldPlatform,
	FieldPluginID,
	FieldTaskType,
	FieldMethod,
	FieldEndpoint,
	FieldRequestPath,
	FieldModel,
	FieldHTTPStatus,
	FieldUpstreamStatus,
	FieldErrorCode,
	FieldErrorType,
	FieldCount,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldResolvedAt,
	FieldIgnoredAt,
	FieldAutoResolveAt,
	FieldExpiresAt,
	FieldDetail,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultSource holds the default value on creation for the "source" field.
	DefaultSource string
	// SourceValidator is a validator for the "source" field. It is called by the builders before save.
	SourceValidator func(string) error
	// DefaultSubjectType holds the default value on creation for the "subject_type" field.
	DefaultSubjectType string
	// SubjectTypeValidator is a validator for the "subject_type" field. It is called by the builders before save.
	SubjectTypeValidator func(string) error
	// DefaultSubjectID holds the default value on creation for the "subject_id" field.
	DefaultSubjectID string
	// SubjectIDValidator is a validator for the "subject_id" field. It is called by the builders before save.
	SubjectIDValidator func(string) error
	// FingerprintValidator is a validator for the "fingerprint" field. It is called by the builders before save.
	FingerprintValidator func(string) error
	// DefaultTitle holds the default value on creation for the "title" field.
	DefaultTitle string
	// TitleValidator is a validator for the "title" field. It is called by the builders before save.
	TitleValidator func(string) error
	// DefaultMessage holds the default value on creation for the "message" field.
	DefaultMessage string
	// MessageValidator is a validator for the "message" field. It is called by the builders before save.
	MessageValidator func(string) error
	// DefaultAPIKeyNameSnapshot holds the default value on creation for the "api_key_name_snapshot" field.
	DefaultAPIKeyNameSnapshot string
	// APIKeyNameSnapshotValidator is a validator for the "api_key_name_snapshot" field. It is called by the builders before save.
	APIKeyNameSnapshotValidator func(string) error
	// DefaultAPIKeyPrefix holds the default value on creation for the "api_key_prefix" field.
	DefaultAPIKeyPrefix string
	// APIKeyPrefixValidator is a validator for the "api_key_prefix" field. It is called by the builders before save.
	APIKeyPrefixValidator func(string) error
	// DefaultUserEmailSnapshot holds the default value on creation for the "user_email_snapshot" field.
	DefaultUserEmailSnapshot string
	// UserEmailSnapshotValidator is a validator for the "user_email_snapshot" field. It is called by the builders before save.
	UserEmailSnapshotValidator func(string) error
	// DefaultAccountNameSnapshot holds the default value on creation for the "account_name_snapshot" field.
	DefaultAccountNameSnapshot string
	// AccountNameSnapshotValidator is a validator for the "account_name_snapshot" field. It is called by the builders before save.
	AccountNameSnapshotValidator func(string) error
	// DefaultPlatform holds the default value on creation for the "platform" field.
	DefaultPlatform string
	// PlatformValidator is a validator for the "platform" field. It is called by the builders before save.
	PlatformValidator func(string) error
	// DefaultPluginID holds the default value on creation for the "plugin_id" field.
	DefaultPluginID string
	// PluginIDValidator is a validator for the "plugin_id" field. It is called by the builders before save.
	PluginIDValidator func(string) error
	// DefaultTaskType holds the default value on creation for the "task_type" field.
	DefaultTaskType string
	// TaskTypeValidator is a validator for the "task_type" field. It is called by the builders before save.
	TaskTypeValidator func(string) error
	// DefaultMethod holds the default value on creation for the "method" field.
	DefaultMethod string
	// MethodValidator is a validator for the "method" field. It is called by the builders before save.
	MethodValidator func(string) error
	// DefaultEndpoint holds the default value on creation for the "endpoint" field.
	DefaultEndpoint string
	// EndpointValidator is a validator for the "endpoint" field. It is called by the builders before save.
	EndpointValidator func(string) error
	// DefaultRequestPath holds the default value on creation for the "request_path" field.
	DefaultRequestPath string
	// RequestPathValidator is a validator for the "request_path" field. It is called by the builders before save.
	RequestPathValidator func(string) error
	// DefaultModel holds the default value on creation for the "model" field.
	DefaultModel string
	// ModelValidator is a validator for the "model" field. It is called by the builders before save.
	ModelValidator func(string) error
	// DefaultErrorCode holds the default value on creation for the "error_code" field.
	DefaultErrorCode string
	// ErrorCodeValidator is a validator for the "error_code" field. It is called by the builders before save.
	ErrorCodeValidator func(string) error
	// DefaultErrorType holds the default value on creation for the "error_type" field.
	DefaultErrorType string
	// ErrorTypeValidator is a validator for the "error_type" field. It is called by the builders before save.
	ErrorTypeValidator func(string) error
	// DefaultCount holds the default value on creation for the "count" field.
	DefaultCount int64
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// DefaultExpiresAt holds the default value on creation for the "expires_at" field.
	DefaultExpiresAt func() time.Time
	// DefaultDetail holds the default value on creation for the "detail" field.
	DefaultDetail map[string]interface{}
)

// Kind defines the type for the "kind" enum field.
type Kind string

// Kind values.
const (
	KindAPIRequestError      Kind = "api_request_error"
	KindSchedulerError       Kind = "scheduler_error"
	KindUpstreamAccountError Kind = "upstream_account_error"
	KindPluginError          Kind = "plugin_error"
	KindTaskError            Kind = "task_error"
	KindSystemError          Kind = "system_error"
)

func (k Kind) String() string {
	return string(k)
}

// KindValidator is a validator for the "kind" field enum values. It is called by the builders before save.
func KindValidator(k Kind) error {
	switch k {
	case KindAPIRequestError, KindSchedulerError, KindUpstreamAccountError, KindPluginError, KindTaskError, KindSystemError:
		return nil
	default:
		return fmt.Errorf("monitorevent: invalid enum value for kind field: %q", k)
	}
}

// Severity defines the type for the "severity" enum field.
type Severity string

// SeverityWarning is the default value of the Severity enum.
const DefaultSeverity = SeverityWarning

// Severity values.
const (
	SeverityWarning  Severity = "warning"
	SeverityError    Severity = "error"
	SeverityCritical Severity = "critical"
)

func (s Severity) String() string {
	return string(s)
}

// SeverityValidator is a validator for the "severity" field enum values. It is called by the builders before save.
func SeverityValidator(s Severity) error {
	switch s {
	case SeverityWarning, SeverityError, SeverityCritical:
		return nil
	default:
		return fmt.Errorf("monitorevent: invalid enum value for severity field: %q", s)
	}
}

// Status defines the type for the "status" enum field.
type Status string

// StatusActive is the default value of the Status enum.
const DefaultStatus = StatusActive

// Status values.
const (
	StatusActive   Status = "active"
	StatusResolved Status = "resolved"
	StatusIgnored  Status = "ignored"
)

func (s Status) String() string {
	return string(s)
}

// StatusValidator is a validator for the "status" field enum values. It is called by the builders before save.
func StatusValidator(s Status) error {
	switch s {
	case StatusActive, StatusResolved, StatusIgnored:
		return nil
	default:
		return fmt.Errorf("monitorevent: invalid enum value for status field: %q", s)
	}
}

// OrderOption defines the ordering options for the MonitorEvent queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByKind orders the results by the kind field.
func ByKind(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldKind, opts...).ToFunc()
}

// BySeverity orders the results by the severity field.
func BySeverity(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSeverity, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// BySource orders the results by the source field.
func BySource(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSource, opts...).ToFunc()
}

// BySubjectType orders the results by the subject_type field.
func BySubjectType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSubjectType, opts...).ToFunc()
}

// BySubjectID orders the results by the subject_id field.
func BySubjectID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSubjectID, opts...).ToFunc()
}

// ByFingerprint orders the results by the fingerprint field.
func ByFingerprint(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFingerprint, opts...).ToFunc()
}

// ByTitle orders the results by the title field.
func ByTitle(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTitle, opts...).ToFunc()
}

// ByMessage orders the results by the message field.
func ByMessage(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMessage, opts...).ToFunc()
}

// ByAPIKeyID orders the results by the api_key_id field.
func ByAPIKeyID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAPIKeyID, opts...).ToFunc()
}

// ByAPIKeyNameSnapshot orders the results by the api_key_name_snapshot field.
func ByAPIKeyNameSnapshot(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAPIKeyNameSnapshot, opts...).ToFunc()
}

// ByAPIKeyPrefix orders the results by the api_key_prefix field.
func ByAPIKeyPrefix(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAPIKeyPrefix, opts...).ToFunc()
}

// ByUserID orders the results by the user_id field.
func ByUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUserID, opts...).ToFunc()
}

// ByUserEmailSnapshot orders the results by the user_email_snapshot field.
func ByUserEmailSnapshot(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUserEmailSnapshot, opts...).ToFunc()
}

// ByGroupID orders the results by the group_id field.
func ByGroupID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldGroupID, opts...).ToFunc()
}

// ByAccountID orders the results by the account_id field.
func ByAccountID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAccountID, opts...).ToFunc()
}

// ByAccountNameSnapshot orders the results by the account_name_snapshot field.
func ByAccountNameSnapshot(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAccountNameSnapshot, opts...).ToFunc()
}

// ByPlatform orders the results by the platform field.
func ByPlatform(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPlatform, opts...).ToFunc()
}

// ByPluginID orders the results by the plugin_id field.
func ByPluginID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPluginID, opts...).ToFunc()
}

// ByTaskType orders the results by the task_type field.
func ByTaskType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTaskType, opts...).ToFunc()
}

// ByMethod orders the results by the method field.
func ByMethod(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMethod, opts...).ToFunc()
}

// ByEndpoint orders the results by the endpoint field.
func ByEndpoint(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEndpoint, opts...).ToFunc()
}

// ByRequestPath orders the results by the request_path field.
func ByRequestPath(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRequestPath, opts...).ToFunc()
}

// ByModel orders the results by the model field.
func ByModel(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldModel, opts...).ToFunc()
}

// ByHTTPStatus orders the results by the http_status field.
func ByHTTPStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldHTTPStatus, opts...).ToFunc()
}

// ByUpstreamStatus orders the results by the upstream_status field.
func ByUpstreamStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpstreamStatus, opts...).ToFunc()
}

// ByErrorCode orders the results by the error_code field.
func ByErrorCode(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldErrorCode, opts...).ToFunc()
}

// ByErrorType orders the results by the error_type field.
func ByErrorType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldErrorType, opts...).ToFunc()
}

// ByCount orders the results by the count field.
func ByCount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCount, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByResolvedAt orders the results by the resolved_at field.
func ByResolvedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldResolvedAt, opts...).ToFunc()
}

// ByIgnoredAt orders the results by the ignored_at field.
func ByIgnoredAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIgnoredAt, opts...).ToFunc()
}

// ByAutoResolveAt orders the results by the auto_resolve_at field.
func ByAutoResolveAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAutoResolveAt, opts...).ToFunc()
}

// ByExpiresAt orders the results by the expires_at field.
func ByExpiresAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldExpiresAt, opts...).ToFunc()
}
