// Code generated by ent, DO NOT EDIT.

package monitorevent

import (
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the monitorevent type in the database.
	Label = "monitor_event"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldType holds the string denoting the type field in the database.
	FieldType = "type"
	// FieldSeverity holds the string denoting the severity field in the database.
	FieldSeverity = "severity"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldSource holds the string denoting the source field in the database.
	FieldSource = "source"
	// FieldSubjectType holds the string denoting the subject_type field in the database.
	FieldSubjectType = "subject_type"
	// FieldSubjectID holds the string denoting the subject_id field in the database.
	FieldSubjectID = "subject_id"
	// FieldHash holds the string denoting the hash field in the database.
	FieldHash = "hash"
	// FieldTitle holds the string denoting the title field in the database.
	FieldTitle = "title"
	// FieldMessage holds the string denoting the message field in the database.
	FieldMessage = "message"
	// FieldAccountID holds the string denoting the account_id field in the database.
	FieldAccountID = "account_id"
	// FieldAccountNameSnapshot holds the string denoting the account_name_snapshot field in the database.
	FieldAccountNameSnapshot = "account_name_snapshot"
	// FieldPlatform holds the string denoting the platform field in the database.
	FieldPlatform = "platform"
	// FieldPluginID holds the string denoting the plugin_id field in the database.
	FieldPluginID = "plugin_id"
	// FieldTaskType holds the string denoting the task_type field in the database.
	FieldTaskType = "task_type"
	// FieldErrorCode holds the string denoting the error_code field in the database.
	FieldErrorCode = "error_code"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldResolvedAt holds the string denoting the resolved_at field in the database.
	FieldResolvedAt = "resolved_at"
	// FieldIgnoredAt holds the string denoting the ignored_at field in the database.
	FieldIgnoredAt = "ignored_at"
	// FieldAutoResolveAt holds the string denoting the auto_resolve_at field in the database.
	FieldAutoResolveAt = "auto_resolve_at"
	// FieldExpiresAt holds the string denoting the expires_at field in the database.
	FieldExpiresAt = "expires_at"
	// FieldLastNotifiedAt holds the string denoting the last_notified_at field in the database.
	FieldLastNotifiedAt = "last_notified_at"
	// FieldNextNotifyAt holds the string denoting the next_notify_at field in the database.
	FieldNextNotifyAt = "next_notify_at"
	// FieldNotifyError holds the string denoting the notify_error field in the database.
	FieldNotifyError = "notify_error"
	// FieldDetail holds the string denoting the detail field in the database.
	FieldDetail = "detail"
	// Table holds the table name of the monitorevent in the database.
	Table = "monitor_events"
)

// Columns holds all SQL columns for monitorevent fields.
var Columns = []string{
	FieldID,
	FieldType,
	FieldSeverity,
	FieldStatus,
	FieldSource,
	FieldSubjectType,
	FieldSubjectID,
	FieldHash,
	FieldTitle,
	FieldMessage,
	FieldAccountID,
	FieldAccountNameSnapshot,
	FieldPlatform,
	FieldPluginID,
	FieldTaskType,
	FieldErrorCode,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldResolvedAt,
	FieldIgnoredAt,
	FieldAutoResolveAt,
	FieldExpiresAt,
	FieldLastNotifiedAt,
	FieldNextNotifyAt,
	FieldNotifyError,
	FieldDetail,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultSource holds the default value on creation for the "source" field.
	DefaultSource string
	// SourceValidator is a validator for the "source" field. It is called by the builders before save.
	SourceValidator func(string) error
	// DefaultSubjectType holds the default value on creation for the "subject_type" field.
	DefaultSubjectType string
	// SubjectTypeValidator is a validator for the "subject_type" field. It is called by the builders before save.
	SubjectTypeValidator func(string) error
	// DefaultSubjectID holds the default value on creation for the "subject_id" field.
	DefaultSubjectID string
	// SubjectIDValidator is a validator for the "subject_id" field. It is called by the builders before save.
	SubjectIDValidator func(string) error
	// HashValidator is a validator for the "hash" field. It is called by the builders before save.
	HashValidator func(string) error
	// DefaultTitle holds the default value on creation for the "title" field.
	DefaultTitle string
	// TitleValidator is a validator for the "title" field. It is called by the builders before save.
	TitleValidator func(string) error
	// DefaultMessage holds the default value on creation for the "message" field.
	DefaultMessage string
	// MessageValidator is a validator for the "message" field. It is called by the builders before save.
	MessageValidator func(string) error
	// DefaultAccountNameSnapshot holds the default value on creation for the "account_name_snapshot" field.
	DefaultAccountNameSnapshot string
	// AccountNameSnapshotValidator is a validator for the "account_name_snapshot" field. It is called by the builders before save.
	AccountNameSnapshotValidator func(string) error
	// DefaultPlatform holds the default value on creation for the "platform" field.
	DefaultPlatform string
	// PlatformValidator is a validator for the "platform" field. It is called by the builders before save.
	PlatformValidator func(string) error
	// DefaultPluginID holds the default value on creation for the "plugin_id" field.
	DefaultPluginID string
	// PluginIDValidator is a validator for the "plugin_id" field. It is called by the builders before save.
	PluginIDValidator func(string) error
	// DefaultTaskType holds the default value on creation for the "task_type" field.
	DefaultTaskType string
	// TaskTypeValidator is a validator for the "task_type" field. It is called by the builders before save.
	TaskTypeValidator func(string) error
	// DefaultErrorCode holds the default value on creation for the "error_code" field.
	DefaultErrorCode string
	// ErrorCodeValidator is a validator for the "error_code" field. It is called by the builders before save.
	ErrorCodeValidator func(string) error
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// DefaultExpiresAt holds the default value on creation for the "expires_at" field.
	DefaultExpiresAt func() time.Time
	// DefaultNotifyError holds the default value on creation for the "notify_error" field.
	DefaultNotifyError string
	// NotifyErrorValidator is a validator for the "notify_error" field. It is called by the builders before save.
	NotifyErrorValidator func(string) error
	// DefaultDetail holds the default value on creation for the "detail" field.
	DefaultDetail map[string]interface{}
)

// Type defines the type for the "type" enum field.
type Type string

// Type values.
const (
	TypeSchedulerError       Type = "scheduler_error"
	TypeUpstreamAccountError Type = "upstream_account_error"
	TypePluginError          Type = "plugin_error"
	TypeTaskError            Type = "task_error"
	TypeSystemError          Type = "system_error"
)

func (_type Type) String() string {
	return string(_type)
}

// TypeValidator is a validator for the "type" field enum values. It is called by the builders before save.
func TypeValidator(_type Type) error {
	switch _type {
	case TypeSchedulerError, TypeUpstreamAccountError, TypePluginError, TypeTaskError, TypeSystemError:
		return nil
	default:
		return fmt.Errorf("monitorevent: invalid enum value for type field: %q", _type)
	}
}

// Severity defines the type for the "severity" enum field.
type Severity string

// SeverityWarning is the default value of the Severity enum.
const DefaultSeverity = SeverityWarning

// Severity values.
const (
	SeverityWarning  Severity = "warning"
	SeverityError    Severity = "error"
	SeverityCritical Severity = "critical"
)

func (s Severity) String() string {
	return string(s)
}

// SeverityValidator is a validator for the "severity" field enum values. It is called by the builders before save.
func SeverityValidator(s Severity) error {
	switch s {
	case SeverityWarning, SeverityError, SeverityCritical:
		return nil
	default:
		return fmt.Errorf("monitorevent: invalid enum value for severity field: %q", s)
	}
}

// Status defines the type for the "status" enum field.
type Status string

// StatusActive is the default value of the Status enum.
const DefaultStatus = StatusActive

// Status values.
const (
	StatusActive   Status = "active"
	StatusResolved Status = "resolved"
	StatusIgnored  Status = "ignored"
)

func (s Status) String() string {
	return string(s)
}

// StatusValidator is a validator for the "status" field enum values. It is called by the builders before save.
func StatusValidator(s Status) error {
	switch s {
	case StatusActive, StatusResolved, StatusIgnored:
		return nil
	default:
		return fmt.Errorf("monitorevent: invalid enum value for status field: %q", s)
	}
}

// OrderOption defines the ordering options for the MonitorEvent queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByType orders the results by the type field.
func ByType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldType, opts...).ToFunc()
}

// BySeverity orders the results by the severity field.
func BySeverity(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSeverity, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// BySource orders the results by the source field.
func BySource(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSource, opts...).ToFunc()
}

// BySubjectType orders the results by the subject_type field.
func BySubjectType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSubjectType, opts...).ToFunc()
}

// BySubjectID orders the results by the subject_id field.
func BySubjectID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSubjectID, opts...).ToFunc()
}

// ByHash orders the results by the hash field.
func ByHash(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldHash, opts...).ToFunc()
}

// ByTitle orders the results by the title field.
func ByTitle(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTitle, opts...).ToFunc()
}

// ByMessage orders the results by the message field.
func ByMessage(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMessage, opts...).ToFunc()
}

// ByAccountID orders the results by the account_id field.
func ByAccountID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAccountID, opts...).ToFunc()
}

// ByAccountNameSnapshot orders the results by the account_name_snapshot field.
func ByAccountNameSnapshot(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAccountNameSnapshot, opts...).ToFunc()
}

// ByPlatform orders the results by the platform field.
func ByPlatform(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPlatform, opts...).ToFunc()
}

// ByPluginID orders the results by the plugin_id field.
func ByPluginID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPluginID, opts...).ToFunc()
}

// ByTaskType orders the results by the task_type field.
func ByTaskType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTaskType, opts...).ToFunc()
}

// ByErrorCode orders the results by the error_code field.
func ByErrorCode(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldErrorCode, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByResolvedAt orders the results by the resolved_at field.
func ByResolvedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldResolvedAt, opts...).ToFunc()
}

// ByIgnoredAt orders the results by the ignored_at field.
func ByIgnoredAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIgnoredAt, opts...).ToFunc()
}

// ByAutoResolveAt orders the results by the auto_resolve_at field.
func ByAutoResolveAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAutoResolveAt, opts...).ToFunc()
}

// ByExpiresAt orders the results by the expires_at field.
func ByExpiresAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldExpiresAt, opts...).ToFunc()
}

// ByLastNotifiedAt orders the results by the last_notified_at field.
func ByLastNotifiedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastNotifiedAt, opts...).ToFunc()
}

// ByNextNotifyAt orders the results by the next_notify_at field.
func ByNextNotifyAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldNextNotifyAt, opts...).ToFunc()
}

// ByNotifyError orders the results by the notify_error field.
func ByNotifyError(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldNotifyError, opts...).ToFunc()
}
