// Code generated by ent, DO NOT EDIT.

package monitorrequesttrace

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the monitorrequesttrace type in the database.
	Label = "monitor_request_trace"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldHash holds the string denoting the hash field in the database.
	FieldHash = "hash"
	// FieldSchemaVersion holds the string denoting the schema_version field in the database.
	FieldSchemaVersion = "schema_version"
	// FieldEncoding holds the string denoting the encoding field in the database.
	FieldEncoding = "encoding"
	// FieldPayload holds the string denoting the payload field in the database.
	FieldPayload = "payload"
	// FieldRawSize holds the string denoting the raw_size field in the database.
	FieldRawSize = "raw_size"
	// FieldCompressedSize holds the string denoting the compressed_size field in the database.
	FieldCompressedSize = "compressed_size"
	// FieldSeenCount holds the string denoting the seen_count field in the database.
	FieldSeenCount = "seen_count"
	// FieldFirstSeenAt holds the string denoting the first_seen_at field in the database.
	FieldFirstSeenAt = "first_seen_at"
	// FieldLastSeenAt holds the string denoting the last_seen_at field in the database.
	FieldLastSeenAt = "last_seen_at"
	// FieldExpiresAt holds the string denoting the expires_at field in the database.
	FieldExpiresAt = "expires_at"
	// Table holds the table name of the monitorrequesttrace in the database.
	Table = "monitor_request_trace"
)

// Columns holds all SQL columns for monitorrequesttrace fields.
var Columns = []string{
	FieldID,
	FieldHash,
	FieldSchemaVersion,
	FieldEncoding,
	FieldPayload,
	FieldRawSize,
	FieldCompressedSize,
	FieldSeenCount,
	FieldFirstSeenAt,
	FieldLastSeenAt,
	FieldExpiresAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// HashValidator is a validator for the "hash" field. It is called by the builders before save.
	HashValidator func(string) error
	// DefaultSchemaVersion holds the default value on creation for the "schema_version" field.
	DefaultSchemaVersion int
	// DefaultEncoding holds the default value on creation for the "encoding" field.
	DefaultEncoding string
	// EncodingValidator is a validator for the "encoding" field. It is called by the builders before save.
	EncodingValidator func(string) error
	// DefaultRawSize holds the default value on creation for the "raw_size" field.
	DefaultRawSize int64
	// DefaultCompressedSize holds the default value on creation for the "compressed_size" field.
	DefaultCompressedSize int64
	// DefaultSeenCount holds the default value on creation for the "seen_count" field.
	DefaultSeenCount int64
	// DefaultFirstSeenAt holds the default value on creation for the "first_seen_at" field.
	DefaultFirstSeenAt func() time.Time
	// DefaultLastSeenAt holds the default value on creation for the "last_seen_at" field.
	DefaultLastSeenAt func() time.Time
	// DefaultExpiresAt holds the default value on creation for the "expires_at" field.
	DefaultExpiresAt func() time.Time
)

// OrderOption defines the ordering options for the MonitorRequestTrace queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByHash orders the results by the hash field.
func ByHash(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldHash, opts...).ToFunc()
}

// BySchemaVersion orders the results by the schema_version field.
func BySchemaVersion(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSchemaVersion, opts...).ToFunc()
}

// ByEncoding orders the results by the encoding field.
func ByEncoding(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEncoding, opts...).ToFunc()
}

// ByRawSize orders the results by the raw_size field.
func ByRawSize(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRawSize, opts...).ToFunc()
}

// ByCompressedSize orders the results by the compressed_size field.
func ByCompressedSize(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCompressedSize, opts...).ToFunc()
}

// BySeenCount orders the results by the seen_count field.
func BySeenCount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSeenCount, opts...).ToFunc()
}

// ByFirstSeenAt orders the results by the first_seen_at field.
func ByFirstSeenAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFirstSeenAt, opts...).ToFunc()
}

// ByLastSeenAt orders the results by the last_seen_at field.
func ByLastSeenAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastSeenAt, opts...).ToFunc()
}

// ByExpiresAt orders the results by the expires_at field.
func ByExpiresAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldExpiresAt, opts...).ToFunc()
}
