// Code generated by ent, DO NOT EDIT.

package monitorrequesttrace

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/DevilGenius/airgate-core/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.MonitorRequestTrace {
	return predicate.MonitorRequestTrace(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.MonitorRequestTrace {
	return predicate.MonitorRequestTrace(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.MonitorRequestTrace {
	return predicate.MonitorRequestTrace(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.MonitorRequestTrace {
	return predicate.MonitorRequestTrace(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.MonitorRequestTrace {
	return predicate.MonitorRequestTrace(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.MonitorRequestTrace {
	return predicate.MonitorRequestTrace(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.MonitorRequestTrace {
	return predicate.MonitorRequestTrace(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.MonitorRequestTrace {
	return predicate.MonitorRequestTrace(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.MonitorRequestTrace {
	return predicate.MonitorRequestTrace(sql.FieldLTE(FieldID, id))
}

// Hash applies equality check predicate on the "hash" field. It's identical to HashEQ.
func Hash(v string) predicate.MonitorRequestTrace {
	return predicate.MonitorRequestTrace(sql.FieldEQ(FieldHash, v))
}

// SchemaVersion applies equality check predicate on the "schema_version" field. It's identical to SchemaVersionEQ.
func SchemaVersion(v int) predicate.MonitorRequestTrace {
	return predicate.MonitorRequestTrace(sql.FieldEQ(FieldSchemaVersion, v))
}

// Encoding applies equality check predicate on the "encoding" field. It's identical to EncodingEQ.
func Encoding(v string) predicate.MonitorRequestTrace {
	return predicate.MonitorRequestTrace(sql.FieldEQ(FieldEncoding, v))
}

// Payload applies equality check predicate on the "payload" field. It's identical to PayloadEQ.
func Payload(v []byte) predicate.MonitorRequestTrace {
	return predicate.MonitorRequestTrace(sql.FieldEQ(FieldPayload, v))
}

// RawSize applies equality check predicate on the "raw_size" field. It's identical to RawSizeEQ.
func RawSize(v int64) predicate.MonitorRequestTrace {
	return predicate.MonitorRequestTrace(sql.FieldEQ(FieldRawSize, v))
}

// CompressedSize applies equality check predicate on the "compressed_size" field. It's identical to CompressedSizeEQ.
func CompressedSize(v int64) predicate.MonitorRequestTrace {
	return predicate.MonitorRequestTrace(sql.FieldEQ(FieldCompressedSize, v))
}

// SeenCount applies equality check predicate on the "seen_count" field. It's identical to SeenCountEQ.
func SeenCount(v int64) predicate.MonitorRequestTrace {
	return predicate.MonitorRequestTrace(sql.FieldEQ(FieldSeenCount, v))
}

// FirstSeenAt applies equality check predicate on the "first_seen_at" field. It's identical to FirstSeenAtEQ.
func FirstSeenAt(v time.Time) predicate.MonitorRequestTrace {
	return predicate.MonitorRequestTrace(sql.FieldEQ(FieldFirstSeenAt, v))
}

// LastSeenAt applies equality check predicate on the "last_seen_at" field. It's identical to LastSeenAtEQ.
func LastSeenAt(v time.Time) predicate.MonitorRequestTrace {
	return predicate.MonitorRequestTrace(sql.FieldEQ(FieldLastSeenAt, v))
}

// ExpiresAt applies equality check predicate on the "expires_at" field. It's identical to ExpiresAtEQ.
func ExpiresAt(v time.Time) predicate.MonitorRequestTrace {
	return predicate.MonitorRequestTrace(sql.FieldEQ(FieldExpiresAt, v))
}

// HashEQ applies the EQ predicate on the "hash" field.
func HashEQ(v string) predicate.MonitorRequestTrace {
	return predicate.MonitorRequestTrace(sql.FieldEQ(FieldHash, v))
}

// HashNEQ applies the NEQ predicate on the "hash" field.
func HashNEQ(v string) predicate.MonitorRequestTrace {
	return predicate.MonitorRequestTrace(sql.FieldNEQ(FieldHash, v))
}

// HashIn applies the In predicate on the "hash" field.
func HashIn(vs ...string) predicate.MonitorRequestTrace {
	return predicate.MonitorRequestTrace(sql.FieldIn(FieldHash, vs...))
}

// HashNotIn applies the NotIn predicate on the "hash" field.
func HashNotIn(vs ...string) predicate.MonitorRequestTrace {
	return predicate.MonitorRequestTrace(sql.FieldNotIn(FieldHash, vs...))
}

// HashGT applies the GT predicate on the "hash" field.
func HashGT(v string) predicate.MonitorRequestTrace {
	return predicate.MonitorRequestTrace(sql.FieldGT(FieldHash, v))
}

// HashGTE applies the GTE predicate on the "hash" field.
func HashGTE(v string) predicate.MonitorRequestTrace {
	return predicate.MonitorRequestTrace(sql.FieldGTE(FieldHash, v))
}

// HashLT applies the LT predicate on the "hash" field.
func HashLT(v string) predicate.MonitorRequestTrace {
	return predicate.MonitorRequestTrace(sql.FieldLT(FieldHash, v))
}

// HashLTE applies the LTE predicate on the "hash" field.
func HashLTE(v string) predicate.MonitorRequestTrace {
	return predicate.MonitorRequestTrace(sql.FieldLTE(FieldHash, v))
}

// HashContains applies the Contains predicate on the "hash" field.
func HashContains(v string) predicate.MonitorRequestTrace {
	return predicate.MonitorRequestTrace(sql.FieldContains(FieldHash, v))
}

// HashHasPrefix applies the HasPrefix predicate on the "hash" field.
func HashHasPrefix(v string) predicate.MonitorRequestTrace {
	return predicate.MonitorRequestTrace(sql.FieldHasPrefix(FieldHash, v))
}

// HashHasSuffix applies the HasSuffix predicate on the "hash" field.
func HashHasSuffix(v string) predicate.MonitorRequestTrace {
	return predicate.MonitorRequestTrace(sql.FieldHasSuffix(FieldHash, v))
}

// HashEqualFold applies the EqualFold predicate on the "hash" field.
func HashEqualFold(v string) predicate.MonitorRequestTrace {
	return predicate.MonitorRequestTrace(sql.FieldEqualFold(FieldHash, v))
}

// HashContainsFold applies the ContainsFold predicate on the "hash" field.
func HashContainsFold(v string) predicate.MonitorRequestTrace {
	return predicate.MonitorRequestTrace(sql.FieldContainsFold(FieldHash, v))
}

// SchemaVersionEQ applies the EQ predicate on the "schema_version" field.
func SchemaVersionEQ(v int) predicate.MonitorRequestTrace {
	return predicate.MonitorRequestTrace(sql.FieldEQ(FieldSchemaVersion, v))
}

// SchemaVersionNEQ applies the NEQ predicate on the "schema_version" field.
func SchemaVersionNEQ(v int) predicate.MonitorRequestTrace {
	return predicate.MonitorRequestTrace(sql.FieldNEQ(FieldSchemaVersion, v))
}

// SchemaVersionIn applies the In predicate on the "schema_version" field.
func SchemaVersionIn(vs ...int) predicate.MonitorRequestTrace {
	return predicate.MonitorRequestTrace(sql.FieldIn(FieldSchemaVersion, vs...))
}

// SchemaVersionNotIn applies the NotIn predicate on the "schema_version" field.
func SchemaVersionNotIn(vs ...int) predicate.MonitorRequestTrace {
	return predicate.MonitorRequestTrace(sql.FieldNotIn(FieldSchemaVersion, vs...))
}

// SchemaVersionGT applies the GT predicate on the "schema_version" field.
func SchemaVersionGT(v int) predicate.MonitorRequestTrace {
	return predicate.MonitorRequestTrace(sql.FieldGT(FieldSchemaVersion, v))
}

// SchemaVersionGTE applies the GTE predicate on the "schema_version" field.
func SchemaVersionGTE(v int) predicate.MonitorRequestTrace {
	return predicate.MonitorRequestTrace(sql.FieldGTE(FieldSchemaVersion, v))
}

// SchemaVersionLT applies the LT predicate on the "schema_version" field.
func SchemaVersionLT(v int) predicate.MonitorRequestTrace {
	return predicate.MonitorRequestTrace(sql.FieldLT(FieldSchemaVersion, v))
}

// SchemaVersionLTE applies the LTE predicate on the "schema_version" field.
func SchemaVersionLTE(v int) predicate.MonitorRequestTrace {
	return predicate.MonitorRequestTrace(sql.FieldLTE(FieldSchemaVersion, v))
}

// EncodingEQ applies the EQ predicate on the "encoding" field.
func EncodingEQ(v string) predicate.MonitorRequestTrace {
	return predicate.MonitorRequestTrace(sql.FieldEQ(FieldEncoding, v))
}

// EncodingNEQ applies the NEQ predicate on the "encoding" field.
func EncodingNEQ(v string) predicate.MonitorRequestTrace {
	return predicate.MonitorRequestTrace(sql.FieldNEQ(FieldEncoding, v))
}

// EncodingIn applies the In predicate on the "encoding" field.
func EncodingIn(vs ...string) predicate.MonitorRequestTrace {
	return predicate.MonitorRequestTrace(sql.FieldIn(FieldEncoding, vs...))
}

// EncodingNotIn applies the NotIn predicate on the "encoding" field.
func EncodingNotIn(vs ...string) predicate.MonitorRequestTrace {
	return predicate.MonitorRequestTrace(sql.FieldNotIn(FieldEncoding, vs...))
}

// EncodingGT applies the GT predicate on the "encoding" field.
func EncodingGT(v string) predicate.MonitorRequestTrace {
	return predicate.MonitorRequestTrace(sql.FieldGT(FieldEncoding, v))
}

// EncodingGTE applies the GTE predicate on the "encoding" field.
func EncodingGTE(v string) predicate.MonitorRequestTrace {
	return predicate.MonitorRequestTrace(sql.FieldGTE(FieldEncoding, v))
}

// EncodingLT applies the LT predicate on the "encoding" field.
func EncodingLT(v string) predicate.MonitorRequestTrace {
	return predicate.MonitorRequestTrace(sql.FieldLT(FieldEncoding, v))
}

// EncodingLTE applies the LTE predicate on the "encoding" field.
func EncodingLTE(v string) predicate.MonitorRequestTrace {
	return predicate.MonitorRequestTrace(sql.FieldLTE(FieldEncoding, v))
}

// EncodingContains applies the Contains predicate on the "encoding" field.
func EncodingContains(v string) predicate.MonitorRequestTrace {
	return predicate.MonitorRequestTrace(sql.FieldContains(FieldEncoding, v))
}

// EncodingHasPrefix applies the HasPrefix predicate on the "encoding" field.
func EncodingHasPrefix(v string) predicate.MonitorRequestTrace {
	return predicate.MonitorRequestTrace(sql.FieldHasPrefix(FieldEncoding, v))
}

// EncodingHasSuffix applies the HasSuffix predicate on the "encoding" field.
func EncodingHasSuffix(v string) predicate.MonitorRequestTrace {
	return predicate.MonitorRequestTrace(sql.FieldHasSuffix(FieldEncoding, v))
}

// EncodingEqualFold applies the EqualFold predicate on the "encoding" field.
func EncodingEqualFold(v string) predicate.MonitorRequestTrace {
	return predicate.MonitorRequestTrace(sql.FieldEqualFold(FieldEncoding, v))
}

// EncodingContainsFold applies the ContainsFold predicate on the "encoding" field.
func EncodingContainsFold(v string) predicate.MonitorRequestTrace {
	return predicate.MonitorRequestTrace(sql.FieldContainsFold(FieldEncoding, v))
}

// PayloadEQ applies the EQ predicate on the "payload" field.
func PayloadEQ(v []byte) predicate.MonitorRequestTrace {
	return predicate.MonitorRequestTrace(sql.FieldEQ(FieldPayload, v))
}

// PayloadNEQ applies the NEQ predicate on the "payload" field.
func PayloadNEQ(v []byte) predicate.MonitorRequestTrace {
	return predicate.MonitorRequestTrace(sql.FieldNEQ(FieldPayload, v))
}

// PayloadIn applies the In predicate on the "payload" field.
func PayloadIn(vs ...[]byte) predicate.MonitorRequestTrace {
	return predicate.MonitorRequestTrace(sql.FieldIn(FieldPayload, vs...))
}

// PayloadNotIn applies the NotIn predicate on the "payload" field.
func PayloadNotIn(vs ...[]byte) predicate.MonitorRequestTrace {
	return predicate.MonitorRequestTrace(sql.FieldNotIn(FieldPayload, vs...))
}

// PayloadGT applies the GT predicate on the "payload" field.
func PayloadGT(v []byte) predicate.MonitorRequestTrace {
	return predicate.MonitorRequestTrace(sql.FieldGT(FieldPayload, v))
}

// PayloadGTE applies the GTE predicate on the "payload" field.
func PayloadGTE(v []byte) predicate.MonitorRequestTrace {
	return predicate.MonitorRequestTrace(sql.FieldGTE(FieldPayload, v))
}

// PayloadLT applies the LT predicate on the "payload" field.
func PayloadLT(v []byte) predicate.MonitorRequestTrace {
	return predicate.MonitorRequestTrace(sql.FieldLT(FieldPayload, v))
}

// PayloadLTE applies the LTE predicate on the "payload" field.
func PayloadLTE(v []byte) predicate.MonitorRequestTrace {
	return predicate.MonitorRequestTrace(sql.FieldLTE(FieldPayload, v))
}

// RawSizeEQ applies the EQ predicate on the "raw_size" field.
func RawSizeEQ(v int64) predicate.MonitorRequestTrace {
	return predicate.MonitorRequestTrace(sql.FieldEQ(FieldRawSize, v))
}

// RawSizeNEQ applies the NEQ predicate on the "raw_size" field.
func RawSizeNEQ(v int64) predicate.MonitorRequestTrace {
	return predicate.MonitorRequestTrace(sql.FieldNEQ(FieldRawSize, v))
}

// RawSizeIn applies the In predicate on the "raw_size" field.
func RawSizeIn(vs ...int64) predicate.MonitorRequestTrace {
	return predicate.MonitorRequestTrace(sql.FieldIn(FieldRawSize, vs...))
}

// RawSizeNotIn applies the NotIn predicate on the "raw_size" field.
func RawSizeNotIn(vs ...int64) predicate.MonitorRequestTrace {
	return predicate.MonitorRequestTrace(sql.FieldNotIn(FieldRawSize, vs...))
}

// RawSizeGT applies the GT predicate on the "raw_size" field.
func RawSizeGT(v int64) predicate.MonitorRequestTrace {
	return predicate.MonitorRequestTrace(sql.FieldGT(FieldRawSize, v))
}

// RawSizeGTE applies the GTE predicate on the "raw_size" field.
func RawSizeGTE(v int64) predicate.MonitorRequestTrace {
	return predicate.MonitorRequestTrace(sql.FieldGTE(FieldRawSize, v))
}

// RawSizeLT applies the LT predicate on the "raw_size" field.
func RawSizeLT(v int64) predicate.MonitorRequestTrace {
	return predicate.MonitorRequestTrace(sql.FieldLT(FieldRawSize, v))
}

// RawSizeLTE applies the LTE predicate on the "raw_size" field.
func RawSizeLTE(v int64) predicate.MonitorRequestTrace {
	return predicate.MonitorRequestTrace(sql.FieldLTE(FieldRawSize, v))
}

// CompressedSizeEQ applies the EQ predicate on the "compressed_size" field.
func CompressedSizeEQ(v int64) predicate.MonitorRequestTrace {
	return predicate.MonitorRequestTrace(sql.FieldEQ(FieldCompressedSize, v))
}

// CompressedSizeNEQ applies the NEQ predicate on the "compressed_size" field.
func CompressedSizeNEQ(v int64) predicate.MonitorRequestTrace {
	return predicate.MonitorRequestTrace(sql.FieldNEQ(FieldCompressedSize, v))
}

// CompressedSizeIn applies the In predicate on the "compressed_size" field.
func CompressedSizeIn(vs ...int64) predicate.MonitorRequestTrace {
	return predicate.MonitorRequestTrace(sql.FieldIn(FieldCompressedSize, vs...))
}

// CompressedSizeNotIn applies the NotIn predicate on the "compressed_size" field.
func CompressedSizeNotIn(vs ...int64) predicate.MonitorRequestTrace {
	return predicate.MonitorRequestTrace(sql.FieldNotIn(FieldCompressedSize, vs...))
}

// CompressedSizeGT applies the GT predicate on the "compressed_size" field.
func CompressedSizeGT(v int64) predicate.MonitorRequestTrace {
	return predicate.MonitorRequestTrace(sql.FieldGT(FieldCompressedSize, v))
}

// CompressedSizeGTE applies the GTE predicate on the "compressed_size" field.
func CompressedSizeGTE(v int64) predicate.MonitorRequestTrace {
	return predicate.MonitorRequestTrace(sql.FieldGTE(FieldCompressedSize, v))
}

// CompressedSizeLT applies the LT predicate on the "compressed_size" field.
func CompressedSizeLT(v int64) predicate.MonitorRequestTrace {
	return predicate.MonitorRequestTrace(sql.FieldLT(FieldCompressedSize, v))
}

// CompressedSizeLTE applies the LTE predicate on the "compressed_size" field.
func CompressedSizeLTE(v int64) predicate.MonitorRequestTrace {
	return predicate.MonitorRequestTrace(sql.FieldLTE(FieldCompressedSize, v))
}

// SeenCountEQ applies the EQ predicate on the "seen_count" field.
func SeenCountEQ(v int64) predicate.MonitorRequestTrace {
	return predicate.MonitorRequestTrace(sql.FieldEQ(FieldSeenCount, v))
}

// SeenCountNEQ applies the NEQ predicate on the "seen_count" field.
func SeenCountNEQ(v int64) predicate.MonitorRequestTrace {
	return predicate.MonitorRequestTrace(sql.FieldNEQ(FieldSeenCount, v))
}

// SeenCountIn applies the In predicate on the "seen_count" field.
func SeenCountIn(vs ...int64) predicate.MonitorRequestTrace {
	return predicate.MonitorRequestTrace(sql.FieldIn(FieldSeenCount, vs...))
}

// SeenCountNotIn applies the NotIn predicate on the "seen_count" field.
func SeenCountNotIn(vs ...int64) predicate.MonitorRequestTrace {
	return predicate.MonitorRequestTrace(sql.FieldNotIn(FieldSeenCount, vs...))
}

// SeenCountGT applies the GT predicate on the "seen_count" field.
func SeenCountGT(v int64) predicate.MonitorRequestTrace {
	return predicate.MonitorRequestTrace(sql.FieldGT(FieldSeenCount, v))
}

// SeenCountGTE applies the GTE predicate on the "seen_count" field.
func SeenCountGTE(v int64) predicate.MonitorRequestTrace {
	return predicate.MonitorRequestTrace(sql.FieldGTE(FieldSeenCount, v))
}

// SeenCountLT applies the LT predicate on the "seen_count" field.
func SeenCountLT(v int64) predicate.MonitorRequestTrace {
	return predicate.MonitorRequestTrace(sql.FieldLT(FieldSeenCount, v))
}

// SeenCountLTE applies the LTE predicate on the "seen_count" field.
func SeenCountLTE(v int64) predicate.MonitorRequestTrace {
	return predicate.MonitorRequestTrace(sql.FieldLTE(FieldSeenCount, v))
}

// FirstSeenAtEQ applies the EQ predicate on the "first_seen_at" field.
func FirstSeenAtEQ(v time.Time) predicate.MonitorRequestTrace {
	return predicate.MonitorRequestTrace(sql.FieldEQ(FieldFirstSeenAt, v))
}

// FirstSeenAtNEQ applies the NEQ predicate on the "first_seen_at" field.
func FirstSeenAtNEQ(v time.Time) predicate.MonitorRequestTrace {
	return predicate.MonitorRequestTrace(sql.FieldNEQ(FieldFirstSeenAt, v))
}

// FirstSeenAtIn applies the In predicate on the "first_seen_at" field.
func FirstSeenAtIn(vs ...time.Time) predicate.MonitorRequestTrace {
	return predicate.MonitorRequestTrace(sql.FieldIn(FieldFirstSeenAt, vs...))
}

// FirstSeenAtNotIn applies the NotIn predicate on the "first_seen_at" field.
func FirstSeenAtNotIn(vs ...time.Time) predicate.MonitorRequestTrace {
	return predicate.MonitorRequestTrace(sql.FieldNotIn(FieldFirstSeenAt, vs...))
}

// FirstSeenAtGT applies the GT predicate on the "first_seen_at" field.
func FirstSeenAtGT(v time.Time) predicate.MonitorRequestTrace {
	return predicate.MonitorRequestTrace(sql.FieldGT(FieldFirstSeenAt, v))
}

// FirstSeenAtGTE applies the GTE predicate on the "first_seen_at" field.
func FirstSeenAtGTE(v time.Time) predicate.MonitorRequestTrace {
	return predicate.MonitorRequestTrace(sql.FieldGTE(FieldFirstSeenAt, v))
}

// FirstSeenAtLT applies the LT predicate on the "first_seen_at" field.
func FirstSeenAtLT(v time.Time) predicate.MonitorRequestTrace {
	return predicate.MonitorRequestTrace(sql.FieldLT(FieldFirstSeenAt, v))
}

// FirstSeenAtLTE applies the LTE predicate on the "first_seen_at" field.
func FirstSeenAtLTE(v time.Time) predicate.MonitorRequestTrace {
	return predicate.MonitorRequestTrace(sql.FieldLTE(FieldFirstSeenAt, v))
}

// LastSeenAtEQ applies the EQ predicate on the "last_seen_at" field.
func LastSeenAtEQ(v time.Time) predicate.MonitorRequestTrace {
	return predicate.MonitorRequestTrace(sql.FieldEQ(FieldLastSeenAt, v))
}

// LastSeenAtNEQ applies the NEQ predicate on the "last_seen_at" field.
func LastSeenAtNEQ(v time.Time) predicate.MonitorRequestTrace {
	return predicate.MonitorRequestTrace(sql.FieldNEQ(FieldLastSeenAt, v))
}

// LastSeenAtIn applies the In predicate on the "last_seen_at" field.
func LastSeenAtIn(vs ...time.Time) predicate.MonitorRequestTrace {
	return predicate.MonitorRequestTrace(sql.FieldIn(FieldLastSeenAt, vs...))
}

// LastSeenAtNotIn applies the NotIn predicate on the "last_seen_at" field.
func LastSeenAtNotIn(vs ...time.Time) predicate.MonitorRequestTrace {
	return predicate.MonitorRequestTrace(sql.FieldNotIn(FieldLastSeenAt, vs...))
}

// LastSeenAtGT applies the GT predicate on the "last_seen_at" field.
func LastSeenAtGT(v time.Time) predicate.MonitorRequestTrace {
	return predicate.MonitorRequestTrace(sql.FieldGT(FieldLastSeenAt, v))
}

// LastSeenAtGTE applies the GTE predicate on the "last_seen_at" field.
func LastSeenAtGTE(v time.Time) predicate.MonitorRequestTrace {
	return predicate.MonitorRequestTrace(sql.FieldGTE(FieldLastSeenAt, v))
}

// LastSeenAtLT applies the LT predicate on the "last_seen_at" field.
func LastSeenAtLT(v time.Time) predicate.MonitorRequestTrace {
	return predicate.MonitorRequestTrace(sql.FieldLT(FieldLastSeenAt, v))
}

// LastSeenAtLTE applies the LTE predicate on the "last_seen_at" field.
func LastSeenAtLTE(v time.Time) predicate.MonitorRequestTrace {
	return predicate.MonitorRequestTrace(sql.FieldLTE(FieldLastSeenAt, v))
}

// ExpiresAtEQ applies the EQ predicate on the "expires_at" field.
func ExpiresAtEQ(v time.Time) predicate.MonitorRequestTrace {
	return predicate.MonitorRequestTrace(sql.FieldEQ(FieldExpiresAt, v))
}

// ExpiresAtNEQ applies the NEQ predicate on the "expires_at" field.
func ExpiresAtNEQ(v time.Time) predicate.MonitorRequestTrace {
	return predicate.MonitorRequestTrace(sql.FieldNEQ(FieldExpiresAt, v))
}

// ExpiresAtIn applies the In predicate on the "expires_at" field.
func ExpiresAtIn(vs ...time.Time) predicate.MonitorRequestTrace {
	return predicate.MonitorRequestTrace(sql.FieldIn(FieldExpiresAt, vs...))
}

// ExpiresAtNotIn applies the NotIn predicate on the "expires_at" field.
func ExpiresAtNotIn(vs ...time.Time) predicate.MonitorRequestTrace {
	return predicate.MonitorRequestTrace(sql.FieldNotIn(FieldExpiresAt, vs...))
}

// ExpiresAtGT applies the GT predicate on the "expires_at" field.
func ExpiresAtGT(v time.Time) predicate.MonitorRequestTrace {
	return predicate.MonitorRequestTrace(sql.FieldGT(FieldExpiresAt, v))
}

// ExpiresAtGTE applies the GTE predicate on the "expires_at" field.
func ExpiresAtGTE(v time.Time) predicate.MonitorRequestTrace {
	return predicate.MonitorRequestTrace(sql.FieldGTE(FieldExpiresAt, v))
}

// ExpiresAtLT applies the LT predicate on the "expires_at" field.
func ExpiresAtLT(v time.Time) predicate.MonitorRequestTrace {
	return predicate.MonitorRequestTrace(sql.FieldLT(FieldExpiresAt, v))
}

// ExpiresAtLTE applies the LTE predicate on the "expires_at" field.
func ExpiresAtLTE(v time.Time) predicate.MonitorRequestTrace {
	return predicate.MonitorRequestTrace(sql.FieldLTE(FieldExpiresAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.MonitorRequestTrace) predicate.MonitorRequestTrace {
	return predicate.MonitorRequestTrace(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.MonitorRequestTrace) predicate.MonitorRequestTrace {
	return predicate.MonitorRequestTrace(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.MonitorRequestTrace) predicate.MonitorRequestTrace {
	return predicate.MonitorRequestTrace(sql.NotPredicates(p))
}
