// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/DevilGenius/airgate-core/ent/monitorevent"
	"github.com/DevilGenius/airgate-core/ent/predicate"
)

// MonitorEventUpdate is the builder for updating MonitorEvent entities.
type MonitorEventUpdate struct {
	config
	hooks    []Hook
	mutation *MonitorEventMutation
}

// Where appends a list predicates to the MonitorEventUpdate builder.
func (meu *MonitorEventUpdate) Where(ps ...predicate.MonitorEvent) *MonitorEventUpdate {
	meu.mutation.Where(ps...)
	return meu
}

// SetType sets the "type" field.
func (meu *MonitorEventUpdate) SetType(m monitorevent.Type) *MonitorEventUpdate {
	meu.mutation.SetType(m)
	return meu
}

// SetNillableType sets the "type" field if the given value is not nil.
func (meu *MonitorEventUpdate) SetNillableType(m *monitorevent.Type) *MonitorEventUpdate {
	if m != nil {
		meu.SetType(*m)
	}
	return meu
}

// SetSeverity sets the "severity" field.
func (meu *MonitorEventUpdate) SetSeverity(m monitorevent.Severity) *MonitorEventUpdate {
	meu.mutation.SetSeverity(m)
	return meu
}

// SetNillableSeverity sets the "severity" field if the given value is not nil.
func (meu *MonitorEventUpdate) SetNillableSeverity(m *monitorevent.Severity) *MonitorEventUpdate {
	if m != nil {
		meu.SetSeverity(*m)
	}
	return meu
}

// SetStatus sets the "status" field.
func (meu *MonitorEventUpdate) SetStatus(m monitorevent.Status) *MonitorEventUpdate {
	meu.mutation.SetStatus(m)
	return meu
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (meu *MonitorEventUpdate) SetNillableStatus(m *monitorevent.Status) *MonitorEventUpdate {
	if m != nil {
		meu.SetStatus(*m)
	}
	return meu
}

// SetSource sets the "source" field.
func (meu *MonitorEventUpdate) SetSource(s string) *MonitorEventUpdate {
	meu.mutation.SetSource(s)
	return meu
}

// SetNillableSource sets the "source" field if the given value is not nil.
func (meu *MonitorEventUpdate) SetNillableSource(s *string) *MonitorEventUpdate {
	if s != nil {
		meu.SetSource(*s)
	}
	return meu
}

// SetSubjectType sets the "subject_type" field.
func (meu *MonitorEventUpdate) SetSubjectType(s string) *MonitorEventUpdate {
	meu.mutation.SetSubjectType(s)
	return meu
}

// SetNillableSubjectType sets the "subject_type" field if the given value is not nil.
func (meu *MonitorEventUpdate) SetNillableSubjectType(s *string) *MonitorEventUpdate {
	if s != nil {
		meu.SetSubjectType(*s)
	}
	return meu
}

// SetSubjectID sets the "subject_id" field.
func (meu *MonitorEventUpdate) SetSubjectID(s string) *MonitorEventUpdate {
	meu.mutation.SetSubjectID(s)
	return meu
}

// SetNillableSubjectID sets the "subject_id" field if the given value is not nil.
func (meu *MonitorEventUpdate) SetNillableSubjectID(s *string) *MonitorEventUpdate {
	if s != nil {
		meu.SetSubjectID(*s)
	}
	return meu
}

// SetFingerprint sets the "fingerprint" field.
func (meu *MonitorEventUpdate) SetFingerprint(s string) *MonitorEventUpdate {
	meu.mutation.SetFingerprint(s)
	return meu
}

// SetNillableFingerprint sets the "fingerprint" field if the given value is not nil.
func (meu *MonitorEventUpdate) SetNillableFingerprint(s *string) *MonitorEventUpdate {
	if s != nil {
		meu.SetFingerprint(*s)
	}
	return meu
}

// SetTitle sets the "title" field.
func (meu *MonitorEventUpdate) SetTitle(s string) *MonitorEventUpdate {
	meu.mutation.SetTitle(s)
	return meu
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (meu *MonitorEventUpdate) SetNillableTitle(s *string) *MonitorEventUpdate {
	if s != nil {
		meu.SetTitle(*s)
	}
	return meu
}

// SetMessage sets the "message" field.
func (meu *MonitorEventUpdate) SetMessage(s string) *MonitorEventUpdate {
	meu.mutation.SetMessage(s)
	return meu
}

// SetNillableMessage sets the "message" field if the given value is not nil.
func (meu *MonitorEventUpdate) SetNillableMessage(s *string) *MonitorEventUpdate {
	if s != nil {
		meu.SetMessage(*s)
	}
	return meu
}

// SetAPIKeyID sets the "api_key_id" field.
func (meu *MonitorEventUpdate) SetAPIKeyID(i int) *MonitorEventUpdate {
	meu.mutation.ResetAPIKeyID()
	meu.mutation.SetAPIKeyID(i)
	return meu
}

// SetNillableAPIKeyID sets the "api_key_id" field if the given value is not nil.
func (meu *MonitorEventUpdate) SetNillableAPIKeyID(i *int) *MonitorEventUpdate {
	if i != nil {
		meu.SetAPIKeyID(*i)
	}
	return meu
}

// AddAPIKeyID adds i to the "api_key_id" field.
func (meu *MonitorEventUpdate) AddAPIKeyID(i int) *MonitorEventUpdate {
	meu.mutation.AddAPIKeyID(i)
	return meu
}

// ClearAPIKeyID clears the value of the "api_key_id" field.
func (meu *MonitorEventUpdate) ClearAPIKeyID() *MonitorEventUpdate {
	meu.mutation.ClearAPIKeyID()
	return meu
}

// SetAPIKeyNameSnapshot sets the "api_key_name_snapshot" field.
func (meu *MonitorEventUpdate) SetAPIKeyNameSnapshot(s string) *MonitorEventUpdate {
	meu.mutation.SetAPIKeyNameSnapshot(s)
	return meu
}

// SetNillableAPIKeyNameSnapshot sets the "api_key_name_snapshot" field if the given value is not nil.
func (meu *MonitorEventUpdate) SetNillableAPIKeyNameSnapshot(s *string) *MonitorEventUpdate {
	if s != nil {
		meu.SetAPIKeyNameSnapshot(*s)
	}
	return meu
}

// SetUserID sets the "user_id" field.
func (meu *MonitorEventUpdate) SetUserID(i int) *MonitorEventUpdate {
	meu.mutation.ResetUserID()
	meu.mutation.SetUserID(i)
	return meu
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (meu *MonitorEventUpdate) SetNillableUserID(i *int) *MonitorEventUpdate {
	if i != nil {
		meu.SetUserID(*i)
	}
	return meu
}

// AddUserID adds i to the "user_id" field.
func (meu *MonitorEventUpdate) AddUserID(i int) *MonitorEventUpdate {
	meu.mutation.AddUserID(i)
	return meu
}

// ClearUserID clears the value of the "user_id" field.
func (meu *MonitorEventUpdate) ClearUserID() *MonitorEventUpdate {
	meu.mutation.ClearUserID()
	return meu
}

// SetUserEmailSnapshot sets the "user_email_snapshot" field.
func (meu *MonitorEventUpdate) SetUserEmailSnapshot(s string) *MonitorEventUpdate {
	meu.mutation.SetUserEmailSnapshot(s)
	return meu
}

// SetNillableUserEmailSnapshot sets the "user_email_snapshot" field if the given value is not nil.
func (meu *MonitorEventUpdate) SetNillableUserEmailSnapshot(s *string) *MonitorEventUpdate {
	if s != nil {
		meu.SetUserEmailSnapshot(*s)
	}
	return meu
}

// SetGroupID sets the "group_id" field.
func (meu *MonitorEventUpdate) SetGroupID(i int) *MonitorEventUpdate {
	meu.mutation.ResetGroupID()
	meu.mutation.SetGroupID(i)
	return meu
}

// SetNillableGroupID sets the "group_id" field if the given value is not nil.
func (meu *MonitorEventUpdate) SetNillableGroupID(i *int) *MonitorEventUpdate {
	if i != nil {
		meu.SetGroupID(*i)
	}
	return meu
}

// AddGroupID adds i to the "group_id" field.
func (meu *MonitorEventUpdate) AddGroupID(i int) *MonitorEventUpdate {
	meu.mutation.AddGroupID(i)
	return meu
}

// ClearGroupID clears the value of the "group_id" field.
func (meu *MonitorEventUpdate) ClearGroupID() *MonitorEventUpdate {
	meu.mutation.ClearGroupID()
	return meu
}

// SetAccountID sets the "account_id" field.
func (meu *MonitorEventUpdate) SetAccountID(i int) *MonitorEventUpdate {
	meu.mutation.ResetAccountID()
	meu.mutation.SetAccountID(i)
	return meu
}

// SetNillableAccountID sets the "account_id" field if the given value is not nil.
func (meu *MonitorEventUpdate) SetNillableAccountID(i *int) *MonitorEventUpdate {
	if i != nil {
		meu.SetAccountID(*i)
	}
	return meu
}

// AddAccountID adds i to the "account_id" field.
func (meu *MonitorEventUpdate) AddAccountID(i int) *MonitorEventUpdate {
	meu.mutation.AddAccountID(i)
	return meu
}

// ClearAccountID clears the value of the "account_id" field.
func (meu *MonitorEventUpdate) ClearAccountID() *MonitorEventUpdate {
	meu.mutation.ClearAccountID()
	return meu
}

// SetAccountNameSnapshot sets the "account_name_snapshot" field.
func (meu *MonitorEventUpdate) SetAccountNameSnapshot(s string) *MonitorEventUpdate {
	meu.mutation.SetAccountNameSnapshot(s)
	return meu
}

// SetNillableAccountNameSnapshot sets the "account_name_snapshot" field if the given value is not nil.
func (meu *MonitorEventUpdate) SetNillableAccountNameSnapshot(s *string) *MonitorEventUpdate {
	if s != nil {
		meu.SetAccountNameSnapshot(*s)
	}
	return meu
}

// SetPlatform sets the "platform" field.
func (meu *MonitorEventUpdate) SetPlatform(s string) *MonitorEventUpdate {
	meu.mutation.SetPlatform(s)
	return meu
}

// SetNillablePlatform sets the "platform" field if the given value is not nil.
func (meu *MonitorEventUpdate) SetNillablePlatform(s *string) *MonitorEventUpdate {
	if s != nil {
		meu.SetPlatform(*s)
	}
	return meu
}

// SetPluginID sets the "plugin_id" field.
func (meu *MonitorEventUpdate) SetPluginID(s string) *MonitorEventUpdate {
	meu.mutation.SetPluginID(s)
	return meu
}

// SetNillablePluginID sets the "plugin_id" field if the given value is not nil.
func (meu *MonitorEventUpdate) SetNillablePluginID(s *string) *MonitorEventUpdate {
	if s != nil {
		meu.SetPluginID(*s)
	}
	return meu
}

// SetTaskType sets the "task_type" field.
func (meu *MonitorEventUpdate) SetTaskType(s string) *MonitorEventUpdate {
	meu.mutation.SetTaskType(s)
	return meu
}

// SetNillableTaskType sets the "task_type" field if the given value is not nil.
func (meu *MonitorEventUpdate) SetNillableTaskType(s *string) *MonitorEventUpdate {
	if s != nil {
		meu.SetTaskType(*s)
	}
	return meu
}

// SetMethod sets the "method" field.
func (meu *MonitorEventUpdate) SetMethod(s string) *MonitorEventUpdate {
	meu.mutation.SetMethod(s)
	return meu
}

// SetNillableMethod sets the "method" field if the given value is not nil.
func (meu *MonitorEventUpdate) SetNillableMethod(s *string) *MonitorEventUpdate {
	if s != nil {
		meu.SetMethod(*s)
	}
	return meu
}

// SetEndpoint sets the "endpoint" field.
func (meu *MonitorEventUpdate) SetEndpoint(s string) *MonitorEventUpdate {
	meu.mutation.SetEndpoint(s)
	return meu
}

// SetNillableEndpoint sets the "endpoint" field if the given value is not nil.
func (meu *MonitorEventUpdate) SetNillableEndpoint(s *string) *MonitorEventUpdate {
	if s != nil {
		meu.SetEndpoint(*s)
	}
	return meu
}

// SetModel sets the "model" field.
func (meu *MonitorEventUpdate) SetModel(s string) *MonitorEventUpdate {
	meu.mutation.SetModel(s)
	return meu
}

// SetNillableModel sets the "model" field if the given value is not nil.
func (meu *MonitorEventUpdate) SetNillableModel(s *string) *MonitorEventUpdate {
	if s != nil {
		meu.SetModel(*s)
	}
	return meu
}

// SetHTTPStatus sets the "http_status" field.
func (meu *MonitorEventUpdate) SetHTTPStatus(i int) *MonitorEventUpdate {
	meu.mutation.ResetHTTPStatus()
	meu.mutation.SetHTTPStatus(i)
	return meu
}

// SetNillableHTTPStatus sets the "http_status" field if the given value is not nil.
func (meu *MonitorEventUpdate) SetNillableHTTPStatus(i *int) *MonitorEventUpdate {
	if i != nil {
		meu.SetHTTPStatus(*i)
	}
	return meu
}

// AddHTTPStatus adds i to the "http_status" field.
func (meu *MonitorEventUpdate) AddHTTPStatus(i int) *MonitorEventUpdate {
	meu.mutation.AddHTTPStatus(i)
	return meu
}

// ClearHTTPStatus clears the value of the "http_status" field.
func (meu *MonitorEventUpdate) ClearHTTPStatus() *MonitorEventUpdate {
	meu.mutation.ClearHTTPStatus()
	return meu
}

// SetUpstreamStatus sets the "upstream_status" field.
func (meu *MonitorEventUpdate) SetUpstreamStatus(i int) *MonitorEventUpdate {
	meu.mutation.ResetUpstreamStatus()
	meu.mutation.SetUpstreamStatus(i)
	return meu
}

// SetNillableUpstreamStatus sets the "upstream_status" field if the given value is not nil.
func (meu *MonitorEventUpdate) SetNillableUpstreamStatus(i *int) *MonitorEventUpdate {
	if i != nil {
		meu.SetUpstreamStatus(*i)
	}
	return meu
}

// AddUpstreamStatus adds i to the "upstream_status" field.
func (meu *MonitorEventUpdate) AddUpstreamStatus(i int) *MonitorEventUpdate {
	meu.mutation.AddUpstreamStatus(i)
	return meu
}

// ClearUpstreamStatus clears the value of the "upstream_status" field.
func (meu *MonitorEventUpdate) ClearUpstreamStatus() *MonitorEventUpdate {
	meu.mutation.ClearUpstreamStatus()
	return meu
}

// SetErrorCode sets the "error_code" field.
func (meu *MonitorEventUpdate) SetErrorCode(s string) *MonitorEventUpdate {
	meu.mutation.SetErrorCode(s)
	return meu
}

// SetNillableErrorCode sets the "error_code" field if the given value is not nil.
func (meu *MonitorEventUpdate) SetNillableErrorCode(s *string) *MonitorEventUpdate {
	if s != nil {
		meu.SetErrorCode(*s)
	}
	return meu
}

// SetCreatedAt sets the "created_at" field.
func (meu *MonitorEventUpdate) SetCreatedAt(t time.Time) *MonitorEventUpdate {
	meu.mutation.SetCreatedAt(t)
	return meu
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (meu *MonitorEventUpdate) SetNillableCreatedAt(t *time.Time) *MonitorEventUpdate {
	if t != nil {
		meu.SetCreatedAt(*t)
	}
	return meu
}

// SetUpdatedAt sets the "updated_at" field.
func (meu *MonitorEventUpdate) SetUpdatedAt(t time.Time) *MonitorEventUpdate {
	meu.mutation.SetUpdatedAt(t)
	return meu
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (meu *MonitorEventUpdate) SetNillableUpdatedAt(t *time.Time) *MonitorEventUpdate {
	if t != nil {
		meu.SetUpdatedAt(*t)
	}
	return meu
}

// SetResolvedAt sets the "resolved_at" field.
func (meu *MonitorEventUpdate) SetResolvedAt(t time.Time) *MonitorEventUpdate {
	meu.mutation.SetResolvedAt(t)
	return meu
}

// SetNillableResolvedAt sets the "resolved_at" field if the given value is not nil.
func (meu *MonitorEventUpdate) SetNillableResolvedAt(t *time.Time) *MonitorEventUpdate {
	if t != nil {
		meu.SetResolvedAt(*t)
	}
	return meu
}

// ClearResolvedAt clears the value of the "resolved_at" field.
func (meu *MonitorEventUpdate) ClearResolvedAt() *MonitorEventUpdate {
	meu.mutation.ClearResolvedAt()
	return meu
}

// SetIgnoredAt sets the "ignored_at" field.
func (meu *MonitorEventUpdate) SetIgnoredAt(t time.Time) *MonitorEventUpdate {
	meu.mutation.SetIgnoredAt(t)
	return meu
}

// SetNillableIgnoredAt sets the "ignored_at" field if the given value is not nil.
func (meu *MonitorEventUpdate) SetNillableIgnoredAt(t *time.Time) *MonitorEventUpdate {
	if t != nil {
		meu.SetIgnoredAt(*t)
	}
	return meu
}

// ClearIgnoredAt clears the value of the "ignored_at" field.
func (meu *MonitorEventUpdate) ClearIgnoredAt() *MonitorEventUpdate {
	meu.mutation.ClearIgnoredAt()
	return meu
}

// SetAutoResolveAt sets the "auto_resolve_at" field.
func (meu *MonitorEventUpdate) SetAutoResolveAt(t time.Time) *MonitorEventUpdate {
	meu.mutation.SetAutoResolveAt(t)
	return meu
}

// SetNillableAutoResolveAt sets the "auto_resolve_at" field if the given value is not nil.
func (meu *MonitorEventUpdate) SetNillableAutoResolveAt(t *time.Time) *MonitorEventUpdate {
	if t != nil {
		meu.SetAutoResolveAt(*t)
	}
	return meu
}

// ClearAutoResolveAt clears the value of the "auto_resolve_at" field.
func (meu *MonitorEventUpdate) ClearAutoResolveAt() *MonitorEventUpdate {
	meu.mutation.ClearAutoResolveAt()
	return meu
}

// SetExpiresAt sets the "expires_at" field.
func (meu *MonitorEventUpdate) SetExpiresAt(t time.Time) *MonitorEventUpdate {
	meu.mutation.SetExpiresAt(t)
	return meu
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (meu *MonitorEventUpdate) SetNillableExpiresAt(t *time.Time) *MonitorEventUpdate {
	if t != nil {
		meu.SetExpiresAt(*t)
	}
	return meu
}

// SetLastNotifiedAt sets the "last_notified_at" field.
func (meu *MonitorEventUpdate) SetLastNotifiedAt(t time.Time) *MonitorEventUpdate {
	meu.mutation.SetLastNotifiedAt(t)
	return meu
}

// SetNillableLastNotifiedAt sets the "last_notified_at" field if the given value is not nil.
func (meu *MonitorEventUpdate) SetNillableLastNotifiedAt(t *time.Time) *MonitorEventUpdate {
	if t != nil {
		meu.SetLastNotifiedAt(*t)
	}
	return meu
}

// ClearLastNotifiedAt clears the value of the "last_notified_at" field.
func (meu *MonitorEventUpdate) ClearLastNotifiedAt() *MonitorEventUpdate {
	meu.mutation.ClearLastNotifiedAt()
	return meu
}

// SetNextNotifyAt sets the "next_notify_at" field.
func (meu *MonitorEventUpdate) SetNextNotifyAt(t time.Time) *MonitorEventUpdate {
	meu.mutation.SetNextNotifyAt(t)
	return meu
}

// SetNillableNextNotifyAt sets the "next_notify_at" field if the given value is not nil.
func (meu *MonitorEventUpdate) SetNillableNextNotifyAt(t *time.Time) *MonitorEventUpdate {
	if t != nil {
		meu.SetNextNotifyAt(*t)
	}
	return meu
}

// ClearNextNotifyAt clears the value of the "next_notify_at" field.
func (meu *MonitorEventUpdate) ClearNextNotifyAt() *MonitorEventUpdate {
	meu.mutation.ClearNextNotifyAt()
	return meu
}

// SetNotifyError sets the "notify_error" field.
func (meu *MonitorEventUpdate) SetNotifyError(s string) *MonitorEventUpdate {
	meu.mutation.SetNotifyError(s)
	return meu
}

// SetNillableNotifyError sets the "notify_error" field if the given value is not nil.
func (meu *MonitorEventUpdate) SetNillableNotifyError(s *string) *MonitorEventUpdate {
	if s != nil {
		meu.SetNotifyError(*s)
	}
	return meu
}

// SetDetail sets the "detail" field.
func (meu *MonitorEventUpdate) SetDetail(m map[string]interface{}) *MonitorEventUpdate {
	meu.mutation.SetDetail(m)
	return meu
}

// ClearDetail clears the value of the "detail" field.
func (meu *MonitorEventUpdate) ClearDetail() *MonitorEventUpdate {
	meu.mutation.ClearDetail()
	return meu
}

// Mutation returns the MonitorEventMutation object of the builder.
func (meu *MonitorEventUpdate) Mutation() *MonitorEventMutation {
	return meu.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (meu *MonitorEventUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, meu.sqlSave, meu.mutation, meu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (meu *MonitorEventUpdate) SaveX(ctx context.Context) int {
	affected, err := meu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (meu *MonitorEventUpdate) Exec(ctx context.Context) error {
	_, err := meu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (meu *MonitorEventUpdate) ExecX(ctx context.Context) {
	if err := meu.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (meu *MonitorEventUpdate) check() error {
	if v, ok := meu.mutation.GetType(); ok {
		if err := monitorevent.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "MonitorEvent.type": %w`, err)}
		}
	}
	if v, ok := meu.mutation.Severity(); ok {
		if err := monitorevent.SeverityValidator(v); err != nil {
			return &ValidationError{Name: "severity", err: fmt.Errorf(`ent: validator failed for field "MonitorEvent.severity": %w`, err)}
		}
	}
	if v, ok := meu.mutation.Status(); ok {
		if err := monitorevent.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "MonitorEvent.status": %w`, err)}
		}
	}
	if v, ok := meu.mutation.Source(); ok {
		if err := monitorevent.SourceValidator(v); err != nil {
			return &ValidationError{Name: "source", err: fmt.Errorf(`ent: validator failed for field "MonitorEvent.source": %w`, err)}
		}
	}
	if v, ok := meu.mutation.SubjectType(); ok {
		if err := monitorevent.SubjectTypeValidator(v); err != nil {
			return &ValidationError{Name: "subject_type", err: fmt.Errorf(`ent: validator failed for field "MonitorEvent.subject_type": %w`, err)}
		}
	}
	if v, ok := meu.mutation.SubjectID(); ok {
		if err := monitorevent.SubjectIDValidator(v); err != nil {
			return &ValidationError{Name: "subject_id", err: fmt.Errorf(`ent: validator failed for field "MonitorEvent.subject_id": %w`, err)}
		}
	}
	if v, ok := meu.mutation.Fingerprint(); ok {
		if err := monitorevent.FingerprintValidator(v); err != nil {
			return &ValidationError{Name: "fingerprint", err: fmt.Errorf(`ent: validator failed for field "MonitorEvent.fingerprint": %w`, err)}
		}
	}
	if v, ok := meu.mutation.Title(); ok {
		if err := monitorevent.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "MonitorEvent.title": %w`, err)}
		}
	}
	if v, ok := meu.mutation.Message(); ok {
		if err := monitorevent.MessageValidator(v); err != nil {
			return &ValidationError{Name: "message", err: fmt.Errorf(`ent: validator failed for field "MonitorEvent.message": %w`, err)}
		}
	}
	if v, ok := meu.mutation.APIKeyNameSnapshot(); ok {
		if err := monitorevent.APIKeyNameSnapshotValidator(v); err != nil {
			return &ValidationError{Name: "api_key_name_snapshot", err: fmt.Errorf(`ent: validator failed for field "MonitorEvent.api_key_name_snapshot": %w`, err)}
		}
	}
	if v, ok := meu.mutation.UserEmailSnapshot(); ok {
		if err := monitorevent.UserEmailSnapshotValidator(v); err != nil {
			return &ValidationError{Name: "user_email_snapshot", err: fmt.Errorf(`ent: validator failed for field "MonitorEvent.user_email_snapshot": %w`, err)}
		}
	}
	if v, ok := meu.mutation.AccountNameSnapshot(); ok {
		if err := monitorevent.AccountNameSnapshotValidator(v); err != nil {
			return &ValidationError{Name: "account_name_snapshot", err: fmt.Errorf(`ent: validator failed for field "MonitorEvent.account_name_snapshot": %w`, err)}
		}
	}
	if v, ok := meu.mutation.Platform(); ok {
		if err := monitorevent.PlatformValidator(v); err != nil {
			return &ValidationError{Name: "platform", err: fmt.Errorf(`ent: validator failed for field "MonitorEvent.platform": %w`, err)}
		}
	}
	if v, ok := meu.mutation.PluginID(); ok {
		if err := monitorevent.PluginIDValidator(v); err != nil {
			return &ValidationError{Name: "plugin_id", err: fmt.Errorf(`ent: validator failed for field "MonitorEvent.plugin_id": %w`, err)}
		}
	}
	if v, ok := meu.mutation.TaskType(); ok {
		if err := monitorevent.TaskTypeValidator(v); err != nil {
			return &ValidationError{Name: "task_type", err: fmt.Errorf(`ent: validator failed for field "MonitorEvent.task_type": %w`, err)}
		}
	}
	if v, ok := meu.mutation.Method(); ok {
		if err := monitorevent.MethodValidator(v); err != nil {
			return &ValidationError{Name: "method", err: fmt.Errorf(`ent: validator failed for field "MonitorEvent.method": %w`, err)}
		}
	}
	if v, ok := meu.mutation.Endpoint(); ok {
		if err := monitorevent.EndpointValidator(v); err != nil {
			return &ValidationError{Name: "endpoint", err: fmt.Errorf(`ent: validator failed for field "MonitorEvent.endpoint": %w`, err)}
		}
	}
	if v, ok := meu.mutation.Model(); ok {
		if err := monitorevent.ModelValidator(v); err != nil {
			return &ValidationError{Name: "model", err: fmt.Errorf(`ent: validator failed for field "MonitorEvent.model": %w`, err)}
		}
	}
	if v, ok := meu.mutation.ErrorCode(); ok {
		if err := monitorevent.ErrorCodeValidator(v); err != nil {
			return &ValidationError{Name: "error_code", err: fmt.Errorf(`ent: validator failed for field "MonitorEvent.error_code": %w`, err)}
		}
	}
	if v, ok := meu.mutation.NotifyError(); ok {
		if err := monitorevent.NotifyErrorValidator(v); err != nil {
			return &ValidationError{Name: "notify_error", err: fmt.Errorf(`ent: validator failed for field "MonitorEvent.notify_error": %w`, err)}
		}
	}
	return nil
}

func (meu *MonitorEventUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := meu.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(monitorevent.Table, monitorevent.Columns, sqlgraph.NewFieldSpec(monitorevent.FieldID, field.TypeInt))
	if ps := meu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := meu.mutation.GetType(); ok {
		_spec.SetField(monitorevent.FieldType, field.TypeEnum, value)
	}
	if value, ok := meu.mutation.Severity(); ok {
		_spec.SetField(monitorevent.FieldSeverity, field.TypeEnum, value)
	}
	if value, ok := meu.mutation.Status(); ok {
		_spec.SetField(monitorevent.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := meu.mutation.Source(); ok {
		_spec.SetField(monitorevent.FieldSource, field.TypeString, value)
	}
	if value, ok := meu.mutation.SubjectType(); ok {
		_spec.SetField(monitorevent.FieldSubjectType, field.TypeString, value)
	}
	if value, ok := meu.mutation.SubjectID(); ok {
		_spec.SetField(monitorevent.FieldSubjectID, field.TypeString, value)
	}
	if value, ok := meu.mutation.Fingerprint(); ok {
		_spec.SetField(monitorevent.FieldFingerprint, field.TypeString, value)
	}
	if value, ok := meu.mutation.Title(); ok {
		_spec.SetField(monitorevent.FieldTitle, field.TypeString, value)
	}
	if value, ok := meu.mutation.Message(); ok {
		_spec.SetField(monitorevent.FieldMessage, field.TypeString, value)
	}
	if value, ok := meu.mutation.APIKeyID(); ok {
		_spec.SetField(monitorevent.FieldAPIKeyID, field.TypeInt, value)
	}
	if value, ok := meu.mutation.AddedAPIKeyID(); ok {
		_spec.AddField(monitorevent.FieldAPIKeyID, field.TypeInt, value)
	}
	if meu.mutation.APIKeyIDCleared() {
		_spec.ClearField(monitorevent.FieldAPIKeyID, field.TypeInt)
	}
	if value, ok := meu.mutation.APIKeyNameSnapshot(); ok {
		_spec.SetField(monitorevent.FieldAPIKeyNameSnapshot, field.TypeString, value)
	}
	if value, ok := meu.mutation.UserID(); ok {
		_spec.SetField(monitorevent.FieldUserID, field.TypeInt, value)
	}
	if value, ok := meu.mutation.AddedUserID(); ok {
		_spec.AddField(monitorevent.FieldUserID, field.TypeInt, value)
	}
	if meu.mutation.UserIDCleared() {
		_spec.ClearField(monitorevent.FieldUserID, field.TypeInt)
	}
	if value, ok := meu.mutation.UserEmailSnapshot(); ok {
		_spec.SetField(monitorevent.FieldUserEmailSnapshot, field.TypeString, value)
	}
	if value, ok := meu.mutation.GroupID(); ok {
		_spec.SetField(monitorevent.FieldGroupID, field.TypeInt, value)
	}
	if value, ok := meu.mutation.AddedGroupID(); ok {
		_spec.AddField(monitorevent.FieldGroupID, field.TypeInt, value)
	}
	if meu.mutation.GroupIDCleared() {
		_spec.ClearField(monitorevent.FieldGroupID, field.TypeInt)
	}
	if value, ok := meu.mutation.AccountID(); ok {
		_spec.SetField(monitorevent.FieldAccountID, field.TypeInt, value)
	}
	if value, ok := meu.mutation.AddedAccountID(); ok {
		_spec.AddField(monitorevent.FieldAccountID, field.TypeInt, value)
	}
	if meu.mutation.AccountIDCleared() {
		_spec.ClearField(monitorevent.FieldAccountID, field.TypeInt)
	}
	if value, ok := meu.mutation.AccountNameSnapshot(); ok {
		_spec.SetField(monitorevent.FieldAccountNameSnapshot, field.TypeString, value)
	}
	if value, ok := meu.mutation.Platform(); ok {
		_spec.SetField(monitorevent.FieldPlatform, field.TypeString, value)
	}
	if value, ok := meu.mutation.PluginID(); ok {
		_spec.SetField(monitorevent.FieldPluginID, field.TypeString, value)
	}
	if value, ok := meu.mutation.TaskType(); ok {
		_spec.SetField(monitorevent.FieldTaskType, field.TypeString, value)
	}
	if value, ok := meu.mutation.Method(); ok {
		_spec.SetField(monitorevent.FieldMethod, field.TypeString, value)
	}
	if value, ok := meu.mutation.Endpoint(); ok {
		_spec.SetField(monitorevent.FieldEndpoint, field.TypeString, value)
	}
	if value, ok := meu.mutation.Model(); ok {
		_spec.SetField(monitorevent.FieldModel, field.TypeString, value)
	}
	if value, ok := meu.mutation.HTTPStatus(); ok {
		_spec.SetField(monitorevent.FieldHTTPStatus, field.TypeInt, value)
	}
	if value, ok := meu.mutation.AddedHTTPStatus(); ok {
		_spec.AddField(monitorevent.FieldHTTPStatus, field.TypeInt, value)
	}
	if meu.mutation.HTTPStatusCleared() {
		_spec.ClearField(monitorevent.FieldHTTPStatus, field.TypeInt)
	}
	if value, ok := meu.mutation.UpstreamStatus(); ok {
		_spec.SetField(monitorevent.FieldUpstreamStatus, field.TypeInt, value)
	}
	if value, ok := meu.mutation.AddedUpstreamStatus(); ok {
		_spec.AddField(monitorevent.FieldUpstreamStatus, field.TypeInt, value)
	}
	if meu.mutation.UpstreamStatusCleared() {
		_spec.ClearField(monitorevent.FieldUpstreamStatus, field.TypeInt)
	}
	if value, ok := meu.mutation.ErrorCode(); ok {
		_spec.SetField(monitorevent.FieldErrorCode, field.TypeString, value)
	}
	if value, ok := meu.mutation.CreatedAt(); ok {
		_spec.SetField(monitorevent.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := meu.mutation.UpdatedAt(); ok {
		_spec.SetField(monitorevent.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := meu.mutation.ResolvedAt(); ok {
		_spec.SetField(monitorevent.FieldResolvedAt, field.TypeTime, value)
	}
	if meu.mutation.ResolvedAtCleared() {
		_spec.ClearField(monitorevent.FieldResolvedAt, field.TypeTime)
	}
	if value, ok := meu.mutation.IgnoredAt(); ok {
		_spec.SetField(monitorevent.FieldIgnoredAt, field.TypeTime, value)
	}
	if meu.mutation.IgnoredAtCleared() {
		_spec.ClearField(monitorevent.FieldIgnoredAt, field.TypeTime)
	}
	if value, ok := meu.mutation.AutoResolveAt(); ok {
		_spec.SetField(monitorevent.FieldAutoResolveAt, field.TypeTime, value)
	}
	if meu.mutation.AutoResolveAtCleared() {
		_spec.ClearField(monitorevent.FieldAutoResolveAt, field.TypeTime)
	}
	if value, ok := meu.mutation.ExpiresAt(); ok {
		_spec.SetField(monitorevent.FieldExpiresAt, field.TypeTime, value)
	}
	if value, ok := meu.mutation.LastNotifiedAt(); ok {
		_spec.SetField(monitorevent.FieldLastNotifiedAt, field.TypeTime, value)
	}
	if meu.mutation.LastNotifiedAtCleared() {
		_spec.ClearField(monitorevent.FieldLastNotifiedAt, field.TypeTime)
	}
	if value, ok := meu.mutation.NextNotifyAt(); ok {
		_spec.SetField(monitorevent.FieldNextNotifyAt, field.TypeTime, value)
	}
	if meu.mutation.NextNotifyAtCleared() {
		_spec.ClearField(monitorevent.FieldNextNotifyAt, field.TypeTime)
	}
	if value, ok := meu.mutation.NotifyError(); ok {
		_spec.SetField(monitorevent.FieldNotifyError, field.TypeString, value)
	}
	if value, ok := meu.mutation.Detail(); ok {
		_spec.SetField(monitorevent.FieldDetail, field.TypeJSON, value)
	}
	if meu.mutation.DetailCleared() {
		_spec.ClearField(monitorevent.FieldDetail, field.TypeJSON)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, meu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{monitorevent.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	meu.mutation.done = true
	return n, nil
}

// MonitorEventUpdateOne is the builder for updating a single MonitorEvent entity.
type MonitorEventUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *MonitorEventMutation
}

// SetType sets the "type" field.
func (meuo *MonitorEventUpdateOne) SetType(m monitorevent.Type) *MonitorEventUpdateOne {
	meuo.mutation.SetType(m)
	return meuo
}

// SetNillableType sets the "type" field if the given value is not nil.
func (meuo *MonitorEventUpdateOne) SetNillableType(m *monitorevent.Type) *MonitorEventUpdateOne {
	if m != nil {
		meuo.SetType(*m)
	}
	return meuo
}

// SetSeverity sets the "severity" field.
func (meuo *MonitorEventUpdateOne) SetSeverity(m monitorevent.Severity) *MonitorEventUpdateOne {
	meuo.mutation.SetSeverity(m)
	return meuo
}

// SetNillableSeverity sets the "severity" field if the given value is not nil.
func (meuo *MonitorEventUpdateOne) SetNillableSeverity(m *monitorevent.Severity) *MonitorEventUpdateOne {
	if m != nil {
		meuo.SetSeverity(*m)
	}
	return meuo
}

// SetStatus sets the "status" field.
func (meuo *MonitorEventUpdateOne) SetStatus(m monitorevent.Status) *MonitorEventUpdateOne {
	meuo.mutation.SetStatus(m)
	return meuo
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (meuo *MonitorEventUpdateOne) SetNillableStatus(m *monitorevent.Status) *MonitorEventUpdateOne {
	if m != nil {
		meuo.SetStatus(*m)
	}
	return meuo
}

// SetSource sets the "source" field.
func (meuo *MonitorEventUpdateOne) SetSource(s string) *MonitorEventUpdateOne {
	meuo.mutation.SetSource(s)
	return meuo
}

// SetNillableSource sets the "source" field if the given value is not nil.
func (meuo *MonitorEventUpdateOne) SetNillableSource(s *string) *MonitorEventUpdateOne {
	if s != nil {
		meuo.SetSource(*s)
	}
	return meuo
}

// SetSubjectType sets the "subject_type" field.
func (meuo *MonitorEventUpdateOne) SetSubjectType(s string) *MonitorEventUpdateOne {
	meuo.mutation.SetSubjectType(s)
	return meuo
}

// SetNillableSubjectType sets the "subject_type" field if the given value is not nil.
func (meuo *MonitorEventUpdateOne) SetNillableSubjectType(s *string) *MonitorEventUpdateOne {
	if s != nil {
		meuo.SetSubjectType(*s)
	}
	return meuo
}

// SetSubjectID sets the "subject_id" field.
func (meuo *MonitorEventUpdateOne) SetSubjectID(s string) *MonitorEventUpdateOne {
	meuo.mutation.SetSubjectID(s)
	return meuo
}

// SetNillableSubjectID sets the "subject_id" field if the given value is not nil.
func (meuo *MonitorEventUpdateOne) SetNillableSubjectID(s *string) *MonitorEventUpdateOne {
	if s != nil {
		meuo.SetSubjectID(*s)
	}
	return meuo
}

// SetFingerprint sets the "fingerprint" field.
func (meuo *MonitorEventUpdateOne) SetFingerprint(s string) *MonitorEventUpdateOne {
	meuo.mutation.SetFingerprint(s)
	return meuo
}

// SetNillableFingerprint sets the "fingerprint" field if the given value is not nil.
func (meuo *MonitorEventUpdateOne) SetNillableFingerprint(s *string) *MonitorEventUpdateOne {
	if s != nil {
		meuo.SetFingerprint(*s)
	}
	return meuo
}

// SetTitle sets the "title" field.
func (meuo *MonitorEventUpdateOne) SetTitle(s string) *MonitorEventUpdateOne {
	meuo.mutation.SetTitle(s)
	return meuo
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (meuo *MonitorEventUpdateOne) SetNillableTitle(s *string) *MonitorEventUpdateOne {
	if s != nil {
		meuo.SetTitle(*s)
	}
	return meuo
}

// SetMessage sets the "message" field.
func (meuo *MonitorEventUpdateOne) SetMessage(s string) *MonitorEventUpdateOne {
	meuo.mutation.SetMessage(s)
	return meuo
}

// SetNillableMessage sets the "message" field if the given value is not nil.
func (meuo *MonitorEventUpdateOne) SetNillableMessage(s *string) *MonitorEventUpdateOne {
	if s != nil {
		meuo.SetMessage(*s)
	}
	return meuo
}

// SetAPIKeyID sets the "api_key_id" field.
func (meuo *MonitorEventUpdateOne) SetAPIKeyID(i int) *MonitorEventUpdateOne {
	meuo.mutation.ResetAPIKeyID()
	meuo.mutation.SetAPIKeyID(i)
	return meuo
}

// SetNillableAPIKeyID sets the "api_key_id" field if the given value is not nil.
func (meuo *MonitorEventUpdateOne) SetNillableAPIKeyID(i *int) *MonitorEventUpdateOne {
	if i != nil {
		meuo.SetAPIKeyID(*i)
	}
	return meuo
}

// AddAPIKeyID adds i to the "api_key_id" field.
func (meuo *MonitorEventUpdateOne) AddAPIKeyID(i int) *MonitorEventUpdateOne {
	meuo.mutation.AddAPIKeyID(i)
	return meuo
}

// ClearAPIKeyID clears the value of the "api_key_id" field.
func (meuo *MonitorEventUpdateOne) ClearAPIKeyID() *MonitorEventUpdateOne {
	meuo.mutation.ClearAPIKeyID()
	return meuo
}

// SetAPIKeyNameSnapshot sets the "api_key_name_snapshot" field.
func (meuo *MonitorEventUpdateOne) SetAPIKeyNameSnapshot(s string) *MonitorEventUpdateOne {
	meuo.mutation.SetAPIKeyNameSnapshot(s)
	return meuo
}

// SetNillableAPIKeyNameSnapshot sets the "api_key_name_snapshot" field if the given value is not nil.
func (meuo *MonitorEventUpdateOne) SetNillableAPIKeyNameSnapshot(s *string) *MonitorEventUpdateOne {
	if s != nil {
		meuo.SetAPIKeyNameSnapshot(*s)
	}
	return meuo
}

// SetUserID sets the "user_id" field.
func (meuo *MonitorEventUpdateOne) SetUserID(i int) *MonitorEventUpdateOne {
	meuo.mutation.ResetUserID()
	meuo.mutation.SetUserID(i)
	return meuo
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (meuo *MonitorEventUpdateOne) SetNillableUserID(i *int) *MonitorEventUpdateOne {
	if i != nil {
		meuo.SetUserID(*i)
	}
	return meuo
}

// AddUserID adds i to the "user_id" field.
func (meuo *MonitorEventUpdateOne) AddUserID(i int) *MonitorEventUpdateOne {
	meuo.mutation.AddUserID(i)
	return meuo
}

// ClearUserID clears the value of the "user_id" field.
func (meuo *MonitorEventUpdateOne) ClearUserID() *MonitorEventUpdateOne {
	meuo.mutation.ClearUserID()
	return meuo
}

// SetUserEmailSnapshot sets the "user_email_snapshot" field.
func (meuo *MonitorEventUpdateOne) SetUserEmailSnapshot(s string) *MonitorEventUpdateOne {
	meuo.mutation.SetUserEmailSnapshot(s)
	return meuo
}

// SetNillableUserEmailSnapshot sets the "user_email_snapshot" field if the given value is not nil.
func (meuo *MonitorEventUpdateOne) SetNillableUserEmailSnapshot(s *string) *MonitorEventUpdateOne {
	if s != nil {
		meuo.SetUserEmailSnapshot(*s)
	}
	return meuo
}

// SetGroupID sets the "group_id" field.
func (meuo *MonitorEventUpdateOne) SetGroupID(i int) *MonitorEventUpdateOne {
	meuo.mutation.ResetGroupID()
	meuo.mutation.SetGroupID(i)
	return meuo
}

// SetNillableGroupID sets the "group_id" field if the given value is not nil.
func (meuo *MonitorEventUpdateOne) SetNillableGroupID(i *int) *MonitorEventUpdateOne {
	if i != nil {
		meuo.SetGroupID(*i)
	}
	return meuo
}

// AddGroupID adds i to the "group_id" field.
func (meuo *MonitorEventUpdateOne) AddGroupID(i int) *MonitorEventUpdateOne {
	meuo.mutation.AddGroupID(i)
	return meuo
}

// ClearGroupID clears the value of the "group_id" field.
func (meuo *MonitorEventUpdateOne) ClearGroupID() *MonitorEventUpdateOne {
	meuo.mutation.ClearGroupID()
	return meuo
}

// SetAccountID sets the "account_id" field.
func (meuo *MonitorEventUpdateOne) SetAccountID(i int) *MonitorEventUpdateOne {
	meuo.mutation.ResetAccountID()
	meuo.mutation.SetAccountID(i)
	return meuo
}

// SetNillableAccountID sets the "account_id" field if the given value is not nil.
func (meuo *MonitorEventUpdateOne) SetNillableAccountID(i *int) *MonitorEventUpdateOne {
	if i != nil {
		meuo.SetAccountID(*i)
	}
	return meuo
}

// AddAccountID adds i to the "account_id" field.
func (meuo *MonitorEventUpdateOne) AddAccountID(i int) *MonitorEventUpdateOne {
	meuo.mutation.AddAccountID(i)
	return meuo
}

// ClearAccountID clears the value of the "account_id" field.
func (meuo *MonitorEventUpdateOne) ClearAccountID() *MonitorEventUpdateOne {
	meuo.mutation.ClearAccountID()
	return meuo
}

// SetAccountNameSnapshot sets the "account_name_snapshot" field.
func (meuo *MonitorEventUpdateOne) SetAccountNameSnapshot(s string) *MonitorEventUpdateOne {
	meuo.mutation.SetAccountNameSnapshot(s)
	return meuo
}

// SetNillableAccountNameSnapshot sets the "account_name_snapshot" field if the given value is not nil.
func (meuo *MonitorEventUpdateOne) SetNillableAccountNameSnapshot(s *string) *MonitorEventUpdateOne {
	if s != nil {
		meuo.SetAccountNameSnapshot(*s)
	}
	return meuo
}

// SetPlatform sets the "platform" field.
func (meuo *MonitorEventUpdateOne) SetPlatform(s string) *MonitorEventUpdateOne {
	meuo.mutation.SetPlatform(s)
	return meuo
}

// SetNillablePlatform sets the "platform" field if the given value is not nil.
func (meuo *MonitorEventUpdateOne) SetNillablePlatform(s *string) *MonitorEventUpdateOne {
	if s != nil {
		meuo.SetPlatform(*s)
	}
	return meuo
}

// SetPluginID sets the "plugin_id" field.
func (meuo *MonitorEventUpdateOne) SetPluginID(s string) *MonitorEventUpdateOne {
	meuo.mutation.SetPluginID(s)
	return meuo
}

// SetNillablePluginID sets the "plugin_id" field if the given value is not nil.
func (meuo *MonitorEventUpdateOne) SetNillablePluginID(s *string) *MonitorEventUpdateOne {
	if s != nil {
		meuo.SetPluginID(*s)
	}
	return meuo
}

// SetTaskType sets the "task_type" field.
func (meuo *MonitorEventUpdateOne) SetTaskType(s string) *MonitorEventUpdateOne {
	meuo.mutation.SetTaskType(s)
	return meuo
}

// SetNillableTaskType sets the "task_type" field if the given value is not nil.
func (meuo *MonitorEventUpdateOne) SetNillableTaskType(s *string) *MonitorEventUpdateOne {
	if s != nil {
		meuo.SetTaskType(*s)
	}
	return meuo
}

// SetMethod sets the "method" field.
func (meuo *MonitorEventUpdateOne) SetMethod(s string) *MonitorEventUpdateOne {
	meuo.mutation.SetMethod(s)
	return meuo
}

// SetNillableMethod sets the "method" field if the given value is not nil.
func (meuo *MonitorEventUpdateOne) SetNillableMethod(s *string) *MonitorEventUpdateOne {
	if s != nil {
		meuo.SetMethod(*s)
	}
	return meuo
}

// SetEndpoint sets the "endpoint" field.
func (meuo *MonitorEventUpdateOne) SetEndpoint(s string) *MonitorEventUpdateOne {
	meuo.mutation.SetEndpoint(s)
	return meuo
}

// SetNillableEndpoint sets the "endpoint" field if the given value is not nil.
func (meuo *MonitorEventUpdateOne) SetNillableEndpoint(s *string) *MonitorEventUpdateOne {
	if s != nil {
		meuo.SetEndpoint(*s)
	}
	return meuo
}

// SetModel sets the "model" field.
func (meuo *MonitorEventUpdateOne) SetModel(s string) *MonitorEventUpdateOne {
	meuo.mutation.SetModel(s)
	return meuo
}

// SetNillableModel sets the "model" field if the given value is not nil.
func (meuo *MonitorEventUpdateOne) SetNillableModel(s *string) *MonitorEventUpdateOne {
	if s != nil {
		meuo.SetModel(*s)
	}
	return meuo
}

// SetHTTPStatus sets the "http_status" field.
func (meuo *MonitorEventUpdateOne) SetHTTPStatus(i int) *MonitorEventUpdateOne {
	meuo.mutation.ResetHTTPStatus()
	meuo.mutation.SetHTTPStatus(i)
	return meuo
}

// SetNillableHTTPStatus sets the "http_status" field if the given value is not nil.
func (meuo *MonitorEventUpdateOne) SetNillableHTTPStatus(i *int) *MonitorEventUpdateOne {
	if i != nil {
		meuo.SetHTTPStatus(*i)
	}
	return meuo
}

// AddHTTPStatus adds i to the "http_status" field.
func (meuo *MonitorEventUpdateOne) AddHTTPStatus(i int) *MonitorEventUpdateOne {
	meuo.mutation.AddHTTPStatus(i)
	return meuo
}

// ClearHTTPStatus clears the value of the "http_status" field.
func (meuo *MonitorEventUpdateOne) ClearHTTPStatus() *MonitorEventUpdateOne {
	meuo.mutation.ClearHTTPStatus()
	return meuo
}

// SetUpstreamStatus sets the "upstream_status" field.
func (meuo *MonitorEventUpdateOne) SetUpstreamStatus(i int) *MonitorEventUpdateOne {
	meuo.mutation.ResetUpstreamStatus()
	meuo.mutation.SetUpstreamStatus(i)
	return meuo
}

// SetNillableUpstreamStatus sets the "upstream_status" field if the given value is not nil.
func (meuo *MonitorEventUpdateOne) SetNillableUpstreamStatus(i *int) *MonitorEventUpdateOne {
	if i != nil {
		meuo.SetUpstreamStatus(*i)
	}
	return meuo
}

// AddUpstreamStatus adds i to the "upstream_status" field.
func (meuo *MonitorEventUpdateOne) AddUpstreamStatus(i int) *MonitorEventUpdateOne {
	meuo.mutation.AddUpstreamStatus(i)
	return meuo
}

// ClearUpstreamStatus clears the value of the "upstream_status" field.
func (meuo *MonitorEventUpdateOne) ClearUpstreamStatus() *MonitorEventUpdateOne {
	meuo.mutation.ClearUpstreamStatus()
	return meuo
}

// SetErrorCode sets the "error_code" field.
func (meuo *MonitorEventUpdateOne) SetErrorCode(s string) *MonitorEventUpdateOne {
	meuo.mutation.SetErrorCode(s)
	return meuo
}

// SetNillableErrorCode sets the "error_code" field if the given value is not nil.
func (meuo *MonitorEventUpdateOne) SetNillableErrorCode(s *string) *MonitorEventUpdateOne {
	if s != nil {
		meuo.SetErrorCode(*s)
	}
	return meuo
}

// SetCreatedAt sets the "created_at" field.
func (meuo *MonitorEventUpdateOne) SetCreatedAt(t time.Time) *MonitorEventUpdateOne {
	meuo.mutation.SetCreatedAt(t)
	return meuo
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (meuo *MonitorEventUpdateOne) SetNillableCreatedAt(t *time.Time) *MonitorEventUpdateOne {
	if t != nil {
		meuo.SetCreatedAt(*t)
	}
	return meuo
}

// SetUpdatedAt sets the "updated_at" field.
func (meuo *MonitorEventUpdateOne) SetUpdatedAt(t time.Time) *MonitorEventUpdateOne {
	meuo.mutation.SetUpdatedAt(t)
	return meuo
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (meuo *MonitorEventUpdateOne) SetNillableUpdatedAt(t *time.Time) *MonitorEventUpdateOne {
	if t != nil {
		meuo.SetUpdatedAt(*t)
	}
	return meuo
}

// SetResolvedAt sets the "resolved_at" field.
func (meuo *MonitorEventUpdateOne) SetResolvedAt(t time.Time) *MonitorEventUpdateOne {
	meuo.mutation.SetResolvedAt(t)
	return meuo
}

// SetNillableResolvedAt sets the "resolved_at" field if the given value is not nil.
func (meuo *MonitorEventUpdateOne) SetNillableResolvedAt(t *time.Time) *MonitorEventUpdateOne {
	if t != nil {
		meuo.SetResolvedAt(*t)
	}
	return meuo
}

// ClearResolvedAt clears the value of the "resolved_at" field.
func (meuo *MonitorEventUpdateOne) ClearResolvedAt() *MonitorEventUpdateOne {
	meuo.mutation.ClearResolvedAt()
	return meuo
}

// SetIgnoredAt sets the "ignored_at" field.
func (meuo *MonitorEventUpdateOne) SetIgnoredAt(t time.Time) *MonitorEventUpdateOne {
	meuo.mutation.SetIgnoredAt(t)
	return meuo
}

// SetNillableIgnoredAt sets the "ignored_at" field if the given value is not nil.
func (meuo *MonitorEventUpdateOne) SetNillableIgnoredAt(t *time.Time) *MonitorEventUpdateOne {
	if t != nil {
		meuo.SetIgnoredAt(*t)
	}
	return meuo
}

// ClearIgnoredAt clears the value of the "ignored_at" field.
func (meuo *MonitorEventUpdateOne) ClearIgnoredAt() *MonitorEventUpdateOne {
	meuo.mutation.ClearIgnoredAt()
	return meuo
}

// SetAutoResolveAt sets the "auto_resolve_at" field.
func (meuo *MonitorEventUpdateOne) SetAutoResolveAt(t time.Time) *MonitorEventUpdateOne {
	meuo.mutation.SetAutoResolveAt(t)
	return meuo
}

// SetNillableAutoResolveAt sets the "auto_resolve_at" field if the given value is not nil.
func (meuo *MonitorEventUpdateOne) SetNillableAutoResolveAt(t *time.Time) *MonitorEventUpdateOne {
	if t != nil {
		meuo.SetAutoResolveAt(*t)
	}
	return meuo
}

// ClearAutoResolveAt clears the value of the "auto_resolve_at" field.
func (meuo *MonitorEventUpdateOne) ClearAutoResolveAt() *MonitorEventUpdateOne {
	meuo.mutation.ClearAutoResolveAt()
	return meuo
}

// SetExpiresAt sets the "expires_at" field.
func (meuo *MonitorEventUpdateOne) SetExpiresAt(t time.Time) *MonitorEventUpdateOne {
	meuo.mutation.SetExpiresAt(t)
	return meuo
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (meuo *MonitorEventUpdateOne) SetNillableExpiresAt(t *time.Time) *MonitorEventUpdateOne {
	if t != nil {
		meuo.SetExpiresAt(*t)
	}
	return meuo
}

// SetLastNotifiedAt sets the "last_notified_at" field.
func (meuo *MonitorEventUpdateOne) SetLastNotifiedAt(t time.Time) *MonitorEventUpdateOne {
	meuo.mutation.SetLastNotifiedAt(t)
	return meuo
}

// SetNillableLastNotifiedAt sets the "last_notified_at" field if the given value is not nil.
func (meuo *MonitorEventUpdateOne) SetNillableLastNotifiedAt(t *time.Time) *MonitorEventUpdateOne {
	if t != nil {
		meuo.SetLastNotifiedAt(*t)
	}
	return meuo
}

// ClearLastNotifiedAt clears the value of the "last_notified_at" field.
func (meuo *MonitorEventUpdateOne) ClearLastNotifiedAt() *MonitorEventUpdateOne {
	meuo.mutation.ClearLastNotifiedAt()
	return meuo
}

// SetNextNotifyAt sets the "next_notify_at" field.
func (meuo *MonitorEventUpdateOne) SetNextNotifyAt(t time.Time) *MonitorEventUpdateOne {
	meuo.mutation.SetNextNotifyAt(t)
	return meuo
}

// SetNillableNextNotifyAt sets the "next_notify_at" field if the given value is not nil.
func (meuo *MonitorEventUpdateOne) SetNillableNextNotifyAt(t *time.Time) *MonitorEventUpdateOne {
	if t != nil {
		meuo.SetNextNotifyAt(*t)
	}
	return meuo
}

// ClearNextNotifyAt clears the value of the "next_notify_at" field.
func (meuo *MonitorEventUpdateOne) ClearNextNotifyAt() *MonitorEventUpdateOne {
	meuo.mutation.ClearNextNotifyAt()
	return meuo
}

// SetNotifyError sets the "notify_error" field.
func (meuo *MonitorEventUpdateOne) SetNotifyError(s string) *MonitorEventUpdateOne {
	meuo.mutation.SetNotifyError(s)
	return meuo
}

// SetNillableNotifyError sets the "notify_error" field if the given value is not nil.
func (meuo *MonitorEventUpdateOne) SetNillableNotifyError(s *string) *MonitorEventUpdateOne {
	if s != nil {
		meuo.SetNotifyError(*s)
	}
	return meuo
}

// SetDetail sets the "detail" field.
func (meuo *MonitorEventUpdateOne) SetDetail(m map[string]interface{}) *MonitorEventUpdateOne {
	meuo.mutation.SetDetail(m)
	return meuo
}

// ClearDetail clears the value of the "detail" field.
func (meuo *MonitorEventUpdateOne) ClearDetail() *MonitorEventUpdateOne {
	meuo.mutation.ClearDetail()
	return meuo
}

// Mutation returns the MonitorEventMutation object of the builder.
func (meuo *MonitorEventUpdateOne) Mutation() *MonitorEventMutation {
	return meuo.mutation
}

// Where appends a list predicates to the MonitorEventUpdate builder.
func (meuo *MonitorEventUpdateOne) Where(ps ...predicate.MonitorEvent) *MonitorEventUpdateOne {
	meuo.mutation.Where(ps...)
	return meuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (meuo *MonitorEventUpdateOne) Select(field string, fields ...string) *MonitorEventUpdateOne {
	meuo.fields = append([]string{field}, fields...)
	return meuo
}

// Save executes the query and returns the updated MonitorEvent entity.
func (meuo *MonitorEventUpdateOne) Save(ctx context.Context) (*MonitorEvent, error) {
	return withHooks(ctx, meuo.sqlSave, meuo.mutation, meuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (meuo *MonitorEventUpdateOne) SaveX(ctx context.Context) *MonitorEvent {
	node, err := meuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (meuo *MonitorEventUpdateOne) Exec(ctx context.Context) error {
	_, err := meuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (meuo *MonitorEventUpdateOne) ExecX(ctx context.Context) {
	if err := meuo.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (meuo *MonitorEventUpdateOne) check() error {
	if v, ok := meuo.mutation.GetType(); ok {
		if err := monitorevent.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "MonitorEvent.type": %w`, err)}
		}
	}
	if v, ok := meuo.mutation.Severity(); ok {
		if err := monitorevent.SeverityValidator(v); err != nil {
			return &ValidationError{Name: "severity", err: fmt.Errorf(`ent: validator failed for field "MonitorEvent.severity": %w`, err)}
		}
	}
	if v, ok := meuo.mutation.Status(); ok {
		if err := monitorevent.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "MonitorEvent.status": %w`, err)}
		}
	}
	if v, ok := meuo.mutation.Source(); ok {
		if err := monitorevent.SourceValidator(v); err != nil {
			return &ValidationError{Name: "source", err: fmt.Errorf(`ent: validator failed for field "MonitorEvent.source": %w`, err)}
		}
	}
	if v, ok := meuo.mutation.SubjectType(); ok {
		if err := monitorevent.SubjectTypeValidator(v); err != nil {
			return &ValidationError{Name: "subject_type", err: fmt.Errorf(`ent: validator failed for field "MonitorEvent.subject_type": %w`, err)}
		}
	}
	if v, ok := meuo.mutation.SubjectID(); ok {
		if err := monitorevent.SubjectIDValidator(v); err != nil {
			return &ValidationError{Name: "subject_id", err: fmt.Errorf(`ent: validator failed for field "MonitorEvent.subject_id": %w`, err)}
		}
	}
	if v, ok := meuo.mutation.Fingerprint(); ok {
		if err := monitorevent.FingerprintValidator(v); err != nil {
			return &ValidationError{Name: "fingerprint", err: fmt.Errorf(`ent: validator failed for field "MonitorEvent.fingerprint": %w`, err)}
		}
	}
	if v, ok := meuo.mutation.Title(); ok {
		if err := monitorevent.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "MonitorEvent.title": %w`, err)}
		}
	}
	if v, ok := meuo.mutation.Message(); ok {
		if err := monitorevent.MessageValidator(v); err != nil {
			return &ValidationError{Name: "message", err: fmt.Errorf(`ent: validator failed for field "MonitorEvent.message": %w`, err)}
		}
	}
	if v, ok := meuo.mutation.APIKeyNameSnapshot(); ok {
		if err := monitorevent.APIKeyNameSnapshotValidator(v); err != nil {
			return &ValidationError{Name: "api_key_name_snapshot", err: fmt.Errorf(`ent: validator failed for field "MonitorEvent.api_key_name_snapshot": %w`, err)}
		}
	}
	if v, ok := meuo.mutation.UserEmailSnapshot(); ok {
		if err := monitorevent.UserEmailSnapshotValidator(v); err != nil {
			return &ValidationError{Name: "user_email_snapshot", err: fmt.Errorf(`ent: validator failed for field "MonitorEvent.user_email_snapshot": %w`, err)}
		}
	}
	if v, ok := meuo.mutation.AccountNameSnapshot(); ok {
		if err := monitorevent.AccountNameSnapshotValidator(v); err != nil {
			return &ValidationError{Name: "account_name_snapshot", err: fmt.Errorf(`ent: validator failed for field "MonitorEvent.account_name_snapshot": %w`, err)}
		}
	}
	if v, ok := meuo.mutation.Platform(); ok {
		if err := monitorevent.PlatformValidator(v); err != nil {
			return &ValidationError{Name: "platform", err: fmt.Errorf(`ent: validator failed for field "MonitorEvent.platform": %w`, err)}
		}
	}
	if v, ok := meuo.mutation.PluginID(); ok {
		if err := monitorevent.PluginIDValidator(v); err != nil {
			return &ValidationError{Name: "plugin_id", err: fmt.Errorf(`ent: validator failed for field "MonitorEvent.plugin_id": %w`, err)}
		}
	}
	if v, ok := meuo.mutation.TaskType(); ok {
		if err := monitorevent.TaskTypeValidator(v); err != nil {
			return &ValidationError{Name: "task_type", err: fmt.Errorf(`ent: validator failed for field "MonitorEvent.task_type": %w`, err)}
		}
	}
	if v, ok := meuo.mutation.Method(); ok {
		if err := monitorevent.MethodValidator(v); err != nil {
			return &ValidationError{Name: "method", err: fmt.Errorf(`ent: validator failed for field "MonitorEvent.method": %w`, err)}
		}
	}
	if v, ok := meuo.mutation.Endpoint(); ok {
		if err := monitorevent.EndpointValidator(v); err != nil {
			return &ValidationError{Name: "endpoint", err: fmt.Errorf(`ent: validator failed for field "MonitorEvent.endpoint": %w`, err)}
		}
	}
	if v, ok := meuo.mutation.Model(); ok {
		if err := monitorevent.ModelValidator(v); err != nil {
			return &ValidationError{Name: "model", err: fmt.Errorf(`ent: validator failed for field "MonitorEvent.model": %w`, err)}
		}
	}
	if v, ok := meuo.mutation.ErrorCode(); ok {
		if err := monitorevent.ErrorCodeValidator(v); err != nil {
			return &ValidationError{Name: "error_code", err: fmt.Errorf(`ent: validator failed for field "MonitorEvent.error_code": %w`, err)}
		}
	}
	if v, ok := meuo.mutation.NotifyError(); ok {
		if err := monitorevent.NotifyErrorValidator(v); err != nil {
			return &ValidationError{Name: "notify_error", err: fmt.Errorf(`ent: validator failed for field "MonitorEvent.notify_error": %w`, err)}
		}
	}
	return nil
}

func (meuo *MonitorEventUpdateOne) sqlSave(ctx context.Context) (_node *MonitorEvent, err error) {
	if err := meuo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(monitorevent.Table, monitorevent.Columns, sqlgraph.NewFieldSpec(monitorevent.FieldID, field.TypeInt))
	id, ok := meuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "MonitorEvent.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := meuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, monitorevent.FieldID)
		for _, f := range fields {
			if !monitorevent.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != monitorevent.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := meuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := meuo.mutation.GetType(); ok {
		_spec.SetField(monitorevent.FieldType, field.TypeEnum, value)
	}
	if value, ok := meuo.mutation.Severity(); ok {
		_spec.SetField(monitorevent.FieldSeverity, field.TypeEnum, value)
	}
	if value, ok := meuo.mutation.Status(); ok {
		_spec.SetField(monitorevent.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := meuo.mutation.Source(); ok {
		_spec.SetField(monitorevent.FieldSource, field.TypeString, value)
	}
	if value, ok := meuo.mutation.SubjectType(); ok {
		_spec.SetField(monitorevent.FieldSubjectType, field.TypeString, value)
	}
	if value, ok := meuo.mutation.SubjectID(); ok {
		_spec.SetField(monitorevent.FieldSubjectID, field.TypeString, value)
	}
	if value, ok := meuo.mutation.Fingerprint(); ok {
		_spec.SetField(monitorevent.FieldFingerprint, field.TypeString, value)
	}
	if value, ok := meuo.mutation.Title(); ok {
		_spec.SetField(monitorevent.FieldTitle, field.TypeString, value)
	}
	if value, ok := meuo.mutation.Message(); ok {
		_spec.SetField(monitorevent.FieldMessage, field.TypeString, value)
	}
	if value, ok := meuo.mutation.APIKeyID(); ok {
		_spec.SetField(monitorevent.FieldAPIKeyID, field.TypeInt, value)
	}
	if value, ok := meuo.mutation.AddedAPIKeyID(); ok {
		_spec.AddField(monitorevent.FieldAPIKeyID, field.TypeInt, value)
	}
	if meuo.mutation.APIKeyIDCleared() {
		_spec.ClearField(monitorevent.FieldAPIKeyID, field.TypeInt)
	}
	if value, ok := meuo.mutation.APIKeyNameSnapshot(); ok {
		_spec.SetField(monitorevent.FieldAPIKeyNameSnapshot, field.TypeString, value)
	}
	if value, ok := meuo.mutation.UserID(); ok {
		_spec.SetField(monitorevent.FieldUserID, field.TypeInt, value)
	}
	if value, ok := meuo.mutation.AddedUserID(); ok {
		_spec.AddField(monitorevent.FieldUserID, field.TypeInt, value)
	}
	if meuo.mutation.UserIDCleared() {
		_spec.ClearField(monitorevent.FieldUserID, field.TypeInt)
	}
	if value, ok := meuo.mutation.UserEmailSnapshot(); ok {
		_spec.SetField(monitorevent.FieldUserEmailSnapshot, field.TypeString, value)
	}
	if value, ok := meuo.mutation.GroupID(); ok {
		_spec.SetField(monitorevent.FieldGroupID, field.TypeInt, value)
	}
	if value, ok := meuo.mutation.AddedGroupID(); ok {
		_spec.AddField(monitorevent.FieldGroupID, field.TypeInt, value)
	}
	if meuo.mutation.GroupIDCleared() {
		_spec.ClearField(monitorevent.FieldGroupID, field.TypeInt)
	}
	if value, ok := meuo.mutation.AccountID(); ok {
		_spec.SetField(monitorevent.FieldAccountID, field.TypeInt, value)
	}
	if value, ok := meuo.mutation.AddedAccountID(); ok {
		_spec.AddField(monitorevent.FieldAccountID, field.TypeInt, value)
	}
	if meuo.mutation.AccountIDCleared() {
		_spec.ClearField(monitorevent.FieldAccountID, field.TypeInt)
	}
	if value, ok := meuo.mutation.AccountNameSnapshot(); ok {
		_spec.SetField(monitorevent.FieldAccountNameSnapshot, field.TypeString, value)
	}
	if value, ok := meuo.mutation.Platform(); ok {
		_spec.SetField(monitorevent.FieldPlatform, field.TypeString, value)
	}
	if value, ok := meuo.mutation.PluginID(); ok {
		_spec.SetField(monitorevent.FieldPluginID, field.TypeString, value)
	}
	if value, ok := meuo.mutation.TaskType(); ok {
		_spec.SetField(monitorevent.FieldTaskType, field.TypeString, value)
	}
	if value, ok := meuo.mutation.Method(); ok {
		_spec.SetField(monitorevent.FieldMethod, field.TypeString, value)
	}
	if value, ok := meuo.mutation.Endpoint(); ok {
		_spec.SetField(monitorevent.FieldEndpoint, field.TypeString, value)
	}
	if value, ok := meuo.mutation.Model(); ok {
		_spec.SetField(monitorevent.FieldModel, field.TypeString, value)
	}
	if value, ok := meuo.mutation.HTTPStatus(); ok {
		_spec.SetField(monitorevent.FieldHTTPStatus, field.TypeInt, value)
	}
	if value, ok := meuo.mutation.AddedHTTPStatus(); ok {
		_spec.AddField(monitorevent.FieldHTTPStatus, field.TypeInt, value)
	}
	if meuo.mutation.HTTPStatusCleared() {
		_spec.ClearField(monitorevent.FieldHTTPStatus, field.TypeInt)
	}
	if value, ok := meuo.mutation.UpstreamStatus(); ok {
		_spec.SetField(monitorevent.FieldUpstreamStatus, field.TypeInt, value)
	}
	if value, ok := meuo.mutation.AddedUpstreamStatus(); ok {
		_spec.AddField(monitorevent.FieldUpstreamStatus, field.TypeInt, value)
	}
	if meuo.mutation.UpstreamStatusCleared() {
		_spec.ClearField(monitorevent.FieldUpstreamStatus, field.TypeInt)
	}
	if value, ok := meuo.mutation.ErrorCode(); ok {
		_spec.SetField(monitorevent.FieldErrorCode, field.TypeString, value)
	}
	if value, ok := meuo.mutation.CreatedAt(); ok {
		_spec.SetField(monitorevent.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := meuo.mutation.UpdatedAt(); ok {
		_spec.SetField(monitorevent.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := meuo.mutation.ResolvedAt(); ok {
		_spec.SetField(monitorevent.FieldResolvedAt, field.TypeTime, value)
	}
	if meuo.mutation.ResolvedAtCleared() {
		_spec.ClearField(monitorevent.FieldResolvedAt, field.TypeTime)
	}
	if value, ok := meuo.mutation.IgnoredAt(); ok {
		_spec.SetField(monitorevent.FieldIgnoredAt, field.TypeTime, value)
	}
	if meuo.mutation.IgnoredAtCleared() {
		_spec.ClearField(monitorevent.FieldIgnoredAt, field.TypeTime)
	}
	if value, ok := meuo.mutation.AutoResolveAt(); ok {
		_spec.SetField(monitorevent.FieldAutoResolveAt, field.TypeTime, value)
	}
	if meuo.mutation.AutoResolveAtCleared() {
		_spec.ClearField(monitorevent.FieldAutoResolveAt, field.TypeTime)
	}
	if value, ok := meuo.mutation.ExpiresAt(); ok {
		_spec.SetField(monitorevent.FieldExpiresAt, field.TypeTime, value)
	}
	if value, ok := meuo.mutation.LastNotifiedAt(); ok {
		_spec.SetField(monitorevent.FieldLastNotifiedAt, field.TypeTime, value)
	}
	if meuo.mutation.LastNotifiedAtCleared() {
		_spec.ClearField(monitorevent.FieldLastNotifiedAt, field.TypeTime)
	}
	if value, ok := meuo.mutation.NextNotifyAt(); ok {
		_spec.SetField(monitorevent.FieldNextNotifyAt, field.TypeTime, value)
	}
	if meuo.mutation.NextNotifyAtCleared() {
		_spec.ClearField(monitorevent.FieldNextNotifyAt, field.TypeTime)
	}
	if value, ok := meuo.mutation.NotifyError(); ok {
		_spec.SetField(monitorevent.FieldNotifyError, field.TypeString, value)
	}
	if value, ok := meuo.mutation.Detail(); ok {
		_spec.SetField(monitorevent.FieldDetail, field.TypeJSON, value)
	}
	if meuo.mutation.DetailCleared() {
		_spec.ClearField(monitorevent.FieldDetail, field.TypeJSON)
	}
	_node = &MonitorEvent{config: meuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, meuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{monitorevent.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	meuo.mutation.done = true
	return _node, nil
}
