// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/DevilGenius/airgate-core/ent/monitorevent"
)

// MonitorEvent is the model entity for the MonitorEvent schema.
type MonitorEvent struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Kind holds the value of the "kind" field.
	Kind monitorevent.Kind `json:"kind,omitempty"`
	// Severity holds the value of the "severity" field.
	Severity monitorevent.Severity `json:"severity,omitempty"`
	// Status holds the value of the "status" field.
	Status monitorevent.Status `json:"status,omitempty"`
	// Source holds the value of the "source" field.
	Source string `json:"source,omitempty"`
	// SubjectType holds the value of the "subject_type" field.
	SubjectType string `json:"subject_type,omitempty"`
	// SubjectID holds the value of the "subject_id" field.
	SubjectID string `json:"subject_id,omitempty"`
	// Fingerprint holds the value of the "fingerprint" field.
	Fingerprint string `json:"fingerprint,omitempty"`
	// Title holds the value of the "title" field.
	Title string `json:"title,omitempty"`
	// Message holds the value of the "message" field.
	Message string `json:"message,omitempty"`
	// APIKeyID holds the value of the "api_key_id" field.
	APIKeyID *int `json:"api_key_id,omitempty"`
	// APIKeyNameSnapshot holds the value of the "api_key_name_snapshot" field.
	APIKeyNameSnapshot string `json:"api_key_name_snapshot,omitempty"`
	// APIKeyPrefix holds the value of the "api_key_prefix" field.
	APIKeyPrefix string `json:"api_key_prefix,omitempty"`
	// UserID holds the value of the "user_id" field.
	UserID *int `json:"user_id,omitempty"`
	// UserEmailSnapshot holds the value of the "user_email_snapshot" field.
	UserEmailSnapshot string `json:"user_email_snapshot,omitempty"`
	// GroupID holds the value of the "group_id" field.
	GroupID *int `json:"group_id,omitempty"`
	// AccountID holds the value of the "account_id" field.
	AccountID *int `json:"account_id,omitempty"`
	// AccountNameSnapshot holds the value of the "account_name_snapshot" field.
	AccountNameSnapshot string `json:"account_name_snapshot,omitempty"`
	// Platform holds the value of the "platform" field.
	Platform string `json:"platform,omitempty"`
	// PluginID holds the value of the "plugin_id" field.
	PluginID string `json:"plugin_id,omitempty"`
	// TaskType holds the value of the "task_type" field.
	TaskType string `json:"task_type,omitempty"`
	// Method holds the value of the "method" field.
	Method string `json:"method,omitempty"`
	// Endpoint holds the value of the "endpoint" field.
	Endpoint string `json:"endpoint,omitempty"`
	// RequestPath holds the value of the "request_path" field.
	RequestPath string `json:"request_path,omitempty"`
	// Model holds the value of the "model" field.
	Model string `json:"model,omitempty"`
	// HTTPStatus holds the value of the "http_status" field.
	HTTPStatus *int `json:"http_status,omitempty"`
	// UpstreamStatus holds the value of the "upstream_status" field.
	UpstreamStatus *int `json:"upstream_status,omitempty"`
	// ErrorCode holds the value of the "error_code" field.
	ErrorCode string `json:"error_code,omitempty"`
	// ErrorType holds the value of the "error_type" field.
	ErrorType string `json:"error_type,omitempty"`
	// Count holds the value of the "count" field.
	Count int64 `json:"count,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// ResolvedAt holds the value of the "resolved_at" field.
	ResolvedAt *time.Time `json:"resolved_at,omitempty"`
	// IgnoredAt holds the value of the "ignored_at" field.
	IgnoredAt *time.Time `json:"ignored_at,omitempty"`
	// AutoResolveAt holds the value of the "auto_resolve_at" field.
	AutoResolveAt *time.Time `json:"auto_resolve_at,omitempty"`
	// ExpiresAt holds the value of the "expires_at" field.
	ExpiresAt time.Time `json:"expires_at,omitempty"`
	// Detail holds the value of the "detail" field.
	Detail       map[string]interface{} `json:"detail,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*MonitorEvent) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case monitorevent.FieldDetail:
			values[i] = new([]byte)
		case monitorevent.FieldID, monitorevent.FieldAPIKeyID, monitorevent.FieldUserID, monitorevent.FieldGroupID, monitorevent.FieldAccountID, monitorevent.FieldHTTPStatus, monitorevent.FieldUpstreamStatus, monitorevent.FieldCount:
			values[i] = new(sql.NullInt64)
		case monitorevent.FieldKind, monitorevent.FieldSeverity, monitorevent.FieldStatus, monitorevent.FieldSource, monitorevent.FieldSubjectType, monitorevent.FieldSubjectID, monitorevent.FieldFingerprint, monitorevent.FieldTitle, monitorevent.FieldMessage, monitorevent.FieldAPIKeyNameSnapshot, monitorevent.FieldAPIKeyPrefix, monitorevent.FieldUserEmailSnapshot, monitorevent.FieldAccountNameSnapshot, monitorevent.FieldPlatform, monitorevent.FieldPluginID, monitorevent.FieldTaskType, monitorevent.FieldMethod, monitorevent.FieldEndpoint, monitorevent.FieldRequestPath, monitorevent.FieldModel, monitorevent.FieldErrorCode, monitorevent.FieldErrorType:
			values[i] = new(sql.NullString)
		case monitorevent.FieldCreatedAt, monitorevent.FieldUpdatedAt, monitorevent.FieldResolvedAt, monitorevent.FieldIgnoredAt, monitorevent.FieldAutoResolveAt, monitorevent.FieldExpiresAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the MonitorEvent fields.
func (me *MonitorEvent) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case monitorevent.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			me.ID = int(value.Int64)
		case monitorevent.FieldKind:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field kind", values[i])
			} else if value.Valid {
				me.Kind = monitorevent.Kind(value.String)
			}
		case monitorevent.FieldSeverity:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field severity", values[i])
			} else if value.Valid {
				me.Severity = monitorevent.Severity(value.String)
			}
		case monitorevent.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				me.Status = monitorevent.Status(value.String)
			}
		case monitorevent.FieldSource:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field source", values[i])
			} else if value.Valid {
				me.Source = value.String
			}
		case monitorevent.FieldSubjectType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field subject_type", values[i])
			} else if value.Valid {
				me.SubjectType = value.String
			}
		case monitorevent.FieldSubjectID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field subject_id", values[i])
			} else if value.Valid {
				me.SubjectID = value.String
			}
		case monitorevent.FieldFingerprint:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field fingerprint", values[i])
			} else if value.Valid {
				me.Fingerprint = value.String
			}
		case monitorevent.FieldTitle:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field title", values[i])
			} else if value.Valid {
				me.Title = value.String
			}
		case monitorevent.FieldMessage:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field message", values[i])
			} else if value.Valid {
				me.Message = value.String
			}
		case monitorevent.FieldAPIKeyID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field api_key_id", values[i])
			} else if value.Valid {
				me.APIKeyID = new(int)
				*me.APIKeyID = int(value.Int64)
			}
		case monitorevent.FieldAPIKeyNameSnapshot:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field api_key_name_snapshot", values[i])
			} else if value.Valid {
				me.APIKeyNameSnapshot = value.String
			}
		case monitorevent.FieldAPIKeyPrefix:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field api_key_prefix", values[i])
			} else if value.Valid {
				me.APIKeyPrefix = value.String
			}
		case monitorevent.FieldUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				me.UserID = new(int)
				*me.UserID = int(value.Int64)
			}
		case monitorevent.FieldUserEmailSnapshot:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field user_email_snapshot", values[i])
			} else if value.Valid {
				me.UserEmailSnapshot = value.String
			}
		case monitorevent.FieldGroupID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field group_id", values[i])
			} else if value.Valid {
				me.GroupID = new(int)
				*me.GroupID = int(value.Int64)
			}
		case monitorevent.FieldAccountID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field account_id", values[i])
			} else if value.Valid {
				me.AccountID = new(int)
				*me.AccountID = int(value.Int64)
			}
		case monitorevent.FieldAccountNameSnapshot:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field account_name_snapshot", values[i])
			} else if value.Valid {
				me.AccountNameSnapshot = value.String
			}
		case monitorevent.FieldPlatform:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field platform", values[i])
			} else if value.Valid {
				me.Platform = value.String
			}
		case monitorevent.FieldPluginID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field plugin_id", values[i])
			} else if value.Valid {
				me.PluginID = value.String
			}
		case monitorevent.FieldTaskType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field task_type", values[i])
			} else if value.Valid {
				me.TaskType = value.String
			}
		case monitorevent.FieldMethod:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field method", values[i])
			} else if value.Valid {
				me.Method = value.String
			}
		case monitorevent.FieldEndpoint:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field endpoint", values[i])
			} else if value.Valid {
				me.Endpoint = value.String
			}
		case monitorevent.FieldRequestPath:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field request_path", values[i])
			} else if value.Valid {
				me.RequestPath = value.String
			}
		case monitorevent.FieldModel:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field model", values[i])
			} else if value.Valid {
				me.Model = value.String
			}
		case monitorevent.FieldHTTPStatus:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field http_status", values[i])
			} else if value.Valid {
				me.HTTPStatus = new(int)
				*me.HTTPStatus = int(value.Int64)
			}
		case monitorevent.FieldUpstreamStatus:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field upstream_status", values[i])
			} else if value.Valid {
				me.UpstreamStatus = new(int)
				*me.UpstreamStatus = int(value.Int64)
			}
		case monitorevent.FieldErrorCode:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field error_code", values[i])
			} else if value.Valid {
				me.ErrorCode = value.String
			}
		case monitorevent.FieldErrorType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field error_type", values[i])
			} else if value.Valid {
				me.ErrorType = value.String
			}
		case monitorevent.FieldCount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field count", values[i])
			} else if value.Valid {
				me.Count = value.Int64
			}
		case monitorevent.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				me.CreatedAt = value.Time
			}
		case monitorevent.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				me.UpdatedAt = value.Time
			}
		case monitorevent.FieldResolvedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field resolved_at", values[i])
			} else if value.Valid {
				me.ResolvedAt = new(time.Time)
				*me.ResolvedAt = value.Time
			}
		case monitorevent.FieldIgnoredAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field ignored_at", values[i])
			} else if value.Valid {
				me.IgnoredAt = new(time.Time)
				*me.IgnoredAt = value.Time
			}
		case monitorevent.FieldAutoResolveAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field auto_resolve_at", values[i])
			} else if value.Valid {
				me.AutoResolveAt = new(time.Time)
				*me.AutoResolveAt = value.Time
			}
		case monitorevent.FieldExpiresAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field expires_at", values[i])
			} else if value.Valid {
				me.ExpiresAt = value.Time
			}
		case monitorevent.FieldDetail:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field detail", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &me.Detail); err != nil {
					return fmt.Errorf("unmarshal field detail: %w", err)
				}
			}
		default:
			me.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the MonitorEvent.
// This includes values selected through modifiers, order, etc.
func (me *MonitorEvent) Value(name string) (ent.Value, error) {
	return me.selectValues.Get(name)
}

// Update returns a builder for updating this MonitorEvent.
// Note that you need to call MonitorEvent.Unwrap() before calling this method if this MonitorEvent
// was returned from a transaction, and the transaction was committed or rolled back.
func (me *MonitorEvent) Update() *MonitorEventUpdateOne {
	return NewMonitorEventClient(me.config).UpdateOne(me)
}

// Unwrap unwraps the MonitorEvent entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (me *MonitorEvent) Unwrap() *MonitorEvent {
	_tx, ok := me.config.driver.(*txDriver)
	if !ok {
		panic("ent: MonitorEvent is not a transactional entity")
	}
	me.config.driver = _tx.drv
	return me
}

// String implements the fmt.Stringer.
func (me *MonitorEvent) String() string {
	var builder strings.Builder
	builder.WriteString("MonitorEvent(")
	builder.WriteString(fmt.Sprintf("id=%v, ", me.ID))
	builder.WriteString("kind=")
	builder.WriteString(fmt.Sprintf("%v", me.Kind))
	builder.WriteString(", ")
	builder.WriteString("severity=")
	builder.WriteString(fmt.Sprintf("%v", me.Severity))
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(fmt.Sprintf("%v", me.Status))
	builder.WriteString(", ")
	builder.WriteString("source=")
	builder.WriteString(me.Source)
	builder.WriteString(", ")
	builder.WriteString("subject_type=")
	builder.WriteString(me.SubjectType)
	builder.WriteString(", ")
	builder.WriteString("subject_id=")
	builder.WriteString(me.SubjectID)
	builder.WriteString(", ")
	builder.WriteString("fingerprint=")
	builder.WriteString(me.Fingerprint)
	builder.WriteString(", ")
	builder.WriteString("title=")
	builder.WriteString(me.Title)
	builder.WriteString(", ")
	builder.WriteString("message=")
	builder.WriteString(me.Message)
	builder.WriteString(", ")
	if v := me.APIKeyID; v != nil {
		builder.WriteString("api_key_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("api_key_name_snapshot=")
	builder.WriteString(me.APIKeyNameSnapshot)
	builder.WriteString(", ")
	builder.WriteString("api_key_prefix=")
	builder.WriteString(me.APIKeyPrefix)
	builder.WriteString(", ")
	if v := me.UserID; v != nil {
		builder.WriteString("user_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("user_email_snapshot=")
	builder.WriteString(me.UserEmailSnapshot)
	builder.WriteString(", ")
	if v := me.GroupID; v != nil {
		builder.WriteString("group_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := me.AccountID; v != nil {
		builder.WriteString("account_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("account_name_snapshot=")
	builder.WriteString(me.AccountNameSnapshot)
	builder.WriteString(", ")
	builder.WriteString("platform=")
	builder.WriteString(me.Platform)
	builder.WriteString(", ")
	builder.WriteString("plugin_id=")
	builder.WriteString(me.PluginID)
	builder.WriteString(", ")
	builder.WriteString("task_type=")
	builder.WriteString(me.TaskType)
	builder.WriteString(", ")
	builder.WriteString("method=")
	builder.WriteString(me.Method)
	builder.WriteString(", ")
	builder.WriteString("endpoint=")
	builder.WriteString(me.Endpoint)
	builder.WriteString(", ")
	builder.WriteString("request_path=")
	builder.WriteString(me.RequestPath)
	builder.WriteString(", ")
	builder.WriteString("model=")
	builder.WriteString(me.Model)
	builder.WriteString(", ")
	if v := me.HTTPStatus; v != nil {
		builder.WriteString("http_status=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := me.UpstreamStatus; v != nil {
		builder.WriteString("upstream_status=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("error_code=")
	builder.WriteString(me.ErrorCode)
	builder.WriteString(", ")
	builder.WriteString("error_type=")
	builder.WriteString(me.ErrorType)
	builder.WriteString(", ")
	builder.WriteString("count=")
	builder.WriteString(fmt.Sprintf("%v", me.Count))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(me.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(me.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := me.ResolvedAt; v != nil {
		builder.WriteString("resolved_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := me.IgnoredAt; v != nil {
		builder.WriteString("ignored_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := me.AutoResolveAt; v != nil {
		builder.WriteString("auto_resolve_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("expires_at=")
	builder.WriteString(me.ExpiresAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("detail=")
	builder.WriteString(fmt.Sprintf("%v", me.Detail))
	builder.WriteByte(')')
	return builder.String()
}

// MonitorEvents is a parsable slice of MonitorEvent.
type MonitorEvents []*MonitorEvent
