// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/DevilGenius/airgate-core/ent/monitorrequestevent"
)

// MonitorRequestEventCreate is the builder for creating a MonitorRequestEvent entity.
type MonitorRequestEventCreate struct {
	config
	mutation *MonitorRequestEventMutation
	hooks    []Hook
}

// SetType sets the "type" field.
func (mrec *MonitorRequestEventCreate) SetType(s string) *MonitorRequestEventCreate {
	mrec.mutation.SetType(s)
	return mrec
}

// SetNillableType sets the "type" field if the given value is not nil.
func (mrec *MonitorRequestEventCreate) SetNillableType(s *string) *MonitorRequestEventCreate {
	if s != nil {
		mrec.SetType(*s)
	}
	return mrec
}

// SetSeverity sets the "severity" field.
func (mrec *MonitorRequestEventCreate) SetSeverity(m monitorrequestevent.Severity) *MonitorRequestEventCreate {
	mrec.mutation.SetSeverity(m)
	return mrec
}

// SetNillableSeverity sets the "severity" field if the given value is not nil.
func (mrec *MonitorRequestEventCreate) SetNillableSeverity(m *monitorrequestevent.Severity) *MonitorRequestEventCreate {
	if m != nil {
		mrec.SetSeverity(*m)
	}
	return mrec
}

// SetSource sets the "source" field.
func (mrec *MonitorRequestEventCreate) SetSource(s string) *MonitorRequestEventCreate {
	mrec.mutation.SetSource(s)
	return mrec
}

// SetNillableSource sets the "source" field if the given value is not nil.
func (mrec *MonitorRequestEventCreate) SetNillableSource(s *string) *MonitorRequestEventCreate {
	if s != nil {
		mrec.SetSource(*s)
	}
	return mrec
}

// SetHash sets the "hash" field.
func (mrec *MonitorRequestEventCreate) SetHash(s string) *MonitorRequestEventCreate {
	mrec.mutation.SetHash(s)
	return mrec
}

// SetTraceHash sets the "trace_hash" field.
func (mrec *MonitorRequestEventCreate) SetTraceHash(s string) *MonitorRequestEventCreate {
	mrec.mutation.SetTraceHash(s)
	return mrec
}

// SetNillableTraceHash sets the "trace_hash" field if the given value is not nil.
func (mrec *MonitorRequestEventCreate) SetNillableTraceHash(s *string) *MonitorRequestEventCreate {
	if s != nil {
		mrec.SetTraceHash(*s)
	}
	return mrec
}

// SetFingerprint sets the "fingerprint" field.
func (mrec *MonitorRequestEventCreate) SetFingerprint(s string) *MonitorRequestEventCreate {
	mrec.mutation.SetFingerprint(s)
	return mrec
}

// SetNillableFingerprint sets the "fingerprint" field if the given value is not nil.
func (mrec *MonitorRequestEventCreate) SetNillableFingerprint(s *string) *MonitorRequestEventCreate {
	if s != nil {
		mrec.SetFingerprint(*s)
	}
	return mrec
}

// SetTitle sets the "title" field.
func (mrec *MonitorRequestEventCreate) SetTitle(s string) *MonitorRequestEventCreate {
	mrec.mutation.SetTitle(s)
	return mrec
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (mrec *MonitorRequestEventCreate) SetNillableTitle(s *string) *MonitorRequestEventCreate {
	if s != nil {
		mrec.SetTitle(*s)
	}
	return mrec
}

// SetMessage sets the "message" field.
func (mrec *MonitorRequestEventCreate) SetMessage(s string) *MonitorRequestEventCreate {
	mrec.mutation.SetMessage(s)
	return mrec
}

// SetNillableMessage sets the "message" field if the given value is not nil.
func (mrec *MonitorRequestEventCreate) SetNillableMessage(s *string) *MonitorRequestEventCreate {
	if s != nil {
		mrec.SetMessage(*s)
	}
	return mrec
}

// SetRequestID sets the "request_id" field.
func (mrec *MonitorRequestEventCreate) SetRequestID(s string) *MonitorRequestEventCreate {
	mrec.mutation.SetRequestID(s)
	return mrec
}

// SetNillableRequestID sets the "request_id" field if the given value is not nil.
func (mrec *MonitorRequestEventCreate) SetNillableRequestID(s *string) *MonitorRequestEventCreate {
	if s != nil {
		mrec.SetRequestID(*s)
	}
	return mrec
}

// SetAPIKeyID sets the "api_key_id" field.
func (mrec *MonitorRequestEventCreate) SetAPIKeyID(i int) *MonitorRequestEventCreate {
	mrec.mutation.SetAPIKeyID(i)
	return mrec
}

// SetNillableAPIKeyID sets the "api_key_id" field if the given value is not nil.
func (mrec *MonitorRequestEventCreate) SetNillableAPIKeyID(i *int) *MonitorRequestEventCreate {
	if i != nil {
		mrec.SetAPIKeyID(*i)
	}
	return mrec
}

// SetAPIKeyNameSnapshot sets the "api_key_name_snapshot" field.
func (mrec *MonitorRequestEventCreate) SetAPIKeyNameSnapshot(s string) *MonitorRequestEventCreate {
	mrec.mutation.SetAPIKeyNameSnapshot(s)
	return mrec
}

// SetNillableAPIKeyNameSnapshot sets the "api_key_name_snapshot" field if the given value is not nil.
func (mrec *MonitorRequestEventCreate) SetNillableAPIKeyNameSnapshot(s *string) *MonitorRequestEventCreate {
	if s != nil {
		mrec.SetAPIKeyNameSnapshot(*s)
	}
	return mrec
}

// SetUserID sets the "user_id" field.
func (mrec *MonitorRequestEventCreate) SetUserID(i int) *MonitorRequestEventCreate {
	mrec.mutation.SetUserID(i)
	return mrec
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (mrec *MonitorRequestEventCreate) SetNillableUserID(i *int) *MonitorRequestEventCreate {
	if i != nil {
		mrec.SetUserID(*i)
	}
	return mrec
}

// SetUserEmailSnapshot sets the "user_email_snapshot" field.
func (mrec *MonitorRequestEventCreate) SetUserEmailSnapshot(s string) *MonitorRequestEventCreate {
	mrec.mutation.SetUserEmailSnapshot(s)
	return mrec
}

// SetNillableUserEmailSnapshot sets the "user_email_snapshot" field if the given value is not nil.
func (mrec *MonitorRequestEventCreate) SetNillableUserEmailSnapshot(s *string) *MonitorRequestEventCreate {
	if s != nil {
		mrec.SetUserEmailSnapshot(*s)
	}
	return mrec
}

// SetGroupID sets the "group_id" field.
func (mrec *MonitorRequestEventCreate) SetGroupID(i int) *MonitorRequestEventCreate {
	mrec.mutation.SetGroupID(i)
	return mrec
}

// SetNillableGroupID sets the "group_id" field if the given value is not nil.
func (mrec *MonitorRequestEventCreate) SetNillableGroupID(i *int) *MonitorRequestEventCreate {
	if i != nil {
		mrec.SetGroupID(*i)
	}
	return mrec
}

// SetAccountID sets the "account_id" field.
func (mrec *MonitorRequestEventCreate) SetAccountID(i int) *MonitorRequestEventCreate {
	mrec.mutation.SetAccountID(i)
	return mrec
}

// SetNillableAccountID sets the "account_id" field if the given value is not nil.
func (mrec *MonitorRequestEventCreate) SetNillableAccountID(i *int) *MonitorRequestEventCreate {
	if i != nil {
		mrec.SetAccountID(*i)
	}
	return mrec
}

// SetAccountNameSnapshot sets the "account_name_snapshot" field.
func (mrec *MonitorRequestEventCreate) SetAccountNameSnapshot(s string) *MonitorRequestEventCreate {
	mrec.mutation.SetAccountNameSnapshot(s)
	return mrec
}

// SetNillableAccountNameSnapshot sets the "account_name_snapshot" field if the given value is not nil.
func (mrec *MonitorRequestEventCreate) SetNillableAccountNameSnapshot(s *string) *MonitorRequestEventCreate {
	if s != nil {
		mrec.SetAccountNameSnapshot(*s)
	}
	return mrec
}

// SetPlatform sets the "platform" field.
func (mrec *MonitorRequestEventCreate) SetPlatform(s string) *MonitorRequestEventCreate {
	mrec.mutation.SetPlatform(s)
	return mrec
}

// SetNillablePlatform sets the "platform" field if the given value is not nil.
func (mrec *MonitorRequestEventCreate) SetNillablePlatform(s *string) *MonitorRequestEventCreate {
	if s != nil {
		mrec.SetPlatform(*s)
	}
	return mrec
}

// SetPluginID sets the "plugin_id" field.
func (mrec *MonitorRequestEventCreate) SetPluginID(s string) *MonitorRequestEventCreate {
	mrec.mutation.SetPluginID(s)
	return mrec
}

// SetNillablePluginID sets the "plugin_id" field if the given value is not nil.
func (mrec *MonitorRequestEventCreate) SetNillablePluginID(s *string) *MonitorRequestEventCreate {
	if s != nil {
		mrec.SetPluginID(*s)
	}
	return mrec
}

// SetMethod sets the "method" field.
func (mrec *MonitorRequestEventCreate) SetMethod(s string) *MonitorRequestEventCreate {
	mrec.mutation.SetMethod(s)
	return mrec
}

// SetNillableMethod sets the "method" field if the given value is not nil.
func (mrec *MonitorRequestEventCreate) SetNillableMethod(s *string) *MonitorRequestEventCreate {
	if s != nil {
		mrec.SetMethod(*s)
	}
	return mrec
}

// SetEndpoint sets the "endpoint" field.
func (mrec *MonitorRequestEventCreate) SetEndpoint(s string) *MonitorRequestEventCreate {
	mrec.mutation.SetEndpoint(s)
	return mrec
}

// SetNillableEndpoint sets the "endpoint" field if the given value is not nil.
func (mrec *MonitorRequestEventCreate) SetNillableEndpoint(s *string) *MonitorRequestEventCreate {
	if s != nil {
		mrec.SetEndpoint(*s)
	}
	return mrec
}

// SetModel sets the "model" field.
func (mrec *MonitorRequestEventCreate) SetModel(s string) *MonitorRequestEventCreate {
	mrec.mutation.SetModel(s)
	return mrec
}

// SetNillableModel sets the "model" field if the given value is not nil.
func (mrec *MonitorRequestEventCreate) SetNillableModel(s *string) *MonitorRequestEventCreate {
	if s != nil {
		mrec.SetModel(*s)
	}
	return mrec
}

// SetHTTPStatus sets the "http_status" field.
func (mrec *MonitorRequestEventCreate) SetHTTPStatus(i int) *MonitorRequestEventCreate {
	mrec.mutation.SetHTTPStatus(i)
	return mrec
}

// SetNillableHTTPStatus sets the "http_status" field if the given value is not nil.
func (mrec *MonitorRequestEventCreate) SetNillableHTTPStatus(i *int) *MonitorRequestEventCreate {
	if i != nil {
		mrec.SetHTTPStatus(*i)
	}
	return mrec
}

// SetUpstreamStatus sets the "upstream_status" field.
func (mrec *MonitorRequestEventCreate) SetUpstreamStatus(i int) *MonitorRequestEventCreate {
	mrec.mutation.SetUpstreamStatus(i)
	return mrec
}

// SetNillableUpstreamStatus sets the "upstream_status" field if the given value is not nil.
func (mrec *MonitorRequestEventCreate) SetNillableUpstreamStatus(i *int) *MonitorRequestEventCreate {
	if i != nil {
		mrec.SetUpstreamStatus(*i)
	}
	return mrec
}

// SetErrorCode sets the "error_code" field.
func (mrec *MonitorRequestEventCreate) SetErrorCode(s string) *MonitorRequestEventCreate {
	mrec.mutation.SetErrorCode(s)
	return mrec
}

// SetNillableErrorCode sets the "error_code" field if the given value is not nil.
func (mrec *MonitorRequestEventCreate) SetNillableErrorCode(s *string) *MonitorRequestEventCreate {
	if s != nil {
		mrec.SetErrorCode(*s)
	}
	return mrec
}

// SetDurationMs sets the "duration_ms" field.
func (mrec *MonitorRequestEventCreate) SetDurationMs(i int64) *MonitorRequestEventCreate {
	mrec.mutation.SetDurationMs(i)
	return mrec
}

// SetNillableDurationMs sets the "duration_ms" field if the given value is not nil.
func (mrec *MonitorRequestEventCreate) SetNillableDurationMs(i *int64) *MonitorRequestEventCreate {
	if i != nil {
		mrec.SetDurationMs(*i)
	}
	return mrec
}

// SetCreatedAt sets the "created_at" field.
func (mrec *MonitorRequestEventCreate) SetCreatedAt(t time.Time) *MonitorRequestEventCreate {
	mrec.mutation.SetCreatedAt(t)
	return mrec
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (mrec *MonitorRequestEventCreate) SetNillableCreatedAt(t *time.Time) *MonitorRequestEventCreate {
	if t != nil {
		mrec.SetCreatedAt(*t)
	}
	return mrec
}

// SetExpiresAt sets the "expires_at" field.
func (mrec *MonitorRequestEventCreate) SetExpiresAt(t time.Time) *MonitorRequestEventCreate {
	mrec.mutation.SetExpiresAt(t)
	return mrec
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (mrec *MonitorRequestEventCreate) SetNillableExpiresAt(t *time.Time) *MonitorRequestEventCreate {
	if t != nil {
		mrec.SetExpiresAt(*t)
	}
	return mrec
}

// SetDetail sets the "detail" field.
func (mrec *MonitorRequestEventCreate) SetDetail(m map[string]interface{}) *MonitorRequestEventCreate {
	mrec.mutation.SetDetail(m)
	return mrec
}

// Mutation returns the MonitorRequestEventMutation object of the builder.
func (mrec *MonitorRequestEventCreate) Mutation() *MonitorRequestEventMutation {
	return mrec.mutation
}

// Save creates the MonitorRequestEvent in the database.
func (mrec *MonitorRequestEventCreate) Save(ctx context.Context) (*MonitorRequestEvent, error) {
	mrec.defaults()
	return withHooks(ctx, mrec.sqlSave, mrec.mutation, mrec.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (mrec *MonitorRequestEventCreate) SaveX(ctx context.Context) *MonitorRequestEvent {
	v, err := mrec.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (mrec *MonitorRequestEventCreate) Exec(ctx context.Context) error {
	_, err := mrec.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (mrec *MonitorRequestEventCreate) ExecX(ctx context.Context) {
	if err := mrec.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (mrec *MonitorRequestEventCreate) defaults() {
	if _, ok := mrec.mutation.GetType(); !ok {
		v := monitorrequestevent.DefaultType
		mrec.mutation.SetType(v)
	}
	if _, ok := mrec.mutation.Severity(); !ok {
		v := monitorrequestevent.DefaultSeverity
		mrec.mutation.SetSeverity(v)
	}
	if _, ok := mrec.mutation.Source(); !ok {
		v := monitorrequestevent.DefaultSource
		mrec.mutation.SetSource(v)
	}
	if _, ok := mrec.mutation.TraceHash(); !ok {
		v := monitorrequestevent.DefaultTraceHash
		mrec.mutation.SetTraceHash(v)
	}
	if _, ok := mrec.mutation.Fingerprint(); !ok {
		v := monitorrequestevent.DefaultFingerprint
		mrec.mutation.SetFingerprint(v)
	}
	if _, ok := mrec.mutation.Title(); !ok {
		v := monitorrequestevent.DefaultTitle
		mrec.mutation.SetTitle(v)
	}
	if _, ok := mrec.mutation.Message(); !ok {
		v := monitorrequestevent.DefaultMessage
		mrec.mutation.SetMessage(v)
	}
	if _, ok := mrec.mutation.RequestID(); !ok {
		v := monitorrequestevent.DefaultRequestID
		mrec.mutation.SetRequestID(v)
	}
	if _, ok := mrec.mutation.APIKeyNameSnapshot(); !ok {
		v := monitorrequestevent.DefaultAPIKeyNameSnapshot
		mrec.mutation.SetAPIKeyNameSnapshot(v)
	}
	if _, ok := mrec.mutation.UserEmailSnapshot(); !ok {
		v := monitorrequestevent.DefaultUserEmailSnapshot
		mrec.mutation.SetUserEmailSnapshot(v)
	}
	if _, ok := mrec.mutation.AccountNameSnapshot(); !ok {
		v := monitorrequestevent.DefaultAccountNameSnapshot
		mrec.mutation.SetAccountNameSnapshot(v)
	}
	if _, ok := mrec.mutation.Platform(); !ok {
		v := monitorrequestevent.DefaultPlatform
		mrec.mutation.SetPlatform(v)
	}
	if _, ok := mrec.mutation.PluginID(); !ok {
		v := monitorrequestevent.DefaultPluginID
		mrec.mutation.SetPluginID(v)
	}
	if _, ok := mrec.mutation.Method(); !ok {
		v := monitorrequestevent.DefaultMethod
		mrec.mutation.SetMethod(v)
	}
	if _, ok := mrec.mutation.Endpoint(); !ok {
		v := monitorrequestevent.DefaultEndpoint
		mrec.mutation.SetEndpoint(v)
	}
	if _, ok := mrec.mutation.Model(); !ok {
		v := monitorrequestevent.DefaultModel
		mrec.mutation.SetModel(v)
	}
	if _, ok := mrec.mutation.ErrorCode(); !ok {
		v := monitorrequestevent.DefaultErrorCode
		mrec.mutation.SetErrorCode(v)
	}
	if _, ok := mrec.mutation.DurationMs(); !ok {
		v := monitorrequestevent.DefaultDurationMs
		mrec.mutation.SetDurationMs(v)
	}
	if _, ok := mrec.mutation.CreatedAt(); !ok {
		v := monitorrequestevent.DefaultCreatedAt()
		mrec.mutation.SetCreatedAt(v)
	}
	if _, ok := mrec.mutation.ExpiresAt(); !ok {
		v := monitorrequestevent.DefaultExpiresAt()
		mrec.mutation.SetExpiresAt(v)
	}
	if _, ok := mrec.mutation.Detail(); !ok {
		v := monitorrequestevent.DefaultDetail
		mrec.mutation.SetDetail(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (mrec *MonitorRequestEventCreate) check() error {
	if _, ok := mrec.mutation.GetType(); !ok {
		return &ValidationError{Name: "type", err: errors.New(`ent: missing required field "MonitorRequestEvent.type"`)}
	}
	if v, ok := mrec.mutation.GetType(); ok {
		if err := monitorrequestevent.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "MonitorRequestEvent.type": %w`, err)}
		}
	}
	if _, ok := mrec.mutation.Severity(); !ok {
		return &ValidationError{Name: "severity", err: errors.New(`ent: missing required field "MonitorRequestEvent.severity"`)}
	}
	if v, ok := mrec.mutation.Severity(); ok {
		if err := monitorrequestevent.SeverityValidator(v); err != nil {
			return &ValidationError{Name: "severity", err: fmt.Errorf(`ent: validator failed for field "MonitorRequestEvent.severity": %w`, err)}
		}
	}
	if _, ok := mrec.mutation.Source(); !ok {
		return &ValidationError{Name: "source", err: errors.New(`ent: missing required field "MonitorRequestEvent.source"`)}
	}
	if v, ok := mrec.mutation.Source(); ok {
		if err := monitorrequestevent.SourceValidator(v); err != nil {
			return &ValidationError{Name: "source", err: fmt.Errorf(`ent: validator failed for field "MonitorRequestEvent.source": %w`, err)}
		}
	}
	if _, ok := mrec.mutation.Hash(); !ok {
		return &ValidationError{Name: "hash", err: errors.New(`ent: missing required field "MonitorRequestEvent.hash"`)}
	}
	if v, ok := mrec.mutation.Hash(); ok {
		if err := monitorrequestevent.HashValidator(v); err != nil {
			return &ValidationError{Name: "hash", err: fmt.Errorf(`ent: validator failed for field "MonitorRequestEvent.hash": %w`, err)}
		}
	}
	if _, ok := mrec.mutation.TraceHash(); !ok {
		return &ValidationError{Name: "trace_hash", err: errors.New(`ent: missing required field "MonitorRequestEvent.trace_hash"`)}
	}
	if v, ok := mrec.mutation.TraceHash(); ok {
		if err := monitorrequestevent.TraceHashValidator(v); err != nil {
			return &ValidationError{Name: "trace_hash", err: fmt.Errorf(`ent: validator failed for field "MonitorRequestEvent.trace_hash": %w`, err)}
		}
	}
	if _, ok := mrec.mutation.Fingerprint(); !ok {
		return &ValidationError{Name: "fingerprint", err: errors.New(`ent: missing required field "MonitorRequestEvent.fingerprint"`)}
	}
	if v, ok := mrec.mutation.Fingerprint(); ok {
		if err := monitorrequestevent.FingerprintValidator(v); err != nil {
			return &ValidationError{Name: "fingerprint", err: fmt.Errorf(`ent: validator failed for field "MonitorRequestEvent.fingerprint": %w`, err)}
		}
	}
	if _, ok := mrec.mutation.Title(); !ok {
		return &ValidationError{Name: "title", err: errors.New(`ent: missing required field "MonitorRequestEvent.title"`)}
	}
	if v, ok := mrec.mutation.Title(); ok {
		if err := monitorrequestevent.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "MonitorRequestEvent.title": %w`, err)}
		}
	}
	if _, ok := mrec.mutation.Message(); !ok {
		return &ValidationError{Name: "message", err: errors.New(`ent: missing required field "MonitorRequestEvent.message"`)}
	}
	if v, ok := mrec.mutation.Message(); ok {
		if err := monitorrequestevent.MessageValidator(v); err != nil {
			return &ValidationError{Name: "message", err: fmt.Errorf(`ent: validator failed for field "MonitorRequestEvent.message": %w`, err)}
		}
	}
	if _, ok := mrec.mutation.RequestID(); !ok {
		return &ValidationError{Name: "request_id", err: errors.New(`ent: missing required field "MonitorRequestEvent.request_id"`)}
	}
	if v, ok := mrec.mutation.RequestID(); ok {
		if err := monitorrequestevent.RequestIDValidator(v); err != nil {
			return &ValidationError{Name: "request_id", err: fmt.Errorf(`ent: validator failed for field "MonitorRequestEvent.request_id": %w`, err)}
		}
	}
	if _, ok := mrec.mutation.APIKeyNameSnapshot(); !ok {
		return &ValidationError{Name: "api_key_name_snapshot", err: errors.New(`ent: missing required field "MonitorRequestEvent.api_key_name_snapshot"`)}
	}
	if v, ok := mrec.mutation.APIKeyNameSnapshot(); ok {
		if err := monitorrequestevent.APIKeyNameSnapshotValidator(v); err != nil {
			return &ValidationError{Name: "api_key_name_snapshot", err: fmt.Errorf(`ent: validator failed for field "MonitorRequestEvent.api_key_name_snapshot": %w`, err)}
		}
	}
	if _, ok := mrec.mutation.UserEmailSnapshot(); !ok {
		return &ValidationError{Name: "user_email_snapshot", err: errors.New(`ent: missing required field "MonitorRequestEvent.user_email_snapshot"`)}
	}
	if v, ok := mrec.mutation.UserEmailSnapshot(); ok {
		if err := monitorrequestevent.UserEmailSnapshotValidator(v); err != nil {
			return &ValidationError{Name: "user_email_snapshot", err: fmt.Errorf(`ent: validator failed for field "MonitorRequestEvent.user_email_snapshot": %w`, err)}
		}
	}
	if _, ok := mrec.mutation.AccountNameSnapshot(); !ok {
		return &ValidationError{Name: "account_name_snapshot", err: errors.New(`ent: missing required field "MonitorRequestEvent.account_name_snapshot"`)}
	}
	if v, ok := mrec.mutation.AccountNameSnapshot(); ok {
		if err := monitorrequestevent.AccountNameSnapshotValidator(v); err != nil {
			return &ValidationError{Name: "account_name_snapshot", err: fmt.Errorf(`ent: validator failed for field "MonitorRequestEvent.account_name_snapshot": %w`, err)}
		}
	}
	if _, ok := mrec.mutation.Platform(); !ok {
		return &ValidationError{Name: "platform", err: errors.New(`ent: missing required field "MonitorRequestEvent.platform"`)}
	}
	if v, ok := mrec.mutation.Platform(); ok {
		if err := monitorrequestevent.PlatformValidator(v); err != nil {
			return &ValidationError{Name: "platform", err: fmt.Errorf(`ent: validator failed for field "MonitorRequestEvent.platform": %w`, err)}
		}
	}
	if _, ok := mrec.mutation.PluginID(); !ok {
		return &ValidationError{Name: "plugin_id", err: errors.New(`ent: missing required field "MonitorRequestEvent.plugin_id"`)}
	}
	if v, ok := mrec.mutation.PluginID(); ok {
		if err := monitorrequestevent.PluginIDValidator(v); err != nil {
			return &ValidationError{Name: "plugin_id", err: fmt.Errorf(`ent: validator failed for field "MonitorRequestEvent.plugin_id": %w`, err)}
		}
	}
	if _, ok := mrec.mutation.Method(); !ok {
		return &ValidationError{Name: "method", err: errors.New(`ent: missing required field "MonitorRequestEvent.method"`)}
	}
	if v, ok := mrec.mutation.Method(); ok {
		if err := monitorrequestevent.MethodValidator(v); err != nil {
			return &ValidationError{Name: "method", err: fmt.Errorf(`ent: validator failed for field "MonitorRequestEvent.method": %w`, err)}
		}
	}
	if _, ok := mrec.mutation.Endpoint(); !ok {
		return &ValidationError{Name: "endpoint", err: errors.New(`ent: missing required field "MonitorRequestEvent.endpoint"`)}
	}
	if v, ok := mrec.mutation.Endpoint(); ok {
		if err := monitorrequestevent.EndpointValidator(v); err != nil {
			return &ValidationError{Name: "endpoint", err: fmt.Errorf(`ent: validator failed for field "MonitorRequestEvent.endpoint": %w`, err)}
		}
	}
	if _, ok := mrec.mutation.Model(); !ok {
		return &ValidationError{Name: "model", err: errors.New(`ent: missing required field "MonitorRequestEvent.model"`)}
	}
	if v, ok := mrec.mutation.Model(); ok {
		if err := monitorrequestevent.ModelValidator(v); err != nil {
			return &ValidationError{Name: "model", err: fmt.Errorf(`ent: validator failed for field "MonitorRequestEvent.model": %w`, err)}
		}
	}
	if _, ok := mrec.mutation.ErrorCode(); !ok {
		return &ValidationError{Name: "error_code", err: errors.New(`ent: missing required field "MonitorRequestEvent.error_code"`)}
	}
	if v, ok := mrec.mutation.ErrorCode(); ok {
		if err := monitorrequestevent.ErrorCodeValidator(v); err != nil {
			return &ValidationError{Name: "error_code", err: fmt.Errorf(`ent: validator failed for field "MonitorRequestEvent.error_code": %w`, err)}
		}
	}
	if _, ok := mrec.mutation.DurationMs(); !ok {
		return &ValidationError{Name: "duration_ms", err: errors.New(`ent: missing required field "MonitorRequestEvent.duration_ms"`)}
	}
	if _, ok := mrec.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "MonitorRequestEvent.created_at"`)}
	}
	if _, ok := mrec.mutation.ExpiresAt(); !ok {
		return &ValidationError{Name: "expires_at", err: errors.New(`ent: missing required field "MonitorRequestEvent.expires_at"`)}
	}
	return nil
}

func (mrec *MonitorRequestEventCreate) sqlSave(ctx context.Context) (*MonitorRequestEvent, error) {
	if err := mrec.check(); err != nil {
		return nil, err
	}
	_node, _spec := mrec.createSpec()
	if err := sqlgraph.CreateNode(ctx, mrec.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	mrec.mutation.id = &_node.ID
	mrec.mutation.done = true
	return _node, nil
}

func (mrec *MonitorRequestEventCreate) createSpec() (*MonitorRequestEvent, *sqlgraph.CreateSpec) {
	var (
		_node = &MonitorRequestEvent{config: mrec.config}
		_spec = sqlgraph.NewCreateSpec(monitorrequestevent.Table, sqlgraph.NewFieldSpec(monitorrequestevent.FieldID, field.TypeInt))
	)
	if value, ok := mrec.mutation.GetType(); ok {
		_spec.SetField(monitorrequestevent.FieldType, field.TypeString, value)
		_node.Type = value
	}
	if value, ok := mrec.mutation.Severity(); ok {
		_spec.SetField(monitorrequestevent.FieldSeverity, field.TypeEnum, value)
		_node.Severity = value
	}
	if value, ok := mrec.mutation.Source(); ok {
		_spec.SetField(monitorrequestevent.FieldSource, field.TypeString, value)
		_node.Source = value
	}
	if value, ok := mrec.mutation.Hash(); ok {
		_spec.SetField(monitorrequestevent.FieldHash, field.TypeString, value)
		_node.Hash = value
	}
	if value, ok := mrec.mutation.TraceHash(); ok {
		_spec.SetField(monitorrequestevent.FieldTraceHash, field.TypeString, value)
		_node.TraceHash = value
	}
	if value, ok := mrec.mutation.Fingerprint(); ok {
		_spec.SetField(monitorrequestevent.FieldFingerprint, field.TypeString, value)
		_node.Fingerprint = value
	}
	if value, ok := mrec.mutation.Title(); ok {
		_spec.SetField(monitorrequestevent.FieldTitle, field.TypeString, value)
		_node.Title = value
	}
	if value, ok := mrec.mutation.Message(); ok {
		_spec.SetField(monitorrequestevent.FieldMessage, field.TypeString, value)
		_node.Message = value
	}
	if value, ok := mrec.mutation.RequestID(); ok {
		_spec.SetField(monitorrequestevent.FieldRequestID, field.TypeString, value)
		_node.RequestID = value
	}
	if value, ok := mrec.mutation.APIKeyID(); ok {
		_spec.SetField(monitorrequestevent.FieldAPIKeyID, field.TypeInt, value)
		_node.APIKeyID = &value
	}
	if value, ok := mrec.mutation.APIKeyNameSnapshot(); ok {
		_spec.SetField(monitorrequestevent.FieldAPIKeyNameSnapshot, field.TypeString, value)
		_node.APIKeyNameSnapshot = value
	}
	if value, ok := mrec.mutation.UserID(); ok {
		_spec.SetField(monitorrequestevent.FieldUserID, field.TypeInt, value)
		_node.UserID = &value
	}
	if value, ok := mrec.mutation.UserEmailSnapshot(); ok {
		_spec.SetField(monitorrequestevent.FieldUserEmailSnapshot, field.TypeString, value)
		_node.UserEmailSnapshot = value
	}
	if value, ok := mrec.mutation.GroupID(); ok {
		_spec.SetField(monitorrequestevent.FieldGroupID, field.TypeInt, value)
		_node.GroupID = &value
	}
	if value, ok := mrec.mutation.AccountID(); ok {
		_spec.SetField(monitorrequestevent.FieldAccountID, field.TypeInt, value)
		_node.AccountID = &value
	}
	if value, ok := mrec.mutation.AccountNameSnapshot(); ok {
		_spec.SetField(monitorrequestevent.FieldAccountNameSnapshot, field.TypeString, value)
		_node.AccountNameSnapshot = value
	}
	if value, ok := mrec.mutation.Platform(); ok {
		_spec.SetField(monitorrequestevent.FieldPlatform, field.TypeString, value)
		_node.Platform = value
	}
	if value, ok := mrec.mutation.PluginID(); ok {
		_spec.SetField(monitorrequestevent.FieldPluginID, field.TypeString, value)
		_node.PluginID = value
	}
	if value, ok := mrec.mutation.Method(); ok {
		_spec.SetField(monitorrequestevent.FieldMethod, field.TypeString, value)
		_node.Method = value
	}
	if value, ok := mrec.mutation.Endpoint(); ok {
		_spec.SetField(monitorrequestevent.FieldEndpoint, field.TypeString, value)
		_node.Endpoint = value
	}
	if value, ok := mrec.mutation.Model(); ok {
		_spec.SetField(monitorrequestevent.FieldModel, field.TypeString, value)
		_node.Model = value
	}
	if value, ok := mrec.mutation.HTTPStatus(); ok {
		_spec.SetField(monitorrequestevent.FieldHTTPStatus, field.TypeInt, value)
		_node.HTTPStatus = &value
	}
	if value, ok := mrec.mutation.UpstreamStatus(); ok {
		_spec.SetField(monitorrequestevent.FieldUpstreamStatus, field.TypeInt, value)
		_node.UpstreamStatus = &value
	}
	if value, ok := mrec.mutation.ErrorCode(); ok {
		_spec.SetField(monitorrequestevent.FieldErrorCode, field.TypeString, value)
		_node.ErrorCode = value
	}
	if value, ok := mrec.mutation.DurationMs(); ok {
		_spec.SetField(monitorrequestevent.FieldDurationMs, field.TypeInt64, value)
		_node.DurationMs = value
	}
	if value, ok := mrec.mutation.CreatedAt(); ok {
		_spec.SetField(monitorrequestevent.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := mrec.mutation.ExpiresAt(); ok {
		_spec.SetField(monitorrequestevent.FieldExpiresAt, field.TypeTime, value)
		_node.ExpiresAt = value
	}
	if value, ok := mrec.mutation.Detail(); ok {
		_spec.SetField(monitorrequestevent.FieldDetail, field.TypeJSON, value)
		_node.Detail = value
	}
	return _node, _spec
}

// MonitorRequestEventCreateBulk is the builder for creating many MonitorRequestEvent entities in bulk.
type MonitorRequestEventCreateBulk struct {
	config
	err      error
	builders []*MonitorRequestEventCreate
}

// Save creates the MonitorRequestEvent entities in the database.
func (mrecb *MonitorRequestEventCreateBulk) Save(ctx context.Context) ([]*MonitorRequestEvent, error) {
	if mrecb.err != nil {
		return nil, mrecb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(mrecb.builders))
	nodes := make([]*MonitorRequestEvent, len(mrecb.builders))
	mutators := make([]Mutator, len(mrecb.builders))
	for i := range mrecb.builders {
		func(i int, root context.Context) {
			builder := mrecb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*MonitorRequestEventMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, mrecb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, mrecb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, mrecb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (mrecb *MonitorRequestEventCreateBulk) SaveX(ctx context.Context) []*MonitorRequestEvent {
	v, err := mrecb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (mrecb *MonitorRequestEventCreateBulk) Exec(ctx context.Context) error {
	_, err := mrecb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (mrecb *MonitorRequestEventCreateBulk) ExecX(ctx context.Context) {
	if err := mrecb.Exec(ctx); err != nil {
		panic(err)
	}
}
