// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/DevilGenius/airgate-core/ent/monitorevent"
)

// MonitorEventCreate is the builder for creating a MonitorEvent entity.
type MonitorEventCreate struct {
	config
	mutation *MonitorEventMutation
	hooks    []Hook
}

// SetType sets the "type" field.
func (mec *MonitorEventCreate) SetType(m monitorevent.Type) *MonitorEventCreate {
	mec.mutation.SetType(m)
	return mec
}

// SetSeverity sets the "severity" field.
func (mec *MonitorEventCreate) SetSeverity(m monitorevent.Severity) *MonitorEventCreate {
	mec.mutation.SetSeverity(m)
	return mec
}

// SetNillableSeverity sets the "severity" field if the given value is not nil.
func (mec *MonitorEventCreate) SetNillableSeverity(m *monitorevent.Severity) *MonitorEventCreate {
	if m != nil {
		mec.SetSeverity(*m)
	}
	return mec
}

// SetStatus sets the "status" field.
func (mec *MonitorEventCreate) SetStatus(m monitorevent.Status) *MonitorEventCreate {
	mec.mutation.SetStatus(m)
	return mec
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (mec *MonitorEventCreate) SetNillableStatus(m *monitorevent.Status) *MonitorEventCreate {
	if m != nil {
		mec.SetStatus(*m)
	}
	return mec
}

// SetSource sets the "source" field.
func (mec *MonitorEventCreate) SetSource(s string) *MonitorEventCreate {
	mec.mutation.SetSource(s)
	return mec
}

// SetNillableSource sets the "source" field if the given value is not nil.
func (mec *MonitorEventCreate) SetNillableSource(s *string) *MonitorEventCreate {
	if s != nil {
		mec.SetSource(*s)
	}
	return mec
}

// SetSubjectType sets the "subject_type" field.
func (mec *MonitorEventCreate) SetSubjectType(s string) *MonitorEventCreate {
	mec.mutation.SetSubjectType(s)
	return mec
}

// SetNillableSubjectType sets the "subject_type" field if the given value is not nil.
func (mec *MonitorEventCreate) SetNillableSubjectType(s *string) *MonitorEventCreate {
	if s != nil {
		mec.SetSubjectType(*s)
	}
	return mec
}

// SetSubjectID sets the "subject_id" field.
func (mec *MonitorEventCreate) SetSubjectID(s string) *MonitorEventCreate {
	mec.mutation.SetSubjectID(s)
	return mec
}

// SetNillableSubjectID sets the "subject_id" field if the given value is not nil.
func (mec *MonitorEventCreate) SetNillableSubjectID(s *string) *MonitorEventCreate {
	if s != nil {
		mec.SetSubjectID(*s)
	}
	return mec
}

// SetHash sets the "hash" field.
func (mec *MonitorEventCreate) SetHash(s string) *MonitorEventCreate {
	mec.mutation.SetHash(s)
	return mec
}

// SetTitle sets the "title" field.
func (mec *MonitorEventCreate) SetTitle(s string) *MonitorEventCreate {
	mec.mutation.SetTitle(s)
	return mec
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (mec *MonitorEventCreate) SetNillableTitle(s *string) *MonitorEventCreate {
	if s != nil {
		mec.SetTitle(*s)
	}
	return mec
}

// SetMessage sets the "message" field.
func (mec *MonitorEventCreate) SetMessage(s string) *MonitorEventCreate {
	mec.mutation.SetMessage(s)
	return mec
}

// SetNillableMessage sets the "message" field if the given value is not nil.
func (mec *MonitorEventCreate) SetNillableMessage(s *string) *MonitorEventCreate {
	if s != nil {
		mec.SetMessage(*s)
	}
	return mec
}

// SetAccountID sets the "account_id" field.
func (mec *MonitorEventCreate) SetAccountID(i int) *MonitorEventCreate {
	mec.mutation.SetAccountID(i)
	return mec
}

// SetNillableAccountID sets the "account_id" field if the given value is not nil.
func (mec *MonitorEventCreate) SetNillableAccountID(i *int) *MonitorEventCreate {
	if i != nil {
		mec.SetAccountID(*i)
	}
	return mec
}

// SetAccountNameSnapshot sets the "account_name_snapshot" field.
func (mec *MonitorEventCreate) SetAccountNameSnapshot(s string) *MonitorEventCreate {
	mec.mutation.SetAccountNameSnapshot(s)
	return mec
}

// SetNillableAccountNameSnapshot sets the "account_name_snapshot" field if the given value is not nil.
func (mec *MonitorEventCreate) SetNillableAccountNameSnapshot(s *string) *MonitorEventCreate {
	if s != nil {
		mec.SetAccountNameSnapshot(*s)
	}
	return mec
}

// SetPlatform sets the "platform" field.
func (mec *MonitorEventCreate) SetPlatform(s string) *MonitorEventCreate {
	mec.mutation.SetPlatform(s)
	return mec
}

// SetNillablePlatform sets the "platform" field if the given value is not nil.
func (mec *MonitorEventCreate) SetNillablePlatform(s *string) *MonitorEventCreate {
	if s != nil {
		mec.SetPlatform(*s)
	}
	return mec
}

// SetPluginID sets the "plugin_id" field.
func (mec *MonitorEventCreate) SetPluginID(s string) *MonitorEventCreate {
	mec.mutation.SetPluginID(s)
	return mec
}

// SetNillablePluginID sets the "plugin_id" field if the given value is not nil.
func (mec *MonitorEventCreate) SetNillablePluginID(s *string) *MonitorEventCreate {
	if s != nil {
		mec.SetPluginID(*s)
	}
	return mec
}

// SetTaskType sets the "task_type" field.
func (mec *MonitorEventCreate) SetTaskType(s string) *MonitorEventCreate {
	mec.mutation.SetTaskType(s)
	return mec
}

// SetNillableTaskType sets the "task_type" field if the given value is not nil.
func (mec *MonitorEventCreate) SetNillableTaskType(s *string) *MonitorEventCreate {
	if s != nil {
		mec.SetTaskType(*s)
	}
	return mec
}

// SetErrorCode sets the "error_code" field.
func (mec *MonitorEventCreate) SetErrorCode(s string) *MonitorEventCreate {
	mec.mutation.SetErrorCode(s)
	return mec
}

// SetNillableErrorCode sets the "error_code" field if the given value is not nil.
func (mec *MonitorEventCreate) SetNillableErrorCode(s *string) *MonitorEventCreate {
	if s != nil {
		mec.SetErrorCode(*s)
	}
	return mec
}

// SetCreatedAt sets the "created_at" field.
func (mec *MonitorEventCreate) SetCreatedAt(t time.Time) *MonitorEventCreate {
	mec.mutation.SetCreatedAt(t)
	return mec
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (mec *MonitorEventCreate) SetNillableCreatedAt(t *time.Time) *MonitorEventCreate {
	if t != nil {
		mec.SetCreatedAt(*t)
	}
	return mec
}

// SetUpdatedAt sets the "updated_at" field.
func (mec *MonitorEventCreate) SetUpdatedAt(t time.Time) *MonitorEventCreate {
	mec.mutation.SetUpdatedAt(t)
	return mec
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (mec *MonitorEventCreate) SetNillableUpdatedAt(t *time.Time) *MonitorEventCreate {
	if t != nil {
		mec.SetUpdatedAt(*t)
	}
	return mec
}

// SetResolvedAt sets the "resolved_at" field.
func (mec *MonitorEventCreate) SetResolvedAt(t time.Time) *MonitorEventCreate {
	mec.mutation.SetResolvedAt(t)
	return mec
}

// SetNillableResolvedAt sets the "resolved_at" field if the given value is not nil.
func (mec *MonitorEventCreate) SetNillableResolvedAt(t *time.Time) *MonitorEventCreate {
	if t != nil {
		mec.SetResolvedAt(*t)
	}
	return mec
}

// SetIgnoredAt sets the "ignored_at" field.
func (mec *MonitorEventCreate) SetIgnoredAt(t time.Time) *MonitorEventCreate {
	mec.mutation.SetIgnoredAt(t)
	return mec
}

// SetNillableIgnoredAt sets the "ignored_at" field if the given value is not nil.
func (mec *MonitorEventCreate) SetNillableIgnoredAt(t *time.Time) *MonitorEventCreate {
	if t != nil {
		mec.SetIgnoredAt(*t)
	}
	return mec
}

// SetAutoResolveAt sets the "auto_resolve_at" field.
func (mec *MonitorEventCreate) SetAutoResolveAt(t time.Time) *MonitorEventCreate {
	mec.mutation.SetAutoResolveAt(t)
	return mec
}

// SetNillableAutoResolveAt sets the "auto_resolve_at" field if the given value is not nil.
func (mec *MonitorEventCreate) SetNillableAutoResolveAt(t *time.Time) *MonitorEventCreate {
	if t != nil {
		mec.SetAutoResolveAt(*t)
	}
	return mec
}

// SetExpiresAt sets the "expires_at" field.
func (mec *MonitorEventCreate) SetExpiresAt(t time.Time) *MonitorEventCreate {
	mec.mutation.SetExpiresAt(t)
	return mec
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (mec *MonitorEventCreate) SetNillableExpiresAt(t *time.Time) *MonitorEventCreate {
	if t != nil {
		mec.SetExpiresAt(*t)
	}
	return mec
}

// SetLastNotifiedAt sets the "last_notified_at" field.
func (mec *MonitorEventCreate) SetLastNotifiedAt(t time.Time) *MonitorEventCreate {
	mec.mutation.SetLastNotifiedAt(t)
	return mec
}

// SetNillableLastNotifiedAt sets the "last_notified_at" field if the given value is not nil.
func (mec *MonitorEventCreate) SetNillableLastNotifiedAt(t *time.Time) *MonitorEventCreate {
	if t != nil {
		mec.SetLastNotifiedAt(*t)
	}
	return mec
}

// SetNextNotifyAt sets the "next_notify_at" field.
func (mec *MonitorEventCreate) SetNextNotifyAt(t time.Time) *MonitorEventCreate {
	mec.mutation.SetNextNotifyAt(t)
	return mec
}

// SetNillableNextNotifyAt sets the "next_notify_at" field if the given value is not nil.
func (mec *MonitorEventCreate) SetNillableNextNotifyAt(t *time.Time) *MonitorEventCreate {
	if t != nil {
		mec.SetNextNotifyAt(*t)
	}
	return mec
}

// SetNotifyError sets the "notify_error" field.
func (mec *MonitorEventCreate) SetNotifyError(s string) *MonitorEventCreate {
	mec.mutation.SetNotifyError(s)
	return mec
}

// SetNillableNotifyError sets the "notify_error" field if the given value is not nil.
func (mec *MonitorEventCreate) SetNillableNotifyError(s *string) *MonitorEventCreate {
	if s != nil {
		mec.SetNotifyError(*s)
	}
	return mec
}

// SetDetail sets the "detail" field.
func (mec *MonitorEventCreate) SetDetail(m map[string]interface{}) *MonitorEventCreate {
	mec.mutation.SetDetail(m)
	return mec
}

// Mutation returns the MonitorEventMutation object of the builder.
func (mec *MonitorEventCreate) Mutation() *MonitorEventMutation {
	return mec.mutation
}

// Save creates the MonitorEvent in the database.
func (mec *MonitorEventCreate) Save(ctx context.Context) (*MonitorEvent, error) {
	mec.defaults()
	return withHooks(ctx, mec.sqlSave, mec.mutation, mec.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (mec *MonitorEventCreate) SaveX(ctx context.Context) *MonitorEvent {
	v, err := mec.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (mec *MonitorEventCreate) Exec(ctx context.Context) error {
	_, err := mec.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (mec *MonitorEventCreate) ExecX(ctx context.Context) {
	if err := mec.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (mec *MonitorEventCreate) defaults() {
	if _, ok := mec.mutation.Severity(); !ok {
		v := monitorevent.DefaultSeverity
		mec.mutation.SetSeverity(v)
	}
	if _, ok := mec.mutation.Status(); !ok {
		v := monitorevent.DefaultStatus
		mec.mutation.SetStatus(v)
	}
	if _, ok := mec.mutation.Source(); !ok {
		v := monitorevent.DefaultSource
		mec.mutation.SetSource(v)
	}
	if _, ok := mec.mutation.SubjectType(); !ok {
		v := monitorevent.DefaultSubjectType
		mec.mutation.SetSubjectType(v)
	}
	if _, ok := mec.mutation.SubjectID(); !ok {
		v := monitorevent.DefaultSubjectID
		mec.mutation.SetSubjectID(v)
	}
	if _, ok := mec.mutation.Title(); !ok {
		v := monitorevent.DefaultTitle
		mec.mutation.SetTitle(v)
	}
	if _, ok := mec.mutation.Message(); !ok {
		v := monitorevent.DefaultMessage
		mec.mutation.SetMessage(v)
	}
	if _, ok := mec.mutation.AccountNameSnapshot(); !ok {
		v := monitorevent.DefaultAccountNameSnapshot
		mec.mutation.SetAccountNameSnapshot(v)
	}
	if _, ok := mec.mutation.Platform(); !ok {
		v := monitorevent.DefaultPlatform
		mec.mutation.SetPlatform(v)
	}
	if _, ok := mec.mutation.PluginID(); !ok {
		v := monitorevent.DefaultPluginID
		mec.mutation.SetPluginID(v)
	}
	if _, ok := mec.mutation.TaskType(); !ok {
		v := monitorevent.DefaultTaskType
		mec.mutation.SetTaskType(v)
	}
	if _, ok := mec.mutation.ErrorCode(); !ok {
		v := monitorevent.DefaultErrorCode
		mec.mutation.SetErrorCode(v)
	}
	if _, ok := mec.mutation.CreatedAt(); !ok {
		v := monitorevent.DefaultCreatedAt()
		mec.mutation.SetCreatedAt(v)
	}
	if _, ok := mec.mutation.UpdatedAt(); !ok {
		v := monitorevent.DefaultUpdatedAt()
		mec.mutation.SetUpdatedAt(v)
	}
	if _, ok := mec.mutation.ExpiresAt(); !ok {
		v := monitorevent.DefaultExpiresAt()
		mec.mutation.SetExpiresAt(v)
	}
	if _, ok := mec.mutation.NotifyError(); !ok {
		v := monitorevent.DefaultNotifyError
		mec.mutation.SetNotifyError(v)
	}
	if _, ok := mec.mutation.Detail(); !ok {
		v := monitorevent.DefaultDetail
		mec.mutation.SetDetail(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (mec *MonitorEventCreate) check() error {
	if _, ok := mec.mutation.GetType(); !ok {
		return &ValidationError{Name: "type", err: errors.New(`ent: missing required field "MonitorEvent.type"`)}
	}
	if v, ok := mec.mutation.GetType(); ok {
		if err := monitorevent.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "MonitorEvent.type": %w`, err)}
		}
	}
	if _, ok := mec.mutation.Severity(); !ok {
		return &ValidationError{Name: "severity", err: errors.New(`ent: missing required field "MonitorEvent.severity"`)}
	}
	if v, ok := mec.mutation.Severity(); ok {
		if err := monitorevent.SeverityValidator(v); err != nil {
			return &ValidationError{Name: "severity", err: fmt.Errorf(`ent: validator failed for field "MonitorEvent.severity": %w`, err)}
		}
	}
	if _, ok := mec.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "MonitorEvent.status"`)}
	}
	if v, ok := mec.mutation.Status(); ok {
		if err := monitorevent.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "MonitorEvent.status": %w`, err)}
		}
	}
	if _, ok := mec.mutation.Source(); !ok {
		return &ValidationError{Name: "source", err: errors.New(`ent: missing required field "MonitorEvent.source"`)}
	}
	if v, ok := mec.mutation.Source(); ok {
		if err := monitorevent.SourceValidator(v); err != nil {
			return &ValidationError{Name: "source", err: fmt.Errorf(`ent: validator failed for field "MonitorEvent.source": %w`, err)}
		}
	}
	if _, ok := mec.mutation.SubjectType(); !ok {
		return &ValidationError{Name: "subject_type", err: errors.New(`ent: missing required field "MonitorEvent.subject_type"`)}
	}
	if v, ok := mec.mutation.SubjectType(); ok {
		if err := monitorevent.SubjectTypeValidator(v); err != nil {
			return &ValidationError{Name: "subject_type", err: fmt.Errorf(`ent: validator failed for field "MonitorEvent.subject_type": %w`, err)}
		}
	}
	if _, ok := mec.mutation.SubjectID(); !ok {
		return &ValidationError{Name: "subject_id", err: errors.New(`ent: missing required field "MonitorEvent.subject_id"`)}
	}
	if v, ok := mec.mutation.SubjectID(); ok {
		if err := monitorevent.SubjectIDValidator(v); err != nil {
			return &ValidationError{Name: "subject_id", err: fmt.Errorf(`ent: validator failed for field "MonitorEvent.subject_id": %w`, err)}
		}
	}
	if _, ok := mec.mutation.Hash(); !ok {
		return &ValidationError{Name: "hash", err: errors.New(`ent: missing required field "MonitorEvent.hash"`)}
	}
	if v, ok := mec.mutation.Hash(); ok {
		if err := monitorevent.HashValidator(v); err != nil {
			return &ValidationError{Name: "hash", err: fmt.Errorf(`ent: validator failed for field "MonitorEvent.hash": %w`, err)}
		}
	}
	if _, ok := mec.mutation.Title(); !ok {
		return &ValidationError{Name: "title", err: errors.New(`ent: missing required field "MonitorEvent.title"`)}
	}
	if v, ok := mec.mutation.Title(); ok {
		if err := monitorevent.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "MonitorEvent.title": %w`, err)}
		}
	}
	if _, ok := mec.mutation.Message(); !ok {
		return &ValidationError{Name: "message", err: errors.New(`ent: missing required field "MonitorEvent.message"`)}
	}
	if v, ok := mec.mutation.Message(); ok {
		if err := monitorevent.MessageValidator(v); err != nil {
			return &ValidationError{Name: "message", err: fmt.Errorf(`ent: validator failed for field "MonitorEvent.message": %w`, err)}
		}
	}
	if _, ok := mec.mutation.AccountNameSnapshot(); !ok {
		return &ValidationError{Name: "account_name_snapshot", err: errors.New(`ent: missing required field "MonitorEvent.account_name_snapshot"`)}
	}
	if v, ok := mec.mutation.AccountNameSnapshot(); ok {
		if err := monitorevent.AccountNameSnapshotValidator(v); err != nil {
			return &ValidationError{Name: "account_name_snapshot", err: fmt.Errorf(`ent: validator failed for field "MonitorEvent.account_name_snapshot": %w`, err)}
		}
	}
	if _, ok := mec.mutation.Platform(); !ok {
		return &ValidationError{Name: "platform", err: errors.New(`ent: missing required field "MonitorEvent.platform"`)}
	}
	if v, ok := mec.mutation.Platform(); ok {
		if err := monitorevent.PlatformValidator(v); err != nil {
			return &ValidationError{Name: "platform", err: fmt.Errorf(`ent: validator failed for field "MonitorEvent.platform": %w`, err)}
		}
	}
	if _, ok := mec.mutation.PluginID(); !ok {
		return &ValidationError{Name: "plugin_id", err: errors.New(`ent: missing required field "MonitorEvent.plugin_id"`)}
	}
	if v, ok := mec.mutation.PluginID(); ok {
		if err := monitorevent.PluginIDValidator(v); err != nil {
			return &ValidationError{Name: "plugin_id", err: fmt.Errorf(`ent: validator failed for field "MonitorEvent.plugin_id": %w`, err)}
		}
	}
	if _, ok := mec.mutation.TaskType(); !ok {
		return &ValidationError{Name: "task_type", err: errors.New(`ent: missing required field "MonitorEvent.task_type"`)}
	}
	if v, ok := mec.mutation.TaskType(); ok {
		if err := monitorevent.TaskTypeValidator(v); err != nil {
			return &ValidationError{Name: "task_type", err: fmt.Errorf(`ent: validator failed for field "MonitorEvent.task_type": %w`, err)}
		}
	}
	if _, ok := mec.mutation.ErrorCode(); !ok {
		return &ValidationError{Name: "error_code", err: errors.New(`ent: missing required field "MonitorEvent.error_code"`)}
	}
	if v, ok := mec.mutation.ErrorCode(); ok {
		if err := monitorevent.ErrorCodeValidator(v); err != nil {
			return &ValidationError{Name: "error_code", err: fmt.Errorf(`ent: validator failed for field "MonitorEvent.error_code": %w`, err)}
		}
	}
	if _, ok := mec.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "MonitorEvent.created_at"`)}
	}
	if _, ok := mec.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "MonitorEvent.updated_at"`)}
	}
	if _, ok := mec.mutation.ExpiresAt(); !ok {
		return &ValidationError{Name: "expires_at", err: errors.New(`ent: missing required field "MonitorEvent.expires_at"`)}
	}
	if _, ok := mec.mutation.NotifyError(); !ok {
		return &ValidationError{Name: "notify_error", err: errors.New(`ent: missing required field "MonitorEvent.notify_error"`)}
	}
	if v, ok := mec.mutation.NotifyError(); ok {
		if err := monitorevent.NotifyErrorValidator(v); err != nil {
			return &ValidationError{Name: "notify_error", err: fmt.Errorf(`ent: validator failed for field "MonitorEvent.notify_error": %w`, err)}
		}
	}
	return nil
}

func (mec *MonitorEventCreate) sqlSave(ctx context.Context) (*MonitorEvent, error) {
	if err := mec.check(); err != nil {
		return nil, err
	}
	_node, _spec := mec.createSpec()
	if err := sqlgraph.CreateNode(ctx, mec.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	mec.mutation.id = &_node.ID
	mec.mutation.done = true
	return _node, nil
}

func (mec *MonitorEventCreate) createSpec() (*MonitorEvent, *sqlgraph.CreateSpec) {
	var (
		_node = &MonitorEvent{config: mec.config}
		_spec = sqlgraph.NewCreateSpec(monitorevent.Table, sqlgraph.NewFieldSpec(monitorevent.FieldID, field.TypeInt))
	)
	if value, ok := mec.mutation.GetType(); ok {
		_spec.SetField(monitorevent.FieldType, field.TypeEnum, value)
		_node.Type = value
	}
	if value, ok := mec.mutation.Severity(); ok {
		_spec.SetField(monitorevent.FieldSeverity, field.TypeEnum, value)
		_node.Severity = value
	}
	if value, ok := mec.mutation.Status(); ok {
		_spec.SetField(monitorevent.FieldStatus, field.TypeEnum, value)
		_node.Status = value
	}
	if value, ok := mec.mutation.Source(); ok {
		_spec.SetField(monitorevent.FieldSource, field.TypeString, value)
		_node.Source = value
	}
	if value, ok := mec.mutation.SubjectType(); ok {
		_spec.SetField(monitorevent.FieldSubjectType, field.TypeString, value)
		_node.SubjectType = value
	}
	if value, ok := mec.mutation.SubjectID(); ok {
		_spec.SetField(monitorevent.FieldSubjectID, field.TypeString, value)
		_node.SubjectID = value
	}
	if value, ok := mec.mutation.Hash(); ok {
		_spec.SetField(monitorevent.FieldHash, field.TypeString, value)
		_node.Hash = value
	}
	if value, ok := mec.mutation.Title(); ok {
		_spec.SetField(monitorevent.FieldTitle, field.TypeString, value)
		_node.Title = value
	}
	if value, ok := mec.mutation.Message(); ok {
		_spec.SetField(monitorevent.FieldMessage, field.TypeString, value)
		_node.Message = value
	}
	if value, ok := mec.mutation.AccountID(); ok {
		_spec.SetField(monitorevent.FieldAccountID, field.TypeInt, value)
		_node.AccountID = &value
	}
	if value, ok := mec.mutation.AccountNameSnapshot(); ok {
		_spec.SetField(monitorevent.FieldAccountNameSnapshot, field.TypeString, value)
		_node.AccountNameSnapshot = value
	}
	if value, ok := mec.mutation.Platform(); ok {
		_spec.SetField(monitorevent.FieldPlatform, field.TypeString, value)
		_node.Platform = value
	}
	if value, ok := mec.mutation.PluginID(); ok {
		_spec.SetField(monitorevent.FieldPluginID, field.TypeString, value)
		_node.PluginID = value
	}
	if value, ok := mec.mutation.TaskType(); ok {
		_spec.SetField(monitorevent.FieldTaskType, field.TypeString, value)
		_node.TaskType = value
	}
	if value, ok := mec.mutation.ErrorCode(); ok {
		_spec.SetField(monitorevent.FieldErrorCode, field.TypeString, value)
		_node.ErrorCode = value
	}
	if value, ok := mec.mutation.CreatedAt(); ok {
		_spec.SetField(monitorevent.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := mec.mutation.UpdatedAt(); ok {
		_spec.SetField(monitorevent.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := mec.mutation.ResolvedAt(); ok {
		_spec.SetField(monitorevent.FieldResolvedAt, field.TypeTime, value)
		_node.ResolvedAt = &value
	}
	if value, ok := mec.mutation.IgnoredAt(); ok {
		_spec.SetField(monitorevent.FieldIgnoredAt, field.TypeTime, value)
		_node.IgnoredAt = &value
	}
	if value, ok := mec.mutation.AutoResolveAt(); ok {
		_spec.SetField(monitorevent.FieldAutoResolveAt, field.TypeTime, value)
		_node.AutoResolveAt = &value
	}
	if value, ok := mec.mutation.ExpiresAt(); ok {
		_spec.SetField(monitorevent.FieldExpiresAt, field.TypeTime, value)
		_node.ExpiresAt = value
	}
	if value, ok := mec.mutation.LastNotifiedAt(); ok {
		_spec.SetField(monitorevent.FieldLastNotifiedAt, field.TypeTime, value)
		_node.LastNotifiedAt = &value
	}
	if value, ok := mec.mutation.NextNotifyAt(); ok {
		_spec.SetField(monitorevent.FieldNextNotifyAt, field.TypeTime, value)
		_node.NextNotifyAt = &value
	}
	if value, ok := mec.mutation.NotifyError(); ok {
		_spec.SetField(monitorevent.FieldNotifyError, field.TypeString, value)
		_node.NotifyError = value
	}
	if value, ok := mec.mutation.Detail(); ok {
		_spec.SetField(monitorevent.FieldDetail, field.TypeJSON, value)
		_node.Detail = value
	}
	return _node, _spec
}

// MonitorEventCreateBulk is the builder for creating many MonitorEvent entities in bulk.
type MonitorEventCreateBulk struct {
	config
	err      error
	builders []*MonitorEventCreate
}

// Save creates the MonitorEvent entities in the database.
func (mecb *MonitorEventCreateBulk) Save(ctx context.Context) ([]*MonitorEvent, error) {
	if mecb.err != nil {
		return nil, mecb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(mecb.builders))
	nodes := make([]*MonitorEvent, len(mecb.builders))
	mutators := make([]Mutator, len(mecb.builders))
	for i := range mecb.builders {
		func(i int, root context.Context) {
			builder := mecb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*MonitorEventMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, mecb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, mecb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, mecb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (mecb *MonitorEventCreateBulk) SaveX(ctx context.Context) []*MonitorEvent {
	v, err := mecb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (mecb *MonitorEventCreateBulk) Exec(ctx context.Context) error {
	_, err := mecb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (mecb *MonitorEventCreateBulk) ExecX(ctx context.Context) {
	if err := mecb.Exec(ctx); err != nil {
		panic(err)
	}
}
