// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/DevilGenius/airgate-core/ent/monitorrequesttrace"
	"github.com/DevilGenius/airgate-core/ent/predicate"
)

// MonitorRequestTraceUpdate is the builder for updating MonitorRequestTrace entities.
type MonitorRequestTraceUpdate struct {
	config
	hooks    []Hook
	mutation *MonitorRequestTraceMutation
}

// Where appends a list predicates to the MonitorRequestTraceUpdate builder.
func (mrtu *MonitorRequestTraceUpdate) Where(ps ...predicate.MonitorRequestTrace) *MonitorRequestTraceUpdate {
	mrtu.mutation.Where(ps...)
	return mrtu
}

// SetHash sets the "hash" field.
func (mrtu *MonitorRequestTraceUpdate) SetHash(s string) *MonitorRequestTraceUpdate {
	mrtu.mutation.SetHash(s)
	return mrtu
}

// SetNillableHash sets the "hash" field if the given value is not nil.
func (mrtu *MonitorRequestTraceUpdate) SetNillableHash(s *string) *MonitorRequestTraceUpdate {
	if s != nil {
		mrtu.SetHash(*s)
	}
	return mrtu
}

// SetSchemaVersion sets the "schema_version" field.
func (mrtu *MonitorRequestTraceUpdate) SetSchemaVersion(i int) *MonitorRequestTraceUpdate {
	mrtu.mutation.ResetSchemaVersion()
	mrtu.mutation.SetSchemaVersion(i)
	return mrtu
}

// SetNillableSchemaVersion sets the "schema_version" field if the given value is not nil.
func (mrtu *MonitorRequestTraceUpdate) SetNillableSchemaVersion(i *int) *MonitorRequestTraceUpdate {
	if i != nil {
		mrtu.SetSchemaVersion(*i)
	}
	return mrtu
}

// AddSchemaVersion adds i to the "schema_version" field.
func (mrtu *MonitorRequestTraceUpdate) AddSchemaVersion(i int) *MonitorRequestTraceUpdate {
	mrtu.mutation.AddSchemaVersion(i)
	return mrtu
}

// SetEncoding sets the "encoding" field.
func (mrtu *MonitorRequestTraceUpdate) SetEncoding(s string) *MonitorRequestTraceUpdate {
	mrtu.mutation.SetEncoding(s)
	return mrtu
}

// SetNillableEncoding sets the "encoding" field if the given value is not nil.
func (mrtu *MonitorRequestTraceUpdate) SetNillableEncoding(s *string) *MonitorRequestTraceUpdate {
	if s != nil {
		mrtu.SetEncoding(*s)
	}
	return mrtu
}

// SetPayload sets the "payload" field.
func (mrtu *MonitorRequestTraceUpdate) SetPayload(b []byte) *MonitorRequestTraceUpdate {
	mrtu.mutation.SetPayload(b)
	return mrtu
}

// SetRawSize sets the "raw_size" field.
func (mrtu *MonitorRequestTraceUpdate) SetRawSize(i int64) *MonitorRequestTraceUpdate {
	mrtu.mutation.ResetRawSize()
	mrtu.mutation.SetRawSize(i)
	return mrtu
}

// SetNillableRawSize sets the "raw_size" field if the given value is not nil.
func (mrtu *MonitorRequestTraceUpdate) SetNillableRawSize(i *int64) *MonitorRequestTraceUpdate {
	if i != nil {
		mrtu.SetRawSize(*i)
	}
	return mrtu
}

// AddRawSize adds i to the "raw_size" field.
func (mrtu *MonitorRequestTraceUpdate) AddRawSize(i int64) *MonitorRequestTraceUpdate {
	mrtu.mutation.AddRawSize(i)
	return mrtu
}

// SetCompressedSize sets the "compressed_size" field.
func (mrtu *MonitorRequestTraceUpdate) SetCompressedSize(i int64) *MonitorRequestTraceUpdate {
	mrtu.mutation.ResetCompressedSize()
	mrtu.mutation.SetCompressedSize(i)
	return mrtu
}

// SetNillableCompressedSize sets the "compressed_size" field if the given value is not nil.
func (mrtu *MonitorRequestTraceUpdate) SetNillableCompressedSize(i *int64) *MonitorRequestTraceUpdate {
	if i != nil {
		mrtu.SetCompressedSize(*i)
	}
	return mrtu
}

// AddCompressedSize adds i to the "compressed_size" field.
func (mrtu *MonitorRequestTraceUpdate) AddCompressedSize(i int64) *MonitorRequestTraceUpdate {
	mrtu.mutation.AddCompressedSize(i)
	return mrtu
}

// SetSeenCount sets the "seen_count" field.
func (mrtu *MonitorRequestTraceUpdate) SetSeenCount(i int64) *MonitorRequestTraceUpdate {
	mrtu.mutation.ResetSeenCount()
	mrtu.mutation.SetSeenCount(i)
	return mrtu
}

// SetNillableSeenCount sets the "seen_count" field if the given value is not nil.
func (mrtu *MonitorRequestTraceUpdate) SetNillableSeenCount(i *int64) *MonitorRequestTraceUpdate {
	if i != nil {
		mrtu.SetSeenCount(*i)
	}
	return mrtu
}

// AddSeenCount adds i to the "seen_count" field.
func (mrtu *MonitorRequestTraceUpdate) AddSeenCount(i int64) *MonitorRequestTraceUpdate {
	mrtu.mutation.AddSeenCount(i)
	return mrtu
}

// SetFirstSeenAt sets the "first_seen_at" field.
func (mrtu *MonitorRequestTraceUpdate) SetFirstSeenAt(t time.Time) *MonitorRequestTraceUpdate {
	mrtu.mutation.SetFirstSeenAt(t)
	return mrtu
}

// SetNillableFirstSeenAt sets the "first_seen_at" field if the given value is not nil.
func (mrtu *MonitorRequestTraceUpdate) SetNillableFirstSeenAt(t *time.Time) *MonitorRequestTraceUpdate {
	if t != nil {
		mrtu.SetFirstSeenAt(*t)
	}
	return mrtu
}

// SetLastSeenAt sets the "last_seen_at" field.
func (mrtu *MonitorRequestTraceUpdate) SetLastSeenAt(t time.Time) *MonitorRequestTraceUpdate {
	mrtu.mutation.SetLastSeenAt(t)
	return mrtu
}

// SetNillableLastSeenAt sets the "last_seen_at" field if the given value is not nil.
func (mrtu *MonitorRequestTraceUpdate) SetNillableLastSeenAt(t *time.Time) *MonitorRequestTraceUpdate {
	if t != nil {
		mrtu.SetLastSeenAt(*t)
	}
	return mrtu
}

// SetExpiresAt sets the "expires_at" field.
func (mrtu *MonitorRequestTraceUpdate) SetExpiresAt(t time.Time) *MonitorRequestTraceUpdate {
	mrtu.mutation.SetExpiresAt(t)
	return mrtu
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (mrtu *MonitorRequestTraceUpdate) SetNillableExpiresAt(t *time.Time) *MonitorRequestTraceUpdate {
	if t != nil {
		mrtu.SetExpiresAt(*t)
	}
	return mrtu
}

// Mutation returns the MonitorRequestTraceMutation object of the builder.
func (mrtu *MonitorRequestTraceUpdate) Mutation() *MonitorRequestTraceMutation {
	return mrtu.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (mrtu *MonitorRequestTraceUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, mrtu.sqlSave, mrtu.mutation, mrtu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (mrtu *MonitorRequestTraceUpdate) SaveX(ctx context.Context) int {
	affected, err := mrtu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (mrtu *MonitorRequestTraceUpdate) Exec(ctx context.Context) error {
	_, err := mrtu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (mrtu *MonitorRequestTraceUpdate) ExecX(ctx context.Context) {
	if err := mrtu.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (mrtu *MonitorRequestTraceUpdate) check() error {
	if v, ok := mrtu.mutation.Hash(); ok {
		if err := monitorrequesttrace.HashValidator(v); err != nil {
			return &ValidationError{Name: "hash", err: fmt.Errorf(`ent: validator failed for field "MonitorRequestTrace.hash": %w`, err)}
		}
	}
	if v, ok := mrtu.mutation.Encoding(); ok {
		if err := monitorrequesttrace.EncodingValidator(v); err != nil {
			return &ValidationError{Name: "encoding", err: fmt.Errorf(`ent: validator failed for field "MonitorRequestTrace.encoding": %w`, err)}
		}
	}
	return nil
}

func (mrtu *MonitorRequestTraceUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := mrtu.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(monitorrequesttrace.Table, monitorrequesttrace.Columns, sqlgraph.NewFieldSpec(monitorrequesttrace.FieldID, field.TypeInt))
	if ps := mrtu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := mrtu.mutation.Hash(); ok {
		_spec.SetField(monitorrequesttrace.FieldHash, field.TypeString, value)
	}
	if value, ok := mrtu.mutation.SchemaVersion(); ok {
		_spec.SetField(monitorrequesttrace.FieldSchemaVersion, field.TypeInt, value)
	}
	if value, ok := mrtu.mutation.AddedSchemaVersion(); ok {
		_spec.AddField(monitorrequesttrace.FieldSchemaVersion, field.TypeInt, value)
	}
	if value, ok := mrtu.mutation.Encoding(); ok {
		_spec.SetField(monitorrequesttrace.FieldEncoding, field.TypeString, value)
	}
	if value, ok := mrtu.mutation.Payload(); ok {
		_spec.SetField(monitorrequesttrace.FieldPayload, field.TypeBytes, value)
	}
	if value, ok := mrtu.mutation.RawSize(); ok {
		_spec.SetField(monitorrequesttrace.FieldRawSize, field.TypeInt64, value)
	}
	if value, ok := mrtu.mutation.AddedRawSize(); ok {
		_spec.AddField(monitorrequesttrace.FieldRawSize, field.TypeInt64, value)
	}
	if value, ok := mrtu.mutation.CompressedSize(); ok {
		_spec.SetField(monitorrequesttrace.FieldCompressedSize, field.TypeInt64, value)
	}
	if value, ok := mrtu.mutation.AddedCompressedSize(); ok {
		_spec.AddField(monitorrequesttrace.FieldCompressedSize, field.TypeInt64, value)
	}
	if value, ok := mrtu.mutation.SeenCount(); ok {
		_spec.SetField(monitorrequesttrace.FieldSeenCount, field.TypeInt64, value)
	}
	if value, ok := mrtu.mutation.AddedSeenCount(); ok {
		_spec.AddField(monitorrequesttrace.FieldSeenCount, field.TypeInt64, value)
	}
	if value, ok := mrtu.mutation.FirstSeenAt(); ok {
		_spec.SetField(monitorrequesttrace.FieldFirstSeenAt, field.TypeTime, value)
	}
	if value, ok := mrtu.mutation.LastSeenAt(); ok {
		_spec.SetField(monitorrequesttrace.FieldLastSeenAt, field.TypeTime, value)
	}
	if value, ok := mrtu.mutation.ExpiresAt(); ok {
		_spec.SetField(monitorrequesttrace.FieldExpiresAt, field.TypeTime, value)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, mrtu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{monitorrequesttrace.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	mrtu.mutation.done = true
	return n, nil
}

// MonitorRequestTraceUpdateOne is the builder for updating a single MonitorRequestTrace entity.
type MonitorRequestTraceUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *MonitorRequestTraceMutation
}

// SetHash sets the "hash" field.
func (mrtuo *MonitorRequestTraceUpdateOne) SetHash(s string) *MonitorRequestTraceUpdateOne {
	mrtuo.mutation.SetHash(s)
	return mrtuo
}

// SetNillableHash sets the "hash" field if the given value is not nil.
func (mrtuo *MonitorRequestTraceUpdateOne) SetNillableHash(s *string) *MonitorRequestTraceUpdateOne {
	if s != nil {
		mrtuo.SetHash(*s)
	}
	return mrtuo
}

// SetSchemaVersion sets the "schema_version" field.
func (mrtuo *MonitorRequestTraceUpdateOne) SetSchemaVersion(i int) *MonitorRequestTraceUpdateOne {
	mrtuo.mutation.ResetSchemaVersion()
	mrtuo.mutation.SetSchemaVersion(i)
	return mrtuo
}

// SetNillableSchemaVersion sets the "schema_version" field if the given value is not nil.
func (mrtuo *MonitorRequestTraceUpdateOne) SetNillableSchemaVersion(i *int) *MonitorRequestTraceUpdateOne {
	if i != nil {
		mrtuo.SetSchemaVersion(*i)
	}
	return mrtuo
}

// AddSchemaVersion adds i to the "schema_version" field.
func (mrtuo *MonitorRequestTraceUpdateOne) AddSchemaVersion(i int) *MonitorRequestTraceUpdateOne {
	mrtuo.mutation.AddSchemaVersion(i)
	return mrtuo
}

// SetEncoding sets the "encoding" field.
func (mrtuo *MonitorRequestTraceUpdateOne) SetEncoding(s string) *MonitorRequestTraceUpdateOne {
	mrtuo.mutation.SetEncoding(s)
	return mrtuo
}

// SetNillableEncoding sets the "encoding" field if the given value is not nil.
func (mrtuo *MonitorRequestTraceUpdateOne) SetNillableEncoding(s *string) *MonitorRequestTraceUpdateOne {
	if s != nil {
		mrtuo.SetEncoding(*s)
	}
	return mrtuo
}

// SetPayload sets the "payload" field.
func (mrtuo *MonitorRequestTraceUpdateOne) SetPayload(b []byte) *MonitorRequestTraceUpdateOne {
	mrtuo.mutation.SetPayload(b)
	return mrtuo
}

// SetRawSize sets the "raw_size" field.
func (mrtuo *MonitorRequestTraceUpdateOne) SetRawSize(i int64) *MonitorRequestTraceUpdateOne {
	mrtuo.mutation.ResetRawSize()
	mrtuo.mutation.SetRawSize(i)
	return mrtuo
}

// SetNillableRawSize sets the "raw_size" field if the given value is not nil.
func (mrtuo *MonitorRequestTraceUpdateOne) SetNillableRawSize(i *int64) *MonitorRequestTraceUpdateOne {
	if i != nil {
		mrtuo.SetRawSize(*i)
	}
	return mrtuo
}

// AddRawSize adds i to the "raw_size" field.
func (mrtuo *MonitorRequestTraceUpdateOne) AddRawSize(i int64) *MonitorRequestTraceUpdateOne {
	mrtuo.mutation.AddRawSize(i)
	return mrtuo
}

// SetCompressedSize sets the "compressed_size" field.
func (mrtuo *MonitorRequestTraceUpdateOne) SetCompressedSize(i int64) *MonitorRequestTraceUpdateOne {
	mrtuo.mutation.ResetCompressedSize()
	mrtuo.mutation.SetCompressedSize(i)
	return mrtuo
}

// SetNillableCompressedSize sets the "compressed_size" field if the given value is not nil.
func (mrtuo *MonitorRequestTraceUpdateOne) SetNillableCompressedSize(i *int64) *MonitorRequestTraceUpdateOne {
	if i != nil {
		mrtuo.SetCompressedSize(*i)
	}
	return mrtuo
}

// AddCompressedSize adds i to the "compressed_size" field.
func (mrtuo *MonitorRequestTraceUpdateOne) AddCompressedSize(i int64) *MonitorRequestTraceUpdateOne {
	mrtuo.mutation.AddCompressedSize(i)
	return mrtuo
}

// SetSeenCount sets the "seen_count" field.
func (mrtuo *MonitorRequestTraceUpdateOne) SetSeenCount(i int64) *MonitorRequestTraceUpdateOne {
	mrtuo.mutation.ResetSeenCount()
	mrtuo.mutation.SetSeenCount(i)
	return mrtuo
}

// SetNillableSeenCount sets the "seen_count" field if the given value is not nil.
func (mrtuo *MonitorRequestTraceUpdateOne) SetNillableSeenCount(i *int64) *MonitorRequestTraceUpdateOne {
	if i != nil {
		mrtuo.SetSeenCount(*i)
	}
	return mrtuo
}

// AddSeenCount adds i to the "seen_count" field.
func (mrtuo *MonitorRequestTraceUpdateOne) AddSeenCount(i int64) *MonitorRequestTraceUpdateOne {
	mrtuo.mutation.AddSeenCount(i)
	return mrtuo
}

// SetFirstSeenAt sets the "first_seen_at" field.
func (mrtuo *MonitorRequestTraceUpdateOne) SetFirstSeenAt(t time.Time) *MonitorRequestTraceUpdateOne {
	mrtuo.mutation.SetFirstSeenAt(t)
	return mrtuo
}

// SetNillableFirstSeenAt sets the "first_seen_at" field if the given value is not nil.
func (mrtuo *MonitorRequestTraceUpdateOne) SetNillableFirstSeenAt(t *time.Time) *MonitorRequestTraceUpdateOne {
	if t != nil {
		mrtuo.SetFirstSeenAt(*t)
	}
	return mrtuo
}

// SetLastSeenAt sets the "last_seen_at" field.
func (mrtuo *MonitorRequestTraceUpdateOne) SetLastSeenAt(t time.Time) *MonitorRequestTraceUpdateOne {
	mrtuo.mutation.SetLastSeenAt(t)
	return mrtuo
}

// SetNillableLastSeenAt sets the "last_seen_at" field if the given value is not nil.
func (mrtuo *MonitorRequestTraceUpdateOne) SetNillableLastSeenAt(t *time.Time) *MonitorRequestTraceUpdateOne {
	if t != nil {
		mrtuo.SetLastSeenAt(*t)
	}
	return mrtuo
}

// SetExpiresAt sets the "expires_at" field.
func (mrtuo *MonitorRequestTraceUpdateOne) SetExpiresAt(t time.Time) *MonitorRequestTraceUpdateOne {
	mrtuo.mutation.SetExpiresAt(t)
	return mrtuo
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (mrtuo *MonitorRequestTraceUpdateOne) SetNillableExpiresAt(t *time.Time) *MonitorRequestTraceUpdateOne {
	if t != nil {
		mrtuo.SetExpiresAt(*t)
	}
	return mrtuo
}

// Mutation returns the MonitorRequestTraceMutation object of the builder.
func (mrtuo *MonitorRequestTraceUpdateOne) Mutation() *MonitorRequestTraceMutation {
	return mrtuo.mutation
}

// Where appends a list predicates to the MonitorRequestTraceUpdate builder.
func (mrtuo *MonitorRequestTraceUpdateOne) Where(ps ...predicate.MonitorRequestTrace) *MonitorRequestTraceUpdateOne {
	mrtuo.mutation.Where(ps...)
	return mrtuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (mrtuo *MonitorRequestTraceUpdateOne) Select(field string, fields ...string) *MonitorRequestTraceUpdateOne {
	mrtuo.fields = append([]string{field}, fields...)
	return mrtuo
}

// Save executes the query and returns the updated MonitorRequestTrace entity.
func (mrtuo *MonitorRequestTraceUpdateOne) Save(ctx context.Context) (*MonitorRequestTrace, error) {
	return withHooks(ctx, mrtuo.sqlSave, mrtuo.mutation, mrtuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (mrtuo *MonitorRequestTraceUpdateOne) SaveX(ctx context.Context) *MonitorRequestTrace {
	node, err := mrtuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (mrtuo *MonitorRequestTraceUpdateOne) Exec(ctx context.Context) error {
	_, err := mrtuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (mrtuo *MonitorRequestTraceUpdateOne) ExecX(ctx context.Context) {
	if err := mrtuo.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (mrtuo *MonitorRequestTraceUpdateOne) check() error {
	if v, ok := mrtuo.mutation.Hash(); ok {
		if err := monitorrequesttrace.HashValidator(v); err != nil {
			return &ValidationError{Name: "hash", err: fmt.Errorf(`ent: validator failed for field "MonitorRequestTrace.hash": %w`, err)}
		}
	}
	if v, ok := mrtuo.mutation.Encoding(); ok {
		if err := monitorrequesttrace.EncodingValidator(v); err != nil {
			return &ValidationError{Name: "encoding", err: fmt.Errorf(`ent: validator failed for field "MonitorRequestTrace.encoding": %w`, err)}
		}
	}
	return nil
}

func (mrtuo *MonitorRequestTraceUpdateOne) sqlSave(ctx context.Context) (_node *MonitorRequestTrace, err error) {
	if err := mrtuo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(monitorrequesttrace.Table, monitorrequesttrace.Columns, sqlgraph.NewFieldSpec(monitorrequesttrace.FieldID, field.TypeInt))
	id, ok := mrtuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "MonitorRequestTrace.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := mrtuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, monitorrequesttrace.FieldID)
		for _, f := range fields {
			if !monitorrequesttrace.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != monitorrequesttrace.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := mrtuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := mrtuo.mutation.Hash(); ok {
		_spec.SetField(monitorrequesttrace.FieldHash, field.TypeString, value)
	}
	if value, ok := mrtuo.mutation.SchemaVersion(); ok {
		_spec.SetField(monitorrequesttrace.FieldSchemaVersion, field.TypeInt, value)
	}
	if value, ok := mrtuo.mutation.AddedSchemaVersion(); ok {
		_spec.AddField(monitorrequesttrace.FieldSchemaVersion, field.TypeInt, value)
	}
	if value, ok := mrtuo.mutation.Encoding(); ok {
		_spec.SetField(monitorrequesttrace.FieldEncoding, field.TypeString, value)
	}
	if value, ok := mrtuo.mutation.Payload(); ok {
		_spec.SetField(monitorrequesttrace.FieldPayload, field.TypeBytes, value)
	}
	if value, ok := mrtuo.mutation.RawSize(); ok {
		_spec.SetField(monitorrequesttrace.FieldRawSize, field.TypeInt64, value)
	}
	if value, ok := mrtuo.mutation.AddedRawSize(); ok {
		_spec.AddField(monitorrequesttrace.FieldRawSize, field.TypeInt64, value)
	}
	if value, ok := mrtuo.mutation.CompressedSize(); ok {
		_spec.SetField(monitorrequesttrace.FieldCompressedSize, field.TypeInt64, value)
	}
	if value, ok := mrtuo.mutation.AddedCompressedSize(); ok {
		_spec.AddField(monitorrequesttrace.FieldCompressedSize, field.TypeInt64, value)
	}
	if value, ok := mrtuo.mutation.SeenCount(); ok {
		_spec.SetField(monitorrequesttrace.FieldSeenCount, field.TypeInt64, value)
	}
	if value, ok := mrtuo.mutation.AddedSeenCount(); ok {
		_spec.AddField(monitorrequesttrace.FieldSeenCount, field.TypeInt64, value)
	}
	if value, ok := mrtuo.mutation.FirstSeenAt(); ok {
		_spec.SetField(monitorrequesttrace.FieldFirstSeenAt, field.TypeTime, value)
	}
	if value, ok := mrtuo.mutation.LastSeenAt(); ok {
		_spec.SetField(monitorrequesttrace.FieldLastSeenAt, field.TypeTime, value)
	}
	if value, ok := mrtuo.mutation.ExpiresAt(); ok {
		_spec.SetField(monitorrequesttrace.FieldExpiresAt, field.TypeTime, value)
	}
	_node = &MonitorRequestTrace{config: mrtuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, mrtuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{monitorrequesttrace.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	mrtuo.mutation.done = true
	return _node, nil
}
