// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/DevilGenius/airgate-core/ent/monitorrequestevent"
	"github.com/DevilGenius/airgate-core/ent/predicate"
)

// MonitorRequestEventUpdate is the builder for updating MonitorRequestEvent entities.
type MonitorRequestEventUpdate struct {
	config
	hooks    []Hook
	mutation *MonitorRequestEventMutation
}

// Where appends a list predicates to the MonitorRequestEventUpdate builder.
func (mreu *MonitorRequestEventUpdate) Where(ps ...predicate.MonitorRequestEvent) *MonitorRequestEventUpdate {
	mreu.mutation.Where(ps...)
	return mreu
}

// SetType sets the "type" field.
func (mreu *MonitorRequestEventUpdate) SetType(s string) *MonitorRequestEventUpdate {
	mreu.mutation.SetType(s)
	return mreu
}

// SetNillableType sets the "type" field if the given value is not nil.
func (mreu *MonitorRequestEventUpdate) SetNillableType(s *string) *MonitorRequestEventUpdate {
	if s != nil {
		mreu.SetType(*s)
	}
	return mreu
}

// SetSeverity sets the "severity" field.
func (mreu *MonitorRequestEventUpdate) SetSeverity(m monitorrequestevent.Severity) *MonitorRequestEventUpdate {
	mreu.mutation.SetSeverity(m)
	return mreu
}

// SetNillableSeverity sets the "severity" field if the given value is not nil.
func (mreu *MonitorRequestEventUpdate) SetNillableSeverity(m *monitorrequestevent.Severity) *MonitorRequestEventUpdate {
	if m != nil {
		mreu.SetSeverity(*m)
	}
	return mreu
}

// SetSource sets the "source" field.
func (mreu *MonitorRequestEventUpdate) SetSource(s string) *MonitorRequestEventUpdate {
	mreu.mutation.SetSource(s)
	return mreu
}

// SetNillableSource sets the "source" field if the given value is not nil.
func (mreu *MonitorRequestEventUpdate) SetNillableSource(s *string) *MonitorRequestEventUpdate {
	if s != nil {
		mreu.SetSource(*s)
	}
	return mreu
}

// SetHash sets the "hash" field.
func (mreu *MonitorRequestEventUpdate) SetHash(s string) *MonitorRequestEventUpdate {
	mreu.mutation.SetHash(s)
	return mreu
}

// SetNillableHash sets the "hash" field if the given value is not nil.
func (mreu *MonitorRequestEventUpdate) SetNillableHash(s *string) *MonitorRequestEventUpdate {
	if s != nil {
		mreu.SetHash(*s)
	}
	return mreu
}

// SetFingerprint sets the "fingerprint" field.
func (mreu *MonitorRequestEventUpdate) SetFingerprint(s string) *MonitorRequestEventUpdate {
	mreu.mutation.SetFingerprint(s)
	return mreu
}

// SetNillableFingerprint sets the "fingerprint" field if the given value is not nil.
func (mreu *MonitorRequestEventUpdate) SetNillableFingerprint(s *string) *MonitorRequestEventUpdate {
	if s != nil {
		mreu.SetFingerprint(*s)
	}
	return mreu
}

// SetTitle sets the "title" field.
func (mreu *MonitorRequestEventUpdate) SetTitle(s string) *MonitorRequestEventUpdate {
	mreu.mutation.SetTitle(s)
	return mreu
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (mreu *MonitorRequestEventUpdate) SetNillableTitle(s *string) *MonitorRequestEventUpdate {
	if s != nil {
		mreu.SetTitle(*s)
	}
	return mreu
}

// SetMessage sets the "message" field.
func (mreu *MonitorRequestEventUpdate) SetMessage(s string) *MonitorRequestEventUpdate {
	mreu.mutation.SetMessage(s)
	return mreu
}

// SetNillableMessage sets the "message" field if the given value is not nil.
func (mreu *MonitorRequestEventUpdate) SetNillableMessage(s *string) *MonitorRequestEventUpdate {
	if s != nil {
		mreu.SetMessage(*s)
	}
	return mreu
}

// SetRequestID sets the "request_id" field.
func (mreu *MonitorRequestEventUpdate) SetRequestID(s string) *MonitorRequestEventUpdate {
	mreu.mutation.SetRequestID(s)
	return mreu
}

// SetNillableRequestID sets the "request_id" field if the given value is not nil.
func (mreu *MonitorRequestEventUpdate) SetNillableRequestID(s *string) *MonitorRequestEventUpdate {
	if s != nil {
		mreu.SetRequestID(*s)
	}
	return mreu
}

// SetAPIKeyID sets the "api_key_id" field.
func (mreu *MonitorRequestEventUpdate) SetAPIKeyID(i int) *MonitorRequestEventUpdate {
	mreu.mutation.ResetAPIKeyID()
	mreu.mutation.SetAPIKeyID(i)
	return mreu
}

// SetNillableAPIKeyID sets the "api_key_id" field if the given value is not nil.
func (mreu *MonitorRequestEventUpdate) SetNillableAPIKeyID(i *int) *MonitorRequestEventUpdate {
	if i != nil {
		mreu.SetAPIKeyID(*i)
	}
	return mreu
}

// AddAPIKeyID adds i to the "api_key_id" field.
func (mreu *MonitorRequestEventUpdate) AddAPIKeyID(i int) *MonitorRequestEventUpdate {
	mreu.mutation.AddAPIKeyID(i)
	return mreu
}

// ClearAPIKeyID clears the value of the "api_key_id" field.
func (mreu *MonitorRequestEventUpdate) ClearAPIKeyID() *MonitorRequestEventUpdate {
	mreu.mutation.ClearAPIKeyID()
	return mreu
}

// SetAPIKeyNameSnapshot sets the "api_key_name_snapshot" field.
func (mreu *MonitorRequestEventUpdate) SetAPIKeyNameSnapshot(s string) *MonitorRequestEventUpdate {
	mreu.mutation.SetAPIKeyNameSnapshot(s)
	return mreu
}

// SetNillableAPIKeyNameSnapshot sets the "api_key_name_snapshot" field if the given value is not nil.
func (mreu *MonitorRequestEventUpdate) SetNillableAPIKeyNameSnapshot(s *string) *MonitorRequestEventUpdate {
	if s != nil {
		mreu.SetAPIKeyNameSnapshot(*s)
	}
	return mreu
}

// SetUserID sets the "user_id" field.
func (mreu *MonitorRequestEventUpdate) SetUserID(i int) *MonitorRequestEventUpdate {
	mreu.mutation.ResetUserID()
	mreu.mutation.SetUserID(i)
	return mreu
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (mreu *MonitorRequestEventUpdate) SetNillableUserID(i *int) *MonitorRequestEventUpdate {
	if i != nil {
		mreu.SetUserID(*i)
	}
	return mreu
}

// AddUserID adds i to the "user_id" field.
func (mreu *MonitorRequestEventUpdate) AddUserID(i int) *MonitorRequestEventUpdate {
	mreu.mutation.AddUserID(i)
	return mreu
}

// ClearUserID clears the value of the "user_id" field.
func (mreu *MonitorRequestEventUpdate) ClearUserID() *MonitorRequestEventUpdate {
	mreu.mutation.ClearUserID()
	return mreu
}

// SetUserEmailSnapshot sets the "user_email_snapshot" field.
func (mreu *MonitorRequestEventUpdate) SetUserEmailSnapshot(s string) *MonitorRequestEventUpdate {
	mreu.mutation.SetUserEmailSnapshot(s)
	return mreu
}

// SetNillableUserEmailSnapshot sets the "user_email_snapshot" field if the given value is not nil.
func (mreu *MonitorRequestEventUpdate) SetNillableUserEmailSnapshot(s *string) *MonitorRequestEventUpdate {
	if s != nil {
		mreu.SetUserEmailSnapshot(*s)
	}
	return mreu
}

// SetGroupID sets the "group_id" field.
func (mreu *MonitorRequestEventUpdate) SetGroupID(i int) *MonitorRequestEventUpdate {
	mreu.mutation.ResetGroupID()
	mreu.mutation.SetGroupID(i)
	return mreu
}

// SetNillableGroupID sets the "group_id" field if the given value is not nil.
func (mreu *MonitorRequestEventUpdate) SetNillableGroupID(i *int) *MonitorRequestEventUpdate {
	if i != nil {
		mreu.SetGroupID(*i)
	}
	return mreu
}

// AddGroupID adds i to the "group_id" field.
func (mreu *MonitorRequestEventUpdate) AddGroupID(i int) *MonitorRequestEventUpdate {
	mreu.mutation.AddGroupID(i)
	return mreu
}

// ClearGroupID clears the value of the "group_id" field.
func (mreu *MonitorRequestEventUpdate) ClearGroupID() *MonitorRequestEventUpdate {
	mreu.mutation.ClearGroupID()
	return mreu
}

// SetAccountID sets the "account_id" field.
func (mreu *MonitorRequestEventUpdate) SetAccountID(i int) *MonitorRequestEventUpdate {
	mreu.mutation.ResetAccountID()
	mreu.mutation.SetAccountID(i)
	return mreu
}

// SetNillableAccountID sets the "account_id" field if the given value is not nil.
func (mreu *MonitorRequestEventUpdate) SetNillableAccountID(i *int) *MonitorRequestEventUpdate {
	if i != nil {
		mreu.SetAccountID(*i)
	}
	return mreu
}

// AddAccountID adds i to the "account_id" field.
func (mreu *MonitorRequestEventUpdate) AddAccountID(i int) *MonitorRequestEventUpdate {
	mreu.mutation.AddAccountID(i)
	return mreu
}

// ClearAccountID clears the value of the "account_id" field.
func (mreu *MonitorRequestEventUpdate) ClearAccountID() *MonitorRequestEventUpdate {
	mreu.mutation.ClearAccountID()
	return mreu
}

// SetAccountNameSnapshot sets the "account_name_snapshot" field.
func (mreu *MonitorRequestEventUpdate) SetAccountNameSnapshot(s string) *MonitorRequestEventUpdate {
	mreu.mutation.SetAccountNameSnapshot(s)
	return mreu
}

// SetNillableAccountNameSnapshot sets the "account_name_snapshot" field if the given value is not nil.
func (mreu *MonitorRequestEventUpdate) SetNillableAccountNameSnapshot(s *string) *MonitorRequestEventUpdate {
	if s != nil {
		mreu.SetAccountNameSnapshot(*s)
	}
	return mreu
}

// SetPlatform sets the "platform" field.
func (mreu *MonitorRequestEventUpdate) SetPlatform(s string) *MonitorRequestEventUpdate {
	mreu.mutation.SetPlatform(s)
	return mreu
}

// SetNillablePlatform sets the "platform" field if the given value is not nil.
func (mreu *MonitorRequestEventUpdate) SetNillablePlatform(s *string) *MonitorRequestEventUpdate {
	if s != nil {
		mreu.SetPlatform(*s)
	}
	return mreu
}

// SetPluginID sets the "plugin_id" field.
func (mreu *MonitorRequestEventUpdate) SetPluginID(s string) *MonitorRequestEventUpdate {
	mreu.mutation.SetPluginID(s)
	return mreu
}

// SetNillablePluginID sets the "plugin_id" field if the given value is not nil.
func (mreu *MonitorRequestEventUpdate) SetNillablePluginID(s *string) *MonitorRequestEventUpdate {
	if s != nil {
		mreu.SetPluginID(*s)
	}
	return mreu
}

// SetMethod sets the "method" field.
func (mreu *MonitorRequestEventUpdate) SetMethod(s string) *MonitorRequestEventUpdate {
	mreu.mutation.SetMethod(s)
	return mreu
}

// SetNillableMethod sets the "method" field if the given value is not nil.
func (mreu *MonitorRequestEventUpdate) SetNillableMethod(s *string) *MonitorRequestEventUpdate {
	if s != nil {
		mreu.SetMethod(*s)
	}
	return mreu
}

// SetEndpoint sets the "endpoint" field.
func (mreu *MonitorRequestEventUpdate) SetEndpoint(s string) *MonitorRequestEventUpdate {
	mreu.mutation.SetEndpoint(s)
	return mreu
}

// SetNillableEndpoint sets the "endpoint" field if the given value is not nil.
func (mreu *MonitorRequestEventUpdate) SetNillableEndpoint(s *string) *MonitorRequestEventUpdate {
	if s != nil {
		mreu.SetEndpoint(*s)
	}
	return mreu
}

// SetModel sets the "model" field.
func (mreu *MonitorRequestEventUpdate) SetModel(s string) *MonitorRequestEventUpdate {
	mreu.mutation.SetModel(s)
	return mreu
}

// SetNillableModel sets the "model" field if the given value is not nil.
func (mreu *MonitorRequestEventUpdate) SetNillableModel(s *string) *MonitorRequestEventUpdate {
	if s != nil {
		mreu.SetModel(*s)
	}
	return mreu
}

// SetHTTPStatus sets the "http_status" field.
func (mreu *MonitorRequestEventUpdate) SetHTTPStatus(i int) *MonitorRequestEventUpdate {
	mreu.mutation.ResetHTTPStatus()
	mreu.mutation.SetHTTPStatus(i)
	return mreu
}

// SetNillableHTTPStatus sets the "http_status" field if the given value is not nil.
func (mreu *MonitorRequestEventUpdate) SetNillableHTTPStatus(i *int) *MonitorRequestEventUpdate {
	if i != nil {
		mreu.SetHTTPStatus(*i)
	}
	return mreu
}

// AddHTTPStatus adds i to the "http_status" field.
func (mreu *MonitorRequestEventUpdate) AddHTTPStatus(i int) *MonitorRequestEventUpdate {
	mreu.mutation.AddHTTPStatus(i)
	return mreu
}

// ClearHTTPStatus clears the value of the "http_status" field.
func (mreu *MonitorRequestEventUpdate) ClearHTTPStatus() *MonitorRequestEventUpdate {
	mreu.mutation.ClearHTTPStatus()
	return mreu
}

// SetUpstreamStatus sets the "upstream_status" field.
func (mreu *MonitorRequestEventUpdate) SetUpstreamStatus(i int) *MonitorRequestEventUpdate {
	mreu.mutation.ResetUpstreamStatus()
	mreu.mutation.SetUpstreamStatus(i)
	return mreu
}

// SetNillableUpstreamStatus sets the "upstream_status" field if the given value is not nil.
func (mreu *MonitorRequestEventUpdate) SetNillableUpstreamStatus(i *int) *MonitorRequestEventUpdate {
	if i != nil {
		mreu.SetUpstreamStatus(*i)
	}
	return mreu
}

// AddUpstreamStatus adds i to the "upstream_status" field.
func (mreu *MonitorRequestEventUpdate) AddUpstreamStatus(i int) *MonitorRequestEventUpdate {
	mreu.mutation.AddUpstreamStatus(i)
	return mreu
}

// ClearUpstreamStatus clears the value of the "upstream_status" field.
func (mreu *MonitorRequestEventUpdate) ClearUpstreamStatus() *MonitorRequestEventUpdate {
	mreu.mutation.ClearUpstreamStatus()
	return mreu
}

// SetErrorCode sets the "error_code" field.
func (mreu *MonitorRequestEventUpdate) SetErrorCode(s string) *MonitorRequestEventUpdate {
	mreu.mutation.SetErrorCode(s)
	return mreu
}

// SetNillableErrorCode sets the "error_code" field if the given value is not nil.
func (mreu *MonitorRequestEventUpdate) SetNillableErrorCode(s *string) *MonitorRequestEventUpdate {
	if s != nil {
		mreu.SetErrorCode(*s)
	}
	return mreu
}

// SetDurationMs sets the "duration_ms" field.
func (mreu *MonitorRequestEventUpdate) SetDurationMs(i int64) *MonitorRequestEventUpdate {
	mreu.mutation.ResetDurationMs()
	mreu.mutation.SetDurationMs(i)
	return mreu
}

// SetNillableDurationMs sets the "duration_ms" field if the given value is not nil.
func (mreu *MonitorRequestEventUpdate) SetNillableDurationMs(i *int64) *MonitorRequestEventUpdate {
	if i != nil {
		mreu.SetDurationMs(*i)
	}
	return mreu
}

// AddDurationMs adds i to the "duration_ms" field.
func (mreu *MonitorRequestEventUpdate) AddDurationMs(i int64) *MonitorRequestEventUpdate {
	mreu.mutation.AddDurationMs(i)
	return mreu
}

// SetCreatedAt sets the "created_at" field.
func (mreu *MonitorRequestEventUpdate) SetCreatedAt(t time.Time) *MonitorRequestEventUpdate {
	mreu.mutation.SetCreatedAt(t)
	return mreu
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (mreu *MonitorRequestEventUpdate) SetNillableCreatedAt(t *time.Time) *MonitorRequestEventUpdate {
	if t != nil {
		mreu.SetCreatedAt(*t)
	}
	return mreu
}

// SetExpiresAt sets the "expires_at" field.
func (mreu *MonitorRequestEventUpdate) SetExpiresAt(t time.Time) *MonitorRequestEventUpdate {
	mreu.mutation.SetExpiresAt(t)
	return mreu
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (mreu *MonitorRequestEventUpdate) SetNillableExpiresAt(t *time.Time) *MonitorRequestEventUpdate {
	if t != nil {
		mreu.SetExpiresAt(*t)
	}
	return mreu
}

// SetDetail sets the "detail" field.
func (mreu *MonitorRequestEventUpdate) SetDetail(m map[string]interface{}) *MonitorRequestEventUpdate {
	mreu.mutation.SetDetail(m)
	return mreu
}

// ClearDetail clears the value of the "detail" field.
func (mreu *MonitorRequestEventUpdate) ClearDetail() *MonitorRequestEventUpdate {
	mreu.mutation.ClearDetail()
	return mreu
}

// Mutation returns the MonitorRequestEventMutation object of the builder.
func (mreu *MonitorRequestEventUpdate) Mutation() *MonitorRequestEventMutation {
	return mreu.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (mreu *MonitorRequestEventUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, mreu.sqlSave, mreu.mutation, mreu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (mreu *MonitorRequestEventUpdate) SaveX(ctx context.Context) int {
	affected, err := mreu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (mreu *MonitorRequestEventUpdate) Exec(ctx context.Context) error {
	_, err := mreu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (mreu *MonitorRequestEventUpdate) ExecX(ctx context.Context) {
	if err := mreu.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (mreu *MonitorRequestEventUpdate) check() error {
	if v, ok := mreu.mutation.GetType(); ok {
		if err := monitorrequestevent.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "MonitorRequestEvent.type": %w`, err)}
		}
	}
	if v, ok := mreu.mutation.Severity(); ok {
		if err := monitorrequestevent.SeverityValidator(v); err != nil {
			return &ValidationError{Name: "severity", err: fmt.Errorf(`ent: validator failed for field "MonitorRequestEvent.severity": %w`, err)}
		}
	}
	if v, ok := mreu.mutation.Source(); ok {
		if err := monitorrequestevent.SourceValidator(v); err != nil {
			return &ValidationError{Name: "source", err: fmt.Errorf(`ent: validator failed for field "MonitorRequestEvent.source": %w`, err)}
		}
	}
	if v, ok := mreu.mutation.Hash(); ok {
		if err := monitorrequestevent.HashValidator(v); err != nil {
			return &ValidationError{Name: "hash", err: fmt.Errorf(`ent: validator failed for field "MonitorRequestEvent.hash": %w`, err)}
		}
	}
	if v, ok := mreu.mutation.Fingerprint(); ok {
		if err := monitorrequestevent.FingerprintValidator(v); err != nil {
			return &ValidationError{Name: "fingerprint", err: fmt.Errorf(`ent: validator failed for field "MonitorRequestEvent.fingerprint": %w`, err)}
		}
	}
	if v, ok := mreu.mutation.Title(); ok {
		if err := monitorrequestevent.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "MonitorRequestEvent.title": %w`, err)}
		}
	}
	if v, ok := mreu.mutation.Message(); ok {
		if err := monitorrequestevent.MessageValidator(v); err != nil {
			return &ValidationError{Name: "message", err: fmt.Errorf(`ent: validator failed for field "MonitorRequestEvent.message": %w`, err)}
		}
	}
	if v, ok := mreu.mutation.RequestID(); ok {
		if err := monitorrequestevent.RequestIDValidator(v); err != nil {
			return &ValidationError{Name: "request_id", err: fmt.Errorf(`ent: validator failed for field "MonitorRequestEvent.request_id": %w`, err)}
		}
	}
	if v, ok := mreu.mutation.APIKeyNameSnapshot(); ok {
		if err := monitorrequestevent.APIKeyNameSnapshotValidator(v); err != nil {
			return &ValidationError{Name: "api_key_name_snapshot", err: fmt.Errorf(`ent: validator failed for field "MonitorRequestEvent.api_key_name_snapshot": %w`, err)}
		}
	}
	if v, ok := mreu.mutation.UserEmailSnapshot(); ok {
		if err := monitorrequestevent.UserEmailSnapshotValidator(v); err != nil {
			return &ValidationError{Name: "user_email_snapshot", err: fmt.Errorf(`ent: validator failed for field "MonitorRequestEvent.user_email_snapshot": %w`, err)}
		}
	}
	if v, ok := mreu.mutation.AccountNameSnapshot(); ok {
		if err := monitorrequestevent.AccountNameSnapshotValidator(v); err != nil {
			return &ValidationError{Name: "account_name_snapshot", err: fmt.Errorf(`ent: validator failed for field "MonitorRequestEvent.account_name_snapshot": %w`, err)}
		}
	}
	if v, ok := mreu.mutation.Platform(); ok {
		if err := monitorrequestevent.PlatformValidator(v); err != nil {
			return &ValidationError{Name: "platform", err: fmt.Errorf(`ent: validator failed for field "MonitorRequestEvent.platform": %w`, err)}
		}
	}
	if v, ok := mreu.mutation.PluginID(); ok {
		if err := monitorrequestevent.PluginIDValidator(v); err != nil {
			return &ValidationError{Name: "plugin_id", err: fmt.Errorf(`ent: validator failed for field "MonitorRequestEvent.plugin_id": %w`, err)}
		}
	}
	if v, ok := mreu.mutation.Method(); ok {
		if err := monitorrequestevent.MethodValidator(v); err != nil {
			return &ValidationError{Name: "method", err: fmt.Errorf(`ent: validator failed for field "MonitorRequestEvent.method": %w`, err)}
		}
	}
	if v, ok := mreu.mutation.Endpoint(); ok {
		if err := monitorrequestevent.EndpointValidator(v); err != nil {
			return &ValidationError{Name: "endpoint", err: fmt.Errorf(`ent: validator failed for field "MonitorRequestEvent.endpoint": %w`, err)}
		}
	}
	if v, ok := mreu.mutation.Model(); ok {
		if err := monitorrequestevent.ModelValidator(v); err != nil {
			return &ValidationError{Name: "model", err: fmt.Errorf(`ent: validator failed for field "MonitorRequestEvent.model": %w`, err)}
		}
	}
	if v, ok := mreu.mutation.ErrorCode(); ok {
		if err := monitorrequestevent.ErrorCodeValidator(v); err != nil {
			return &ValidationError{Name: "error_code", err: fmt.Errorf(`ent: validator failed for field "MonitorRequestEvent.error_code": %w`, err)}
		}
	}
	return nil
}

func (mreu *MonitorRequestEventUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := mreu.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(monitorrequestevent.Table, monitorrequestevent.Columns, sqlgraph.NewFieldSpec(monitorrequestevent.FieldID, field.TypeInt))
	if ps := mreu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := mreu.mutation.GetType(); ok {
		_spec.SetField(monitorrequestevent.FieldType, field.TypeString, value)
	}
	if value, ok := mreu.mutation.Severity(); ok {
		_spec.SetField(monitorrequestevent.FieldSeverity, field.TypeEnum, value)
	}
	if value, ok := mreu.mutation.Source(); ok {
		_spec.SetField(monitorrequestevent.FieldSource, field.TypeString, value)
	}
	if value, ok := mreu.mutation.Hash(); ok {
		_spec.SetField(monitorrequestevent.FieldHash, field.TypeString, value)
	}
	if value, ok := mreu.mutation.Fingerprint(); ok {
		_spec.SetField(monitorrequestevent.FieldFingerprint, field.TypeString, value)
	}
	if value, ok := mreu.mutation.Title(); ok {
		_spec.SetField(monitorrequestevent.FieldTitle, field.TypeString, value)
	}
	if value, ok := mreu.mutation.Message(); ok {
		_spec.SetField(monitorrequestevent.FieldMessage, field.TypeString, value)
	}
	if value, ok := mreu.mutation.RequestID(); ok {
		_spec.SetField(monitorrequestevent.FieldRequestID, field.TypeString, value)
	}
	if value, ok := mreu.mutation.APIKeyID(); ok {
		_spec.SetField(monitorrequestevent.FieldAPIKeyID, field.TypeInt, value)
	}
	if value, ok := mreu.mutation.AddedAPIKeyID(); ok {
		_spec.AddField(monitorrequestevent.FieldAPIKeyID, field.TypeInt, value)
	}
	if mreu.mutation.APIKeyIDCleared() {
		_spec.ClearField(monitorrequestevent.FieldAPIKeyID, field.TypeInt)
	}
	if value, ok := mreu.mutation.APIKeyNameSnapshot(); ok {
		_spec.SetField(monitorrequestevent.FieldAPIKeyNameSnapshot, field.TypeString, value)
	}
	if value, ok := mreu.mutation.UserID(); ok {
		_spec.SetField(monitorrequestevent.FieldUserID, field.TypeInt, value)
	}
	if value, ok := mreu.mutation.AddedUserID(); ok {
		_spec.AddField(monitorrequestevent.FieldUserID, field.TypeInt, value)
	}
	if mreu.mutation.UserIDCleared() {
		_spec.ClearField(monitorrequestevent.FieldUserID, field.TypeInt)
	}
	if value, ok := mreu.mutation.UserEmailSnapshot(); ok {
		_spec.SetField(monitorrequestevent.FieldUserEmailSnapshot, field.TypeString, value)
	}
	if value, ok := mreu.mutation.GroupID(); ok {
		_spec.SetField(monitorrequestevent.FieldGroupID, field.TypeInt, value)
	}
	if value, ok := mreu.mutation.AddedGroupID(); ok {
		_spec.AddField(monitorrequestevent.FieldGroupID, field.TypeInt, value)
	}
	if mreu.mutation.GroupIDCleared() {
		_spec.ClearField(monitorrequestevent.FieldGroupID, field.TypeInt)
	}
	if value, ok := mreu.mutation.AccountID(); ok {
		_spec.SetField(monitorrequestevent.FieldAccountID, field.TypeInt, value)
	}
	if value, ok := mreu.mutation.AddedAccountID(); ok {
		_spec.AddField(monitorrequestevent.FieldAccountID, field.TypeInt, value)
	}
	if mreu.mutation.AccountIDCleared() {
		_spec.ClearField(monitorrequestevent.FieldAccountID, field.TypeInt)
	}
	if value, ok := mreu.mutation.AccountNameSnapshot(); ok {
		_spec.SetField(monitorrequestevent.FieldAccountNameSnapshot, field.TypeString, value)
	}
	if value, ok := mreu.mutation.Platform(); ok {
		_spec.SetField(monitorrequestevent.FieldPlatform, field.TypeString, value)
	}
	if value, ok := mreu.mutation.PluginID(); ok {
		_spec.SetField(monitorrequestevent.FieldPluginID, field.TypeString, value)
	}
	if value, ok := mreu.mutation.Method(); ok {
		_spec.SetField(monitorrequestevent.FieldMethod, field.TypeString, value)
	}
	if value, ok := mreu.mutation.Endpoint(); ok {
		_spec.SetField(monitorrequestevent.FieldEndpoint, field.TypeString, value)
	}
	if value, ok := mreu.mutation.Model(); ok {
		_spec.SetField(monitorrequestevent.FieldModel, field.TypeString, value)
	}
	if value, ok := mreu.mutation.HTTPStatus(); ok {
		_spec.SetField(monitorrequestevent.FieldHTTPStatus, field.TypeInt, value)
	}
	if value, ok := mreu.mutation.AddedHTTPStatus(); ok {
		_spec.AddField(monitorrequestevent.FieldHTTPStatus, field.TypeInt, value)
	}
	if mreu.mutation.HTTPStatusCleared() {
		_spec.ClearField(monitorrequestevent.FieldHTTPStatus, field.TypeInt)
	}
	if value, ok := mreu.mutation.UpstreamStatus(); ok {
		_spec.SetField(monitorrequestevent.FieldUpstreamStatus, field.TypeInt, value)
	}
	if value, ok := mreu.mutation.AddedUpstreamStatus(); ok {
		_spec.AddField(monitorrequestevent.FieldUpstreamStatus, field.TypeInt, value)
	}
	if mreu.mutation.UpstreamStatusCleared() {
		_spec.ClearField(monitorrequestevent.FieldUpstreamStatus, field.TypeInt)
	}
	if value, ok := mreu.mutation.ErrorCode(); ok {
		_spec.SetField(monitorrequestevent.FieldErrorCode, field.TypeString, value)
	}
	if value, ok := mreu.mutation.DurationMs(); ok {
		_spec.SetField(monitorrequestevent.FieldDurationMs, field.TypeInt64, value)
	}
	if value, ok := mreu.mutation.AddedDurationMs(); ok {
		_spec.AddField(monitorrequestevent.FieldDurationMs, field.TypeInt64, value)
	}
	if value, ok := mreu.mutation.CreatedAt(); ok {
		_spec.SetField(monitorrequestevent.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := mreu.mutation.ExpiresAt(); ok {
		_spec.SetField(monitorrequestevent.FieldExpiresAt, field.TypeTime, value)
	}
	if value, ok := mreu.mutation.Detail(); ok {
		_spec.SetField(monitorrequestevent.FieldDetail, field.TypeJSON, value)
	}
	if mreu.mutation.DetailCleared() {
		_spec.ClearField(monitorrequestevent.FieldDetail, field.TypeJSON)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, mreu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{monitorrequestevent.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	mreu.mutation.done = true
	return n, nil
}

// MonitorRequestEventUpdateOne is the builder for updating a single MonitorRequestEvent entity.
type MonitorRequestEventUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *MonitorRequestEventMutation
}

// SetType sets the "type" field.
func (mreuo *MonitorRequestEventUpdateOne) SetType(s string) *MonitorRequestEventUpdateOne {
	mreuo.mutation.SetType(s)
	return mreuo
}

// SetNillableType sets the "type" field if the given value is not nil.
func (mreuo *MonitorRequestEventUpdateOne) SetNillableType(s *string) *MonitorRequestEventUpdateOne {
	if s != nil {
		mreuo.SetType(*s)
	}
	return mreuo
}

// SetSeverity sets the "severity" field.
func (mreuo *MonitorRequestEventUpdateOne) SetSeverity(m monitorrequestevent.Severity) *MonitorRequestEventUpdateOne {
	mreuo.mutation.SetSeverity(m)
	return mreuo
}

// SetNillableSeverity sets the "severity" field if the given value is not nil.
func (mreuo *MonitorRequestEventUpdateOne) SetNillableSeverity(m *monitorrequestevent.Severity) *MonitorRequestEventUpdateOne {
	if m != nil {
		mreuo.SetSeverity(*m)
	}
	return mreuo
}

// SetSource sets the "source" field.
func (mreuo *MonitorRequestEventUpdateOne) SetSource(s string) *MonitorRequestEventUpdateOne {
	mreuo.mutation.SetSource(s)
	return mreuo
}

// SetNillableSource sets the "source" field if the given value is not nil.
func (mreuo *MonitorRequestEventUpdateOne) SetNillableSource(s *string) *MonitorRequestEventUpdateOne {
	if s != nil {
		mreuo.SetSource(*s)
	}
	return mreuo
}

// SetHash sets the "hash" field.
func (mreuo *MonitorRequestEventUpdateOne) SetHash(s string) *MonitorRequestEventUpdateOne {
	mreuo.mutation.SetHash(s)
	return mreuo
}

// SetNillableHash sets the "hash" field if the given value is not nil.
func (mreuo *MonitorRequestEventUpdateOne) SetNillableHash(s *string) *MonitorRequestEventUpdateOne {
	if s != nil {
		mreuo.SetHash(*s)
	}
	return mreuo
}

// SetFingerprint sets the "fingerprint" field.
func (mreuo *MonitorRequestEventUpdateOne) SetFingerprint(s string) *MonitorRequestEventUpdateOne {
	mreuo.mutation.SetFingerprint(s)
	return mreuo
}

// SetNillableFingerprint sets the "fingerprint" field if the given value is not nil.
func (mreuo *MonitorRequestEventUpdateOne) SetNillableFingerprint(s *string) *MonitorRequestEventUpdateOne {
	if s != nil {
		mreuo.SetFingerprint(*s)
	}
	return mreuo
}

// SetTitle sets the "title" field.
func (mreuo *MonitorRequestEventUpdateOne) SetTitle(s string) *MonitorRequestEventUpdateOne {
	mreuo.mutation.SetTitle(s)
	return mreuo
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (mreuo *MonitorRequestEventUpdateOne) SetNillableTitle(s *string) *MonitorRequestEventUpdateOne {
	if s != nil {
		mreuo.SetTitle(*s)
	}
	return mreuo
}

// SetMessage sets the "message" field.
func (mreuo *MonitorRequestEventUpdateOne) SetMessage(s string) *MonitorRequestEventUpdateOne {
	mreuo.mutation.SetMessage(s)
	return mreuo
}

// SetNillableMessage sets the "message" field if the given value is not nil.
func (mreuo *MonitorRequestEventUpdateOne) SetNillableMessage(s *string) *MonitorRequestEventUpdateOne {
	if s != nil {
		mreuo.SetMessage(*s)
	}
	return mreuo
}

// SetRequestID sets the "request_id" field.
func (mreuo *MonitorRequestEventUpdateOne) SetRequestID(s string) *MonitorRequestEventUpdateOne {
	mreuo.mutation.SetRequestID(s)
	return mreuo
}

// SetNillableRequestID sets the "request_id" field if the given value is not nil.
func (mreuo *MonitorRequestEventUpdateOne) SetNillableRequestID(s *string) *MonitorRequestEventUpdateOne {
	if s != nil {
		mreuo.SetRequestID(*s)
	}
	return mreuo
}

// SetAPIKeyID sets the "api_key_id" field.
func (mreuo *MonitorRequestEventUpdateOne) SetAPIKeyID(i int) *MonitorRequestEventUpdateOne {
	mreuo.mutation.ResetAPIKeyID()
	mreuo.mutation.SetAPIKeyID(i)
	return mreuo
}

// SetNillableAPIKeyID sets the "api_key_id" field if the given value is not nil.
func (mreuo *MonitorRequestEventUpdateOne) SetNillableAPIKeyID(i *int) *MonitorRequestEventUpdateOne {
	if i != nil {
		mreuo.SetAPIKeyID(*i)
	}
	return mreuo
}

// AddAPIKeyID adds i to the "api_key_id" field.
func (mreuo *MonitorRequestEventUpdateOne) AddAPIKeyID(i int) *MonitorRequestEventUpdateOne {
	mreuo.mutation.AddAPIKeyID(i)
	return mreuo
}

// ClearAPIKeyID clears the value of the "api_key_id" field.
func (mreuo *MonitorRequestEventUpdateOne) ClearAPIKeyID() *MonitorRequestEventUpdateOne {
	mreuo.mutation.ClearAPIKeyID()
	return mreuo
}

// SetAPIKeyNameSnapshot sets the "api_key_name_snapshot" field.
func (mreuo *MonitorRequestEventUpdateOne) SetAPIKeyNameSnapshot(s string) *MonitorRequestEventUpdateOne {
	mreuo.mutation.SetAPIKeyNameSnapshot(s)
	return mreuo
}

// SetNillableAPIKeyNameSnapshot sets the "api_key_name_snapshot" field if the given value is not nil.
func (mreuo *MonitorRequestEventUpdateOne) SetNillableAPIKeyNameSnapshot(s *string) *MonitorRequestEventUpdateOne {
	if s != nil {
		mreuo.SetAPIKeyNameSnapshot(*s)
	}
	return mreuo
}

// SetUserID sets the "user_id" field.
func (mreuo *MonitorRequestEventUpdateOne) SetUserID(i int) *MonitorRequestEventUpdateOne {
	mreuo.mutation.ResetUserID()
	mreuo.mutation.SetUserID(i)
	return mreuo
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (mreuo *MonitorRequestEventUpdateOne) SetNillableUserID(i *int) *MonitorRequestEventUpdateOne {
	if i != nil {
		mreuo.SetUserID(*i)
	}
	return mreuo
}

// AddUserID adds i to the "user_id" field.
func (mreuo *MonitorRequestEventUpdateOne) AddUserID(i int) *MonitorRequestEventUpdateOne {
	mreuo.mutation.AddUserID(i)
	return mreuo
}

// ClearUserID clears the value of the "user_id" field.
func (mreuo *MonitorRequestEventUpdateOne) ClearUserID() *MonitorRequestEventUpdateOne {
	mreuo.mutation.ClearUserID()
	return mreuo
}

// SetUserEmailSnapshot sets the "user_email_snapshot" field.
func (mreuo *MonitorRequestEventUpdateOne) SetUserEmailSnapshot(s string) *MonitorRequestEventUpdateOne {
	mreuo.mutation.SetUserEmailSnapshot(s)
	return mreuo
}

// SetNillableUserEmailSnapshot sets the "user_email_snapshot" field if the given value is not nil.
func (mreuo *MonitorRequestEventUpdateOne) SetNillableUserEmailSnapshot(s *string) *MonitorRequestEventUpdateOne {
	if s != nil {
		mreuo.SetUserEmailSnapshot(*s)
	}
	return mreuo
}

// SetGroupID sets the "group_id" field.
func (mreuo *MonitorRequestEventUpdateOne) SetGroupID(i int) *MonitorRequestEventUpdateOne {
	mreuo.mutation.ResetGroupID()
	mreuo.mutation.SetGroupID(i)
	return mreuo
}

// SetNillableGroupID sets the "group_id" field if the given value is not nil.
func (mreuo *MonitorRequestEventUpdateOne) SetNillableGroupID(i *int) *MonitorRequestEventUpdateOne {
	if i != nil {
		mreuo.SetGroupID(*i)
	}
	return mreuo
}

// AddGroupID adds i to the "group_id" field.
func (mreuo *MonitorRequestEventUpdateOne) AddGroupID(i int) *MonitorRequestEventUpdateOne {
	mreuo.mutation.AddGroupID(i)
	return mreuo
}

// ClearGroupID clears the value of the "group_id" field.
func (mreuo *MonitorRequestEventUpdateOne) ClearGroupID() *MonitorRequestEventUpdateOne {
	mreuo.mutation.ClearGroupID()
	return mreuo
}

// SetAccountID sets the "account_id" field.
func (mreuo *MonitorRequestEventUpdateOne) SetAccountID(i int) *MonitorRequestEventUpdateOne {
	mreuo.mutation.ResetAccountID()
	mreuo.mutation.SetAccountID(i)
	return mreuo
}

// SetNillableAccountID sets the "account_id" field if the given value is not nil.
func (mreuo *MonitorRequestEventUpdateOne) SetNillableAccountID(i *int) *MonitorRequestEventUpdateOne {
	if i != nil {
		mreuo.SetAccountID(*i)
	}
	return mreuo
}

// AddAccountID adds i to the "account_id" field.
func (mreuo *MonitorRequestEventUpdateOne) AddAccountID(i int) *MonitorRequestEventUpdateOne {
	mreuo.mutation.AddAccountID(i)
	return mreuo
}

// ClearAccountID clears the value of the "account_id" field.
func (mreuo *MonitorRequestEventUpdateOne) ClearAccountID() *MonitorRequestEventUpdateOne {
	mreuo.mutation.ClearAccountID()
	return mreuo
}

// SetAccountNameSnapshot sets the "account_name_snapshot" field.
func (mreuo *MonitorRequestEventUpdateOne) SetAccountNameSnapshot(s string) *MonitorRequestEventUpdateOne {
	mreuo.mutation.SetAccountNameSnapshot(s)
	return mreuo
}

// SetNillableAccountNameSnapshot sets the "account_name_snapshot" field if the given value is not nil.
func (mreuo *MonitorRequestEventUpdateOne) SetNillableAccountNameSnapshot(s *string) *MonitorRequestEventUpdateOne {
	if s != nil {
		mreuo.SetAccountNameSnapshot(*s)
	}
	return mreuo
}

// SetPlatform sets the "platform" field.
func (mreuo *MonitorRequestEventUpdateOne) SetPlatform(s string) *MonitorRequestEventUpdateOne {
	mreuo.mutation.SetPlatform(s)
	return mreuo
}

// SetNillablePlatform sets the "platform" field if the given value is not nil.
func (mreuo *MonitorRequestEventUpdateOne) SetNillablePlatform(s *string) *MonitorRequestEventUpdateOne {
	if s != nil {
		mreuo.SetPlatform(*s)
	}
	return mreuo
}

// SetPluginID sets the "plugin_id" field.
func (mreuo *MonitorRequestEventUpdateOne) SetPluginID(s string) *MonitorRequestEventUpdateOne {
	mreuo.mutation.SetPluginID(s)
	return mreuo
}

// SetNillablePluginID sets the "plugin_id" field if the given value is not nil.
func (mreuo *MonitorRequestEventUpdateOne) SetNillablePluginID(s *string) *MonitorRequestEventUpdateOne {
	if s != nil {
		mreuo.SetPluginID(*s)
	}
	return mreuo
}

// SetMethod sets the "method" field.
func (mreuo *MonitorRequestEventUpdateOne) SetMethod(s string) *MonitorRequestEventUpdateOne {
	mreuo.mutation.SetMethod(s)
	return mreuo
}

// SetNillableMethod sets the "method" field if the given value is not nil.
func (mreuo *MonitorRequestEventUpdateOne) SetNillableMethod(s *string) *MonitorRequestEventUpdateOne {
	if s != nil {
		mreuo.SetMethod(*s)
	}
	return mreuo
}

// SetEndpoint sets the "endpoint" field.
func (mreuo *MonitorRequestEventUpdateOne) SetEndpoint(s string) *MonitorRequestEventUpdateOne {
	mreuo.mutation.SetEndpoint(s)
	return mreuo
}

// SetNillableEndpoint sets the "endpoint" field if the given value is not nil.
func (mreuo *MonitorRequestEventUpdateOne) SetNillableEndpoint(s *string) *MonitorRequestEventUpdateOne {
	if s != nil {
		mreuo.SetEndpoint(*s)
	}
	return mreuo
}

// SetModel sets the "model" field.
func (mreuo *MonitorRequestEventUpdateOne) SetModel(s string) *MonitorRequestEventUpdateOne {
	mreuo.mutation.SetModel(s)
	return mreuo
}

// SetNillableModel sets the "model" field if the given value is not nil.
func (mreuo *MonitorRequestEventUpdateOne) SetNillableModel(s *string) *MonitorRequestEventUpdateOne {
	if s != nil {
		mreuo.SetModel(*s)
	}
	return mreuo
}

// SetHTTPStatus sets the "http_status" field.
func (mreuo *MonitorRequestEventUpdateOne) SetHTTPStatus(i int) *MonitorRequestEventUpdateOne {
	mreuo.mutation.ResetHTTPStatus()
	mreuo.mutation.SetHTTPStatus(i)
	return mreuo
}

// SetNillableHTTPStatus sets the "http_status" field if the given value is not nil.
func (mreuo *MonitorRequestEventUpdateOne) SetNillableHTTPStatus(i *int) *MonitorRequestEventUpdateOne {
	if i != nil {
		mreuo.SetHTTPStatus(*i)
	}
	return mreuo
}

// AddHTTPStatus adds i to the "http_status" field.
func (mreuo *MonitorRequestEventUpdateOne) AddHTTPStatus(i int) *MonitorRequestEventUpdateOne {
	mreuo.mutation.AddHTTPStatus(i)
	return mreuo
}

// ClearHTTPStatus clears the value of the "http_status" field.
func (mreuo *MonitorRequestEventUpdateOne) ClearHTTPStatus() *MonitorRequestEventUpdateOne {
	mreuo.mutation.ClearHTTPStatus()
	return mreuo
}

// SetUpstreamStatus sets the "upstream_status" field.
func (mreuo *MonitorRequestEventUpdateOne) SetUpstreamStatus(i int) *MonitorRequestEventUpdateOne {
	mreuo.mutation.ResetUpstreamStatus()
	mreuo.mutation.SetUpstreamStatus(i)
	return mreuo
}

// SetNillableUpstreamStatus sets the "upstream_status" field if the given value is not nil.
func (mreuo *MonitorRequestEventUpdateOne) SetNillableUpstreamStatus(i *int) *MonitorRequestEventUpdateOne {
	if i != nil {
		mreuo.SetUpstreamStatus(*i)
	}
	return mreuo
}

// AddUpstreamStatus adds i to the "upstream_status" field.
func (mreuo *MonitorRequestEventUpdateOne) AddUpstreamStatus(i int) *MonitorRequestEventUpdateOne {
	mreuo.mutation.AddUpstreamStatus(i)
	return mreuo
}

// ClearUpstreamStatus clears the value of the "upstream_status" field.
func (mreuo *MonitorRequestEventUpdateOne) ClearUpstreamStatus() *MonitorRequestEventUpdateOne {
	mreuo.mutation.ClearUpstreamStatus()
	return mreuo
}

// SetErrorCode sets the "error_code" field.
func (mreuo *MonitorRequestEventUpdateOne) SetErrorCode(s string) *MonitorRequestEventUpdateOne {
	mreuo.mutation.SetErrorCode(s)
	return mreuo
}

// SetNillableErrorCode sets the "error_code" field if the given value is not nil.
func (mreuo *MonitorRequestEventUpdateOne) SetNillableErrorCode(s *string) *MonitorRequestEventUpdateOne {
	if s != nil {
		mreuo.SetErrorCode(*s)
	}
	return mreuo
}

// SetDurationMs sets the "duration_ms" field.
func (mreuo *MonitorRequestEventUpdateOne) SetDurationMs(i int64) *MonitorRequestEventUpdateOne {
	mreuo.mutation.ResetDurationMs()
	mreuo.mutation.SetDurationMs(i)
	return mreuo
}

// SetNillableDurationMs sets the "duration_ms" field if the given value is not nil.
func (mreuo *MonitorRequestEventUpdateOne) SetNillableDurationMs(i *int64) *MonitorRequestEventUpdateOne {
	if i != nil {
		mreuo.SetDurationMs(*i)
	}
	return mreuo
}

// AddDurationMs adds i to the "duration_ms" field.
func (mreuo *MonitorRequestEventUpdateOne) AddDurationMs(i int64) *MonitorRequestEventUpdateOne {
	mreuo.mutation.AddDurationMs(i)
	return mreuo
}

// SetCreatedAt sets the "created_at" field.
func (mreuo *MonitorRequestEventUpdateOne) SetCreatedAt(t time.Time) *MonitorRequestEventUpdateOne {
	mreuo.mutation.SetCreatedAt(t)
	return mreuo
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (mreuo *MonitorRequestEventUpdateOne) SetNillableCreatedAt(t *time.Time) *MonitorRequestEventUpdateOne {
	if t != nil {
		mreuo.SetCreatedAt(*t)
	}
	return mreuo
}

// SetExpiresAt sets the "expires_at" field.
func (mreuo *MonitorRequestEventUpdateOne) SetExpiresAt(t time.Time) *MonitorRequestEventUpdateOne {
	mreuo.mutation.SetExpiresAt(t)
	return mreuo
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (mreuo *MonitorRequestEventUpdateOne) SetNillableExpiresAt(t *time.Time) *MonitorRequestEventUpdateOne {
	if t != nil {
		mreuo.SetExpiresAt(*t)
	}
	return mreuo
}

// SetDetail sets the "detail" field.
func (mreuo *MonitorRequestEventUpdateOne) SetDetail(m map[string]interface{}) *MonitorRequestEventUpdateOne {
	mreuo.mutation.SetDetail(m)
	return mreuo
}

// ClearDetail clears the value of the "detail" field.
func (mreuo *MonitorRequestEventUpdateOne) ClearDetail() *MonitorRequestEventUpdateOne {
	mreuo.mutation.ClearDetail()
	return mreuo
}

// Mutation returns the MonitorRequestEventMutation object of the builder.
func (mreuo *MonitorRequestEventUpdateOne) Mutation() *MonitorRequestEventMutation {
	return mreuo.mutation
}

// Where appends a list predicates to the MonitorRequestEventUpdate builder.
func (mreuo *MonitorRequestEventUpdateOne) Where(ps ...predicate.MonitorRequestEvent) *MonitorRequestEventUpdateOne {
	mreuo.mutation.Where(ps...)
	return mreuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (mreuo *MonitorRequestEventUpdateOne) Select(field string, fields ...string) *MonitorRequestEventUpdateOne {
	mreuo.fields = append([]string{field}, fields...)
	return mreuo
}

// Save executes the query and returns the updated MonitorRequestEvent entity.
func (mreuo *MonitorRequestEventUpdateOne) Save(ctx context.Context) (*MonitorRequestEvent, error) {
	return withHooks(ctx, mreuo.sqlSave, mreuo.mutation, mreuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (mreuo *MonitorRequestEventUpdateOne) SaveX(ctx context.Context) *MonitorRequestEvent {
	node, err := mreuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (mreuo *MonitorRequestEventUpdateOne) Exec(ctx context.Context) error {
	_, err := mreuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (mreuo *MonitorRequestEventUpdateOne) ExecX(ctx context.Context) {
	if err := mreuo.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (mreuo *MonitorRequestEventUpdateOne) check() error {
	if v, ok := mreuo.mutation.GetType(); ok {
		if err := monitorrequestevent.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "MonitorRequestEvent.type": %w`, err)}
		}
	}
	if v, ok := mreuo.mutation.Severity(); ok {
		if err := monitorrequestevent.SeverityValidator(v); err != nil {
			return &ValidationError{Name: "severity", err: fmt.Errorf(`ent: validator failed for field "MonitorRequestEvent.severity": %w`, err)}
		}
	}
	if v, ok := mreuo.mutation.Source(); ok {
		if err := monitorrequestevent.SourceValidator(v); err != nil {
			return &ValidationError{Name: "source", err: fmt.Errorf(`ent: validator failed for field "MonitorRequestEvent.source": %w`, err)}
		}
	}
	if v, ok := mreuo.mutation.Hash(); ok {
		if err := monitorrequestevent.HashValidator(v); err != nil {
			return &ValidationError{Name: "hash", err: fmt.Errorf(`ent: validator failed for field "MonitorRequestEvent.hash": %w`, err)}
		}
	}
	if v, ok := mreuo.mutation.Fingerprint(); ok {
		if err := monitorrequestevent.FingerprintValidator(v); err != nil {
			return &ValidationError{Name: "fingerprint", err: fmt.Errorf(`ent: validator failed for field "MonitorRequestEvent.fingerprint": %w`, err)}
		}
	}
	if v, ok := mreuo.mutation.Title(); ok {
		if err := monitorrequestevent.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "MonitorRequestEvent.title": %w`, err)}
		}
	}
	if v, ok := mreuo.mutation.Message(); ok {
		if err := monitorrequestevent.MessageValidator(v); err != nil {
			return &ValidationError{Name: "message", err: fmt.Errorf(`ent: validator failed for field "MonitorRequestEvent.message": %w`, err)}
		}
	}
	if v, ok := mreuo.mutation.RequestID(); ok {
		if err := monitorrequestevent.RequestIDValidator(v); err != nil {
			return &ValidationError{Name: "request_id", err: fmt.Errorf(`ent: validator failed for field "MonitorRequestEvent.request_id": %w`, err)}
		}
	}
	if v, ok := mreuo.mutation.APIKeyNameSnapshot(); ok {
		if err := monitorrequestevent.APIKeyNameSnapshotValidator(v); err != nil {
			return &ValidationError{Name: "api_key_name_snapshot", err: fmt.Errorf(`ent: validator failed for field "MonitorRequestEvent.api_key_name_snapshot": %w`, err)}
		}
	}
	if v, ok := mreuo.mutation.UserEmailSnapshot(); ok {
		if err := monitorrequestevent.UserEmailSnapshotValidator(v); err != nil {
			return &ValidationError{Name: "user_email_snapshot", err: fmt.Errorf(`ent: validator failed for field "MonitorRequestEvent.user_email_snapshot": %w`, err)}
		}
	}
	if v, ok := mreuo.mutation.AccountNameSnapshot(); ok {
		if err := monitorrequestevent.AccountNameSnapshotValidator(v); err != nil {
			return &ValidationError{Name: "account_name_snapshot", err: fmt.Errorf(`ent: validator failed for field "MonitorRequestEvent.account_name_snapshot": %w`, err)}
		}
	}
	if v, ok := mreuo.mutation.Platform(); ok {
		if err := monitorrequestevent.PlatformValidator(v); err != nil {
			return &ValidationError{Name: "platform", err: fmt.Errorf(`ent: validator failed for field "MonitorRequestEvent.platform": %w`, err)}
		}
	}
	if v, ok := mreuo.mutation.PluginID(); ok {
		if err := monitorrequestevent.PluginIDValidator(v); err != nil {
			return &ValidationError{Name: "plugin_id", err: fmt.Errorf(`ent: validator failed for field "MonitorRequestEvent.plugin_id": %w`, err)}
		}
	}
	if v, ok := mreuo.mutation.Method(); ok {
		if err := monitorrequestevent.MethodValidator(v); err != nil {
			return &ValidationError{Name: "method", err: fmt.Errorf(`ent: validator failed for field "MonitorRequestEvent.method": %w`, err)}
		}
	}
	if v, ok := mreuo.mutation.Endpoint(); ok {
		if err := monitorrequestevent.EndpointValidator(v); err != nil {
			return &ValidationError{Name: "endpoint", err: fmt.Errorf(`ent: validator failed for field "MonitorRequestEvent.endpoint": %w`, err)}
		}
	}
	if v, ok := mreuo.mutation.Model(); ok {
		if err := monitorrequestevent.ModelValidator(v); err != nil {
			return &ValidationError{Name: "model", err: fmt.Errorf(`ent: validator failed for field "MonitorRequestEvent.model": %w`, err)}
		}
	}
	if v, ok := mreuo.mutation.ErrorCode(); ok {
		if err := monitorrequestevent.ErrorCodeValidator(v); err != nil {
			return &ValidationError{Name: "error_code", err: fmt.Errorf(`ent: validator failed for field "MonitorRequestEvent.error_code": %w`, err)}
		}
	}
	return nil
}

func (mreuo *MonitorRequestEventUpdateOne) sqlSave(ctx context.Context) (_node *MonitorRequestEvent, err error) {
	if err := mreuo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(monitorrequestevent.Table, monitorrequestevent.Columns, sqlgraph.NewFieldSpec(monitorrequestevent.FieldID, field.TypeInt))
	id, ok := mreuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "MonitorRequestEvent.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := mreuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, monitorrequestevent.FieldID)
		for _, f := range fields {
			if !monitorrequestevent.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != monitorrequestevent.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := mreuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := mreuo.mutation.GetType(); ok {
		_spec.SetField(monitorrequestevent.FieldType, field.TypeString, value)
	}
	if value, ok := mreuo.mutation.Severity(); ok {
		_spec.SetField(monitorrequestevent.FieldSeverity, field.TypeEnum, value)
	}
	if value, ok := mreuo.mutation.Source(); ok {
		_spec.SetField(monitorrequestevent.FieldSource, field.TypeString, value)
	}
	if value, ok := mreuo.mutation.Hash(); ok {
		_spec.SetField(monitorrequestevent.FieldHash, field.TypeString, value)
	}
	if value, ok := mreuo.mutation.Fingerprint(); ok {
		_spec.SetField(monitorrequestevent.FieldFingerprint, field.TypeString, value)
	}
	if value, ok := mreuo.mutation.Title(); ok {
		_spec.SetField(monitorrequestevent.FieldTitle, field.TypeString, value)
	}
	if value, ok := mreuo.mutation.Message(); ok {
		_spec.SetField(monitorrequestevent.FieldMessage, field.TypeString, value)
	}
	if value, ok := mreuo.mutation.RequestID(); ok {
		_spec.SetField(monitorrequestevent.FieldRequestID, field.TypeString, value)
	}
	if value, ok := mreuo.mutation.APIKeyID(); ok {
		_spec.SetField(monitorrequestevent.FieldAPIKeyID, field.TypeInt, value)
	}
	if value, ok := mreuo.mutation.AddedAPIKeyID(); ok {
		_spec.AddField(monitorrequestevent.FieldAPIKeyID, field.TypeInt, value)
	}
	if mreuo.mutation.APIKeyIDCleared() {
		_spec.ClearField(monitorrequestevent.FieldAPIKeyID, field.TypeInt)
	}
	if value, ok := mreuo.mutation.APIKeyNameSnapshot(); ok {
		_spec.SetField(monitorrequestevent.FieldAPIKeyNameSnapshot, field.TypeString, value)
	}
	if value, ok := mreuo.mutation.UserID(); ok {
		_spec.SetField(monitorrequestevent.FieldUserID, field.TypeInt, value)
	}
	if value, ok := mreuo.mutation.AddedUserID(); ok {
		_spec.AddField(monitorrequestevent.FieldUserID, field.TypeInt, value)
	}
	if mreuo.mutation.UserIDCleared() {
		_spec.ClearField(monitorrequestevent.FieldUserID, field.TypeInt)
	}
	if value, ok := mreuo.mutation.UserEmailSnapshot(); ok {
		_spec.SetField(monitorrequestevent.FieldUserEmailSnapshot, field.TypeString, value)
	}
	if value, ok := mreuo.mutation.GroupID(); ok {
		_spec.SetField(monitorrequestevent.FieldGroupID, field.TypeInt, value)
	}
	if value, ok := mreuo.mutation.AddedGroupID(); ok {
		_spec.AddField(monitorrequestevent.FieldGroupID, field.TypeInt, value)
	}
	if mreuo.mutation.GroupIDCleared() {
		_spec.ClearField(monitorrequestevent.FieldGroupID, field.TypeInt)
	}
	if value, ok := mreuo.mutation.AccountID(); ok {
		_spec.SetField(monitorrequestevent.FieldAccountID, field.TypeInt, value)
	}
	if value, ok := mreuo.mutation.AddedAccountID(); ok {
		_spec.AddField(monitorrequestevent.FieldAccountID, field.TypeInt, value)
	}
	if mreuo.mutation.AccountIDCleared() {
		_spec.ClearField(monitorrequestevent.FieldAccountID, field.TypeInt)
	}
	if value, ok := mreuo.mutation.AccountNameSnapshot(); ok {
		_spec.SetField(monitorrequestevent.FieldAccountNameSnapshot, field.TypeString, value)
	}
	if value, ok := mreuo.mutation.Platform(); ok {
		_spec.SetField(monitorrequestevent.FieldPlatform, field.TypeString, value)
	}
	if value, ok := mreuo.mutation.PluginID(); ok {
		_spec.SetField(monitorrequestevent.FieldPluginID, field.TypeString, value)
	}
	if value, ok := mreuo.mutation.Method(); ok {
		_spec.SetField(monitorrequestevent.FieldMethod, field.TypeString, value)
	}
	if value, ok := mreuo.mutation.Endpoint(); ok {
		_spec.SetField(monitorrequestevent.FieldEndpoint, field.TypeString, value)
	}
	if value, ok := mreuo.mutation.Model(); ok {
		_spec.SetField(monitorrequestevent.FieldModel, field.TypeString, value)
	}
	if value, ok := mreuo.mutation.HTTPStatus(); ok {
		_spec.SetField(monitorrequestevent.FieldHTTPStatus, field.TypeInt, value)
	}
	if value, ok := mreuo.mutation.AddedHTTPStatus(); ok {
		_spec.AddField(monitorrequestevent.FieldHTTPStatus, field.TypeInt, value)
	}
	if mreuo.mutation.HTTPStatusCleared() {
		_spec.ClearField(monitorrequestevent.FieldHTTPStatus, field.TypeInt)
	}
	if value, ok := mreuo.mutation.UpstreamStatus(); ok {
		_spec.SetField(monitorrequestevent.FieldUpstreamStatus, field.TypeInt, value)
	}
	if value, ok := mreuo.mutation.AddedUpstreamStatus(); ok {
		_spec.AddField(monitorrequestevent.FieldUpstreamStatus, field.TypeInt, value)
	}
	if mreuo.mutation.UpstreamStatusCleared() {
		_spec.ClearField(monitorrequestevent.FieldUpstreamStatus, field.TypeInt)
	}
	if value, ok := mreuo.mutation.ErrorCode(); ok {
		_spec.SetField(monitorrequestevent.FieldErrorCode, field.TypeString, value)
	}
	if value, ok := mreuo.mutation.DurationMs(); ok {
		_spec.SetField(monitorrequestevent.FieldDurationMs, field.TypeInt64, value)
	}
	if value, ok := mreuo.mutation.AddedDurationMs(); ok {
		_spec.AddField(monitorrequestevent.FieldDurationMs, field.TypeInt64, value)
	}
	if value, ok := mreuo.mutation.CreatedAt(); ok {
		_spec.SetField(monitorrequestevent.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := mreuo.mutation.ExpiresAt(); ok {
		_spec.SetField(monitorrequestevent.FieldExpiresAt, field.TypeTime, value)
	}
	if value, ok := mreuo.mutation.Detail(); ok {
		_spec.SetField(monitorrequestevent.FieldDetail, field.TypeJSON, value)
	}
	if mreuo.mutation.DetailCleared() {
		_spec.ClearField(monitorrequestevent.FieldDetail, field.TypeJSON)
	}
	_node = &MonitorRequestEvent{config: mreuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, mreuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{monitorrequestevent.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	mreuo.mutation.done = true
	return _node, nil
}
