// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/DevilGenius/airgate-core/ent/monitorrequesttrace"
)

// MonitorRequestTrace is the model entity for the MonitorRequestTrace schema.
type MonitorRequestTrace struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Hash holds the value of the "hash" field.
	Hash string `json:"hash,omitempty"`
	// SchemaVersion holds the value of the "schema_version" field.
	SchemaVersion int `json:"schema_version,omitempty"`
	// Encoding holds the value of the "encoding" field.
	Encoding string `json:"encoding,omitempty"`
	// Payload holds the value of the "payload" field.
	Payload []byte `json:"payload,omitempty"`
	// RawSize holds the value of the "raw_size" field.
	RawSize int64 `json:"raw_size,omitempty"`
	// CompressedSize holds the value of the "compressed_size" field.
	CompressedSize int64 `json:"compressed_size,omitempty"`
	// SeenCount holds the value of the "seen_count" field.
	SeenCount int64 `json:"seen_count,omitempty"`
	// FirstSeenAt holds the value of the "first_seen_at" field.
	FirstSeenAt time.Time `json:"first_seen_at,omitempty"`
	// LastSeenAt holds the value of the "last_seen_at" field.
	LastSeenAt time.Time `json:"last_seen_at,omitempty"`
	// ExpiresAt holds the value of the "expires_at" field.
	ExpiresAt    time.Time `json:"expires_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*MonitorRequestTrace) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case monitorrequesttrace.FieldPayload:
			values[i] = new([]byte)
		case monitorrequesttrace.FieldID, monitorrequesttrace.FieldSchemaVersion, monitorrequesttrace.FieldRawSize, monitorrequesttrace.FieldCompressedSize, monitorrequesttrace.FieldSeenCount:
			values[i] = new(sql.NullInt64)
		case monitorrequesttrace.FieldHash, monitorrequesttrace.FieldEncoding:
			values[i] = new(sql.NullString)
		case monitorrequesttrace.FieldFirstSeenAt, monitorrequesttrace.FieldLastSeenAt, monitorrequesttrace.FieldExpiresAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the MonitorRequestTrace fields.
func (mrt *MonitorRequestTrace) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case monitorrequesttrace.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			mrt.ID = int(value.Int64)
		case monitorrequesttrace.FieldHash:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field hash", values[i])
			} else if value.Valid {
				mrt.Hash = value.String
			}
		case monitorrequesttrace.FieldSchemaVersion:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field schema_version", values[i])
			} else if value.Valid {
				mrt.SchemaVersion = int(value.Int64)
			}
		case monitorrequesttrace.FieldEncoding:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field encoding", values[i])
			} else if value.Valid {
				mrt.Encoding = value.String
			}
		case monitorrequesttrace.FieldPayload:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field payload", values[i])
			} else if value != nil {
				mrt.Payload = *value
			}
		case monitorrequesttrace.FieldRawSize:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field raw_size", values[i])
			} else if value.Valid {
				mrt.RawSize = value.Int64
			}
		case monitorrequesttrace.FieldCompressedSize:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field compressed_size", values[i])
			} else if value.Valid {
				mrt.CompressedSize = value.Int64
			}
		case monitorrequesttrace.FieldSeenCount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field seen_count", values[i])
			} else if value.Valid {
				mrt.SeenCount = value.Int64
			}
		case monitorrequesttrace.FieldFirstSeenAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field first_seen_at", values[i])
			} else if value.Valid {
				mrt.FirstSeenAt = value.Time
			}
		case monitorrequesttrace.FieldLastSeenAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field last_seen_at", values[i])
			} else if value.Valid {
				mrt.LastSeenAt = value.Time
			}
		case monitorrequesttrace.FieldExpiresAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field expires_at", values[i])
			} else if value.Valid {
				mrt.ExpiresAt = value.Time
			}
		default:
			mrt.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the MonitorRequestTrace.
// This includes values selected through modifiers, order, etc.
func (mrt *MonitorRequestTrace) Value(name string) (ent.Value, error) {
	return mrt.selectValues.Get(name)
}

// Update returns a builder for updating this MonitorRequestTrace.
// Note that you need to call MonitorRequestTrace.Unwrap() before calling this method if this MonitorRequestTrace
// was returned from a transaction, and the transaction was committed or rolled back.
func (mrt *MonitorRequestTrace) Update() *MonitorRequestTraceUpdateOne {
	return NewMonitorRequestTraceClient(mrt.config).UpdateOne(mrt)
}

// Unwrap unwraps the MonitorRequestTrace entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (mrt *MonitorRequestTrace) Unwrap() *MonitorRequestTrace {
	_tx, ok := mrt.config.driver.(*txDriver)
	if !ok {
		panic("ent: MonitorRequestTrace is not a transactional entity")
	}
	mrt.config.driver = _tx.drv
	return mrt
}

// String implements the fmt.Stringer.
func (mrt *MonitorRequestTrace) String() string {
	var builder strings.Builder
	builder.WriteString("MonitorRequestTrace(")
	builder.WriteString(fmt.Sprintf("id=%v, ", mrt.ID))
	builder.WriteString("hash=")
	builder.WriteString(mrt.Hash)
	builder.WriteString(", ")
	builder.WriteString("schema_version=")
	builder.WriteString(fmt.Sprintf("%v", mrt.SchemaVersion))
	builder.WriteString(", ")
	builder.WriteString("encoding=")
	builder.WriteString(mrt.Encoding)
	builder.WriteString(", ")
	builder.WriteString("payload=")
	builder.WriteString(fmt.Sprintf("%v", mrt.Payload))
	builder.WriteString(", ")
	builder.WriteString("raw_size=")
	builder.WriteString(fmt.Sprintf("%v", mrt.RawSize))
	builder.WriteString(", ")
	builder.WriteString("compressed_size=")
	builder.WriteString(fmt.Sprintf("%v", mrt.CompressedSize))
	builder.WriteString(", ")
	builder.WriteString("seen_count=")
	builder.WriteString(fmt.Sprintf("%v", mrt.SeenCount))
	builder.WriteString(", ")
	builder.WriteString("first_seen_at=")
	builder.WriteString(mrt.FirstSeenAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("last_seen_at=")
	builder.WriteString(mrt.LastSeenAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("expires_at=")
	builder.WriteString(mrt.ExpiresAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// MonitorRequestTraces is a parsable slice of MonitorRequestTrace.
type MonitorRequestTraces []*MonitorRequestTrace
