// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/DevilGenius/airgate-core/ent/monitorrequestevent"
	"github.com/DevilGenius/airgate-core/ent/predicate"
)

// MonitorRequestEventQuery is the builder for querying MonitorRequestEvent entities.
type MonitorRequestEventQuery struct {
	config
	ctx        *QueryContext
	order      []monitorrequestevent.OrderOption
	inters     []Interceptor
	predicates []predicate.MonitorRequestEvent
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the MonitorRequestEventQuery builder.
func (mreq *MonitorRequestEventQuery) Where(ps ...predicate.MonitorRequestEvent) *MonitorRequestEventQuery {
	mreq.predicates = append(mreq.predicates, ps...)
	return mreq
}

// Limit the number of records to be returned by this query.
func (mreq *MonitorRequestEventQuery) Limit(limit int) *MonitorRequestEventQuery {
	mreq.ctx.Limit = &limit
	return mreq
}

// Offset to start from.
func (mreq *MonitorRequestEventQuery) Offset(offset int) *MonitorRequestEventQuery {
	mreq.ctx.Offset = &offset
	return mreq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (mreq *MonitorRequestEventQuery) Unique(unique bool) *MonitorRequestEventQuery {
	mreq.ctx.Unique = &unique
	return mreq
}

// Order specifies how the records should be ordered.
func (mreq *MonitorRequestEventQuery) Order(o ...monitorrequestevent.OrderOption) *MonitorRequestEventQuery {
	mreq.order = append(mreq.order, o...)
	return mreq
}

// First returns the first MonitorRequestEvent entity from the query.
// Returns a *NotFoundError when no MonitorRequestEvent was found.
func (mreq *MonitorRequestEventQuery) First(ctx context.Context) (*MonitorRequestEvent, error) {
	nodes, err := mreq.Limit(1).All(setContextOp(ctx, mreq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{monitorrequestevent.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (mreq *MonitorRequestEventQuery) FirstX(ctx context.Context) *MonitorRequestEvent {
	node, err := mreq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first MonitorRequestEvent ID from the query.
// Returns a *NotFoundError when no MonitorRequestEvent ID was found.
func (mreq *MonitorRequestEventQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = mreq.Limit(1).IDs(setContextOp(ctx, mreq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{monitorrequestevent.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (mreq *MonitorRequestEventQuery) FirstIDX(ctx context.Context) int {
	id, err := mreq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single MonitorRequestEvent entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one MonitorRequestEvent entity is found.
// Returns a *NotFoundError when no MonitorRequestEvent entities are found.
func (mreq *MonitorRequestEventQuery) Only(ctx context.Context) (*MonitorRequestEvent, error) {
	nodes, err := mreq.Limit(2).All(setContextOp(ctx, mreq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{monitorrequestevent.Label}
	default:
		return nil, &NotSingularError{monitorrequestevent.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (mreq *MonitorRequestEventQuery) OnlyX(ctx context.Context) *MonitorRequestEvent {
	node, err := mreq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only MonitorRequestEvent ID in the query.
// Returns a *NotSingularError when more than one MonitorRequestEvent ID is found.
// Returns a *NotFoundError when no entities are found.
func (mreq *MonitorRequestEventQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = mreq.Limit(2).IDs(setContextOp(ctx, mreq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{monitorrequestevent.Label}
	default:
		err = &NotSingularError{monitorrequestevent.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (mreq *MonitorRequestEventQuery) OnlyIDX(ctx context.Context) int {
	id, err := mreq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of MonitorRequestEvents.
func (mreq *MonitorRequestEventQuery) All(ctx context.Context) ([]*MonitorRequestEvent, error) {
	ctx = setContextOp(ctx, mreq.ctx, "All")
	if err := mreq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*MonitorRequestEvent, *MonitorRequestEventQuery]()
	return withInterceptors[[]*MonitorRequestEvent](ctx, mreq, qr, mreq.inters)
}

// AllX is like All, but panics if an error occurs.
func (mreq *MonitorRequestEventQuery) AllX(ctx context.Context) []*MonitorRequestEvent {
	nodes, err := mreq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of MonitorRequestEvent IDs.
func (mreq *MonitorRequestEventQuery) IDs(ctx context.Context) (ids []int, err error) {
	if mreq.ctx.Unique == nil && mreq.path != nil {
		mreq.Unique(true)
	}
	ctx = setContextOp(ctx, mreq.ctx, "IDs")
	if err = mreq.Select(monitorrequestevent.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (mreq *MonitorRequestEventQuery) IDsX(ctx context.Context) []int {
	ids, err := mreq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (mreq *MonitorRequestEventQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, mreq.ctx, "Count")
	if err := mreq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, mreq, querierCount[*MonitorRequestEventQuery](), mreq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (mreq *MonitorRequestEventQuery) CountX(ctx context.Context) int {
	count, err := mreq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (mreq *MonitorRequestEventQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, mreq.ctx, "Exist")
	switch _, err := mreq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (mreq *MonitorRequestEventQuery) ExistX(ctx context.Context) bool {
	exist, err := mreq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the MonitorRequestEventQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (mreq *MonitorRequestEventQuery) Clone() *MonitorRequestEventQuery {
	if mreq == nil {
		return nil
	}
	return &MonitorRequestEventQuery{
		config:     mreq.config,
		ctx:        mreq.ctx.Clone(),
		order:      append([]monitorrequestevent.OrderOption{}, mreq.order...),
		inters:     append([]Interceptor{}, mreq.inters...),
		predicates: append([]predicate.MonitorRequestEvent{}, mreq.predicates...),
		// clone intermediate query.
		sql:  mreq.sql.Clone(),
		path: mreq.path,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Type string `json:"type,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.MonitorRequestEvent.Query().
//		GroupBy(monitorrequestevent.FieldType).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (mreq *MonitorRequestEventQuery) GroupBy(field string, fields ...string) *MonitorRequestEventGroupBy {
	mreq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &MonitorRequestEventGroupBy{build: mreq}
	grbuild.flds = &mreq.ctx.Fields
	grbuild.label = monitorrequestevent.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Type string `json:"type,omitempty"`
//	}
//
//	client.MonitorRequestEvent.Query().
//		Select(monitorrequestevent.FieldType).
//		Scan(ctx, &v)
func (mreq *MonitorRequestEventQuery) Select(fields ...string) *MonitorRequestEventSelect {
	mreq.ctx.Fields = append(mreq.ctx.Fields, fields...)
	sbuild := &MonitorRequestEventSelect{MonitorRequestEventQuery: mreq}
	sbuild.label = monitorrequestevent.Label
	sbuild.flds, sbuild.scan = &mreq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a MonitorRequestEventSelect configured with the given aggregations.
func (mreq *MonitorRequestEventQuery) Aggregate(fns ...AggregateFunc) *MonitorRequestEventSelect {
	return mreq.Select().Aggregate(fns...)
}

func (mreq *MonitorRequestEventQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range mreq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, mreq); err != nil {
				return err
			}
		}
	}
	for _, f := range mreq.ctx.Fields {
		if !monitorrequestevent.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if mreq.path != nil {
		prev, err := mreq.path(ctx)
		if err != nil {
			return err
		}
		mreq.sql = prev
	}
	return nil
}

func (mreq *MonitorRequestEventQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*MonitorRequestEvent, error) {
	var (
		nodes = []*MonitorRequestEvent{}
		_spec = mreq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*MonitorRequestEvent).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &MonitorRequestEvent{config: mreq.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, mreq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (mreq *MonitorRequestEventQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := mreq.querySpec()
	_spec.Node.Columns = mreq.ctx.Fields
	if len(mreq.ctx.Fields) > 0 {
		_spec.Unique = mreq.ctx.Unique != nil && *mreq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, mreq.driver, _spec)
}

func (mreq *MonitorRequestEventQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(monitorrequestevent.Table, monitorrequestevent.Columns, sqlgraph.NewFieldSpec(monitorrequestevent.FieldID, field.TypeInt))
	_spec.From = mreq.sql
	if unique := mreq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if mreq.path != nil {
		_spec.Unique = true
	}
	if fields := mreq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, monitorrequestevent.FieldID)
		for i := range fields {
			if fields[i] != monitorrequestevent.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := mreq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := mreq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := mreq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := mreq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (mreq *MonitorRequestEventQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(mreq.driver.Dialect())
	t1 := builder.Table(monitorrequestevent.Table)
	columns := mreq.ctx.Fields
	if len(columns) == 0 {
		columns = monitorrequestevent.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if mreq.sql != nil {
		selector = mreq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if mreq.ctx.Unique != nil && *mreq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range mreq.predicates {
		p(selector)
	}
	for _, p := range mreq.order {
		p(selector)
	}
	if offset := mreq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := mreq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// MonitorRequestEventGroupBy is the group-by builder for MonitorRequestEvent entities.
type MonitorRequestEventGroupBy struct {
	selector
	build *MonitorRequestEventQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (mregb *MonitorRequestEventGroupBy) Aggregate(fns ...AggregateFunc) *MonitorRequestEventGroupBy {
	mregb.fns = append(mregb.fns, fns...)
	return mregb
}

// Scan applies the selector query and scans the result into the given value.
func (mregb *MonitorRequestEventGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, mregb.build.ctx, "GroupBy")
	if err := mregb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*MonitorRequestEventQuery, *MonitorRequestEventGroupBy](ctx, mregb.build, mregb, mregb.build.inters, v)
}

func (mregb *MonitorRequestEventGroupBy) sqlScan(ctx context.Context, root *MonitorRequestEventQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(mregb.fns))
	for _, fn := range mregb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*mregb.flds)+len(mregb.fns))
		for _, f := range *mregb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*mregb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := mregb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// MonitorRequestEventSelect is the builder for selecting fields of MonitorRequestEvent entities.
type MonitorRequestEventSelect struct {
	*MonitorRequestEventQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (mres *MonitorRequestEventSelect) Aggregate(fns ...AggregateFunc) *MonitorRequestEventSelect {
	mres.fns = append(mres.fns, fns...)
	return mres
}

// Scan applies the selector query and scans the result into the given value.
func (mres *MonitorRequestEventSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, mres.ctx, "Select")
	if err := mres.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*MonitorRequestEventQuery, *MonitorRequestEventSelect](ctx, mres.MonitorRequestEventQuery, mres, mres.inters, v)
}

func (mres *MonitorRequestEventSelect) sqlScan(ctx context.Context, root *MonitorRequestEventQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(mres.fns))
	for _, fn := range mres.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*mres.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := mres.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
