// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/DevilGenius/airgate-core/ent/monitorevent"
)

// MonitorEventCreate is the builder for creating a MonitorEvent entity.
type MonitorEventCreate struct {
	config
	mutation *MonitorEventMutation
	hooks    []Hook
}

// SetKind sets the "kind" field.
func (mec *MonitorEventCreate) SetKind(m monitorevent.Kind) *MonitorEventCreate {
	mec.mutation.SetKind(m)
	return mec
}

// SetSeverity sets the "severity" field.
func (mec *MonitorEventCreate) SetSeverity(m monitorevent.Severity) *MonitorEventCreate {
	mec.mutation.SetSeverity(m)
	return mec
}

// SetNillableSeverity sets the "severity" field if the given value is not nil.
func (mec *MonitorEventCreate) SetNillableSeverity(m *monitorevent.Severity) *MonitorEventCreate {
	if m != nil {
		mec.SetSeverity(*m)
	}
	return mec
}

// SetStatus sets the "status" field.
func (mec *MonitorEventCreate) SetStatus(m monitorevent.Status) *MonitorEventCreate {
	mec.mutation.SetStatus(m)
	return mec
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (mec *MonitorEventCreate) SetNillableStatus(m *monitorevent.Status) *MonitorEventCreate {
	if m != nil {
		mec.SetStatus(*m)
	}
	return mec
}

// SetSource sets the "source" field.
func (mec *MonitorEventCreate) SetSource(s string) *MonitorEventCreate {
	mec.mutation.SetSource(s)
	return mec
}

// SetNillableSource sets the "source" field if the given value is not nil.
func (mec *MonitorEventCreate) SetNillableSource(s *string) *MonitorEventCreate {
	if s != nil {
		mec.SetSource(*s)
	}
	return mec
}

// SetSubjectType sets the "subject_type" field.
func (mec *MonitorEventCreate) SetSubjectType(s string) *MonitorEventCreate {
	mec.mutation.SetSubjectType(s)
	return mec
}

// SetNillableSubjectType sets the "subject_type" field if the given value is not nil.
func (mec *MonitorEventCreate) SetNillableSubjectType(s *string) *MonitorEventCreate {
	if s != nil {
		mec.SetSubjectType(*s)
	}
	return mec
}

// SetSubjectID sets the "subject_id" field.
func (mec *MonitorEventCreate) SetSubjectID(s string) *MonitorEventCreate {
	mec.mutation.SetSubjectID(s)
	return mec
}

// SetNillableSubjectID sets the "subject_id" field if the given value is not nil.
func (mec *MonitorEventCreate) SetNillableSubjectID(s *string) *MonitorEventCreate {
	if s != nil {
		mec.SetSubjectID(*s)
	}
	return mec
}

// SetFingerprint sets the "fingerprint" field.
func (mec *MonitorEventCreate) SetFingerprint(s string) *MonitorEventCreate {
	mec.mutation.SetFingerprint(s)
	return mec
}

// SetTitle sets the "title" field.
func (mec *MonitorEventCreate) SetTitle(s string) *MonitorEventCreate {
	mec.mutation.SetTitle(s)
	return mec
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (mec *MonitorEventCreate) SetNillableTitle(s *string) *MonitorEventCreate {
	if s != nil {
		mec.SetTitle(*s)
	}
	return mec
}

// SetMessage sets the "message" field.
func (mec *MonitorEventCreate) SetMessage(s string) *MonitorEventCreate {
	mec.mutation.SetMessage(s)
	return mec
}

// SetNillableMessage sets the "message" field if the given value is not nil.
func (mec *MonitorEventCreate) SetNillableMessage(s *string) *MonitorEventCreate {
	if s != nil {
		mec.SetMessage(*s)
	}
	return mec
}

// SetAPIKeyID sets the "api_key_id" field.
func (mec *MonitorEventCreate) SetAPIKeyID(i int) *MonitorEventCreate {
	mec.mutation.SetAPIKeyID(i)
	return mec
}

// SetNillableAPIKeyID sets the "api_key_id" field if the given value is not nil.
func (mec *MonitorEventCreate) SetNillableAPIKeyID(i *int) *MonitorEventCreate {
	if i != nil {
		mec.SetAPIKeyID(*i)
	}
	return mec
}

// SetAPIKeyNameSnapshot sets the "api_key_name_snapshot" field.
func (mec *MonitorEventCreate) SetAPIKeyNameSnapshot(s string) *MonitorEventCreate {
	mec.mutation.SetAPIKeyNameSnapshot(s)
	return mec
}

// SetNillableAPIKeyNameSnapshot sets the "api_key_name_snapshot" field if the given value is not nil.
func (mec *MonitorEventCreate) SetNillableAPIKeyNameSnapshot(s *string) *MonitorEventCreate {
	if s != nil {
		mec.SetAPIKeyNameSnapshot(*s)
	}
	return mec
}

// SetAPIKeyPrefix sets the "api_key_prefix" field.
func (mec *MonitorEventCreate) SetAPIKeyPrefix(s string) *MonitorEventCreate {
	mec.mutation.SetAPIKeyPrefix(s)
	return mec
}

// SetNillableAPIKeyPrefix sets the "api_key_prefix" field if the given value is not nil.
func (mec *MonitorEventCreate) SetNillableAPIKeyPrefix(s *string) *MonitorEventCreate {
	if s != nil {
		mec.SetAPIKeyPrefix(*s)
	}
	return mec
}

// SetUserID sets the "user_id" field.
func (mec *MonitorEventCreate) SetUserID(i int) *MonitorEventCreate {
	mec.mutation.SetUserID(i)
	return mec
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (mec *MonitorEventCreate) SetNillableUserID(i *int) *MonitorEventCreate {
	if i != nil {
		mec.SetUserID(*i)
	}
	return mec
}

// SetUserEmailSnapshot sets the "user_email_snapshot" field.
func (mec *MonitorEventCreate) SetUserEmailSnapshot(s string) *MonitorEventCreate {
	mec.mutation.SetUserEmailSnapshot(s)
	return mec
}

// SetNillableUserEmailSnapshot sets the "user_email_snapshot" field if the given value is not nil.
func (mec *MonitorEventCreate) SetNillableUserEmailSnapshot(s *string) *MonitorEventCreate {
	if s != nil {
		mec.SetUserEmailSnapshot(*s)
	}
	return mec
}

// SetGroupID sets the "group_id" field.
func (mec *MonitorEventCreate) SetGroupID(i int) *MonitorEventCreate {
	mec.mutation.SetGroupID(i)
	return mec
}

// SetNillableGroupID sets the "group_id" field if the given value is not nil.
func (mec *MonitorEventCreate) SetNillableGroupID(i *int) *MonitorEventCreate {
	if i != nil {
		mec.SetGroupID(*i)
	}
	return mec
}

// SetAccountID sets the "account_id" field.
func (mec *MonitorEventCreate) SetAccountID(i int) *MonitorEventCreate {
	mec.mutation.SetAccountID(i)
	return mec
}

// SetNillableAccountID sets the "account_id" field if the given value is not nil.
func (mec *MonitorEventCreate) SetNillableAccountID(i *int) *MonitorEventCreate {
	if i != nil {
		mec.SetAccountID(*i)
	}
	return mec
}

// SetAccountNameSnapshot sets the "account_name_snapshot" field.
func (mec *MonitorEventCreate) SetAccountNameSnapshot(s string) *MonitorEventCreate {
	mec.mutation.SetAccountNameSnapshot(s)
	return mec
}

// SetNillableAccountNameSnapshot sets the "account_name_snapshot" field if the given value is not nil.
func (mec *MonitorEventCreate) SetNillableAccountNameSnapshot(s *string) *MonitorEventCreate {
	if s != nil {
		mec.SetAccountNameSnapshot(*s)
	}
	return mec
}

// SetPlatform sets the "platform" field.
func (mec *MonitorEventCreate) SetPlatform(s string) *MonitorEventCreate {
	mec.mutation.SetPlatform(s)
	return mec
}

// SetNillablePlatform sets the "platform" field if the given value is not nil.
func (mec *MonitorEventCreate) SetNillablePlatform(s *string) *MonitorEventCreate {
	if s != nil {
		mec.SetPlatform(*s)
	}
	return mec
}

// SetPluginID sets the "plugin_id" field.
func (mec *MonitorEventCreate) SetPluginID(s string) *MonitorEventCreate {
	mec.mutation.SetPluginID(s)
	return mec
}

// SetNillablePluginID sets the "plugin_id" field if the given value is not nil.
func (mec *MonitorEventCreate) SetNillablePluginID(s *string) *MonitorEventCreate {
	if s != nil {
		mec.SetPluginID(*s)
	}
	return mec
}

// SetTaskType sets the "task_type" field.
func (mec *MonitorEventCreate) SetTaskType(s string) *MonitorEventCreate {
	mec.mutation.SetTaskType(s)
	return mec
}

// SetNillableTaskType sets the "task_type" field if the given value is not nil.
func (mec *MonitorEventCreate) SetNillableTaskType(s *string) *MonitorEventCreate {
	if s != nil {
		mec.SetTaskType(*s)
	}
	return mec
}

// SetMethod sets the "method" field.
func (mec *MonitorEventCreate) SetMethod(s string) *MonitorEventCreate {
	mec.mutation.SetMethod(s)
	return mec
}

// SetNillableMethod sets the "method" field if the given value is not nil.
func (mec *MonitorEventCreate) SetNillableMethod(s *string) *MonitorEventCreate {
	if s != nil {
		mec.SetMethod(*s)
	}
	return mec
}

// SetEndpoint sets the "endpoint" field.
func (mec *MonitorEventCreate) SetEndpoint(s string) *MonitorEventCreate {
	mec.mutation.SetEndpoint(s)
	return mec
}

// SetNillableEndpoint sets the "endpoint" field if the given value is not nil.
func (mec *MonitorEventCreate) SetNillableEndpoint(s *string) *MonitorEventCreate {
	if s != nil {
		mec.SetEndpoint(*s)
	}
	return mec
}

// SetRequestPath sets the "request_path" field.
func (mec *MonitorEventCreate) SetRequestPath(s string) *MonitorEventCreate {
	mec.mutation.SetRequestPath(s)
	return mec
}

// SetNillableRequestPath sets the "request_path" field if the given value is not nil.
func (mec *MonitorEventCreate) SetNillableRequestPath(s *string) *MonitorEventCreate {
	if s != nil {
		mec.SetRequestPath(*s)
	}
	return mec
}

// SetModel sets the "model" field.
func (mec *MonitorEventCreate) SetModel(s string) *MonitorEventCreate {
	mec.mutation.SetModel(s)
	return mec
}

// SetNillableModel sets the "model" field if the given value is not nil.
func (mec *MonitorEventCreate) SetNillableModel(s *string) *MonitorEventCreate {
	if s != nil {
		mec.SetModel(*s)
	}
	return mec
}

// SetHTTPStatus sets the "http_status" field.
func (mec *MonitorEventCreate) SetHTTPStatus(i int) *MonitorEventCreate {
	mec.mutation.SetHTTPStatus(i)
	return mec
}

// SetNillableHTTPStatus sets the "http_status" field if the given value is not nil.
func (mec *MonitorEventCreate) SetNillableHTTPStatus(i *int) *MonitorEventCreate {
	if i != nil {
		mec.SetHTTPStatus(*i)
	}
	return mec
}

// SetUpstreamStatus sets the "upstream_status" field.
func (mec *MonitorEventCreate) SetUpstreamStatus(i int) *MonitorEventCreate {
	mec.mutation.SetUpstreamStatus(i)
	return mec
}

// SetNillableUpstreamStatus sets the "upstream_status" field if the given value is not nil.
func (mec *MonitorEventCreate) SetNillableUpstreamStatus(i *int) *MonitorEventCreate {
	if i != nil {
		mec.SetUpstreamStatus(*i)
	}
	return mec
}

// SetErrorCode sets the "error_code" field.
func (mec *MonitorEventCreate) SetErrorCode(s string) *MonitorEventCreate {
	mec.mutation.SetErrorCode(s)
	return mec
}

// SetNillableErrorCode sets the "error_code" field if the given value is not nil.
func (mec *MonitorEventCreate) SetNillableErrorCode(s *string) *MonitorEventCreate {
	if s != nil {
		mec.SetErrorCode(*s)
	}
	return mec
}

// SetErrorType sets the "error_type" field.
func (mec *MonitorEventCreate) SetErrorType(s string) *MonitorEventCreate {
	mec.mutation.SetErrorType(s)
	return mec
}

// SetNillableErrorType sets the "error_type" field if the given value is not nil.
func (mec *MonitorEventCreate) SetNillableErrorType(s *string) *MonitorEventCreate {
	if s != nil {
		mec.SetErrorType(*s)
	}
	return mec
}

// SetCount sets the "count" field.
func (mec *MonitorEventCreate) SetCount(i int64) *MonitorEventCreate {
	mec.mutation.SetCount(i)
	return mec
}

// SetNillableCount sets the "count" field if the given value is not nil.
func (mec *MonitorEventCreate) SetNillableCount(i *int64) *MonitorEventCreate {
	if i != nil {
		mec.SetCount(*i)
	}
	return mec
}

// SetCreatedAt sets the "created_at" field.
func (mec *MonitorEventCreate) SetCreatedAt(t time.Time) *MonitorEventCreate {
	mec.mutation.SetCreatedAt(t)
	return mec
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (mec *MonitorEventCreate) SetNillableCreatedAt(t *time.Time) *MonitorEventCreate {
	if t != nil {
		mec.SetCreatedAt(*t)
	}
	return mec
}

// SetUpdatedAt sets the "updated_at" field.
func (mec *MonitorEventCreate) SetUpdatedAt(t time.Time) *MonitorEventCreate {
	mec.mutation.SetUpdatedAt(t)
	return mec
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (mec *MonitorEventCreate) SetNillableUpdatedAt(t *time.Time) *MonitorEventCreate {
	if t != nil {
		mec.SetUpdatedAt(*t)
	}
	return mec
}

// SetResolvedAt sets the "resolved_at" field.
func (mec *MonitorEventCreate) SetResolvedAt(t time.Time) *MonitorEventCreate {
	mec.mutation.SetResolvedAt(t)
	return mec
}

// SetNillableResolvedAt sets the "resolved_at" field if the given value is not nil.
func (mec *MonitorEventCreate) SetNillableResolvedAt(t *time.Time) *MonitorEventCreate {
	if t != nil {
		mec.SetResolvedAt(*t)
	}
	return mec
}

// SetIgnoredAt sets the "ignored_at" field.
func (mec *MonitorEventCreate) SetIgnoredAt(t time.Time) *MonitorEventCreate {
	mec.mutation.SetIgnoredAt(t)
	return mec
}

// SetNillableIgnoredAt sets the "ignored_at" field if the given value is not nil.
func (mec *MonitorEventCreate) SetNillableIgnoredAt(t *time.Time) *MonitorEventCreate {
	if t != nil {
		mec.SetIgnoredAt(*t)
	}
	return mec
}

// SetAutoResolveAt sets the "auto_resolve_at" field.
func (mec *MonitorEventCreate) SetAutoResolveAt(t time.Time) *MonitorEventCreate {
	mec.mutation.SetAutoResolveAt(t)
	return mec
}

// SetNillableAutoResolveAt sets the "auto_resolve_at" field if the given value is not nil.
func (mec *MonitorEventCreate) SetNillableAutoResolveAt(t *time.Time) *MonitorEventCreate {
	if t != nil {
		mec.SetAutoResolveAt(*t)
	}
	return mec
}

// SetExpiresAt sets the "expires_at" field.
func (mec *MonitorEventCreate) SetExpiresAt(t time.Time) *MonitorEventCreate {
	mec.mutation.SetExpiresAt(t)
	return mec
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (mec *MonitorEventCreate) SetNillableExpiresAt(t *time.Time) *MonitorEventCreate {
	if t != nil {
		mec.SetExpiresAt(*t)
	}
	return mec
}

// SetLastNotifiedAt sets the "last_notified_at" field.
func (mec *MonitorEventCreate) SetLastNotifiedAt(t time.Time) *MonitorEventCreate {
	mec.mutation.SetLastNotifiedAt(t)
	return mec
}

// SetNillableLastNotifiedAt sets the "last_notified_at" field if the given value is not nil.
func (mec *MonitorEventCreate) SetNillableLastNotifiedAt(t *time.Time) *MonitorEventCreate {
	if t != nil {
		mec.SetLastNotifiedAt(*t)
	}
	return mec
}

// SetNextNotifyAt sets the "next_notify_at" field.
func (mec *MonitorEventCreate) SetNextNotifyAt(t time.Time) *MonitorEventCreate {
	mec.mutation.SetNextNotifyAt(t)
	return mec
}

// SetNillableNextNotifyAt sets the "next_notify_at" field if the given value is not nil.
func (mec *MonitorEventCreate) SetNillableNextNotifyAt(t *time.Time) *MonitorEventCreate {
	if t != nil {
		mec.SetNextNotifyAt(*t)
	}
	return mec
}

// SetNotifyError sets the "notify_error" field.
func (mec *MonitorEventCreate) SetNotifyError(s string) *MonitorEventCreate {
	mec.mutation.SetNotifyError(s)
	return mec
}

// SetNillableNotifyError sets the "notify_error" field if the given value is not nil.
func (mec *MonitorEventCreate) SetNillableNotifyError(s *string) *MonitorEventCreate {
	if s != nil {
		mec.SetNotifyError(*s)
	}
	return mec
}

// SetDetail sets the "detail" field.
func (mec *MonitorEventCreate) SetDetail(m map[string]interface{}) *MonitorEventCreate {
	mec.mutation.SetDetail(m)
	return mec
}

// Mutation returns the MonitorEventMutation object of the builder.
func (mec *MonitorEventCreate) Mutation() *MonitorEventMutation {
	return mec.mutation
}

// Save creates the MonitorEvent in the database.
func (mec *MonitorEventCreate) Save(ctx context.Context) (*MonitorEvent, error) {
	mec.defaults()
	return withHooks(ctx, mec.sqlSave, mec.mutation, mec.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (mec *MonitorEventCreate) SaveX(ctx context.Context) *MonitorEvent {
	v, err := mec.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (mec *MonitorEventCreate) Exec(ctx context.Context) error {
	_, err := mec.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (mec *MonitorEventCreate) ExecX(ctx context.Context) {
	if err := mec.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (mec *MonitorEventCreate) defaults() {
	if _, ok := mec.mutation.Severity(); !ok {
		v := monitorevent.DefaultSeverity
		mec.mutation.SetSeverity(v)
	}
	if _, ok := mec.mutation.Status(); !ok {
		v := monitorevent.DefaultStatus
		mec.mutation.SetStatus(v)
	}
	if _, ok := mec.mutation.Source(); !ok {
		v := monitorevent.DefaultSource
		mec.mutation.SetSource(v)
	}
	if _, ok := mec.mutation.SubjectType(); !ok {
		v := monitorevent.DefaultSubjectType
		mec.mutation.SetSubjectType(v)
	}
	if _, ok := mec.mutation.SubjectID(); !ok {
		v := monitorevent.DefaultSubjectID
		mec.mutation.SetSubjectID(v)
	}
	if _, ok := mec.mutation.Title(); !ok {
		v := monitorevent.DefaultTitle
		mec.mutation.SetTitle(v)
	}
	if _, ok := mec.mutation.Message(); !ok {
		v := monitorevent.DefaultMessage
		mec.mutation.SetMessage(v)
	}
	if _, ok := mec.mutation.APIKeyNameSnapshot(); !ok {
		v := monitorevent.DefaultAPIKeyNameSnapshot
		mec.mutation.SetAPIKeyNameSnapshot(v)
	}
	if _, ok := mec.mutation.APIKeyPrefix(); !ok {
		v := monitorevent.DefaultAPIKeyPrefix
		mec.mutation.SetAPIKeyPrefix(v)
	}
	if _, ok := mec.mutation.UserEmailSnapshot(); !ok {
		v := monitorevent.DefaultUserEmailSnapshot
		mec.mutation.SetUserEmailSnapshot(v)
	}
	if _, ok := mec.mutation.AccountNameSnapshot(); !ok {
		v := monitorevent.DefaultAccountNameSnapshot
		mec.mutation.SetAccountNameSnapshot(v)
	}
	if _, ok := mec.mutation.Platform(); !ok {
		v := monitorevent.DefaultPlatform
		mec.mutation.SetPlatform(v)
	}
	if _, ok := mec.mutation.PluginID(); !ok {
		v := monitorevent.DefaultPluginID
		mec.mutation.SetPluginID(v)
	}
	if _, ok := mec.mutation.TaskType(); !ok {
		v := monitorevent.DefaultTaskType
		mec.mutation.SetTaskType(v)
	}
	if _, ok := mec.mutation.Method(); !ok {
		v := monitorevent.DefaultMethod
		mec.mutation.SetMethod(v)
	}
	if _, ok := mec.mutation.Endpoint(); !ok {
		v := monitorevent.DefaultEndpoint
		mec.mutation.SetEndpoint(v)
	}
	if _, ok := mec.mutation.RequestPath(); !ok {
		v := monitorevent.DefaultRequestPath
		mec.mutation.SetRequestPath(v)
	}
	if _, ok := mec.mutation.Model(); !ok {
		v := monitorevent.DefaultModel
		mec.mutation.SetModel(v)
	}
	if _, ok := mec.mutation.ErrorCode(); !ok {
		v := monitorevent.DefaultErrorCode
		mec.mutation.SetErrorCode(v)
	}
	if _, ok := mec.mutation.ErrorType(); !ok {
		v := monitorevent.DefaultErrorType
		mec.mutation.SetErrorType(v)
	}
	if _, ok := mec.mutation.Count(); !ok {
		v := monitorevent.DefaultCount
		mec.mutation.SetCount(v)
	}
	if _, ok := mec.mutation.CreatedAt(); !ok {
		v := monitorevent.DefaultCreatedAt()
		mec.mutation.SetCreatedAt(v)
	}
	if _, ok := mec.mutation.UpdatedAt(); !ok {
		v := monitorevent.DefaultUpdatedAt()
		mec.mutation.SetUpdatedAt(v)
	}
	if _, ok := mec.mutation.ExpiresAt(); !ok {
		v := monitorevent.DefaultExpiresAt()
		mec.mutation.SetExpiresAt(v)
	}
	if _, ok := mec.mutation.NotifyError(); !ok {
		v := monitorevent.DefaultNotifyError
		mec.mutation.SetNotifyError(v)
	}
	if _, ok := mec.mutation.Detail(); !ok {
		v := monitorevent.DefaultDetail
		mec.mutation.SetDetail(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (mec *MonitorEventCreate) check() error {
	if _, ok := mec.mutation.Kind(); !ok {
		return &ValidationError{Name: "kind", err: errors.New(`ent: missing required field "MonitorEvent.kind"`)}
	}
	if v, ok := mec.mutation.Kind(); ok {
		if err := monitorevent.KindValidator(v); err != nil {
			return &ValidationError{Name: "kind", err: fmt.Errorf(`ent: validator failed for field "MonitorEvent.kind": %w`, err)}
		}
	}
	if _, ok := mec.mutation.Severity(); !ok {
		return &ValidationError{Name: "severity", err: errors.New(`ent: missing required field "MonitorEvent.severity"`)}
	}
	if v, ok := mec.mutation.Severity(); ok {
		if err := monitorevent.SeverityValidator(v); err != nil {
			return &ValidationError{Name: "severity", err: fmt.Errorf(`ent: validator failed for field "MonitorEvent.severity": %w`, err)}
		}
	}
	if _, ok := mec.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "MonitorEvent.status"`)}
	}
	if v, ok := mec.mutation.Status(); ok {
		if err := monitorevent.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "MonitorEvent.status": %w`, err)}
		}
	}
	if _, ok := mec.mutation.Source(); !ok {
		return &ValidationError{Name: "source", err: errors.New(`ent: missing required field "MonitorEvent.source"`)}
	}
	if v, ok := mec.mutation.Source(); ok {
		if err := monitorevent.SourceValidator(v); err != nil {
			return &ValidationError{Name: "source", err: fmt.Errorf(`ent: validator failed for field "MonitorEvent.source": %w`, err)}
		}
	}
	if _, ok := mec.mutation.SubjectType(); !ok {
		return &ValidationError{Name: "subject_type", err: errors.New(`ent: missing required field "MonitorEvent.subject_type"`)}
	}
	if v, ok := mec.mutation.SubjectType(); ok {
		if err := monitorevent.SubjectTypeValidator(v); err != nil {
			return &ValidationError{Name: "subject_type", err: fmt.Errorf(`ent: validator failed for field "MonitorEvent.subject_type": %w`, err)}
		}
	}
	if _, ok := mec.mutation.SubjectID(); !ok {
		return &ValidationError{Name: "subject_id", err: errors.New(`ent: missing required field "MonitorEvent.subject_id"`)}
	}
	if v, ok := mec.mutation.SubjectID(); ok {
		if err := monitorevent.SubjectIDValidator(v); err != nil {
			return &ValidationError{Name: "subject_id", err: fmt.Errorf(`ent: validator failed for field "MonitorEvent.subject_id": %w`, err)}
		}
	}
	if _, ok := mec.mutation.Fingerprint(); !ok {
		return &ValidationError{Name: "fingerprint", err: errors.New(`ent: missing required field "MonitorEvent.fingerprint"`)}
	}
	if v, ok := mec.mutation.Fingerprint(); ok {
		if err := monitorevent.FingerprintValidator(v); err != nil {
			return &ValidationError{Name: "fingerprint", err: fmt.Errorf(`ent: validator failed for field "MonitorEvent.fingerprint": %w`, err)}
		}
	}
	if _, ok := mec.mutation.Title(); !ok {
		return &ValidationError{Name: "title", err: errors.New(`ent: missing required field "MonitorEvent.title"`)}
	}
	if v, ok := mec.mutation.Title(); ok {
		if err := monitorevent.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "MonitorEvent.title": %w`, err)}
		}
	}
	if _, ok := mec.mutation.Message(); !ok {
		return &ValidationError{Name: "message", err: errors.New(`ent: missing required field "MonitorEvent.message"`)}
	}
	if v, ok := mec.mutation.Message(); ok {
		if err := monitorevent.MessageValidator(v); err != nil {
			return &ValidationError{Name: "message", err: fmt.Errorf(`ent: validator failed for field "MonitorEvent.message": %w`, err)}
		}
	}
	if _, ok := mec.mutation.APIKeyNameSnapshot(); !ok {
		return &ValidationError{Name: "api_key_name_snapshot", err: errors.New(`ent: missing required field "MonitorEvent.api_key_name_snapshot"`)}
	}
	if v, ok := mec.mutation.APIKeyNameSnapshot(); ok {
		if err := monitorevent.APIKeyNameSnapshotValidator(v); err != nil {
			return &ValidationError{Name: "api_key_name_snapshot", err: fmt.Errorf(`ent: validator failed for field "MonitorEvent.api_key_name_snapshot": %w`, err)}
		}
	}
	if _, ok := mec.mutation.APIKeyPrefix(); !ok {
		return &ValidationError{Name: "api_key_prefix", err: errors.New(`ent: missing required field "MonitorEvent.api_key_prefix"`)}
	}
	if v, ok := mec.mutation.APIKeyPrefix(); ok {
		if err := monitorevent.APIKeyPrefixValidator(v); err != nil {
			return &ValidationError{Name: "api_key_prefix", err: fmt.Errorf(`ent: validator failed for field "MonitorEvent.api_key_prefix": %w`, err)}
		}
	}
	if _, ok := mec.mutation.UserEmailSnapshot(); !ok {
		return &ValidationError{Name: "user_email_snapshot", err: errors.New(`ent: missing required field "MonitorEvent.user_email_snapshot"`)}
	}
	if v, ok := mec.mutation.UserEmailSnapshot(); ok {
		if err := monitorevent.UserEmailSnapshotValidator(v); err != nil {
			return &ValidationError{Name: "user_email_snapshot", err: fmt.Errorf(`ent: validator failed for field "MonitorEvent.user_email_snapshot": %w`, err)}
		}
	}
	if _, ok := mec.mutation.AccountNameSnapshot(); !ok {
		return &ValidationError{Name: "account_name_snapshot", err: errors.New(`ent: missing required field "MonitorEvent.account_name_snapshot"`)}
	}
	if v, ok := mec.mutation.AccountNameSnapshot(); ok {
		if err := monitorevent.AccountNameSnapshotValidator(v); err != nil {
			return &ValidationError{Name: "account_name_snapshot", err: fmt.Errorf(`ent: validator failed for field "MonitorEvent.account_name_snapshot": %w`, err)}
		}
	}
	if _, ok := mec.mutation.Platform(); !ok {
		return &ValidationError{Name: "platform", err: errors.New(`ent: missing required field "MonitorEvent.platform"`)}
	}
	if v, ok := mec.mutation.Platform(); ok {
		if err := monitorevent.PlatformValidator(v); err != nil {
			return &ValidationError{Name: "platform", err: fmt.Errorf(`ent: validator failed for field "MonitorEvent.platform": %w`, err)}
		}
	}
	if _, ok := mec.mutation.PluginID(); !ok {
		return &ValidationError{Name: "plugin_id", err: errors.New(`ent: missing required field "MonitorEvent.plugin_id"`)}
	}
	if v, ok := mec.mutation.PluginID(); ok {
		if err := monitorevent.PluginIDValidator(v); err != nil {
			return &ValidationError{Name: "plugin_id", err: fmt.Errorf(`ent: validator failed for field "MonitorEvent.plugin_id": %w`, err)}
		}
	}
	if _, ok := mec.mutation.TaskType(); !ok {
		return &ValidationError{Name: "task_type", err: errors.New(`ent: missing required field "MonitorEvent.task_type"`)}
	}
	if v, ok := mec.mutation.TaskType(); ok {
		if err := monitorevent.TaskTypeValidator(v); err != nil {
			return &ValidationError{Name: "task_type", err: fmt.Errorf(`ent: validator failed for field "MonitorEvent.task_type": %w`, err)}
		}
	}
	if _, ok := mec.mutation.Method(); !ok {
		return &ValidationError{Name: "method", err: errors.New(`ent: missing required field "MonitorEvent.method"`)}
	}
	if v, ok := mec.mutation.Method(); ok {
		if err := monitorevent.MethodValidator(v); err != nil {
			return &ValidationError{Name: "method", err: fmt.Errorf(`ent: validator failed for field "MonitorEvent.method": %w`, err)}
		}
	}
	if _, ok := mec.mutation.Endpoint(); !ok {
		return &ValidationError{Name: "endpoint", err: errors.New(`ent: missing required field "MonitorEvent.endpoint"`)}
	}
	if v, ok := mec.mutation.Endpoint(); ok {
		if err := monitorevent.EndpointValidator(v); err != nil {
			return &ValidationError{Name: "endpoint", err: fmt.Errorf(`ent: validator failed for field "MonitorEvent.endpoint": %w`, err)}
		}
	}
	if _, ok := mec.mutation.RequestPath(); !ok {
		return &ValidationError{Name: "request_path", err: errors.New(`ent: missing required field "MonitorEvent.request_path"`)}
	}
	if v, ok := mec.mutation.RequestPath(); ok {
		if err := monitorevent.RequestPathValidator(v); err != nil {
			return &ValidationError{Name: "request_path", err: fmt.Errorf(`ent: validator failed for field "MonitorEvent.request_path": %w`, err)}
		}
	}
	if _, ok := mec.mutation.Model(); !ok {
		return &ValidationError{Name: "model", err: errors.New(`ent: missing required field "MonitorEvent.model"`)}
	}
	if v, ok := mec.mutation.Model(); ok {
		if err := monitorevent.ModelValidator(v); err != nil {
			return &ValidationError{Name: "model", err: fmt.Errorf(`ent: validator failed for field "MonitorEvent.model": %w`, err)}
		}
	}
	if _, ok := mec.mutation.ErrorCode(); !ok {
		return &ValidationError{Name: "error_code", err: errors.New(`ent: missing required field "MonitorEvent.error_code"`)}
	}
	if v, ok := mec.mutation.ErrorCode(); ok {
		if err := monitorevent.ErrorCodeValidator(v); err != nil {
			return &ValidationError{Name: "error_code", err: fmt.Errorf(`ent: validator failed for field "MonitorEvent.error_code": %w`, err)}
		}
	}
	if _, ok := mec.mutation.ErrorType(); !ok {
		return &ValidationError{Name: "error_type", err: errors.New(`ent: missing required field "MonitorEvent.error_type"`)}
	}
	if v, ok := mec.mutation.ErrorType(); ok {
		if err := monitorevent.ErrorTypeValidator(v); err != nil {
			return &ValidationError{Name: "error_type", err: fmt.Errorf(`ent: validator failed for field "MonitorEvent.error_type": %w`, err)}
		}
	}
	if _, ok := mec.mutation.Count(); !ok {
		return &ValidationError{Name: "count", err: errors.New(`ent: missing required field "MonitorEvent.count"`)}
	}
	if _, ok := mec.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "MonitorEvent.created_at"`)}
	}
	if _, ok := mec.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "MonitorEvent.updated_at"`)}
	}
	if _, ok := mec.mutation.ExpiresAt(); !ok {
		return &ValidationError{Name: "expires_at", err: errors.New(`ent: missing required field "MonitorEvent.expires_at"`)}
	}
	if _, ok := mec.mutation.NotifyError(); !ok {
		return &ValidationError{Name: "notify_error", err: errors.New(`ent: missing required field "MonitorEvent.notify_error"`)}
	}
	if v, ok := mec.mutation.NotifyError(); ok {
		if err := monitorevent.NotifyErrorValidator(v); err != nil {
			return &ValidationError{Name: "notify_error", err: fmt.Errorf(`ent: validator failed for field "MonitorEvent.notify_error": %w`, err)}
		}
	}
	return nil
}

func (mec *MonitorEventCreate) sqlSave(ctx context.Context) (*MonitorEvent, error) {
	if err := mec.check(); err != nil {
		return nil, err
	}
	_node, _spec := mec.createSpec()
	if err := sqlgraph.CreateNode(ctx, mec.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	mec.mutation.id = &_node.ID
	mec.mutation.done = true
	return _node, nil
}

func (mec *MonitorEventCreate) createSpec() (*MonitorEvent, *sqlgraph.CreateSpec) {
	var (
		_node = &MonitorEvent{config: mec.config}
		_spec = sqlgraph.NewCreateSpec(monitorevent.Table, sqlgraph.NewFieldSpec(monitorevent.FieldID, field.TypeInt))
	)
	if value, ok := mec.mutation.Kind(); ok {
		_spec.SetField(monitorevent.FieldKind, field.TypeEnum, value)
		_node.Kind = value
	}
	if value, ok := mec.mutation.Severity(); ok {
		_spec.SetField(monitorevent.FieldSeverity, field.TypeEnum, value)
		_node.Severity = value
	}
	if value, ok := mec.mutation.Status(); ok {
		_spec.SetField(monitorevent.FieldStatus, field.TypeEnum, value)
		_node.Status = value
	}
	if value, ok := mec.mutation.Source(); ok {
		_spec.SetField(monitorevent.FieldSource, field.TypeString, value)
		_node.Source = value
	}
	if value, ok := mec.mutation.SubjectType(); ok {
		_spec.SetField(monitorevent.FieldSubjectType, field.TypeString, value)
		_node.SubjectType = value
	}
	if value, ok := mec.mutation.SubjectID(); ok {
		_spec.SetField(monitorevent.FieldSubjectID, field.TypeString, value)
		_node.SubjectID = value
	}
	if value, ok := mec.mutation.Fingerprint(); ok {
		_spec.SetField(monitorevent.FieldFingerprint, field.TypeString, value)
		_node.Fingerprint = value
	}
	if value, ok := mec.mutation.Title(); ok {
		_spec.SetField(monitorevent.FieldTitle, field.TypeString, value)
		_node.Title = value
	}
	if value, ok := mec.mutation.Message(); ok {
		_spec.SetField(monitorevent.FieldMessage, field.TypeString, value)
		_node.Message = value
	}
	if value, ok := mec.mutation.APIKeyID(); ok {
		_spec.SetField(monitorevent.FieldAPIKeyID, field.TypeInt, value)
		_node.APIKeyID = &value
	}
	if value, ok := mec.mutation.APIKeyNameSnapshot(); ok {
		_spec.SetField(monitorevent.FieldAPIKeyNameSnapshot, field.TypeString, value)
		_node.APIKeyNameSnapshot = value
	}
	if value, ok := mec.mutation.APIKeyPrefix(); ok {
		_spec.SetField(monitorevent.FieldAPIKeyPrefix, field.TypeString, value)
		_node.APIKeyPrefix = value
	}
	if value, ok := mec.mutation.UserID(); ok {
		_spec.SetField(monitorevent.FieldUserID, field.TypeInt, value)
		_node.UserID = &value
	}
	if value, ok := mec.mutation.UserEmailSnapshot(); ok {
		_spec.SetField(monitorevent.FieldUserEmailSnapshot, field.TypeString, value)
		_node.UserEmailSnapshot = value
	}
	if value, ok := mec.mutation.GroupID(); ok {
		_spec.SetField(monitorevent.FieldGroupID, field.TypeInt, value)
		_node.GroupID = &value
	}
	if value, ok := mec.mutation.AccountID(); ok {
		_spec.SetField(monitorevent.FieldAccountID, field.TypeInt, value)
		_node.AccountID = &value
	}
	if value, ok := mec.mutation.AccountNameSnapshot(); ok {
		_spec.SetField(monitorevent.FieldAccountNameSnapshot, field.TypeString, value)
		_node.AccountNameSnapshot = value
	}
	if value, ok := mec.mutation.Platform(); ok {
		_spec.SetField(monitorevent.FieldPlatform, field.TypeString, value)
		_node.Platform = value
	}
	if value, ok := mec.mutation.PluginID(); ok {
		_spec.SetField(monitorevent.FieldPluginID, field.TypeString, value)
		_node.PluginID = value
	}
	if value, ok := mec.mutation.TaskType(); ok {
		_spec.SetField(monitorevent.FieldTaskType, field.TypeString, value)
		_node.TaskType = value
	}
	if value, ok := mec.mutation.Method(); ok {
		_spec.SetField(monitorevent.FieldMethod, field.TypeString, value)
		_node.Method = value
	}
	if value, ok := mec.mutation.Endpoint(); ok {
		_spec.SetField(monitorevent.FieldEndpoint, field.TypeString, value)
		_node.Endpoint = value
	}
	if value, ok := mec.mutation.RequestPath(); ok {
		_spec.SetField(monitorevent.FieldRequestPath, field.TypeString, value)
		_node.RequestPath = value
	}
	if value, ok := mec.mutation.Model(); ok {
		_spec.SetField(monitorevent.FieldModel, field.TypeString, value)
		_node.Model = value
	}
	if value, ok := mec.mutation.HTTPStatus(); ok {
		_spec.SetField(monitorevent.FieldHTTPStatus, field.TypeInt, value)
		_node.HTTPStatus = &value
	}
	if value, ok := mec.mutation.UpstreamStatus(); ok {
		_spec.SetField(monitorevent.FieldUpstreamStatus, field.TypeInt, value)
		_node.UpstreamStatus = &value
	}
	if value, ok := mec.mutation.ErrorCode(); ok {
		_spec.SetField(monitorevent.FieldErrorCode, field.TypeString, value)
		_node.ErrorCode = value
	}
	if value, ok := mec.mutation.ErrorType(); ok {
		_spec.SetField(monitorevent.FieldErrorType, field.TypeString, value)
		_node.ErrorType = value
	}
	if value, ok := mec.mutation.Count(); ok {
		_spec.SetField(monitorevent.FieldCount, field.TypeInt64, value)
		_node.Count = value
	}
	if value, ok := mec.mutation.CreatedAt(); ok {
		_spec.SetField(monitorevent.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := mec.mutation.UpdatedAt(); ok {
		_spec.SetField(monitorevent.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := mec.mutation.ResolvedAt(); ok {
		_spec.SetField(monitorevent.FieldResolvedAt, field.TypeTime, value)
		_node.ResolvedAt = &value
	}
	if value, ok := mec.mutation.IgnoredAt(); ok {
		_spec.SetField(monitorevent.FieldIgnoredAt, field.TypeTime, value)
		_node.IgnoredAt = &value
	}
	if value, ok := mec.mutation.AutoResolveAt(); ok {
		_spec.SetField(monitorevent.FieldAutoResolveAt, field.TypeTime, value)
		_node.AutoResolveAt = &value
	}
	if value, ok := mec.mutation.ExpiresAt(); ok {
		_spec.SetField(monitorevent.FieldExpiresAt, field.TypeTime, value)
		_node.ExpiresAt = value
	}
	if value, ok := mec.mutation.LastNotifiedAt(); ok {
		_spec.SetField(monitorevent.FieldLastNotifiedAt, field.TypeTime, value)
		_node.LastNotifiedAt = &value
	}
	if value, ok := mec.mutation.NextNotifyAt(); ok {
		_spec.SetField(monitorevent.FieldNextNotifyAt, field.TypeTime, value)
		_node.NextNotifyAt = &value
	}
	if value, ok := mec.mutation.NotifyError(); ok {
		_spec.SetField(monitorevent.FieldNotifyError, field.TypeString, value)
		_node.NotifyError = value
	}
	if value, ok := mec.mutation.Detail(); ok {
		_spec.SetField(monitorevent.FieldDetail, field.TypeJSON, value)
		_node.Detail = value
	}
	return _node, _spec
}

// MonitorEventCreateBulk is the builder for creating many MonitorEvent entities in bulk.
type MonitorEventCreateBulk struct {
	config
	err      error
	builders []*MonitorEventCreate
}

// Save creates the MonitorEvent entities in the database.
func (mecb *MonitorEventCreateBulk) Save(ctx context.Context) ([]*MonitorEvent, error) {
	if mecb.err != nil {
		return nil, mecb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(mecb.builders))
	nodes := make([]*MonitorEvent, len(mecb.builders))
	mutators := make([]Mutator, len(mecb.builders))
	for i := range mecb.builders {
		func(i int, root context.Context) {
			builder := mecb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*MonitorEventMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, mecb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, mecb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, mecb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (mecb *MonitorEventCreateBulk) SaveX(ctx context.Context) []*MonitorEvent {
	v, err := mecb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (mecb *MonitorEventCreateBulk) Exec(ctx context.Context) error {
	_, err := mecb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (mecb *MonitorEventCreateBulk) ExecX(ctx context.Context) {
	if err := mecb.Exec(ctx); err != nil {
		panic(err)
	}
}
