// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/DevilGenius/airgate-core/ent/monitorrequesttrace"
	"github.com/DevilGenius/airgate-core/ent/predicate"
)

// MonitorRequestTraceDelete is the builder for deleting a MonitorRequestTrace entity.
type MonitorRequestTraceDelete struct {
	config
	hooks    []Hook
	mutation *MonitorRequestTraceMutation
}

// Where appends a list predicates to the MonitorRequestTraceDelete builder.
func (mrtd *MonitorRequestTraceDelete) Where(ps ...predicate.MonitorRequestTrace) *MonitorRequestTraceDelete {
	mrtd.mutation.Where(ps...)
	return mrtd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (mrtd *MonitorRequestTraceDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, mrtd.sqlExec, mrtd.mutation, mrtd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (mrtd *MonitorRequestTraceDelete) ExecX(ctx context.Context) int {
	n, err := mrtd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (mrtd *MonitorRequestTraceDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(monitorrequesttrace.Table, sqlgraph.NewFieldSpec(monitorrequesttrace.FieldID, field.TypeInt))
	if ps := mrtd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, mrtd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	mrtd.mutation.done = true
	return affected, err
}

// MonitorRequestTraceDeleteOne is the builder for deleting a single MonitorRequestTrace entity.
type MonitorRequestTraceDeleteOne struct {
	mrtd *MonitorRequestTraceDelete
}

// Where appends a list predicates to the MonitorRequestTraceDelete builder.
func (mrtdo *MonitorRequestTraceDeleteOne) Where(ps ...predicate.MonitorRequestTrace) *MonitorRequestTraceDeleteOne {
	mrtdo.mrtd.mutation.Where(ps...)
	return mrtdo
}

// Exec executes the deletion query.
func (mrtdo *MonitorRequestTraceDeleteOne) Exec(ctx context.Context) error {
	n, err := mrtdo.mrtd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{monitorrequesttrace.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (mrtdo *MonitorRequestTraceDeleteOne) ExecX(ctx context.Context) {
	if err := mrtdo.Exec(ctx); err != nil {
		panic(err)
	}
}
