// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/DevilGenius/airgate-core/ent/monitorrequesttrace"
	"github.com/DevilGenius/airgate-core/ent/predicate"
)

// MonitorRequestTraceQuery is the builder for querying MonitorRequestTrace entities.
type MonitorRequestTraceQuery struct {
	config
	ctx        *QueryContext
	order      []monitorrequesttrace.OrderOption
	inters     []Interceptor
	predicates []predicate.MonitorRequestTrace
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the MonitorRequestTraceQuery builder.
func (mrtq *MonitorRequestTraceQuery) Where(ps ...predicate.MonitorRequestTrace) *MonitorRequestTraceQuery {
	mrtq.predicates = append(mrtq.predicates, ps...)
	return mrtq
}

// Limit the number of records to be returned by this query.
func (mrtq *MonitorRequestTraceQuery) Limit(limit int) *MonitorRequestTraceQuery {
	mrtq.ctx.Limit = &limit
	return mrtq
}

// Offset to start from.
func (mrtq *MonitorRequestTraceQuery) Offset(offset int) *MonitorRequestTraceQuery {
	mrtq.ctx.Offset = &offset
	return mrtq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (mrtq *MonitorRequestTraceQuery) Unique(unique bool) *MonitorRequestTraceQuery {
	mrtq.ctx.Unique = &unique
	return mrtq
}

// Order specifies how the records should be ordered.
func (mrtq *MonitorRequestTraceQuery) Order(o ...monitorrequesttrace.OrderOption) *MonitorRequestTraceQuery {
	mrtq.order = append(mrtq.order, o...)
	return mrtq
}

// First returns the first MonitorRequestTrace entity from the query.
// Returns a *NotFoundError when no MonitorRequestTrace was found.
func (mrtq *MonitorRequestTraceQuery) First(ctx context.Context) (*MonitorRequestTrace, error) {
	nodes, err := mrtq.Limit(1).All(setContextOp(ctx, mrtq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{monitorrequesttrace.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (mrtq *MonitorRequestTraceQuery) FirstX(ctx context.Context) *MonitorRequestTrace {
	node, err := mrtq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first MonitorRequestTrace ID from the query.
// Returns a *NotFoundError when no MonitorRequestTrace ID was found.
func (mrtq *MonitorRequestTraceQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = mrtq.Limit(1).IDs(setContextOp(ctx, mrtq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{monitorrequesttrace.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (mrtq *MonitorRequestTraceQuery) FirstIDX(ctx context.Context) int {
	id, err := mrtq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single MonitorRequestTrace entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one MonitorRequestTrace entity is found.
// Returns a *NotFoundError when no MonitorRequestTrace entities are found.
func (mrtq *MonitorRequestTraceQuery) Only(ctx context.Context) (*MonitorRequestTrace, error) {
	nodes, err := mrtq.Limit(2).All(setContextOp(ctx, mrtq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{monitorrequesttrace.Label}
	default:
		return nil, &NotSingularError{monitorrequesttrace.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (mrtq *MonitorRequestTraceQuery) OnlyX(ctx context.Context) *MonitorRequestTrace {
	node, err := mrtq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only MonitorRequestTrace ID in the query.
// Returns a *NotSingularError when more than one MonitorRequestTrace ID is found.
// Returns a *NotFoundError when no entities are found.
func (mrtq *MonitorRequestTraceQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = mrtq.Limit(2).IDs(setContextOp(ctx, mrtq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{monitorrequesttrace.Label}
	default:
		err = &NotSingularError{monitorrequesttrace.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (mrtq *MonitorRequestTraceQuery) OnlyIDX(ctx context.Context) int {
	id, err := mrtq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of MonitorRequestTraces.
func (mrtq *MonitorRequestTraceQuery) All(ctx context.Context) ([]*MonitorRequestTrace, error) {
	ctx = setContextOp(ctx, mrtq.ctx, "All")
	if err := mrtq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*MonitorRequestTrace, *MonitorRequestTraceQuery]()
	return withInterceptors[[]*MonitorRequestTrace](ctx, mrtq, qr, mrtq.inters)
}

// AllX is like All, but panics if an error occurs.
func (mrtq *MonitorRequestTraceQuery) AllX(ctx context.Context) []*MonitorRequestTrace {
	nodes, err := mrtq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of MonitorRequestTrace IDs.
func (mrtq *MonitorRequestTraceQuery) IDs(ctx context.Context) (ids []int, err error) {
	if mrtq.ctx.Unique == nil && mrtq.path != nil {
		mrtq.Unique(true)
	}
	ctx = setContextOp(ctx, mrtq.ctx, "IDs")
	if err = mrtq.Select(monitorrequesttrace.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (mrtq *MonitorRequestTraceQuery) IDsX(ctx context.Context) []int {
	ids, err := mrtq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (mrtq *MonitorRequestTraceQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, mrtq.ctx, "Count")
	if err := mrtq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, mrtq, querierCount[*MonitorRequestTraceQuery](), mrtq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (mrtq *MonitorRequestTraceQuery) CountX(ctx context.Context) int {
	count, err := mrtq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (mrtq *MonitorRequestTraceQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, mrtq.ctx, "Exist")
	switch _, err := mrtq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (mrtq *MonitorRequestTraceQuery) ExistX(ctx context.Context) bool {
	exist, err := mrtq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the MonitorRequestTraceQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (mrtq *MonitorRequestTraceQuery) Clone() *MonitorRequestTraceQuery {
	if mrtq == nil {
		return nil
	}
	return &MonitorRequestTraceQuery{
		config:     mrtq.config,
		ctx:        mrtq.ctx.Clone(),
		order:      append([]monitorrequesttrace.OrderOption{}, mrtq.order...),
		inters:     append([]Interceptor{}, mrtq.inters...),
		predicates: append([]predicate.MonitorRequestTrace{}, mrtq.predicates...),
		// clone intermediate query.
		sql:  mrtq.sql.Clone(),
		path: mrtq.path,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Hash string `json:"hash,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.MonitorRequestTrace.Query().
//		GroupBy(monitorrequesttrace.FieldHash).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (mrtq *MonitorRequestTraceQuery) GroupBy(field string, fields ...string) *MonitorRequestTraceGroupBy {
	mrtq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &MonitorRequestTraceGroupBy{build: mrtq}
	grbuild.flds = &mrtq.ctx.Fields
	grbuild.label = monitorrequesttrace.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Hash string `json:"hash,omitempty"`
//	}
//
//	client.MonitorRequestTrace.Query().
//		Select(monitorrequesttrace.FieldHash).
//		Scan(ctx, &v)
func (mrtq *MonitorRequestTraceQuery) Select(fields ...string) *MonitorRequestTraceSelect {
	mrtq.ctx.Fields = append(mrtq.ctx.Fields, fields...)
	sbuild := &MonitorRequestTraceSelect{MonitorRequestTraceQuery: mrtq}
	sbuild.label = monitorrequesttrace.Label
	sbuild.flds, sbuild.scan = &mrtq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a MonitorRequestTraceSelect configured with the given aggregations.
func (mrtq *MonitorRequestTraceQuery) Aggregate(fns ...AggregateFunc) *MonitorRequestTraceSelect {
	return mrtq.Select().Aggregate(fns...)
}

func (mrtq *MonitorRequestTraceQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range mrtq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, mrtq); err != nil {
				return err
			}
		}
	}
	for _, f := range mrtq.ctx.Fields {
		if !monitorrequesttrace.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if mrtq.path != nil {
		prev, err := mrtq.path(ctx)
		if err != nil {
			return err
		}
		mrtq.sql = prev
	}
	return nil
}

func (mrtq *MonitorRequestTraceQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*MonitorRequestTrace, error) {
	var (
		nodes = []*MonitorRequestTrace{}
		_spec = mrtq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*MonitorRequestTrace).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &MonitorRequestTrace{config: mrtq.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, mrtq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (mrtq *MonitorRequestTraceQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := mrtq.querySpec()
	_spec.Node.Columns = mrtq.ctx.Fields
	if len(mrtq.ctx.Fields) > 0 {
		_spec.Unique = mrtq.ctx.Unique != nil && *mrtq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, mrtq.driver, _spec)
}

func (mrtq *MonitorRequestTraceQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(monitorrequesttrace.Table, monitorrequesttrace.Columns, sqlgraph.NewFieldSpec(monitorrequesttrace.FieldID, field.TypeInt))
	_spec.From = mrtq.sql
	if unique := mrtq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if mrtq.path != nil {
		_spec.Unique = true
	}
	if fields := mrtq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, monitorrequesttrace.FieldID)
		for i := range fields {
			if fields[i] != monitorrequesttrace.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := mrtq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := mrtq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := mrtq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := mrtq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (mrtq *MonitorRequestTraceQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(mrtq.driver.Dialect())
	t1 := builder.Table(monitorrequesttrace.Table)
	columns := mrtq.ctx.Fields
	if len(columns) == 0 {
		columns = monitorrequesttrace.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if mrtq.sql != nil {
		selector = mrtq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if mrtq.ctx.Unique != nil && *mrtq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range mrtq.predicates {
		p(selector)
	}
	for _, p := range mrtq.order {
		p(selector)
	}
	if offset := mrtq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := mrtq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// MonitorRequestTraceGroupBy is the group-by builder for MonitorRequestTrace entities.
type MonitorRequestTraceGroupBy struct {
	selector
	build *MonitorRequestTraceQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (mrtgb *MonitorRequestTraceGroupBy) Aggregate(fns ...AggregateFunc) *MonitorRequestTraceGroupBy {
	mrtgb.fns = append(mrtgb.fns, fns...)
	return mrtgb
}

// Scan applies the selector query and scans the result into the given value.
func (mrtgb *MonitorRequestTraceGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, mrtgb.build.ctx, "GroupBy")
	if err := mrtgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*MonitorRequestTraceQuery, *MonitorRequestTraceGroupBy](ctx, mrtgb.build, mrtgb, mrtgb.build.inters, v)
}

func (mrtgb *MonitorRequestTraceGroupBy) sqlScan(ctx context.Context, root *MonitorRequestTraceQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(mrtgb.fns))
	for _, fn := range mrtgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*mrtgb.flds)+len(mrtgb.fns))
		for _, f := range *mrtgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*mrtgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := mrtgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// MonitorRequestTraceSelect is the builder for selecting fields of MonitorRequestTrace entities.
type MonitorRequestTraceSelect struct {
	*MonitorRequestTraceQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (mrts *MonitorRequestTraceSelect) Aggregate(fns ...AggregateFunc) *MonitorRequestTraceSelect {
	mrts.fns = append(mrts.fns, fns...)
	return mrts
}

// Scan applies the selector query and scans the result into the given value.
func (mrts *MonitorRequestTraceSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, mrts.ctx, "Select")
	if err := mrts.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*MonitorRequestTraceQuery, *MonitorRequestTraceSelect](ctx, mrts.MonitorRequestTraceQuery, mrts, mrts.inters, v)
}

func (mrts *MonitorRequestTraceSelect) sqlScan(ctx context.Context, root *MonitorRequestTraceQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(mrts.fns))
	for _, fn := range mrts.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*mrts.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := mrts.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
