// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/DevilGenius/airgate-core/ent/account"
	"github.com/DevilGenius/airgate-core/ent/apikey"
	"github.com/DevilGenius/airgate-core/ent/balancelog"
	"github.com/DevilGenius/airgate-core/ent/group"
	"github.com/DevilGenius/airgate-core/ent/monitorevent"
	"github.com/DevilGenius/airgate-core/ent/monitorrequestevent"
	"github.com/DevilGenius/airgate-core/ent/monitorrequesttrace"
	"github.com/DevilGenius/airgate-core/ent/plugin"
	"github.com/DevilGenius/airgate-core/ent/pluginsource"
	"github.com/DevilGenius/airgate-core/ent/proxy"
	"github.com/DevilGenius/airgate-core/ent/schema"
	"github.com/DevilGenius/airgate-core/ent/setting"
	"github.com/DevilGenius/airgate-core/ent/task"
	"github.com/DevilGenius/airgate-core/ent/usagelog"
	"github.com/DevilGenius/airgate-core/ent/user"
	"github.com/DevilGenius/airgate-core/ent/usersubscription"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	apikeyFields := schema.APIKey{}.Fields()
	_ = apikeyFields
	// apikeyDescName is the schema descriptor for name field.
	apikeyDescName := apikeyFields[0].Descriptor()
	// apikey.NameValidator is a validator for the "name" field. It is called by the builders before save.
	apikey.NameValidator = apikeyDescName.Validators[0].(func(string) error)
	// apikeyDescKeyHint is the schema descriptor for key_hint field.
	apikeyDescKeyHint := apikeyFields[1].Descriptor()
	// apikey.DefaultKeyHint holds the default value on creation for the key_hint field.
	apikey.DefaultKeyHint = apikeyDescKeyHint.Default.(string)
	// apikeyDescKeyHash is the schema descriptor for key_hash field.
	apikeyDescKeyHash := apikeyFields[2].Descriptor()
	// apikey.KeyHashValidator is a validator for the "key_hash" field. It is called by the builders before save.
	apikey.KeyHashValidator = apikeyDescKeyHash.Validators[0].(func(string) error)
	// apikeyDescQuotaUsd is the schema descriptor for quota_usd field.
	apikeyDescQuotaUsd := apikeyFields[6].Descriptor()
	// apikey.DefaultQuotaUsd holds the default value on creation for the quota_usd field.
	apikey.DefaultQuotaUsd = apikeyDescQuotaUsd.Default.(float64)
	// apikeyDescUsedQuota is the schema descriptor for used_quota field.
	apikeyDescUsedQuota := apikeyFields[7].Descriptor()
	// apikey.DefaultUsedQuota holds the default value on creation for the used_quota field.
	apikey.DefaultUsedQuota = apikeyDescUsedQuota.Default.(float64)
	// apikeyDescUsedQuotaActual is the schema descriptor for used_quota_actual field.
	apikeyDescUsedQuotaActual := apikeyFields[8].Descriptor()
	// apikey.DefaultUsedQuotaActual holds the default value on creation for the used_quota_actual field.
	apikey.DefaultUsedQuotaActual = apikeyDescUsedQuotaActual.Default.(float64)
	// apikeyDescSellRate is the schema descriptor for sell_rate field.
	apikeyDescSellRate := apikeyFields[9].Descriptor()
	// apikey.DefaultSellRate holds the default value on creation for the sell_rate field.
	apikey.DefaultSellRate = apikeyDescSellRate.Default.(float64)
	// apikey.SellRateValidator is a validator for the "sell_rate" field. It is called by the builders before save.
	apikey.SellRateValidator = func() func(float64) error {
		validators := apikeyDescSellRate.Validators
		fns := [...]func(float64) error{
			validators[0].(func(float64) error),
			validators[1].(func(float64) error),
		}
		return func(sell_rate float64) error {
			for _, fn := range fns {
				if err := fn(sell_rate); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// apikeyDescMaxConcurrency is the schema descriptor for max_concurrency field.
	apikeyDescMaxConcurrency := apikeyFields[10].Descriptor()
	// apikey.DefaultMaxConcurrency holds the default value on creation for the max_concurrency field.
	apikey.DefaultMaxConcurrency = apikeyDescMaxConcurrency.Default.(int)
	// apikey.MaxConcurrencyValidator is a validator for the "max_concurrency" field. It is called by the builders before save.
	apikey.MaxConcurrencyValidator = apikeyDescMaxConcurrency.Validators[0].(func(int) error)
	// apikeyDescBalanceAlertEnabled is the schema descriptor for balance_alert_enabled field.
	apikeyDescBalanceAlertEnabled := apikeyFields[11].Descriptor()
	// apikey.DefaultBalanceAlertEnabled holds the default value on creation for the balance_alert_enabled field.
	apikey.DefaultBalanceAlertEnabled = apikeyDescBalanceAlertEnabled.Default.(bool)
	// apikeyDescBalanceAlertEmail is the schema descriptor for balance_alert_email field.
	apikeyDescBalanceAlertEmail := apikeyFields[12].Descriptor()
	// apikey.DefaultBalanceAlertEmail holds the default value on creation for the balance_alert_email field.
	apikey.DefaultBalanceAlertEmail = apikeyDescBalanceAlertEmail.Default.(string)
	// apikey.BalanceAlertEmailValidator is a validator for the "balance_alert_email" field. It is called by the builders before save.
	apikey.BalanceAlertEmailValidator = apikeyDescBalanceAlertEmail.Validators[0].(func(string) error)
	// apikeyDescBalanceAlertThreshold is the schema descriptor for balance_alert_threshold field.
	apikeyDescBalanceAlertThreshold := apikeyFields[13].Descriptor()
	// apikey.DefaultBalanceAlertThreshold holds the default value on creation for the balance_alert_threshold field.
	apikey.DefaultBalanceAlertThreshold = apikeyDescBalanceAlertThreshold.Default.(float64)
	// apikeyDescBalanceAlertNotified is the schema descriptor for balance_alert_notified field.
	apikeyDescBalanceAlertNotified := apikeyFields[14].Descriptor()
	// apikey.DefaultBalanceAlertNotified holds the default value on creation for the balance_alert_notified field.
	apikey.DefaultBalanceAlertNotified = apikeyDescBalanceAlertNotified.Default.(bool)
	// apikeyDescCreatedAt is the schema descriptor for created_at field.
	apikeyDescCreatedAt := apikeyFields[17].Descriptor()
	// apikey.DefaultCreatedAt holds the default value on creation for the created_at field.
	apikey.DefaultCreatedAt = apikeyDescCreatedAt.Default.(func() time.Time)
	// apikeyDescUpdatedAt is the schema descriptor for updated_at field.
	apikeyDescUpdatedAt := apikeyFields[18].Descriptor()
	// apikey.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	apikey.DefaultUpdatedAt = apikeyDescUpdatedAt.Default.(func() time.Time)
	// apikey.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	apikey.UpdateDefaultUpdatedAt = apikeyDescUpdatedAt.UpdateDefault.(func() time.Time)
	accountFields := schema.Account{}.Fields()
	_ = accountFields
	// accountDescName is the schema descriptor for name field.
	accountDescName := accountFields[0].Descriptor()
	// account.NameValidator is a validator for the "name" field. It is called by the builders before save.
	account.NameValidator = accountDescName.Validators[0].(func(string) error)
	// accountDescPlatform is the schema descriptor for platform field.
	accountDescPlatform := accountFields[2].Descriptor()
	// account.PlatformValidator is a validator for the "platform" field. It is called by the builders before save.
	account.PlatformValidator = accountDescPlatform.Validators[0].(func(string) error)
	// accountDescType is the schema descriptor for type field.
	accountDescType := accountFields[3].Descriptor()
	// account.DefaultType holds the default value on creation for the type field.
	account.DefaultType = accountDescType.Default.(string)
	// accountDescCredentials is the schema descriptor for credentials field.
	accountDescCredentials := accountFields[4].Descriptor()
	// account.DefaultCredentials holds the default value on creation for the credentials field.
	account.DefaultCredentials = accountDescCredentials.Default.(map[string]string)
	// accountDescPriority is the schema descriptor for priority field.
	accountDescPriority := accountFields[8].Descriptor()
	// account.DefaultPriority holds the default value on creation for the priority field.
	account.DefaultPriority = accountDescPriority.Default.(int)
	// account.PriorityValidator is a validator for the "priority" field. It is called by the builders before save.
	account.PriorityValidator = func() func(int) error {
		validators := accountDescPriority.Validators
		fns := [...]func(int) error{
			validators[0].(func(int) error),
			validators[1].(func(int) error),
		}
		return func(priority int) error {
			for _, fn := range fns {
				if err := fn(priority); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// accountDescMaxConcurrency is the schema descriptor for max_concurrency field.
	accountDescMaxConcurrency := accountFields[9].Descriptor()
	// account.DefaultMaxConcurrency holds the default value on creation for the max_concurrency field.
	account.DefaultMaxConcurrency = accountDescMaxConcurrency.Default.(int)
	// accountDescRateMultiplier is the schema descriptor for rate_multiplier field.
	accountDescRateMultiplier := accountFields[10].Descriptor()
	// account.DefaultRateMultiplier holds the default value on creation for the rate_multiplier field.
	account.DefaultRateMultiplier = accountDescRateMultiplier.Default.(float64)
	// account.RateMultiplierValidator is a validator for the "rate_multiplier" field. It is called by the builders before save.
	account.RateMultiplierValidator = func() func(float64) error {
		validators := accountDescRateMultiplier.Validators
		fns := [...]func(float64) error{
			validators[0].(func(float64) error),
			validators[1].(func(float64) error),
		}
		return func(rate_multiplier float64) error {
			for _, fn := range fns {
				if err := fn(rate_multiplier); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// accountDescErrorMsg is the schema descriptor for error_msg field.
	accountDescErrorMsg := accountFields[11].Descriptor()
	// account.DefaultErrorMsg holds the default value on creation for the error_msg field.
	account.DefaultErrorMsg = accountDescErrorMsg.Default.(string)
	// accountDescUpstreamIsPool is the schema descriptor for upstream_is_pool field.
	accountDescUpstreamIsPool := accountFields[12].Descriptor()
	// account.DefaultUpstreamIsPool holds the default value on creation for the upstream_is_pool field.
	account.DefaultUpstreamIsPool = accountDescUpstreamIsPool.Default.(bool)
	// accountDescExtra is the schema descriptor for extra field.
	accountDescExtra := accountFields[14].Descriptor()
	// account.DefaultExtra holds the default value on creation for the extra field.
	account.DefaultExtra = accountDescExtra.Default.(map[string]interface{})
	// accountDescCreatedAt is the schema descriptor for created_at field.
	accountDescCreatedAt := accountFields[16].Descriptor()
	// account.DefaultCreatedAt holds the default value on creation for the created_at field.
	account.DefaultCreatedAt = accountDescCreatedAt.Default.(func() time.Time)
	// accountDescUpdatedAt is the schema descriptor for updated_at field.
	accountDescUpdatedAt := accountFields[17].Descriptor()
	// account.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	account.DefaultUpdatedAt = accountDescUpdatedAt.Default.(func() time.Time)
	// account.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	account.UpdateDefaultUpdatedAt = accountDescUpdatedAt.UpdateDefault.(func() time.Time)
	balancelogFields := schema.BalanceLog{}.Fields()
	_ = balancelogFields
	// balancelogDescRemark is the schema descriptor for remark field.
	balancelogDescRemark := balancelogFields[4].Descriptor()
	// balancelog.DefaultRemark holds the default value on creation for the remark field.
	balancelog.DefaultRemark = balancelogDescRemark.Default.(string)
	// balancelogDescUserIDSnapshot is the schema descriptor for user_id_snapshot field.
	balancelogDescUserIDSnapshot := balancelogFields[5].Descriptor()
	// balancelog.DefaultUserIDSnapshot holds the default value on creation for the user_id_snapshot field.
	balancelog.DefaultUserIDSnapshot = balancelogDescUserIDSnapshot.Default.(int)
	// balancelogDescUserEmailSnapshot is the schema descriptor for user_email_snapshot field.
	balancelogDescUserEmailSnapshot := balancelogFields[6].Descriptor()
	// balancelog.DefaultUserEmailSnapshot holds the default value on creation for the user_email_snapshot field.
	balancelog.DefaultUserEmailSnapshot = balancelogDescUserEmailSnapshot.Default.(string)
	// balancelogDescCreatedAt is the schema descriptor for created_at field.
	balancelogDescCreatedAt := balancelogFields[7].Descriptor()
	// balancelog.DefaultCreatedAt holds the default value on creation for the created_at field.
	balancelog.DefaultCreatedAt = balancelogDescCreatedAt.Default.(func() time.Time)
	groupFields := schema.Group{}.Fields()
	_ = groupFields
	// groupDescName is the schema descriptor for name field.
	groupDescName := groupFields[0].Descriptor()
	// group.NameValidator is a validator for the "name" field. It is called by the builders before save.
	group.NameValidator = groupDescName.Validators[0].(func(string) error)
	// groupDescPlatform is the schema descriptor for platform field.
	groupDescPlatform := groupFields[1].Descriptor()
	// group.PlatformValidator is a validator for the "platform" field. It is called by the builders before save.
	group.PlatformValidator = groupDescPlatform.Validators[0].(func(string) error)
	// groupDescRateMultiplier is the schema descriptor for rate_multiplier field.
	groupDescRateMultiplier := groupFields[2].Descriptor()
	// group.DefaultRateMultiplier holds the default value on creation for the rate_multiplier field.
	group.DefaultRateMultiplier = groupDescRateMultiplier.Default.(float64)
	// group.RateMultiplierValidator is a validator for the "rate_multiplier" field. It is called by the builders before save.
	group.RateMultiplierValidator = func() func(float64) error {
		validators := groupDescRateMultiplier.Validators
		fns := [...]func(float64) error{
			validators[0].(func(float64) error),
			validators[1].(func(float64) error),
		}
		return func(rate_multiplier float64) error {
			for _, fn := range fns {
				if err := fn(rate_multiplier); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// groupDescIsExclusive is the schema descriptor for is_exclusive field.
	groupDescIsExclusive := groupFields[3].Descriptor()
	// group.DefaultIsExclusive holds the default value on creation for the is_exclusive field.
	group.DefaultIsExclusive = groupDescIsExclusive.Default.(bool)
	// groupDescStatusVisible is the schema descriptor for status_visible field.
	groupDescStatusVisible := groupFields[4].Descriptor()
	// group.DefaultStatusVisible holds the default value on creation for the status_visible field.
	group.DefaultStatusVisible = groupDescStatusVisible.Default.(bool)
	// groupDescServiceTier is the schema descriptor for service_tier field.
	groupDescServiceTier := groupFields[13].Descriptor()
	// group.DefaultServiceTier holds the default value on creation for the service_tier field.
	group.DefaultServiceTier = groupDescServiceTier.Default.(string)
	// groupDescForceInstructions is the schema descriptor for force_instructions field.
	groupDescForceInstructions := groupFields[14].Descriptor()
	// group.DefaultForceInstructions holds the default value on creation for the force_instructions field.
	group.DefaultForceInstructions = groupDescForceInstructions.Default.(string)
	// groupDescNote is the schema descriptor for note field.
	groupDescNote := groupFields[15].Descriptor()
	// group.DefaultNote holds the default value on creation for the note field.
	group.DefaultNote = groupDescNote.Default.(string)
	// groupDescSortWeight is the schema descriptor for sort_weight field.
	groupDescSortWeight := groupFields[16].Descriptor()
	// group.DefaultSortWeight holds the default value on creation for the sort_weight field.
	group.DefaultSortWeight = groupDescSortWeight.Default.(int)
	// groupDescCreatedAt is the schema descriptor for created_at field.
	groupDescCreatedAt := groupFields[17].Descriptor()
	// group.DefaultCreatedAt holds the default value on creation for the created_at field.
	group.DefaultCreatedAt = groupDescCreatedAt.Default.(func() time.Time)
	// groupDescUpdatedAt is the schema descriptor for updated_at field.
	groupDescUpdatedAt := groupFields[18].Descriptor()
	// group.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	group.DefaultUpdatedAt = groupDescUpdatedAt.Default.(func() time.Time)
	// group.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	group.UpdateDefaultUpdatedAt = groupDescUpdatedAt.UpdateDefault.(func() time.Time)
	monitoreventFields := schema.MonitorEvent{}.Fields()
	_ = monitoreventFields
	// monitoreventDescSource is the schema descriptor for source field.
	monitoreventDescSource := monitoreventFields[4].Descriptor()
	// monitorevent.DefaultSource holds the default value on creation for the source field.
	monitorevent.DefaultSource = monitoreventDescSource.Default.(string)
	// monitorevent.SourceValidator is a validator for the "source" field. It is called by the builders before save.
	monitorevent.SourceValidator = monitoreventDescSource.Validators[0].(func(string) error)
	// monitoreventDescSubjectType is the schema descriptor for subject_type field.
	monitoreventDescSubjectType := monitoreventFields[5].Descriptor()
	// monitorevent.DefaultSubjectType holds the default value on creation for the subject_type field.
	monitorevent.DefaultSubjectType = monitoreventDescSubjectType.Default.(string)
	// monitorevent.SubjectTypeValidator is a validator for the "subject_type" field. It is called by the builders before save.
	monitorevent.SubjectTypeValidator = monitoreventDescSubjectType.Validators[0].(func(string) error)
	// monitoreventDescSubjectID is the schema descriptor for subject_id field.
	monitoreventDescSubjectID := monitoreventFields[6].Descriptor()
	// monitorevent.DefaultSubjectID holds the default value on creation for the subject_id field.
	monitorevent.DefaultSubjectID = monitoreventDescSubjectID.Default.(string)
	// monitorevent.SubjectIDValidator is a validator for the "subject_id" field. It is called by the builders before save.
	monitorevent.SubjectIDValidator = monitoreventDescSubjectID.Validators[0].(func(string) error)
	// monitoreventDescHash is the schema descriptor for hash field.
	monitoreventDescHash := monitoreventFields[7].Descriptor()
	// monitorevent.HashValidator is a validator for the "hash" field. It is called by the builders before save.
	monitorevent.HashValidator = func() func(string) error {
		validators := monitoreventDescHash.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(hash string) error {
			for _, fn := range fns {
				if err := fn(hash); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// monitoreventDescTitle is the schema descriptor for title field.
	monitoreventDescTitle := monitoreventFields[8].Descriptor()
	// monitorevent.DefaultTitle holds the default value on creation for the title field.
	monitorevent.DefaultTitle = monitoreventDescTitle.Default.(string)
	// monitorevent.TitleValidator is a validator for the "title" field. It is called by the builders before save.
	monitorevent.TitleValidator = monitoreventDescTitle.Validators[0].(func(string) error)
	// monitoreventDescMessage is the schema descriptor for message field.
	monitoreventDescMessage := monitoreventFields[9].Descriptor()
	// monitorevent.DefaultMessage holds the default value on creation for the message field.
	monitorevent.DefaultMessage = monitoreventDescMessage.Default.(string)
	// monitorevent.MessageValidator is a validator for the "message" field. It is called by the builders before save.
	monitorevent.MessageValidator = monitoreventDescMessage.Validators[0].(func(string) error)
	// monitoreventDescAccountNameSnapshot is the schema descriptor for account_name_snapshot field.
	monitoreventDescAccountNameSnapshot := monitoreventFields[11].Descriptor()
	// monitorevent.DefaultAccountNameSnapshot holds the default value on creation for the account_name_snapshot field.
	monitorevent.DefaultAccountNameSnapshot = monitoreventDescAccountNameSnapshot.Default.(string)
	// monitorevent.AccountNameSnapshotValidator is a validator for the "account_name_snapshot" field. It is called by the builders before save.
	monitorevent.AccountNameSnapshotValidator = monitoreventDescAccountNameSnapshot.Validators[0].(func(string) error)
	// monitoreventDescPlatform is the schema descriptor for platform field.
	monitoreventDescPlatform := monitoreventFields[12].Descriptor()
	// monitorevent.DefaultPlatform holds the default value on creation for the platform field.
	monitorevent.DefaultPlatform = monitoreventDescPlatform.Default.(string)
	// monitorevent.PlatformValidator is a validator for the "platform" field. It is called by the builders before save.
	monitorevent.PlatformValidator = monitoreventDescPlatform.Validators[0].(func(string) error)
	// monitoreventDescPluginID is the schema descriptor for plugin_id field.
	monitoreventDescPluginID := monitoreventFields[13].Descriptor()
	// monitorevent.DefaultPluginID holds the default value on creation for the plugin_id field.
	monitorevent.DefaultPluginID = monitoreventDescPluginID.Default.(string)
	// monitorevent.PluginIDValidator is a validator for the "plugin_id" field. It is called by the builders before save.
	monitorevent.PluginIDValidator = monitoreventDescPluginID.Validators[0].(func(string) error)
	// monitoreventDescTaskType is the schema descriptor for task_type field.
	monitoreventDescTaskType := monitoreventFields[14].Descriptor()
	// monitorevent.DefaultTaskType holds the default value on creation for the task_type field.
	monitorevent.DefaultTaskType = monitoreventDescTaskType.Default.(string)
	// monitorevent.TaskTypeValidator is a validator for the "task_type" field. It is called by the builders before save.
	monitorevent.TaskTypeValidator = monitoreventDescTaskType.Validators[0].(func(string) error)
	// monitoreventDescErrorCode is the schema descriptor for error_code field.
	monitoreventDescErrorCode := monitoreventFields[15].Descriptor()
	// monitorevent.DefaultErrorCode holds the default value on creation for the error_code field.
	monitorevent.DefaultErrorCode = monitoreventDescErrorCode.Default.(string)
	// monitorevent.ErrorCodeValidator is a validator for the "error_code" field. It is called by the builders before save.
	monitorevent.ErrorCodeValidator = monitoreventDescErrorCode.Validators[0].(func(string) error)
	// monitoreventDescCreatedAt is the schema descriptor for created_at field.
	monitoreventDescCreatedAt := monitoreventFields[16].Descriptor()
	// monitorevent.DefaultCreatedAt holds the default value on creation for the created_at field.
	monitorevent.DefaultCreatedAt = monitoreventDescCreatedAt.Default.(func() time.Time)
	// monitoreventDescUpdatedAt is the schema descriptor for updated_at field.
	monitoreventDescUpdatedAt := monitoreventFields[17].Descriptor()
	// monitorevent.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	monitorevent.DefaultUpdatedAt = monitoreventDescUpdatedAt.Default.(func() time.Time)
	// monitoreventDescExpiresAt is the schema descriptor for expires_at field.
	monitoreventDescExpiresAt := monitoreventFields[20].Descriptor()
	// monitorevent.DefaultExpiresAt holds the default value on creation for the expires_at field.
	monitorevent.DefaultExpiresAt = monitoreventDescExpiresAt.Default.(func() time.Time)
	// monitoreventDescNotifyError is the schema descriptor for notify_error field.
	monitoreventDescNotifyError := monitoreventFields[23].Descriptor()
	// monitorevent.DefaultNotifyError holds the default value on creation for the notify_error field.
	monitorevent.DefaultNotifyError = monitoreventDescNotifyError.Default.(string)
	// monitorevent.NotifyErrorValidator is a validator for the "notify_error" field. It is called by the builders before save.
	monitorevent.NotifyErrorValidator = monitoreventDescNotifyError.Validators[0].(func(string) error)
	// monitoreventDescDetail is the schema descriptor for detail field.
	monitoreventDescDetail := monitoreventFields[24].Descriptor()
	// monitorevent.DefaultDetail holds the default value on creation for the detail field.
	monitorevent.DefaultDetail = monitoreventDescDetail.Default.(map[string]interface{})
	monitorrequesteventFields := schema.MonitorRequestEvent{}.Fields()
	_ = monitorrequesteventFields
	// monitorrequesteventDescType is the schema descriptor for type field.
	monitorrequesteventDescType := monitorrequesteventFields[0].Descriptor()
	// monitorrequestevent.DefaultType holds the default value on creation for the type field.
	monitorrequestevent.DefaultType = monitorrequesteventDescType.Default.(string)
	// monitorrequestevent.TypeValidator is a validator for the "type" field. It is called by the builders before save.
	monitorrequestevent.TypeValidator = monitorrequesteventDescType.Validators[0].(func(string) error)
	// monitorrequesteventDescSource is the schema descriptor for source field.
	monitorrequesteventDescSource := monitorrequesteventFields[2].Descriptor()
	// monitorrequestevent.DefaultSource holds the default value on creation for the source field.
	monitorrequestevent.DefaultSource = monitorrequesteventDescSource.Default.(string)
	// monitorrequestevent.SourceValidator is a validator for the "source" field. It is called by the builders before save.
	monitorrequestevent.SourceValidator = monitorrequesteventDescSource.Validators[0].(func(string) error)
	// monitorrequesteventDescHash is the schema descriptor for hash field.
	monitorrequesteventDescHash := monitorrequesteventFields[3].Descriptor()
	// monitorrequestevent.HashValidator is a validator for the "hash" field. It is called by the builders before save.
	monitorrequestevent.HashValidator = func() func(string) error {
		validators := monitorrequesteventDescHash.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(hash string) error {
			for _, fn := range fns {
				if err := fn(hash); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// monitorrequesteventDescTraceHash is the schema descriptor for trace_hash field.
	monitorrequesteventDescTraceHash := monitorrequesteventFields[4].Descriptor()
	// monitorrequestevent.DefaultTraceHash holds the default value on creation for the trace_hash field.
	monitorrequestevent.DefaultTraceHash = monitorrequesteventDescTraceHash.Default.(string)
	// monitorrequestevent.TraceHashValidator is a validator for the "trace_hash" field. It is called by the builders before save.
	monitorrequestevent.TraceHashValidator = monitorrequesteventDescTraceHash.Validators[0].(func(string) error)
	// monitorrequesteventDescFingerprint is the schema descriptor for fingerprint field.
	monitorrequesteventDescFingerprint := monitorrequesteventFields[5].Descriptor()
	// monitorrequestevent.DefaultFingerprint holds the default value on creation for the fingerprint field.
	monitorrequestevent.DefaultFingerprint = monitorrequesteventDescFingerprint.Default.(string)
	// monitorrequestevent.FingerprintValidator is a validator for the "fingerprint" field. It is called by the builders before save.
	monitorrequestevent.FingerprintValidator = monitorrequesteventDescFingerprint.Validators[0].(func(string) error)
	// monitorrequesteventDescTitle is the schema descriptor for title field.
	monitorrequesteventDescTitle := monitorrequesteventFields[6].Descriptor()
	// monitorrequestevent.DefaultTitle holds the default value on creation for the title field.
	monitorrequestevent.DefaultTitle = monitorrequesteventDescTitle.Default.(string)
	// monitorrequestevent.TitleValidator is a validator for the "title" field. It is called by the builders before save.
	monitorrequestevent.TitleValidator = monitorrequesteventDescTitle.Validators[0].(func(string) error)
	// monitorrequesteventDescMessage is the schema descriptor for message field.
	monitorrequesteventDescMessage := monitorrequesteventFields[7].Descriptor()
	// monitorrequestevent.DefaultMessage holds the default value on creation for the message field.
	monitorrequestevent.DefaultMessage = monitorrequesteventDescMessage.Default.(string)
	// monitorrequestevent.MessageValidator is a validator for the "message" field. It is called by the builders before save.
	monitorrequestevent.MessageValidator = monitorrequesteventDescMessage.Validators[0].(func(string) error)
	// monitorrequesteventDescRequestID is the schema descriptor for request_id field.
	monitorrequesteventDescRequestID := monitorrequesteventFields[8].Descriptor()
	// monitorrequestevent.DefaultRequestID holds the default value on creation for the request_id field.
	monitorrequestevent.DefaultRequestID = monitorrequesteventDescRequestID.Default.(string)
	// monitorrequestevent.RequestIDValidator is a validator for the "request_id" field. It is called by the builders before save.
	monitorrequestevent.RequestIDValidator = monitorrequesteventDescRequestID.Validators[0].(func(string) error)
	// monitorrequesteventDescAPIKeyNameSnapshot is the schema descriptor for api_key_name_snapshot field.
	monitorrequesteventDescAPIKeyNameSnapshot := monitorrequesteventFields[10].Descriptor()
	// monitorrequestevent.DefaultAPIKeyNameSnapshot holds the default value on creation for the api_key_name_snapshot field.
	monitorrequestevent.DefaultAPIKeyNameSnapshot = monitorrequesteventDescAPIKeyNameSnapshot.Default.(string)
	// monitorrequestevent.APIKeyNameSnapshotValidator is a validator for the "api_key_name_snapshot" field. It is called by the builders before save.
	monitorrequestevent.APIKeyNameSnapshotValidator = monitorrequesteventDescAPIKeyNameSnapshot.Validators[0].(func(string) error)
	// monitorrequesteventDescUserEmailSnapshot is the schema descriptor for user_email_snapshot field.
	monitorrequesteventDescUserEmailSnapshot := monitorrequesteventFields[12].Descriptor()
	// monitorrequestevent.DefaultUserEmailSnapshot holds the default value on creation for the user_email_snapshot field.
	monitorrequestevent.DefaultUserEmailSnapshot = monitorrequesteventDescUserEmailSnapshot.Default.(string)
	// monitorrequestevent.UserEmailSnapshotValidator is a validator for the "user_email_snapshot" field. It is called by the builders before save.
	monitorrequestevent.UserEmailSnapshotValidator = monitorrequesteventDescUserEmailSnapshot.Validators[0].(func(string) error)
	// monitorrequesteventDescAccountNameSnapshot is the schema descriptor for account_name_snapshot field.
	monitorrequesteventDescAccountNameSnapshot := monitorrequesteventFields[15].Descriptor()
	// monitorrequestevent.DefaultAccountNameSnapshot holds the default value on creation for the account_name_snapshot field.
	monitorrequestevent.DefaultAccountNameSnapshot = monitorrequesteventDescAccountNameSnapshot.Default.(string)
	// monitorrequestevent.AccountNameSnapshotValidator is a validator for the "account_name_snapshot" field. It is called by the builders before save.
	monitorrequestevent.AccountNameSnapshotValidator = monitorrequesteventDescAccountNameSnapshot.Validators[0].(func(string) error)
	// monitorrequesteventDescPlatform is the schema descriptor for platform field.
	monitorrequesteventDescPlatform := monitorrequesteventFields[16].Descriptor()
	// monitorrequestevent.DefaultPlatform holds the default value on creation for the platform field.
	monitorrequestevent.DefaultPlatform = monitorrequesteventDescPlatform.Default.(string)
	// monitorrequestevent.PlatformValidator is a validator for the "platform" field. It is called by the builders before save.
	monitorrequestevent.PlatformValidator = monitorrequesteventDescPlatform.Validators[0].(func(string) error)
	// monitorrequesteventDescPluginID is the schema descriptor for plugin_id field.
	monitorrequesteventDescPluginID := monitorrequesteventFields[17].Descriptor()
	// monitorrequestevent.DefaultPluginID holds the default value on creation for the plugin_id field.
	monitorrequestevent.DefaultPluginID = monitorrequesteventDescPluginID.Default.(string)
	// monitorrequestevent.PluginIDValidator is a validator for the "plugin_id" field. It is called by the builders before save.
	monitorrequestevent.PluginIDValidator = monitorrequesteventDescPluginID.Validators[0].(func(string) error)
	// monitorrequesteventDescMethod is the schema descriptor for method field.
	monitorrequesteventDescMethod := monitorrequesteventFields[18].Descriptor()
	// monitorrequestevent.DefaultMethod holds the default value on creation for the method field.
	monitorrequestevent.DefaultMethod = monitorrequesteventDescMethod.Default.(string)
	// monitorrequestevent.MethodValidator is a validator for the "method" field. It is called by the builders before save.
	monitorrequestevent.MethodValidator = monitorrequesteventDescMethod.Validators[0].(func(string) error)
	// monitorrequesteventDescEndpoint is the schema descriptor for endpoint field.
	monitorrequesteventDescEndpoint := monitorrequesteventFields[19].Descriptor()
	// monitorrequestevent.DefaultEndpoint holds the default value on creation for the endpoint field.
	monitorrequestevent.DefaultEndpoint = monitorrequesteventDescEndpoint.Default.(string)
	// monitorrequestevent.EndpointValidator is a validator for the "endpoint" field. It is called by the builders before save.
	monitorrequestevent.EndpointValidator = monitorrequesteventDescEndpoint.Validators[0].(func(string) error)
	// monitorrequesteventDescModel is the schema descriptor for model field.
	monitorrequesteventDescModel := monitorrequesteventFields[20].Descriptor()
	// monitorrequestevent.DefaultModel holds the default value on creation for the model field.
	monitorrequestevent.DefaultModel = monitorrequesteventDescModel.Default.(string)
	// monitorrequestevent.ModelValidator is a validator for the "model" field. It is called by the builders before save.
	monitorrequestevent.ModelValidator = monitorrequesteventDescModel.Validators[0].(func(string) error)
	// monitorrequesteventDescErrorCode is the schema descriptor for error_code field.
	monitorrequesteventDescErrorCode := monitorrequesteventFields[23].Descriptor()
	// monitorrequestevent.DefaultErrorCode holds the default value on creation for the error_code field.
	monitorrequestevent.DefaultErrorCode = monitorrequesteventDescErrorCode.Default.(string)
	// monitorrequestevent.ErrorCodeValidator is a validator for the "error_code" field. It is called by the builders before save.
	monitorrequestevent.ErrorCodeValidator = monitorrequesteventDescErrorCode.Validators[0].(func(string) error)
	// monitorrequesteventDescDurationMs is the schema descriptor for duration_ms field.
	monitorrequesteventDescDurationMs := monitorrequesteventFields[24].Descriptor()
	// monitorrequestevent.DefaultDurationMs holds the default value on creation for the duration_ms field.
	monitorrequestevent.DefaultDurationMs = monitorrequesteventDescDurationMs.Default.(int64)
	// monitorrequesteventDescCreatedAt is the schema descriptor for created_at field.
	monitorrequesteventDescCreatedAt := monitorrequesteventFields[25].Descriptor()
	// monitorrequestevent.DefaultCreatedAt holds the default value on creation for the created_at field.
	monitorrequestevent.DefaultCreatedAt = monitorrequesteventDescCreatedAt.Default.(func() time.Time)
	// monitorrequesteventDescExpiresAt is the schema descriptor for expires_at field.
	monitorrequesteventDescExpiresAt := monitorrequesteventFields[26].Descriptor()
	// monitorrequestevent.DefaultExpiresAt holds the default value on creation for the expires_at field.
	monitorrequestevent.DefaultExpiresAt = monitorrequesteventDescExpiresAt.Default.(func() time.Time)
	// monitorrequesteventDescDetail is the schema descriptor for detail field.
	monitorrequesteventDescDetail := monitorrequesteventFields[27].Descriptor()
	// monitorrequestevent.DefaultDetail holds the default value on creation for the detail field.
	monitorrequestevent.DefaultDetail = monitorrequesteventDescDetail.Default.(map[string]interface{})
	monitorrequesttraceFields := schema.MonitorRequestTrace{}.Fields()
	_ = monitorrequesttraceFields
	// monitorrequesttraceDescHash is the schema descriptor for hash field.
	monitorrequesttraceDescHash := monitorrequesttraceFields[0].Descriptor()
	// monitorrequesttrace.HashValidator is a validator for the "hash" field. It is called by the builders before save.
	monitorrequesttrace.HashValidator = func() func(string) error {
		validators := monitorrequesttraceDescHash.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(hash string) error {
			for _, fn := range fns {
				if err := fn(hash); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// monitorrequesttraceDescSchemaVersion is the schema descriptor for schema_version field.
	monitorrequesttraceDescSchemaVersion := monitorrequesttraceFields[1].Descriptor()
	// monitorrequesttrace.DefaultSchemaVersion holds the default value on creation for the schema_version field.
	monitorrequesttrace.DefaultSchemaVersion = monitorrequesttraceDescSchemaVersion.Default.(int)
	// monitorrequesttraceDescEncoding is the schema descriptor for encoding field.
	monitorrequesttraceDescEncoding := monitorrequesttraceFields[2].Descriptor()
	// monitorrequesttrace.DefaultEncoding holds the default value on creation for the encoding field.
	monitorrequesttrace.DefaultEncoding = monitorrequesttraceDescEncoding.Default.(string)
	// monitorrequesttrace.EncodingValidator is a validator for the "encoding" field. It is called by the builders before save.
	monitorrequesttrace.EncodingValidator = monitorrequesttraceDescEncoding.Validators[0].(func(string) error)
	// monitorrequesttraceDescRawSize is the schema descriptor for raw_size field.
	monitorrequesttraceDescRawSize := monitorrequesttraceFields[4].Descriptor()
	// monitorrequesttrace.DefaultRawSize holds the default value on creation for the raw_size field.
	monitorrequesttrace.DefaultRawSize = monitorrequesttraceDescRawSize.Default.(int64)
	// monitorrequesttraceDescCompressedSize is the schema descriptor for compressed_size field.
	monitorrequesttraceDescCompressedSize := monitorrequesttraceFields[5].Descriptor()
	// monitorrequesttrace.DefaultCompressedSize holds the default value on creation for the compressed_size field.
	monitorrequesttrace.DefaultCompressedSize = monitorrequesttraceDescCompressedSize.Default.(int64)
	// monitorrequesttraceDescSeenCount is the schema descriptor for seen_count field.
	monitorrequesttraceDescSeenCount := monitorrequesttraceFields[6].Descriptor()
	// monitorrequesttrace.DefaultSeenCount holds the default value on creation for the seen_count field.
	monitorrequesttrace.DefaultSeenCount = monitorrequesttraceDescSeenCount.Default.(int64)
	// monitorrequesttraceDescFirstSeenAt is the schema descriptor for first_seen_at field.
	monitorrequesttraceDescFirstSeenAt := monitorrequesttraceFields[7].Descriptor()
	// monitorrequesttrace.DefaultFirstSeenAt holds the default value on creation for the first_seen_at field.
	monitorrequesttrace.DefaultFirstSeenAt = monitorrequesttraceDescFirstSeenAt.Default.(func() time.Time)
	// monitorrequesttraceDescLastSeenAt is the schema descriptor for last_seen_at field.
	monitorrequesttraceDescLastSeenAt := monitorrequesttraceFields[8].Descriptor()
	// monitorrequesttrace.DefaultLastSeenAt holds the default value on creation for the last_seen_at field.
	monitorrequesttrace.DefaultLastSeenAt = monitorrequesttraceDescLastSeenAt.Default.(func() time.Time)
	// monitorrequesttraceDescExpiresAt is the schema descriptor for expires_at field.
	monitorrequesttraceDescExpiresAt := monitorrequesttraceFields[9].Descriptor()
	// monitorrequesttrace.DefaultExpiresAt holds the default value on creation for the expires_at field.
	monitorrequesttrace.DefaultExpiresAt = monitorrequesttraceDescExpiresAt.Default.(func() time.Time)
	pluginFields := schema.Plugin{}.Fields()
	_ = pluginFields
	// pluginDescName is the schema descriptor for name field.
	pluginDescName := pluginFields[0].Descriptor()
	// plugin.NameValidator is a validator for the "name" field. It is called by the builders before save.
	plugin.NameValidator = pluginDescName.Validators[0].(func(string) error)
	// pluginDescPlatform is the schema descriptor for platform field.
	pluginDescPlatform := pluginFields[1].Descriptor()
	// plugin.DefaultPlatform holds the default value on creation for the platform field.
	plugin.DefaultPlatform = pluginDescPlatform.Default.(string)
	// pluginDescVersion is the schema descriptor for version field.
	pluginDescVersion := pluginFields[2].Descriptor()
	// plugin.DefaultVersion holds the default value on creation for the version field.
	plugin.DefaultVersion = pluginDescVersion.Default.(string)
	// pluginDescBinaryPath is the schema descriptor for binary_path field.
	pluginDescBinaryPath := pluginFields[6].Descriptor()
	// plugin.DefaultBinaryPath holds the default value on creation for the binary_path field.
	plugin.DefaultBinaryPath = pluginDescBinaryPath.Default.(string)
	// pluginDescCreatedAt is the schema descriptor for created_at field.
	pluginDescCreatedAt := pluginFields[7].Descriptor()
	// plugin.DefaultCreatedAt holds the default value on creation for the created_at field.
	plugin.DefaultCreatedAt = pluginDescCreatedAt.Default.(func() time.Time)
	// pluginDescUpdatedAt is the schema descriptor for updated_at field.
	pluginDescUpdatedAt := pluginFields[8].Descriptor()
	// plugin.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	plugin.DefaultUpdatedAt = pluginDescUpdatedAt.Default.(func() time.Time)
	// plugin.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	plugin.UpdateDefaultUpdatedAt = pluginDescUpdatedAt.UpdateDefault.(func() time.Time)
	pluginsourceFields := schema.PluginSource{}.Fields()
	_ = pluginsourceFields
	// pluginsourceDescName is the schema descriptor for name field.
	pluginsourceDescName := pluginsourceFields[0].Descriptor()
	// pluginsource.NameValidator is a validator for the "name" field. It is called by the builders before save.
	pluginsource.NameValidator = pluginsourceDescName.Validators[0].(func(string) error)
	// pluginsourceDescURL is the schema descriptor for url field.
	pluginsourceDescURL := pluginsourceFields[1].Descriptor()
	// pluginsource.URLValidator is a validator for the "url" field. It is called by the builders before save.
	pluginsource.URLValidator = pluginsourceDescURL.Validators[0].(func(string) error)
	// pluginsourceDescIsOfficial is the schema descriptor for is_official field.
	pluginsourceDescIsOfficial := pluginsourceFields[2].Descriptor()
	// pluginsource.DefaultIsOfficial holds the default value on creation for the is_official field.
	pluginsource.DefaultIsOfficial = pluginsourceDescIsOfficial.Default.(bool)
	// pluginsourceDescCreatedAt is the schema descriptor for created_at field.
	pluginsourceDescCreatedAt := pluginsourceFields[4].Descriptor()
	// pluginsource.DefaultCreatedAt holds the default value on creation for the created_at field.
	pluginsource.DefaultCreatedAt = pluginsourceDescCreatedAt.Default.(func() time.Time)
	// pluginsourceDescUpdatedAt is the schema descriptor for updated_at field.
	pluginsourceDescUpdatedAt := pluginsourceFields[5].Descriptor()
	// pluginsource.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	pluginsource.DefaultUpdatedAt = pluginsourceDescUpdatedAt.Default.(func() time.Time)
	// pluginsource.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	pluginsource.UpdateDefaultUpdatedAt = pluginsourceDescUpdatedAt.UpdateDefault.(func() time.Time)
	proxyFields := schema.Proxy{}.Fields()
	_ = proxyFields
	// proxyDescName is the schema descriptor for name field.
	proxyDescName := proxyFields[0].Descriptor()
	// proxy.NameValidator is a validator for the "name" field. It is called by the builders before save.
	proxy.NameValidator = proxyDescName.Validators[0].(func(string) error)
	// proxyDescAddress is the schema descriptor for address field.
	proxyDescAddress := proxyFields[2].Descriptor()
	// proxy.AddressValidator is a validator for the "address" field. It is called by the builders before save.
	proxy.AddressValidator = proxyDescAddress.Validators[0].(func(string) error)
	// proxyDescUsername is the schema descriptor for username field.
	proxyDescUsername := proxyFields[4].Descriptor()
	// proxy.DefaultUsername holds the default value on creation for the username field.
	proxy.DefaultUsername = proxyDescUsername.Default.(string)
	// proxyDescPassword is the schema descriptor for password field.
	proxyDescPassword := proxyFields[5].Descriptor()
	// proxy.DefaultPassword holds the default value on creation for the password field.
	proxy.DefaultPassword = proxyDescPassword.Default.(string)
	// proxyDescCreatedAt is the schema descriptor for created_at field.
	proxyDescCreatedAt := proxyFields[7].Descriptor()
	// proxy.DefaultCreatedAt holds the default value on creation for the created_at field.
	proxy.DefaultCreatedAt = proxyDescCreatedAt.Default.(func() time.Time)
	// proxyDescUpdatedAt is the schema descriptor for updated_at field.
	proxyDescUpdatedAt := proxyFields[8].Descriptor()
	// proxy.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	proxy.DefaultUpdatedAt = proxyDescUpdatedAt.Default.(func() time.Time)
	// proxy.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	proxy.UpdateDefaultUpdatedAt = proxyDescUpdatedAt.UpdateDefault.(func() time.Time)
	settingFields := schema.Setting{}.Fields()
	_ = settingFields
	// settingDescKey is the schema descriptor for key field.
	settingDescKey := settingFields[0].Descriptor()
	// setting.KeyValidator is a validator for the "key" field. It is called by the builders before save.
	setting.KeyValidator = settingDescKey.Validators[0].(func(string) error)
	// settingDescValue is the schema descriptor for value field.
	settingDescValue := settingFields[1].Descriptor()
	// setting.DefaultValue holds the default value on creation for the value field.
	setting.DefaultValue = settingDescValue.Default.(string)
	// settingDescGroup is the schema descriptor for group field.
	settingDescGroup := settingFields[2].Descriptor()
	// setting.DefaultGroup holds the default value on creation for the group field.
	setting.DefaultGroup = settingDescGroup.Default.(string)
	// settingDescCreatedAt is the schema descriptor for created_at field.
	settingDescCreatedAt := settingFields[3].Descriptor()
	// setting.DefaultCreatedAt holds the default value on creation for the created_at field.
	setting.DefaultCreatedAt = settingDescCreatedAt.Default.(func() time.Time)
	// settingDescUpdatedAt is the schema descriptor for updated_at field.
	settingDescUpdatedAt := settingFields[4].Descriptor()
	// setting.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	setting.DefaultUpdatedAt = settingDescUpdatedAt.Default.(func() time.Time)
	// setting.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	setting.UpdateDefaultUpdatedAt = settingDescUpdatedAt.UpdateDefault.(func() time.Time)
	taskFields := schema.Task{}.Fields()
	_ = taskFields
	// taskDescPluginID is the schema descriptor for plugin_id field.
	taskDescPluginID := taskFields[0].Descriptor()
	// task.PluginIDValidator is a validator for the "plugin_id" field. It is called by the builders before save.
	task.PluginIDValidator = taskDescPluginID.Validators[0].(func(string) error)
	// taskDescTaskType is the schema descriptor for task_type field.
	taskDescTaskType := taskFields[1].Descriptor()
	// task.TaskTypeValidator is a validator for the "task_type" field. It is called by the builders before save.
	task.TaskTypeValidator = taskDescTaskType.Validators[0].(func(string) error)
	// taskDescStage is the schema descriptor for stage field.
	taskDescStage := taskFields[3].Descriptor()
	// task.DefaultStage holds the default value on creation for the stage field.
	task.DefaultStage = taskDescStage.Default.(string)
	// taskDescUserID is the schema descriptor for user_id field.
	taskDescUserID := taskFields[4].Descriptor()
	// task.UserIDValidator is a validator for the "user_id" field. It is called by the builders before save.
	task.UserIDValidator = taskDescUserID.Validators[0].(func(int) error)
	// taskDescInput is the schema descriptor for input field.
	taskDescInput := taskFields[5].Descriptor()
	// task.DefaultInput holds the default value on creation for the input field.
	task.DefaultInput = taskDescInput.Default.(map[string]interface{})
	// taskDescOutput is the schema descriptor for output field.
	taskDescOutput := taskFields[6].Descriptor()
	// task.DefaultOutput holds the default value on creation for the output field.
	task.DefaultOutput = taskDescOutput.Default.(map[string]interface{})
	// taskDescAttributes is the schema descriptor for attributes field.
	taskDescAttributes := taskFields[7].Descriptor()
	// task.DefaultAttributes holds the default value on creation for the attributes field.
	task.DefaultAttributes = taskDescAttributes.Default.(map[string]interface{})
	// taskDescExecution is the schema descriptor for execution field.
	taskDescExecution := taskFields[8].Descriptor()
	// task.DefaultExecution holds the default value on creation for the execution field.
	task.DefaultExecution = taskDescExecution.Default.(map[string]interface{})
	// taskDescErrorType is the schema descriptor for error_type field.
	taskDescErrorType := taskFields[9].Descriptor()
	// task.DefaultErrorType holds the default value on creation for the error_type field.
	task.DefaultErrorType = taskDescErrorType.Default.(string)
	// taskDescErrorCode is the schema descriptor for error_code field.
	taskDescErrorCode := taskFields[10].Descriptor()
	// task.DefaultErrorCode holds the default value on creation for the error_code field.
	task.DefaultErrorCode = taskDescErrorCode.Default.(string)
	// taskDescErrorMessage is the schema descriptor for error_message field.
	taskDescErrorMessage := taskFields[11].Descriptor()
	// task.DefaultErrorMessage holds the default value on creation for the error_message field.
	task.DefaultErrorMessage = taskDescErrorMessage.Default.(string)
	// taskDescProgress is the schema descriptor for progress field.
	taskDescProgress := taskFields[13].Descriptor()
	// task.DefaultProgress holds the default value on creation for the progress field.
	task.DefaultProgress = taskDescProgress.Default.(int)
	// task.ProgressValidator is a validator for the "progress" field. It is called by the builders before save.
	task.ProgressValidator = func() func(int) error {
		validators := taskDescProgress.Validators
		fns := [...]func(int) error{
			validators[0].(func(int) error),
			validators[1].(func(int) error),
		}
		return func(progress int) error {
			for _, fn := range fns {
				if err := fn(progress); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// taskDescPriority is the schema descriptor for priority field.
	taskDescPriority := taskFields[14].Descriptor()
	// task.DefaultPriority holds the default value on creation for the priority field.
	task.DefaultPriority = taskDescPriority.Default.(int)
	// taskDescAttempts is the schema descriptor for attempts field.
	taskDescAttempts := taskFields[15].Descriptor()
	// task.DefaultAttempts holds the default value on creation for the attempts field.
	task.DefaultAttempts = taskDescAttempts.Default.(int)
	// taskDescMaxAttempts is the schema descriptor for max_attempts field.
	taskDescMaxAttempts := taskFields[16].Descriptor()
	// task.DefaultMaxAttempts holds the default value on creation for the max_attempts field.
	task.DefaultMaxAttempts = taskDescMaxAttempts.Default.(int)
	// taskDescCreatedAt is the schema descriptor for created_at field.
	taskDescCreatedAt := taskFields[19].Descriptor()
	// task.DefaultCreatedAt holds the default value on creation for the created_at field.
	task.DefaultCreatedAt = taskDescCreatedAt.Default.(func() time.Time)
	// taskDescUpdatedAt is the schema descriptor for updated_at field.
	taskDescUpdatedAt := taskFields[20].Descriptor()
	// task.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	task.DefaultUpdatedAt = taskDescUpdatedAt.Default.(func() time.Time)
	// task.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	task.UpdateDefaultUpdatedAt = taskDescUpdatedAt.UpdateDefault.(func() time.Time)
	usagelogFields := schema.UsageLog{}.Fields()
	_ = usagelogFields
	// usagelogDescBillingEventID is the schema descriptor for billing_event_id field.
	usagelogDescBillingEventID := usagelogFields[0].Descriptor()
	// usagelog.BillingEventIDValidator is a validator for the "billing_event_id" field. It is called by the builders before save.
	usagelog.BillingEventIDValidator = usagelogDescBillingEventID.Validators[0].(func(string) error)
	// usagelogDescPlatform is the schema descriptor for platform field.
	usagelogDescPlatform := usagelogFields[1].Descriptor()
	// usagelog.PlatformValidator is a validator for the "platform" field. It is called by the builders before save.
	usagelog.PlatformValidator = usagelogDescPlatform.Validators[0].(func(string) error)
	// usagelogDescModel is the schema descriptor for model field.
	usagelogDescModel := usagelogFields[2].Descriptor()
	// usagelog.ModelValidator is a validator for the "model" field. It is called by the builders before save.
	usagelog.ModelValidator = usagelogDescModel.Validators[0].(func(string) error)
	// usagelogDescInputTokens is the schema descriptor for input_tokens field.
	usagelogDescInputTokens := usagelogFields[3].Descriptor()
	// usagelog.DefaultInputTokens holds the default value on creation for the input_tokens field.
	usagelog.DefaultInputTokens = usagelogDescInputTokens.Default.(int)
	// usagelogDescOutputTokens is the schema descriptor for output_tokens field.
	usagelogDescOutputTokens := usagelogFields[4].Descriptor()
	// usagelog.DefaultOutputTokens holds the default value on creation for the output_tokens field.
	usagelog.DefaultOutputTokens = usagelogDescOutputTokens.Default.(int)
	// usagelogDescCachedInputTokens is the schema descriptor for cached_input_tokens field.
	usagelogDescCachedInputTokens := usagelogFields[5].Descriptor()
	// usagelog.DefaultCachedInputTokens holds the default value on creation for the cached_input_tokens field.
	usagelog.DefaultCachedInputTokens = usagelogDescCachedInputTokens.Default.(int)
	// usagelogDescCacheCreationTokens is the schema descriptor for cache_creation_tokens field.
	usagelogDescCacheCreationTokens := usagelogFields[6].Descriptor()
	// usagelog.DefaultCacheCreationTokens holds the default value on creation for the cache_creation_tokens field.
	usagelog.DefaultCacheCreationTokens = usagelogDescCacheCreationTokens.Default.(int)
	// usagelogDescReasoningOutputTokens is the schema descriptor for reasoning_output_tokens field.
	usagelogDescReasoningOutputTokens := usagelogFields[7].Descriptor()
	// usagelog.DefaultReasoningOutputTokens holds the default value on creation for the reasoning_output_tokens field.
	usagelog.DefaultReasoningOutputTokens = usagelogDescReasoningOutputTokens.Default.(int)
	// usagelogDescInputPrice is the schema descriptor for input_price field.
	usagelogDescInputPrice := usagelogFields[8].Descriptor()
	// usagelog.DefaultInputPrice holds the default value on creation for the input_price field.
	usagelog.DefaultInputPrice = usagelogDescInputPrice.Default.(float64)
	// usagelogDescOutputPrice is the schema descriptor for output_price field.
	usagelogDescOutputPrice := usagelogFields[9].Descriptor()
	// usagelog.DefaultOutputPrice holds the default value on creation for the output_price field.
	usagelog.DefaultOutputPrice = usagelogDescOutputPrice.Default.(float64)
	// usagelogDescCachedInputPrice is the schema descriptor for cached_input_price field.
	usagelogDescCachedInputPrice := usagelogFields[10].Descriptor()
	// usagelog.DefaultCachedInputPrice holds the default value on creation for the cached_input_price field.
	usagelog.DefaultCachedInputPrice = usagelogDescCachedInputPrice.Default.(float64)
	// usagelogDescCacheCreationPrice is the schema descriptor for cache_creation_price field.
	usagelogDescCacheCreationPrice := usagelogFields[11].Descriptor()
	// usagelog.DefaultCacheCreationPrice holds the default value on creation for the cache_creation_price field.
	usagelog.DefaultCacheCreationPrice = usagelogDescCacheCreationPrice.Default.(float64)
	// usagelogDescInputCost is the schema descriptor for input_cost field.
	usagelogDescInputCost := usagelogFields[12].Descriptor()
	// usagelog.DefaultInputCost holds the default value on creation for the input_cost field.
	usagelog.DefaultInputCost = usagelogDescInputCost.Default.(float64)
	// usagelogDescOutputCost is the schema descriptor for output_cost field.
	usagelogDescOutputCost := usagelogFields[13].Descriptor()
	// usagelog.DefaultOutputCost holds the default value on creation for the output_cost field.
	usagelog.DefaultOutputCost = usagelogDescOutputCost.Default.(float64)
	// usagelogDescCachedInputCost is the schema descriptor for cached_input_cost field.
	usagelogDescCachedInputCost := usagelogFields[14].Descriptor()
	// usagelog.DefaultCachedInputCost holds the default value on creation for the cached_input_cost field.
	usagelog.DefaultCachedInputCost = usagelogDescCachedInputCost.Default.(float64)
	// usagelogDescCacheCreationCost is the schema descriptor for cache_creation_cost field.
	usagelogDescCacheCreationCost := usagelogFields[15].Descriptor()
	// usagelog.DefaultCacheCreationCost holds the default value on creation for the cache_creation_cost field.
	usagelog.DefaultCacheCreationCost = usagelogDescCacheCreationCost.Default.(float64)
	// usagelogDescTotalCost is the schema descriptor for total_cost field.
	usagelogDescTotalCost := usagelogFields[16].Descriptor()
	// usagelog.DefaultTotalCost holds the default value on creation for the total_cost field.
	usagelog.DefaultTotalCost = usagelogDescTotalCost.Default.(float64)
	// usagelogDescActualCost is the schema descriptor for actual_cost field.
	usagelogDescActualCost := usagelogFields[17].Descriptor()
	// usagelog.DefaultActualCost holds the default value on creation for the actual_cost field.
	usagelog.DefaultActualCost = usagelogDescActualCost.Default.(float64)
	// usagelogDescBilledCost is the schema descriptor for billed_cost field.
	usagelogDescBilledCost := usagelogFields[18].Descriptor()
	// usagelog.DefaultBilledCost holds the default value on creation for the billed_cost field.
	usagelog.DefaultBilledCost = usagelogDescBilledCost.Default.(float64)
	// usagelogDescAccountCost is the schema descriptor for account_cost field.
	usagelogDescAccountCost := usagelogFields[19].Descriptor()
	// usagelog.DefaultAccountCost holds the default value on creation for the account_cost field.
	usagelog.DefaultAccountCost = usagelogDescAccountCost.Default.(float64)
	// usagelogDescRateMultiplier is the schema descriptor for rate_multiplier field.
	usagelogDescRateMultiplier := usagelogFields[20].Descriptor()
	// usagelog.DefaultRateMultiplier holds the default value on creation for the rate_multiplier field.
	usagelog.DefaultRateMultiplier = usagelogDescRateMultiplier.Default.(float64)
	// usagelog.RateMultiplierValidator is a validator for the "rate_multiplier" field. It is called by the builders before save.
	usagelog.RateMultiplierValidator = func() func(float64) error {
		validators := usagelogDescRateMultiplier.Validators
		fns := [...]func(float64) error{
			validators[0].(func(float64) error),
			validators[1].(func(float64) error),
		}
		return func(rate_multiplier float64) error {
			for _, fn := range fns {
				if err := fn(rate_multiplier); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// usagelogDescSellRate is the schema descriptor for sell_rate field.
	usagelogDescSellRate := usagelogFields[21].Descriptor()
	// usagelog.DefaultSellRate holds the default value on creation for the sell_rate field.
	usagelog.DefaultSellRate = usagelogDescSellRate.Default.(float64)
	// usagelog.SellRateValidator is a validator for the "sell_rate" field. It is called by the builders before save.
	usagelog.SellRateValidator = func() func(float64) error {
		validators := usagelogDescSellRate.Validators
		fns := [...]func(float64) error{
			validators[0].(func(float64) error),
			validators[1].(func(float64) error),
		}
		return func(sell_rate float64) error {
			for _, fn := range fns {
				if err := fn(sell_rate); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// usagelogDescAccountRateMultiplier is the schema descriptor for account_rate_multiplier field.
	usagelogDescAccountRateMultiplier := usagelogFields[22].Descriptor()
	// usagelog.DefaultAccountRateMultiplier holds the default value on creation for the account_rate_multiplier field.
	usagelog.DefaultAccountRateMultiplier = usagelogDescAccountRateMultiplier.Default.(float64)
	// usagelog.AccountRateMultiplierValidator is a validator for the "account_rate_multiplier" field. It is called by the builders before save.
	usagelog.AccountRateMultiplierValidator = func() func(float64) error {
		validators := usagelogDescAccountRateMultiplier.Validators
		fns := [...]func(float64) error{
			validators[0].(func(float64) error),
			validators[1].(func(float64) error),
		}
		return func(account_rate_multiplier float64) error {
			for _, fn := range fns {
				if err := fn(account_rate_multiplier); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// usagelogDescServiceTier is the schema descriptor for service_tier field.
	usagelogDescServiceTier := usagelogFields[23].Descriptor()
	// usagelog.DefaultServiceTier holds the default value on creation for the service_tier field.
	usagelog.DefaultServiceTier = usagelogDescServiceTier.Default.(string)
	// usagelogDescStream is the schema descriptor for stream field.
	usagelogDescStream := usagelogFields[24].Descriptor()
	// usagelog.DefaultStream holds the default value on creation for the stream field.
	usagelog.DefaultStream = usagelogDescStream.Default.(bool)
	// usagelogDescDurationMs is the schema descriptor for duration_ms field.
	usagelogDescDurationMs := usagelogFields[25].Descriptor()
	// usagelog.DefaultDurationMs holds the default value on creation for the duration_ms field.
	usagelog.DefaultDurationMs = usagelogDescDurationMs.Default.(int64)
	// usagelogDescFirstEventMs is the schema descriptor for first_event_ms field.
	usagelogDescFirstEventMs := usagelogFields[26].Descriptor()
	// usagelog.DefaultFirstEventMs holds the default value on creation for the first_event_ms field.
	usagelog.DefaultFirstEventMs = usagelogDescFirstEventMs.Default.(int64)
	// usagelogDescFirstTokenMs is the schema descriptor for first_token_ms field.
	usagelogDescFirstTokenMs := usagelogFields[27].Descriptor()
	// usagelog.DefaultFirstTokenMs holds the default value on creation for the first_token_ms field.
	usagelog.DefaultFirstTokenMs = usagelogDescFirstTokenMs.Default.(int64)
	// usagelogDescWsDialMs is the schema descriptor for ws_dial_ms field.
	usagelogDescWsDialMs := usagelogFields[28].Descriptor()
	// usagelog.DefaultWsDialMs holds the default value on creation for the ws_dial_ms field.
	usagelog.DefaultWsDialMs = usagelogDescWsDialMs.Default.(int64)
	// usagelogDescUserAgent is the schema descriptor for user_agent field.
	usagelogDescUserAgent := usagelogFields[29].Descriptor()
	// usagelog.DefaultUserAgent holds the default value on creation for the user_agent field.
	usagelog.DefaultUserAgent = usagelogDescUserAgent.Default.(string)
	// usagelogDescIPAddress is the schema descriptor for ip_address field.
	usagelogDescIPAddress := usagelogFields[30].Descriptor()
	// usagelog.DefaultIPAddress holds the default value on creation for the ip_address field.
	usagelog.DefaultIPAddress = usagelogDescIPAddress.Default.(string)
	// usagelogDescEndpoint is the schema descriptor for endpoint field.
	usagelogDescEndpoint := usagelogFields[31].Descriptor()
	// usagelog.DefaultEndpoint holds the default value on creation for the endpoint field.
	usagelog.DefaultEndpoint = usagelogDescEndpoint.Default.(string)
	// usagelogDescReasoningEffort is the schema descriptor for reasoning_effort field.
	usagelogDescReasoningEffort := usagelogFields[32].Descriptor()
	// usagelog.DefaultReasoningEffort holds the default value on creation for the reasoning_effort field.
	usagelog.DefaultReasoningEffort = usagelogDescReasoningEffort.Default.(string)
	// usagelogDescUserIDSnapshot is the schema descriptor for user_id_snapshot field.
	usagelogDescUserIDSnapshot := usagelogFields[34].Descriptor()
	// usagelog.DefaultUserIDSnapshot holds the default value on creation for the user_id_snapshot field.
	usagelog.DefaultUserIDSnapshot = usagelogDescUserIDSnapshot.Default.(int)
	// usagelogDescUserEmailSnapshot is the schema descriptor for user_email_snapshot field.
	usagelogDescUserEmailSnapshot := usagelogFields[35].Descriptor()
	// usagelog.DefaultUserEmailSnapshot holds the default value on creation for the user_email_snapshot field.
	usagelog.DefaultUserEmailSnapshot = usagelogDescUserEmailSnapshot.Default.(string)
	// usagelogDescCreatedAt is the schema descriptor for created_at field.
	usagelogDescCreatedAt := usagelogFields[36].Descriptor()
	// usagelog.DefaultCreatedAt holds the default value on creation for the created_at field.
	usagelog.DefaultCreatedAt = usagelogDescCreatedAt.Default.(func() time.Time)
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescEmail is the schema descriptor for email field.
	userDescEmail := userFields[0].Descriptor()
	// user.EmailValidator is a validator for the "email" field. It is called by the builders before save.
	user.EmailValidator = userDescEmail.Validators[0].(func(string) error)
	// userDescPasswordHash is the schema descriptor for password_hash field.
	userDescPasswordHash := userFields[1].Descriptor()
	// user.PasswordHashValidator is a validator for the "password_hash" field. It is called by the builders before save.
	user.PasswordHashValidator = userDescPasswordHash.Validators[0].(func(string) error)
	// userDescUsername is the schema descriptor for username field.
	userDescUsername := userFields[2].Descriptor()
	// user.DefaultUsername holds the default value on creation for the username field.
	user.DefaultUsername = userDescUsername.Default.(string)
	// userDescBalance is the schema descriptor for balance field.
	userDescBalance := userFields[3].Descriptor()
	// user.DefaultBalance holds the default value on creation for the balance field.
	user.DefaultBalance = userDescBalance.Default.(float64)
	// userDescMaxConcurrency is the schema descriptor for max_concurrency field.
	userDescMaxConcurrency := userFields[5].Descriptor()
	// user.DefaultMaxConcurrency holds the default value on creation for the max_concurrency field.
	user.DefaultMaxConcurrency = userDescMaxConcurrency.Default.(int)
	// user.MaxConcurrencyValidator is a validator for the "max_concurrency" field. It is called by the builders before save.
	user.MaxConcurrencyValidator = userDescMaxConcurrency.Validators[0].(func(int) error)
	// userDescBalanceAlertThreshold is the schema descriptor for balance_alert_threshold field.
	userDescBalanceAlertThreshold := userFields[8].Descriptor()
	// user.DefaultBalanceAlertThreshold holds the default value on creation for the balance_alert_threshold field.
	user.DefaultBalanceAlertThreshold = userDescBalanceAlertThreshold.Default.(float64)
	// userDescBalanceAlertNotified is the schema descriptor for balance_alert_notified field.
	userDescBalanceAlertNotified := userFields[9].Descriptor()
	// user.DefaultBalanceAlertNotified holds the default value on creation for the balance_alert_notified field.
	user.DefaultBalanceAlertNotified = userDescBalanceAlertNotified.Default.(bool)
	// userDescCreatedAt is the schema descriptor for created_at field.
	userDescCreatedAt := userFields[11].Descriptor()
	// user.DefaultCreatedAt holds the default value on creation for the created_at field.
	user.DefaultCreatedAt = userDescCreatedAt.Default.(func() time.Time)
	// userDescUpdatedAt is the schema descriptor for updated_at field.
	userDescUpdatedAt := userFields[12].Descriptor()
	// user.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	user.DefaultUpdatedAt = userDescUpdatedAt.Default.(func() time.Time)
	// user.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	user.UpdateDefaultUpdatedAt = userDescUpdatedAt.UpdateDefault.(func() time.Time)
	usersubscriptionFields := schema.UserSubscription{}.Fields()
	_ = usersubscriptionFields
	// usersubscriptionDescCreatedAt is the schema descriptor for created_at field.
	usersubscriptionDescCreatedAt := usersubscriptionFields[4].Descriptor()
	// usersubscription.DefaultCreatedAt holds the default value on creation for the created_at field.
	usersubscription.DefaultCreatedAt = usersubscriptionDescCreatedAt.Default.(func() time.Time)
	// usersubscriptionDescUpdatedAt is the schema descriptor for updated_at field.
	usersubscriptionDescUpdatedAt := usersubscriptionFields[5].Descriptor()
	// usersubscription.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	usersubscription.DefaultUpdatedAt = usersubscriptionDescUpdatedAt.Default.(func() time.Time)
	// usersubscription.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	usersubscription.UpdateDefaultUpdatedAt = usersubscriptionDescUpdatedAt.UpdateDefault.(func() time.Time)
}
